import Foundation

// AUTO-GENERATED by scripts/scrape_pf1.py — do not edit manually
// Source: Archives of Nethys (aonprd.com) — OGL content only
// Total entries: 44

extension SeedDataBuilder {
    func seedClasses() async throws {
        let classes: [ClassEntry] = [

            // // MARK: - Core Rulebook

            .make("Barbarian",
                  hitDie: "d12",
                  skillRanks: 4,
                  bab: "Full",
                  fort: "Good",
                  ref: "Poor",
                  will: "Poor",
                  classSkills: ["Acrobatics", "Climb", "Craft", "Handle Animal", "Intimidate", "Knowledge (nature)", "Perception", "Ride", "Survival", "Swim"],
                  summary: "A ferocious warrior who channels primal rage in battle.",
                  desc: """
                  For some, there is only rage. In the ways of their people, in the fury of their passion, in the howl of battle, conflict is fighting on pure survival instinct. Barbarians call upon inner reserves of strength and ferocity, pushing their bodies beyond normal limits. They are driven by a fierce and primal instinct for survival and conquest, often finding an outlet in battle that other classes cannot match.
                  
                  Barbarians enter a state of rage that grants them extraordinary combat prowess and resilience. While raging, they deal more damage and can absorb more punishment, but their defenses and self-control suffer. As they advance in level, barbarians gain access to more powerful rage powers that allow them to customize their fighting style, from increased damage output to powerful supernatural abilities.
                  
                  In addition to their combat abilities, barbarians are skilled survivalists, able to track prey and endure harsh wilderness conditions. Their martial ability is among the strongest of any class, rivaling even the fighter's raw attack bonus.
                  """,
                  source: "Core Rulebook", isPremium: false),

            .make("Bard",
                  hitDie: "d8",
                  skillRanks: 6,
                  bab: "Medium",
                  fort: "Poor",
                  ref: "Good",
                  will: "Good",
                  classSkills: ["Acrobatics", "Appraise", "Bluff", "Climb", "Craft", "Diplomacy", "Disguise", "Escape Artist", "Intimidate", "Knowledge (all)", "Linguistics", "Perception", "Perform", "Profession", "Sense Motive", "Sleight of Hand", "Spellcraft", "Stealth", "Use Magic Device"],
                  summary: "A versatile performer who uses magic and skill to support and entertain.",
                  desc: """
                  Bards are wanderers who combine magic with performance, skill, and inspiration. They are master jack-of-all-trades who can fill many roles in a party but rarely excel at any single one. A bard's greatest strength is their versatility: they can cast spells, fight reasonably well, use nearly any skill, and inspire their allies.
                  
                  The defining feature of the bard is Bardic Performance, which allows them to use music, poetry, oratory, or other performing arts to create magical effects. At lower levels, bards can inspire courage and competence in their allies; at higher levels, they can fascinate enemies, inspire greatness, or even drive opponents to their doom.
                  
                  Bards cast arcane spells spontaneously from a known spell list, similar to sorcerers. Their spell list focuses on enchantments, illusions, and utility spells that complement their role as a support caster. They also have access to a broad range of skills, making them valuable in social encounters and skill challenges.
                  """,
                  source: "Core Rulebook", isPremium: false),

            .make("Cleric",
                  hitDie: "d8",
                  skillRanks: 2,
                  bab: "Medium",
                  fort: "Good",
                  ref: "Poor",
                  will: "Good",
                  classSkills: ["Appraise", "Craft", "Diplomacy", "Heal", "Knowledge (arcana)", "Knowledge (history)", "Knowledge (nobility)", "Knowledge (planes)", "Knowledge (religion)", "Linguistics", "Profession", "Sense Motive", "Spellcraft"],
                  summary: "A divine spellcaster who channels the power of their deity.",
                  desc: """
                  Clerics are more than just healers. In service to a deity, they wield divine magic to aid their allies, smite their enemies, and advance the cause of their faith. The divine spellcasting of the cleric is among the most powerful in the game, with access to a broad spell list covering healing, protection, combat enhancement, and divine wrath.
                  
                  Clerics may channel energy, a powerful ability that can heal living creatures or harm undead within a large area multiple times per day. Good-aligned clerics channel positive energy (healing); evil-aligned clerics channel negative energy (harming the living). Clerics may also spontaneously convert any prepared spell into a cure (or inflict) spell of equal level.
                  
                  The domains chosen by a cleric reflect their deity's portfolio and grant bonus spells and special abilities. A cleric with the War domain can be a fearsome melee combatant; one with the Healing domain has enhanced healing; one with the Trickery domain excels at deception. Clerics are one of the most flexible classes in the game.
                  """,
                  source: "Core Rulebook", isPremium: false),

            .make("Druid",
                  hitDie: "d8",
                  skillRanks: 4,
                  bab: "Medium",
                  fort: "Good",
                  ref: "Poor",
                  will: "Good",
                  classSkills: ["Climb", "Craft", "Fly", "Handle Animal", "Heal", "Knowledge (geography)", "Knowledge (nature)", "Perception", "Profession", "Ride", "Spellcraft", "Survival", "Swim"],
                  summary: "A nature devotee who shapeshifts and commands the power of the wild.",
                  desc: """
                  Druids are guardians of the natural world, drawing their magical power from nature itself rather than from deities. They are versatile divine spellcasters whose spell list emphasizes natural phenomena, animal control, and earth-shaking power. Druids are also among the few classes that can transform their body into animal forms — the powerful Wild Shape ability.
                  
                  Wild Shape allows the druid to assume the form of animals, plants, and elemental forms at higher levels. While transformed, the druid gains the physical attributes of the new form while retaining their own mental stats and the ability to cast spells (if the form allows it). Wild Shape can be used multiple times per day and lasts longer as the druid levels.
                  
                  Druids also gain an animal companion — a loyal beast that grows in power alongside them. Their natural spell ability allows them to cast spells in wild shape form. Many druids also specialize in a particular aspect of nature through druidic orders that grant unique powers and spell access.
                  """,
                  source: "Core Rulebook", isPremium: false),

            .make("Fighter",
                  hitDie: "d10",
                  skillRanks: 2,
                  bab: "Full",
                  fort: "Good",
                  ref: "Poor",
                  will: "Poor",
                  classSkills: ["Climb", "Craft", "Handle Animal", "Intimidate", "Knowledge (dungeoneering)", "Knowledge (engineering)", "Profession", "Ride", "Survival", "Swim"],
                  summary: "A master of weapons and martial tactics trained for war.",
                  desc: """
                  Some take up arms for glory, wealth, or revenge. Others do battle to prove themselves, to protect others, or because they know nothing else. Still others learn the fighting arts to pursue a spiritual goal, to achieve excellence, or to survive. Whatever their motivation, fighters are among the best combatants in the world.
                  
                  Fighters gain more bonus combat feats than any other class, allowing them to specialize deeply in a weapon or fighting style. Through weapon training and armor training, they become increasingly proficient with their chosen weapons and comfortable with heavier armor over time. At high levels, their weapon mastery provides remarkable benefits with their chosen weapon type.
                  
                  The fighter's greatest strength is its unmatched feat access, full attack bonus, and d10 hit die. They lack the magical support of a paladin or ranger, but compensate with sheer martial mastery. A well-built fighter is a terror to face in melee combat, able to exploit any weapon with devastating effect.
                  """,
                  source: "Core Rulebook", isPremium: false),

            .make("Monk",
                  hitDie: "d8",
                  skillRanks: 4,
                  bab: "Medium",
                  fort: "Good",
                  ref: "Good",
                  will: "Good",
                  classSkills: ["Acrobatics", "Climb", "Craft", "Escape Artist", "Intimidate", "Knowledge (history)", "Knowledge (religion)", "Knowledge (the planes)", "Perception", "Perform", "Profession", "Ride", "Sense Motive", "Stealth", "Swim"],
                  summary: "A martial artist who harnesses inner power to devastating effect.",
                  desc: """
                  Monks are masters of combat, harnessing the power of their own body as a deadly weapon. Through rigorous training and meditation, they have developed an array of superhuman physical capabilities. Unlike most fighters, monks can be effective combatants even when completely unarmed.
                  
                  The monk's unarmed strike deals progressively more damage as they advance in level — eventually rivaling weapons in lethality. Their flurry of blows ability allows them to make multiple attacks at their highest attack bonus, though this requires careful feat investment to maximize. Monks' physical saves are all good progression, making them remarkably resistant to most effects.
                  
                  As monks advance in level, they gain increasingly exotic abilities: stunning fist, abundant step (dimension door), timeless body, and eventually empty body (etherealness). Their ki pool fuels additional attacks, movement, and defensive abilities. Advanced monks can move with impossible speed, survive falls from any height, and resist aging itself.
                  """,
                  source: "Core Rulebook", isPremium: false),

            .make("Paladin",
                  hitDie: "d10",
                  skillRanks: 2,
                  bab: "Full",
                  fort: "Good",
                  ref: "Poor",
                  will: "Good",
                  classSkills: ["Craft", "Diplomacy", "Handle Animal", "Heal", "Knowledge (nobility)", "Knowledge (religion)", "Profession", "Ride", "Sense Motive", "Spellcraft"],
                  summary: "A holy warrior who smites evil and protects the innocent.",
                  desc: """
                  Through a select, worthy few shines the power of the divine. Called paladins, these noble souls dedicate their swords and lives to the battle against evil. Knights, crusaders, and law-bringers, paladins seek not just to spread divine justice but to embody it.
                  
                  The paladin's most iconic ability is Smite Evil, which allows them to channel divine energy into devastating strikes against evil opponents, adding their Charisma bonus to attack rolls and their paladin level to damage. Against undead and evil outsiders, smite evil deals double paladin-level damage. Divine Grace adds their Charisma bonus to all saving throws, making charismatic paladins remarkably resilient.
                  
                  Paladins also have access to divine spells at 4th level, a lay on hands ability that heals hp equal to half their paladin level × Charisma modifier per day, aura of courage to bolster allies against fear, and at higher levels, an aura of resolve and divine bond with a weapon or mount. They must maintain their code of conduct or risk losing their abilities.
                  """,
                  source: "Core Rulebook", isPremium: false),

            .make("Ranger",
                  hitDie: "d10",
                  skillRanks: 6,
                  bab: "Full",
                  fort: "Good",
                  ref: "Good",
                  will: "Poor",
                  classSkills: ["Climb", "Craft", "Handle Animal", "Heal", "Intimidate", "Knowledge (dungeoneering)", "Knowledge (geography)", "Knowledge (nature)", "Perception", "Profession", "Ride", "Spellcraft", "Stealth", "Survival", "Swim"],
                  summary: "A skilled hunter and tracker equally at home in wilderness and combat.",
                  desc: """
                  For those who relish the thrill of the hunt, there are only predators and prey. Be they scouts, hunters, or woodsmen, rangers share a keen ability to keep themselves and their allies alive. Rangers favor a particular enemy type — the favored enemy — against which they gain escalating combat bonuses as they advance in level.
                  
                  Rangers also choose favored terrains, gaining bonuses to initiative, Perception, Stealth, Survival, and Knowledge in their specialized environment. Their combat style focuses on either archery or two-weapon fighting, with bonus feats that support those styles even without meeting normal prerequisites.
                  
                  At 4th level, rangers gain access to divine spells, primarily focused on enhancing their wilderness capabilities, tracking, and communicating with animals. They also gain an animal companion or hunter's bond ability. At higher levels, they can use their Quarry ability to mark a specific target for focused hunting, and their Instant Enemy ability allows them to temporarily designate any creature as a favored enemy.
                  """,
                  source: "Core Rulebook", isPremium: false),

            .make("Rogue",
                  hitDie: "d8",
                  skillRanks: 8,
                  bab: "Medium",
                  fort: "Poor",
                  ref: "Good",
                  will: "Poor",
                  classSkills: ["Acrobatics", "Appraise", "Bluff", "Climb", "Craft", "Diplomacy", "Disable Device", "Disguise", "Escape Artist", "Intimidate", "Knowledge (dungeoneering)", "Knowledge (local)", "Linguistics", "Perception", "Perform", "Profession", "Sense Motive", "Sleight of Hand", "Stealth", "Swim", "Use Magic Device"],
                  summary: "A cunning opportunist who deals devastating sneak attacks.",
                  desc: """
                  Life is an endless series of choices. Most choices amount to little, but the choice to become a rogue makes all others possible. Rogues are adventurers who live on skill — both the skills of their trade and the skills of survival. They are the most adaptable of adventurers, able to find solutions where others see only obstacles.
                  
                  Sneak attack is the rogue's defining combat ability: whenever a rogue attacks a creature that is flat-footed, flanked, or otherwise denied its Dexterity bonus to AC, the rogue deals additional precision damage equal to 1d6 per two rogue levels. At higher levels, this bonus damage becomes enormous and makes positioning and flanking crucial for rogue players.
                  
                  Rogues also gain Rogue Talents — a flexible array of special abilities that allow the player to customize their character's niche. Options range from combat tricks (fast stealth, bleeding attack) to skill enhancements (skill mastery) to unusual capabilities (dispelling attack, crippling strike). Advanced talents become available at 10th level and include increasingly powerful options.
                  """,
                  source: "Core Rulebook", isPremium: false),

            .make("Sorcerer",
                  hitDie: "d6",
                  skillRanks: 2,
                  bab: "Poor",
                  fort: "Poor",
                  ref: "Poor",
                  will: "Good",
                  classSkills: ["Appraise", "Bluff", "Craft", "Fly", "Intimidate", "Knowledge (arcana)", "Profession", "Spellcraft", "Use Magic Device"],
                  summary: "An arcane spellcaster whose power flows from a magical bloodline.",
                  desc: """
                  Scions of innately magical bloodlines, the chosen of deities, the spawn of monsters, pawns of fate and destiny, or simply flukes of fickle magic, sorcerers look within themselves for arcane prowess and find it there. Drawing upon an ability that defies explanation, a sorcerer can draw raw magical energy directly from the cosmos, without study or training.
                  
                  Sorcerers cast arcane spells spontaneously, meaning they can cast any spell they know at any time without preparation, as long as they have remaining spell slots. They know fewer spells than wizards but are more flexible in using them. Their limited but powerful spell list emphasizes impact per cast.
                  
                  Bloodlines are the defining feature that sets sorcerers apart. Each bloodline represents a form of magical heritage — Arcane, Celestial, Draconic, Infernal, Elemental, and many more — and grants bonus spells, special abilities, and bloodline powers that activate at various levels. A draconic sorcerer might gain breath weapons and natural armor; an abyssal sorcerer, demonic strength and summoning powers.
                  """,
                  source: "Core Rulebook", isPremium: false),

            .make("Wizard",
                  hitDie: "d6",
                  skillRanks: 2,
                  bab: "Poor",
                  fort: "Poor",
                  ref: "Poor",
                  will: "Good",
                  classSkills: ["Appraise", "Craft", "Fly", "Knowledge (all)", "Linguistics", "Profession", "Spellcraft"],
                  summary: "A scholarly arcane spellcaster who harnesses the full power of the arcane.",
                  desc: """
                  Beyond the veil of the mundane hide the secrets of absolute power. The information contained in spellbooks is truly prodigious — all of magic in its raw form, waiting for the trained mind to unlock its potential. Wizards are practitioners of the arcane art of magic, spending years of dedicated study to master the most powerful magic available to mortals.
                  
                  Wizards prepare their spells from a spellbook each morning, choosing from the full range of arcane spells they have learned. They gain bonus spells based on their Intelligence score and can add spells to their spellbook through research, purchase, or copying from scrolls and other wizards' books. A wizard with a high enough Intelligence can prepare virtually any combination of arcane magic.
                  
                  Specialization allows wizards to focus on a particular school of magic, gaining additional spell slots and special school powers in exchange for barring access to one or two opposing schools. A universalist wizard avoids these restrictions. The bonded object or familiar both provide additional magical utility. Arcane discovery abilities at high levels allow unique magical insights unavailable to other spellcasters.
                  """,
                  source: "Core Rulebook", isPremium: false),

            // // MARK: - Advanced Player's Guide

            .make("Alchemist",
                  hitDie: "d8",
                  skillRanks: 4,
                  bab: "Medium",
                  fort: "Good",
                  ref: "Good",
                  will: "Poor",
                  classSkills: ["Appraise", "Craft", "Disable Device", "Fly", "Heal", "Knowledge (arcana)", "Knowledge (nature)", "Perception", "Profession", "Sleight of Hand", "Spellcraft", "Survival", "Use Magic Device"],
                  summary: "A mad scientist who brews mutagens and explosive bombs.",
                  desc: """
                  Whether secreted away in a smoky basement laboratory or gleefully experimenting in a well-lit workshop, the alchemist is the philosopher of the fantastical, the curious practitioner of potions, poisons, and explosive extracts. Alchemists are driven by a never-ending curiosity about the world's hidden secrets.
                  
                  The alchemist's most iconic abilities are their bombs and mutagen. Bombs are alchemically created splash weapons that deal fire damage (or other energy types with discoveries) in an area. The mutagen is a potion the alchemist can drink to enhance their physical abilities at the cost of mental stats, temporarily transforming them into a more powerful physical form.
                  
                  Alchemists also brew extracts — spell-like potions that function like wizard spells for personal use. They do not cast spells in the traditional sense; instead their "casting" manifests through alchemical brewing. Their discoveries are akin to rogue talents, offering a broad customization system. At higher levels, discoveries like true mutagen and grand mutagen enable dramatic transformations.
                  """,
                  source: "Advanced Player's Guide", isPremium: true),

            .make("Antipaladin",
                  hitDie: "d10",
                  skillRanks: 2,
                  bab: "Full",
                  fort: "Good",
                  ref: "Poor",
                  will: "Good",
                  classSkills: ["Bluff", "Craft", "Disguise", "Handle Animal", "Intimidate", "Knowledge (religion)", "Profession", "Ride", "Sense Motive", "Spellcraft", "Stealth"],
                  summary: "A servant of darkness who channels evil power to smite the righteous and corrupt the innocent.",
                  desc: """
                  The antipaladin is the antithesis of the paladin — a champion of evil who makes dark pacts with fiends and uses that power to spread tyranny and suffering. Where paladins channel divine grace, antipaladins channel cruelty and corruption.
                  
                  Antipaladins gain Touch of Corruption, a melee touch attack that deals negative energy damage and can impose special conditions similar to paladin mercies, but twisted to cause harm. Their Aura of Cowardice causes fear in nearby enemies, and their Plague Bringer ability makes them immune to disease while spreading it to all they touch.
                  
                  As they advance, antipaladins gain an unholy resilience that adds their Charisma bonus to saving throws, can command undead rather than turning them, and eventually gain a fiendish servant or unholy weapon bond. They are mirror-image counterparts to the paladin in almost every way.
                  """,
                  source: "Advanced Player's Guide", isPremium: true),

            .make("Cavalier",
                  hitDie: "d10",
                  skillRanks: 4,
                  bab: "Full",
                  fort: "Good",
                  ref: "Poor",
                  will: "Poor",
                  classSkills: ["Bluff", "Climb", "Craft", "Diplomacy", "Handle Animal", "Intimidate", "Profession", "Ride", "Sense Motive", "Swim"],
                  summary: "A mounted warrior who leads by example and honors a chivalric order.",
                  desc: """
                  Cavaliers are warriors who have devoted themselves to a particular order, a creed that shapes their ideals and way of life. These warriors are mounted combatants who use superior mobility and battle tactics to demoralize and destroy their foes on horseback.
                  
                  The cavalier's challenge ability allows them to designate an opponent as a challenged target, gaining a bonus to damage against that target while suffering a penalty to AC against attacks from other sources. As the cavalier advances, their mounts become more capable combat partners. Banner ability grants morale bonuses to nearby allies.
                  
                  Each cavalier belongs to an order — such as the Order of the Cockatrice (individual glory), Order of the Dragon (teamwork), Order of the Lion (nobility and leadership), or Order of the Star (faith) — that defines their code, granted abilities, and edicts. Cavaliers who violate their order's code risk losing class abilities until they atone.
                  """,
                  source: "Advanced Player's Guide", isPremium: true),

            .make("Inquisitor",
                  hitDie: "d8",
                  skillRanks: 6,
                  bab: "Medium",
                  fort: "Good",
                  ref: "Poor",
                  will: "Good",
                  classSkills: ["Bluff", "Climb", "Craft", "Diplomacy", "Disguise", "Heal", "Intimidate", "Knowledge (arcana)", "Knowledge (dungeoneering)", "Knowledge (nature)", "Knowledge (planes)", "Knowledge (religion)", "Perception", "Profession", "Ride", "Sense Motive", "Spellcraft", "Stealth", "Survival", "Swim"],
                  summary: "A divine investigator who hunts enemies of the faith with ruthless efficiency.",
                  desc: """
                  Inquisitors are divine servants of their god who stand on the front lines of the battle against heresy, sin, and the enemies of the faith. Unlike clerics, they are not bound by the same codes of conduct; they operate in the moral grey areas of divine law, doing what must be done to protect the faith.
                  
                  Inquisitors are potent solo combatants. Their Judgment ability activates once per encounter and grants powerful benefits — additional attack, damage, or Armor Class — that improve as the inquisitor advances. Solo Tactics allows them to apply teamwork feats as if their allies also had them. Bane allows the inquisitor to enhance their weapon against a specific creature type.
                  
                  Inquisitors also cast divine spells, focusing on combat enhancement, detection, and intimidation rather than pure healing. Their broad skill list makes them excellent investigators, capable of handling most social challenges and gathering intelligence about the enemies of their faith. At higher levels, True Judgment adds devastating divine power to their attacks.
                  """,
                  source: "Advanced Player's Guide", isPremium: true),

            .make("Magus",
                  hitDie: "d8",
                  skillRanks: 2,
                  bab: "Medium",
                  fort: "Good",
                  ref: "Poor",
                  will: "Good",
                  classSkills: ["Climb", "Craft", "Fly", "Intimidate", "Knowledge (arcana)", "Knowledge (dungeoneering)", "Profession", "Ride", "Spellcraft", "Swim", "Use Magic Device"],
                  summary: "A warrior who blends arcane spells with devastating melee attacks.",
                  desc: """
                  There are those who spend their lives poring over tomes and scrolls, learning the power of magic as a weapon. And there are those who spend their lives perfecting the use of a sword. The magus is both. These powerful warriors use academic study of the arcane arts to enhance their martial prowess.
                  
                  Spell Combat allows the magus to cast a spell and make a melee attack in the same action, treating the spell like an off-hand weapon. Spellstrike allows the magus to deliver touch spells through weapon attacks, channeling the spell's energy through the blade. Together, these abilities make the magus one of the deadliest single-target damage dealers in the game.
                  
                  Magi use an arcane pool to enhance their weapons with magical properties or to power special class abilities. Their arcana system (similar to rogue talents) allows customization of their spellblade style. At higher levels, abilities like improved spell combat and counterstrike make the magus a formidable opponent both offensively and defensively.
                  """,
                  source: "Advanced Player's Guide", isPremium: true),

            .make("Oracle",
                  hitDie: "d8",
                  skillRanks: 4,
                  bab: "Medium",
                  fort: "Poor",
                  ref: "Poor",
                  will: "Good",
                  classSkills: ["Craft", "Diplomacy", "Heal", "Knowledge (history)", "Knowledge (planes)", "Knowledge (religion)", "Profession", "Sense Motive", "Spellcraft"],
                  summary: "A spontaneous divine caster cursed and blessed by divine mystery.",
                  desc: """
                  Rather than devote themselves to a single divine being, oracles tend to draw their powers from a broader array of sources: the universe itself, the will of the gods collectively, or powerful natural forces. These divine casters are vessels for power that exceeds their own understanding, and often their own control.
                  
                  The oracle's defining feature is their mystery — a broad divine theme (Battle, Bones, Flame, Lore, Stone, Wind, etc.) that defines their bonus spells and revelation abilities. Revelations are powerful class features that manifest as the oracle advances, ranging from elemental blasts to healing touches to divination abilities, all tied to the mystery's theme.
                  
                  Every oracle also carries a curse — a magical affliction that comes with their divine power. The curse may be debilitating (haunted, clouded vision) but always comes with increasingly powerful compensatory benefits at higher levels. Oracles cast divine spells spontaneously from an expanded version of the cleric spell list, supplemented by their mystery spells.
                  """,
                  source: "Advanced Player's Guide", isPremium: true),

            .make("Summoner",
                  hitDie: "d8",
                  skillRanks: 2,
                  bab: "Medium",
                  fort: "Poor",
                  ref: "Poor",
                  will: "Good",
                  classSkills: ["Craft", "Fly", "Handle Animal", "Knowledge (arcana)", "Knowledge (planes)", "Linguistics", "Profession", "Ride", "Spellcraft", "Use Magic Device"],
                  summary: "A spellcaster bonded to a powerful eidolon that they customize and evolve.",
                  desc: """
                  The summoner is defined by a single extraordinary relationship: the bond with an eidolon, a powerful extraplanar being that the summoner has called forth and shaped into their ideal companion and guardian. The eidolon is customized entirely by the player using an evolution point system, allowing remarkable flexibility in creating exactly the combat monster desired.
                  
                  The eidolon shares a life force with the summoner. When the eidolon takes damage, the summoner can share it; when the summoner falls unconscious, the eidolon disappears. The eidolon can be resummoned after a period of rest. Its form — biped, quadruped, or serpentine — determines its base abilities and how many evolution points it can spend.
                  
                  Summoners also cast arcane spells, primarily focused on the conjuration school and summon monster spells. They can use summon monster as a spell-like ability frequently throughout the day. At higher levels, the summoner can merge with their eidolon, gaining all of its physical abilities while retaining their own mental attributes, creating one of the most powerful physical combatants in the game.
                  """,
                  source: "Advanced Player's Guide", isPremium: true),

            .make("Witch",
                  hitDie: "d6",
                  skillRanks: 2,
                  bab: "Poor",
                  fort: "Poor",
                  ref: "Poor",
                  will: "Good",
                  classSkills: ["Craft", "Fly", "Heal", "Intimidate", "Knowledge (arcana)", "Knowledge (history)", "Knowledge (nature)", "Knowledge (planes)", "Profession", "Spellcraft", "Use Magic Device"],
                  summary: "A sinister spellcaster bonded to a familiar that stores her dark magic.",
                  desc: """
                  Some gain power through study, some through devotion, others through blood, but the witch gains power from a pact made with an otherworldly being. Whether this mysterious patron is a powerful fey, a strange spiritual force, a god, or something else entirely is rarely clear, and the witch herself may not even know. The patron communicates only through the witch's familiar, which serves as the intermediary between witch and patron.
                  
                  The witch's familiar stores all of her spells, similar to a wizard's spellbook. If the familiar is killed or lost, the witch loses access to all prepared spells until a new familiar can be obtained. The familiar can be taught new spells just as a wizard teaches their spellbook. Patrons grant bonus spells throughout the witch's career.
                  
                  Hexes are the defining class feature of the witch — supernatural abilities that can be used at will or once per day. Hexes cover a broad range: the evil eye hex reduces enemy defenses, the healing hex rapidly heals allies, slumber puts enemies to sleep. At higher levels, major and grand hexes include devastating abilities like life giver (raise dead), eternal slumber, and death curse.
                  """,
                  source: "Advanced Player's Guide", isPremium: true),

            // // MARK: - Advanced Class Guide

            .make("Arcanist",
                  hitDie: "d6",
                  skillRanks: 2,
                  bab: "Poor",
                  fort: "Poor",
                  ref: "Poor",
                  will: "Good",
                  classSkills: ["Craft", "Fly", "Knowledge (all)", "Linguistics", "Profession", "Spellcraft", "Use Magic Device"],
                  summary: "A scholar who combines the versatility of a wizard's spellbook with the spontaneity of a sorcerer.",
                  desc: """
                  Arcanists are arcane casters who prepare spells from a spellbook like wizards, but cast them spontaneously using a reservoir of arcane points. This hybrid system gives them more flexibility than either pure class while excelling at short, focused adventuring days.
                  
                  Each day, the arcanist prepares a limited number of spells from their book into available slots. They can cast any prepared spell at will until they run out of slots of the appropriate level. This means they have wizard-like versatility in choosing what to prepare, but sorcerer-like spontaneity in how they cast.
                  
                  Arcanist exploits are their primary class feature — supernatural abilities powered by their arcane reservoir. These exploits range from quick study (adding a spell to prepared list mid-day) to potent offensive and defensive abilities. Their school power and greater exploits at higher levels make arcanists among the most powerful arcane casters in the game.
                  """,
                  source: "Advanced Class Guide", isPremium: true),

            .make("Bloodrager",
                  hitDie: "d10",
                  skillRanks: 4,
                  bab: "Full",
                  fort: "Good",
                  ref: "Poor",
                  will: "Poor",
                  classSkills: ["Acrobatics", "Climb", "Craft", "Handle Animal", "Intimidate", "Knowledge (arcana)", "Perception", "Ride", "Spellcraft", "Survival", "Swim"],
                  summary: "A savage warrior whose bloodline fuels a magical rage, blending barbarian fury with sorcerous power.",
                  desc: """
                  The bloodrager is a primal warrior who channels the power of a magical bloodline through rage. Unlike the barbarian, whose rage is purely physical, the bloodrager's fury manifests magical effects tied to their heritage — a draconic bloodrager might sprout wings, while an abyssal bloodrager grows demonic strength.
                  
                  Bloodrage functions like barbarian rage but adds a spellcasting element: while raging, the bloodrager gains access to spells from their bloodline and a limited arcane spell list. They cast arcane spells spontaneously and can cast while in a bloodrage, though they cannot cast while wearing heavy armor.
                  
                  At higher levels, bloodrager abilities expand to include the ability to enter a greater bloodrage, gain powerful bloodline abilities, and eventually access demon-born or dragon-born transformations. Their combination of martial power and magical bloodline effects makes them a unique and unpredictable opponent.
                  """,
                  source: "Advanced Class Guide", isPremium: true),

            .make("Brawler",
                  hitDie: "d10",
                  skillRanks: 4,
                  bab: "Full",
                  fort: "Good",
                  ref: "Good",
                  will: "Poor",
                  classSkills: ["Acrobatics", "Climb", "Craft", "Escape Artist", "Handle Animal", "Intimidate", "Knowledge (dungeoneering)", "Knowledge (local)", "Perception", "Profession", "Ride", "Sense Motive", "Survival", "Swim"],
                  summary: "A street fighter who combines the monk's unarmed prowess with the fighter's combat flexibility.",
                  desc: """
                  The brawler is a martial artist who relies on improvised moves, grapples, and unarmed strikes rather than formal training. They are more adaptable than monks and less specialized than fighters, combining elements of both.
                  
                  Brawler's Flurry allows the brawler to make a full-attack using unarmed strikes or close weapons, combining attacks in unpredictable ways. Martial Flexibility is the class's signature ability — the brawler can temporarily learn combat feats as a swift action, effectively having access to the entire combat feat list without having to permanently invest in them.
                  
                  Brawlers also deal increasing unarmed damage as they level, gain bonus combat feats, and eventually access AC bonus similar to monk's Wisdom to AC. They excel in close-quarters combat and can adapt to any situation on the fly using Martial Flexibility.
                  """,
                  source: "Advanced Class Guide", isPremium: true),

            .make("Hunter",
                  hitDie: "d8",
                  skillRanks: 6,
                  bab: "Medium",
                  fort: "Good",
                  ref: "Good",
                  will: "Poor",
                  classSkills: ["Climb", "Craft", "Handle Animal", "Heal", "Intimidate", "Knowledge (dungeoneering)", "Knowledge (geography)", "Knowledge (nature)", "Perception", "Profession", "Ride", "Spellcraft", "Stealth", "Survival", "Swim"],
                  summary: "A divine archer and tracker bonded to a powerful animal companion, combining ranger and druid.",
                  desc: """
                  The hunter is a nature warrior who blends the ranger's combat focus with the druid's animal bond and spell list. They are defined by their relationship with their animal companion and their ability to fight seamlessly alongside it.
                  
                  Hunter's Bond grants a powerful animal companion that levels up alongside the hunter. Precise Companion allows the hunter's animal companion to use the hunter's teamwork feats without the companion knowing them. This creates devastating battlefield synergy — a hunter and their companion can execute flanks, pin foes, and combine attacks with unusual efficiency.
                  
                  Hunters cast divine spells from a combined druid/ranger list, focusing on nature magic and animal enhancement. Their Improved Empathic Link allows them to share senses with their companion at higher levels, and their Animal Focus ability grants both hunter and companion powerful bonus traits tied to specific animals.
                  """,
                  source: "Advanced Class Guide", isPremium: true),

            .make("Investigator",
                  hitDie: "d8",
                  skillRanks: 6,
                  bab: "Medium",
                  fort: "Poor",
                  ref: "Good",
                  will: "Good",
                  classSkills: ["Craft", "Disable Device", "Disguise", "Escape Artist", "Heal", "Knowledge (all)", "Linguistics", "Perception", "Perform", "Profession", "Sense Motive", "Sleight of Hand", "Spellcraft", "Stealth", "Use Magic Device"],
                  summary: "A forensic alchemist who uses cunning, extracts, and studied observations to unravel any mystery.",
                  desc: """
                  The investigator combines the alchemist's extract-brewing with the inquisitor's studied strike and the rogue's broad skill base. They are the quintessential skill monkey and knowledge specialist, able to handle complex social and intellectual challenges other classes cannot.
                  
                  Studied Combat is the investigator's primary combat feature — they spend a move action to study an enemy, then gain a bonus to attack rolls and add their Intelligence modifier to damage. This makes Intelligence highly valuable on the investigator beyond just knowledge skills. Studied Strike delivers a burst of precision damage once per study.
                  
                  Investigators brew extracts like alchemists and pick investigator talents like rogue talents. Their Inspiration pool allows them to add bonus dice to skill checks or saving throws, making them extraordinarily reliable at knowledge checks, Perception, and other investigative tasks. At high levels, they become nearly infallible at deduction.
                  """,
                  source: "Advanced Class Guide", isPremium: true),

            .make("Shaman",
                  hitDie: "d8",
                  skillRanks: 4,
                  bab: "Medium",
                  fort: "Poor",
                  ref: "Poor",
                  will: "Good",
                  classSkills: ["Craft", "Diplomacy", "Fly", "Handle Animal", "Heal", "Knowledge (arcana)", "Knowledge (history)", "Knowledge (nature)", "Knowledge (planes)", "Knowledge (religion)", "Profession", "Ride", "Sense Motive", "Spellcraft", "Survival"],
                  summary: "A spirit-bonded divine caster who draws power from nature spirits to cast and channel elemental magic.",
                  desc: """
                  The shaman is a hybrid class that blends the oracle's spontaneous divine casting with the witch's spirit familiar mechanic. Each shaman bonds with a spirit — a manifestation of a natural force — that determines their class abilities and bonus spells.
                  
                  Spirit abilities are the core class feature: a wandering spirit provides temporary abilities, while a primary spirit provides permanent ongoing powers that scale with level. Hexes function identically to witch hexes, giving the shaman access to the full witch hex list through their class.
                  
                  The shaman's familiar is replaced by a spirit guide — an ancestor or nature spirit who teaches hexes and provides spiritual wisdom. At higher levels, shamans can call upon greater spirit manifestations, possess bodies through their spirit, and access the full power of their bound spirit.
                  """,
                  source: "Advanced Class Guide", isPremium: true),

            .make("Skald",
                  hitDie: "d8",
                  skillRanks: 4,
                  bab: "Medium",
                  fort: "Poor",
                  ref: "Good",
                  will: "Good",
                  classSkills: ["Acrobatics", "Appraise", "Bluff", "Climb", "Craft", "Diplomacy", "Escape Artist", "Handle Animal", "Intimidate", "Knowledge (all)", "Linguistics", "Perception", "Perform", "Profession", "Ride", "Sense Motive", "Spellcraft", "Swim"],
                  summary: "A warrior-poet who channels raging battle songs to empower allies with supernatural fury.",
                  desc: """
                  The skald is a bard-barbarian hybrid who combines performance-based party support with the barbarian's rage. Instead of inspire courage, the skald performs Raging Song — a bardic performance that grants the full barbarian rage power to all allies within range.
                  
                  Raging Song is the skald's primary ability: while performing, all allies who choose to participate gain the effects of rage (attack and damage bonuses, Will save boost, penalties to AC and skills). Allies use the skald's rage powers rather than their own. This can make the skald an incredible force multiplier for martial parties.
                  
                  Skalds also cast arcane spells from the bard/skald spell list, including rage-enhancing spells. Their Versatile Performance and lore master abilities match the bard's versions. At high levels, the skald's Inspired Rage becomes powerful enough to grant mythic rage or other extraordinary effects.
                  """,
                  source: "Advanced Class Guide", isPremium: true),

            .make("Slayer",
                  hitDie: "d10",
                  skillRanks: 6,
                  bab: "Full",
                  fort: "Good",
                  ref: "Good",
                  will: "Poor",
                  classSkills: ["Acrobatics", "Bluff", "Climb", "Craft", "Disguise", "Handle Animal", "Heal", "Intimidate", "Knowledge (dungeoneering)", "Knowledge (geography)", "Knowledge (local)", "Linguistics", "Perception", "Profession", "Ride", "Sense Motive", "Stealth", "Survival", "Swim"],
                  summary: "A precision hunter who blends the ranger's tracking with the rogue's lethal strikes.",
                  desc: """
                  The slayer is a studied assassin who uses careful observation to maximize damage against specific targets. They are simpler to play than the ranger (no spells, animal companion) while being more martially focused than the rogue.
                  
                  Studied Target is the slayer's primary mechanic — by spending a move action to study a target, the slayer gains increasing bonuses to attack, damage, and skill checks against that foe. These bonuses scale to +5 at high levels and eventually become a free action. Multiple targets can be studied simultaneously at higher levels.
                  
                  Slayer Talents mirror rogue talents and provide a range of combat enhancements, skill bonuses, and special techniques. They gain sneak attack at a slower rate than rogues, but access fighter and ranger talents in addition to rogue options, providing greater martial versatility. Quarry at high levels designates a single target for maximum focused hunting.
                  """,
                  source: "Advanced Class Guide", isPremium: true),

            .make("Swashbuckler",
                  hitDie: "d10",
                  skillRanks: 4,
                  bab: "Full",
                  fort: "Poor",
                  ref: "Good",
                  will: "Poor",
                  classSkills: ["Acrobatics", "Bluff", "Climb", "Craft", "Diplomacy", "Escape Artist", "Intimidate", "Knowledge (local)", "Knowledge (nobility)", "Perception", "Perform", "Profession", "Ride", "Sense Motive", "Sleight of Hand", "Swim"],
                  summary: "An agile duelist who uses panache and precise weapon work to outmaneuver any foe.",
                  desc: """
                  The swashbuckler is the light-armor melee combatant class, focusing on speed, accuracy, and stylish sword fighting over brute strength. They use Dexterity rather than Strength for attack rolls and eventually for damage through Precise Strike.
                  
                  Panache is the swashbuckler's resource pool, fueling their Deeds — special combat maneuvers similar to the gunslinger's. Deeds include Derring-Do (add die roll to Acrobatics or other checks), Opportune Parry and Riposte (deflect attacks and counter-attack), and Precise Strike (dealing bonus precise damage when attacking with a light or one-handed piercing weapon).
                  
                  Swashbucklers gain Charmed Life, allowing them to add their Charisma modifier to saving throws a limited number of times per day. At higher levels, they become masters of the single blade, gaining abilities that make them nearly impossible to flank, hit, or disable through sheer martial artistry.
                  """,
                  source: "Advanced Class Guide", isPremium: true),

            .make("Warpriest",
                  hitDie: "d8",
                  skillRanks: 2,
                  bab: "Medium",
                  fort: "Good",
                  ref: "Poor",
                  will: "Good",
                  classSkills: ["Climb", "Craft", "Diplomacy", "Heal", "Intimidate", "Knowledge (history)", "Knowledge (religion)", "Profession", "Ride", "Sense Motive", "Spellcraft", "Survival", "Swim"],
                  summary: "A battle-hardened divine warrior who blesses weapons and channels divine power through combat.",
                  desc: """
                  The warpriest is a martial cleric hybrid who uses both weapons and spells to serve their deity on the battlefield. Unlike the cleric, who is primarily a spellcaster, the warpriest splits focus evenly between fighting and divine magic.
                  
                  Sacred Weapon allows the warpriest to empower their favored weapon (tied to their deity) with divine energy, increasing its damage die and adding temporary magical weapon properties for a limited time per day. Fervor is a swift-action healing ability that allows the warpriest to heal themselves or apply touch spells through their weapon strikes.
                  
                  Blessings are the warpriest's class features tied to their deity's domains — two blessings chosen at character creation provide minor and major powers that activate using a daily resource. These include offensive abilities, healing bursts, and domain-specific powers. The warpriest can wear medium armor and fight effectively while still casting cleric spells.
                  """,
                  source: "Advanced Class Guide", isPremium: true),

            // // MARK: - Ultimate Combat

            .make("Gunslinger",
                  hitDie: "d10",
                  skillRanks: 4,
                  bab: "Full",
                  fort: "Good",
                  ref: "Good",
                  will: "Poor",
                  classSkills: ["Acrobatics", "Bluff", "Climb", "Craft", "Handle Animal", "Heal", "Intimidate", "Knowledge (engineering)", "Knowledge (local)", "Perception", "Profession", "Ride", "Sleight of Hand", "Survival", "Swim"],
                  summary: "A firearms expert who uses grit and deadly accuracy to overcome any foe.",
                  desc: """
                  The gunslinger is a specialist in the use of firearms, a relatively rare and expensive weapon type in Pathfinder. They compensate for the slow reload time of guns with the grit system and a broad array of deeds that can only be performed with these weapons.
                  
                  Grit is a resource pool that recharges by confirming critical hits or killing significant enemies. Deeds are special actions powered by grit — the early ones include Deadeye (targeting touch AC at close range), Gunslinger's Dodge (avoiding attacks as an immediate action), and Pistol-Whip (melee attack with a firearm). At higher levels, deeds include Targeting (hit specific body parts for called shot effects) and Slinger's Luck.
                  
                  The gunslinger's Nimble ability eventually grants them a dodge bonus to AC even in light armor, compensating for their inability to use heavy armor. They must manage ammunition, misfires, and the high cost of firearms and ammo, but in return gain unmatched damage potential at range.
                  """,
                  source: "Ultimate Combat", isPremium: true),

            .make("Ninja",
                  hitDie: "d8",
                  skillRanks: 8,
                  bab: "Medium",
                  fort: "Poor",
                  ref: "Good",
                  will: "Poor",
                  classSkills: ["Acrobatics", "Appraise", "Bluff", "Climb", "Craft", "Diplomacy", "Disable Device", "Disguise", "Escape Artist", "Intimidate", "Knowledge (local)", "Knowledge (nobility)", "Linguistics", "Perception", "Perform", "Profession", "Sense Motive", "Sleight of Hand", "Stealth", "Swim", "Use Magic Device"],
                  summary: "A roguish martial artist who uses ki and stealth to strike from the shadows.",
                  desc: """
                  The ninja is functionally similar to the rogue but replaces trap-finding and rogue talents with a ki pool and ninjitsu arts. They are the stealth assassin archetype, excelling at infiltration, sudden death strikes, and vanishing from sight.
                  
                  Sneak attack functions identically to the rogue's version. Ki Pool powers Ninja Tricks — special abilities ranging from invisibility to poison use to acrobatic tricks. Unlike the ki pool's usual function, the ninja uses ki for brief supernatural disappearances (as if casting greater invisibility) and other flash-of-shadow effects.
                  
                  No Trace makes the ninja's passage nearly impossible to follow, imposing penalties on Perception and Tracking checks against them that scale with level. Light Steps allows them to walk on liquid or otherwise unstable terrain. At high levels, ninjas become effectively untouchable in their own environment.
                  """,
                  source: "Ultimate Combat", isPremium: true),

            .make("Samurai",
                  hitDie: "d10",
                  skillRanks: 4,
                  bab: "Full",
                  fort: "Good",
                  ref: "Poor",
                  will: "Poor",
                  classSkills: ["Climb", "Craft", "Diplomacy", "Handle Animal", "Intimidate", "Knowledge (history)", "Knowledge (local)", "Knowledge (nobility)", "Perception", "Profession", "Ride", "Sense Motive", "Swim"],
                  summary: "An honorable mounted warrior who leads by example and embodies an ancient warrior tradition.",
                  desc: """
                  The samurai is a cavalier variant focused on honor, personal excellence, and a strict warrior code. While cavaliers serve orders, samurai serve their personal code of Bushido — a philosophy of loyalty, honor, and martial excellence.
                  
                  The samurai's Challenge ability functions like the cavalier's but with different order abilities. Their Resolve ability allows them to spend free actions to overcome fear, stabilize dying, or resist stunning effects that would normally disable them. This makes the samurai exceptionally difficult to incapacitate.
                  
                  Sword Saint is an alternative capstone that allows the samurai to make a Iaijutsu strike — drawing and attacking in a single fluid motion for massive damage against an unsuspecting target. The samurai can also mount any creature up to two sizes larger than themselves, giving them flexibility in their mount choices at higher levels.
                  """,
                  source: "Ultimate Combat", isPremium: true),

            // // MARK: - Occult Adventures

            .make("Kineticist",
                  hitDie: "d8",
                  skillRanks: 4,
                  bab: "Full",
                  fort: "Good",
                  ref: "Poor",
                  will: "Poor",
                  classSkills: ["Acrobatics", "Craft", "Heal", "Intimidate", "Perception", "Profession", "Stealth", "Use Magic Device"],
                  summary: "A powerful elemental channeler who blasts foes with raw elemental energy and reshapes the battlefield.",
                  desc: """
                  Kineticists are born with a connection to an elemental plane that manifests as the ability to control and project raw elemental energy. They are the closest thing PF1 has to a full-martial blaster — characters who can sustain devastating elemental attacks indefinitely.
                  
                  The kineticist's primary resource is their Burn mechanic. They can push their abilities beyond normal limits by accepting Burn — nonlethal damage from overexertion — in exchange for more powerful blasts or extended effects. Their Constitution modifier directly powers both their blasting and their ability to accept burn, making Con the primary stat.
                  
                  Wild Talents are the kineticist's ability selection system, covering offensive blasts, defensive utility infusions, and utility wild talents. Composite blasts combine multiple elements for enhanced damage. At higher levels, kineticists can fly on elemental power, create walls of fire or stone, and unleash blasts that can affect entire areas.
                  """,
                  source: "Occult Adventures", isPremium: true),

            .make("Medium",
                  hitDie: "d8",
                  skillRanks: 4,
                  bab: "Medium",
                  fort: "Poor",
                  ref: "Poor",
                  will: "Good",
                  classSkills: ["Bluff", "Craft", "Diplomacy", "Fly", "Heal", "Intimidate", "Knowledge (arcana)", "Knowledge (history)", "Knowledge (planes)", "Knowledge (religion)", "Linguistics", "Perception", "Perform", "Profession", "Sense Motive", "Sleight of Hand", "Spellcraft", "Use Magic Device"],
                  summary: "A spiritualist who channels the spirits of legendary figures to gain their power temporarily.",
                  desc: """
                  The medium doesn't have a fixed set of class features — instead, they channel one of six legendary spirits each day, taking on the role and abilities of that archetype. Each spirit provides a different benefit: the Champion grants martial power, the Archmage provides spellcasting, the Trickster enhances skills, the Guardian provides defense, the Hierophant gives divine magic, and the Marshal boosts allies.
                  
                  Seances are the mechanism by which the medium contacts spirits. During a seance, the medium makes contact with a spirit of the appropriate type and invites it to inhabit their body for the day. The stronger the spirit's influence, the more powerful the benefits — but also the more the medium risks the spirit taking greater control.
                  
                  Spirit Surge allows the medium to push their connection for extra power, at the risk of Spirit Influence — the spirit imposing its personality on the medium's actions. At high level, mediums can channel multiple spirits, perform legendary seances, and even return from death through a spirit's power.
                  """,
                  source: "Occult Adventures", isPremium: true),

            .make("Mesmerist",
                  hitDie: "d8",
                  skillRanks: 6,
                  bab: "Medium",
                  fort: "Poor",
                  ref: "Poor",
                  will: "Good",
                  classSkills: ["Bluff", "Craft", "Diplomacy", "Disguise", "Intimidate", "Knowledge (arcana)", "Knowledge (dungeoneering)", "Knowledge (history)", "Knowledge (local)", "Knowledge (planes)", "Knowledge (religion)", "Perception", "Profession", "Sense Motive", "Spellcraft", "Use Magic Device"],
                  summary: "A hypnotic manipulator who implants mental suggestions and stares down foes with psychic power.",
                  desc: """
                  The mesmerist is a psychic class that specializes in manipulation, misdirection, and mental control. They are excellent party support characters who can implant powerful ongoing effects in allies while debilitating enemies with their gaze.
                  
                  Hypnotic Stare is the mesmerist's signature ability — a free action that imposes a –2 penalty on Will saves to a single visible creature, refreshed each round. This is maintained throughout combat and stacks with other effects. Bold Stare improvements at higher levels add additional penalties to the stared target.
                  
                  Mesmerists implant Tricks in allies — beneficial effects that trigger automatically under specific conditions, such as when an ally is hit or fails a save. Multiple tricks can be active at once. Painful Stare allows the mesmerist to add psychic damage whenever the stared target is struck, either as a free action or automatically through a trigger.
                  """,
                  source: "Occult Adventures", isPremium: true),

            .make("Occultist",
                  hitDie: "d8",
                  skillRanks: 4,
                  bab: "Medium",
                  fort: "Good",
                  ref: "Poor",
                  will: "Poor",
                  classSkills: ["Appraise", "Craft", "Diplomacy", "Disable Device", "Fly", "Heal", "Knowledge (arcana)", "Knowledge (engineering)", "Knowledge (history)", "Knowledge (planes)", "Knowledge (religion)", "Linguistics", "Perception", "Profession", "Sense Motive", "Spellcraft", "Use Magic Device"],
                  summary: "A psychic practitioner who channels power through ancient implements imbued with mental energy.",
                  desc: """
                  The occultist is a psychic class that channels power through a collection of implements — specific items tied to different schools of magic. Each implement focuses a different mental discipline and provides a set of spells and focus powers.
                  
                  Each morning the occultist distributes mental focus — a resource pool — among their implements. Spending focus activates focus powers, the class's primary special abilities. Implements grant bonus spells and focus powers based on which schools they represent: an abjuration implement provides defensive powers, an evocation implement grants offensive blasts.
                  
                  Occultists also learn resonant powers — passive benefits that scale with the amount of focus invested in a given implement. They have access to a broad psychic spell list spanning the spell list of multiple schools. At high levels, they can activate greater focus powers and channel legendary powers from historically significant implements.
                  """,
                  source: "Occult Adventures", isPremium: true),

            .make("Psychic",
                  hitDie: "d6",
                  skillRanks: 2,
                  bab: "Poor",
                  fort: "Poor",
                  ref: "Poor",
                  will: "Good",
                  classSkills: ["Bluff", "Craft", "Diplomacy", "Fly", "Intimidate", "Knowledge (all)", "Linguistics", "Perception", "Profession", "Sense Motive", "Spellcraft"],
                  summary: "A powerful psychic spellcaster who bends reality through sheer force of will.",
                  desc: """
                  The psychic is a full arcane spellcaster whose magic comes from mental discipline rather than arcane study. They prepare spells from a unique psychic spell list and can cast them in a manner similar to wizards, but with psychic-specific components — Emotion components and Thought components instead of somatic and verbal.
                  
                  Phrenic Pool is the psychic's class resource, used to activate phrenic amplifications — special modifications to spells that enhance their effect. Amplifications include abilities like Overpowering Mind (increase spell DC), Mirrored Spell (duplicate a spell as a free action), and Will of the Dead (affect undead with mind-affecting spells).
                  
                  Psychics choose a discipline — their specialty area of psychic power — which determines their bonus spells and discipline powers. Disciplines include Abomination, Boundary, Devotion, Fated, Lore, Rebirth, Self-Perfection, Telepathy, and Tranquility. At higher levels, psychics become nearly impossible to detect and can reshape reality through pure thought.
                  """,
                  source: "Occult Adventures", isPremium: true),

            .make("Spiritualist",
                  hitDie: "d8",
                  skillRanks: 4,
                  bab: "Medium",
                  fort: "Poor",
                  ref: "Poor",
                  will: "Good",
                  classSkills: ["Bluff", "Craft", "Disguise", "Fly", "Heal", "Knowledge (arcana)", "Knowledge (dungeoneering)", "Knowledge (planes)", "Knowledge (religion)", "Linguistics", "Perception", "Profession", "Sense Motive", "Spellcraft", "Use Magic Device"],
                  summary: "A medium who forms a permanent bond with a powerful phantom spirit companion.",
                  desc: """
                  The spiritualist maintains a permanent bond with a phantom — a spirit who died with strong emotional burdens that prevent them from passing on. This phantom can manifest in ectoplasmic or incorporeal form and fights alongside the spiritualist like a powerful companion.
                  
                  The phantom's emotional focus determines its abilities: an anger phantom becomes a powerful melee striker, while a despair phantom has debilitating auras. Each phantom type has unique special abilities and emotional conduit powers. The phantom can be recalled to the spiritualist's consciousness when damaged, healing from the connection.
                  
                  Spiritualists can sense the thoughts of nearby creatures through their spiritual bond, detect haunts, and affect incorporeal creatures. At high levels, they can project their consciousness, possess creatures through their phantom, and raise allies from death through the power of the spirit world.
                  """,
                  source: "Occult Adventures", isPremium: true),

            // // MARK: - Pathfinder Unchained

            .make("Barbarian (Unchained)",
                  hitDie: "d12",
                  skillRanks: 4,
                  bab: "Full",
                  fort: "Good",
                  ref: "Poor",
                  will: "Poor",
                  classSkills: ["Acrobatics", "Climb", "Craft", "Handle Animal", "Intimidate", "Knowledge (nature)", "Perception", "Ride", "Survival", "Swim"],
                  summary: "A revised barbarian with a more powerful and cleaner rage system.",
                  desc: """
                  The Unchained Barbarian modernizes the rage system by eliminating the fatigue penalty that followed rage. This single change significantly improves the class's reliability — where the original barbarian had to manage post-rage fatigue, the unchained version rages freely without consequence.
                  
                  Rage Powers work similarly to before, but several have been rebalanced. Instinctive Piety allows the unchained barbarian to add their Constitution modifier to Will saves while raging — one of the most significant changes, as the original barbarian's Will save was its primary defensive weakness.
                  
                  The damage reduction progression and the unchained barbarian's overall durability are slightly adjusted. The class remains fundamentally the same — a powerful melee warrior who channels fury into battle — but without the mechanical annoyance of post-rage recovery that discouraged frequent rage use.
                  """,
                  source: "Pathfinder Unchained", isPremium: true),

            .make("Monk (Unchained)",
                  hitDie: "d10",
                  skillRanks: 4,
                  bab: "Full",
                  fort: "Good",
                  ref: "Good",
                  will: "Good",
                  classSkills: ["Acrobatics", "Climb", "Craft", "Escape Artist", "Intimidate", "Knowledge (history)", "Knowledge (religion)", "Knowledge (the planes)", "Perception", "Perform", "Profession", "Ride", "Sense Motive", "Stealth", "Swim"],
                  summary: "A revised monk with a full BAB progression and a more powerful ki system.",
                  desc: """
                  The Unchained Monk addresses the original monk's most significant mechanical weaknesses: its medium BAB and overall combat inefficiency at higher levels. The Unchained version gains full BAB progression, making it far more effective as a melee combatant.
                  
                  The ki pool remains the core mechanic, fueling additional attacks, speed boosts, and defensive maneuvers. Stunning Fist, flurry of blows, and the unarmed strike damage progression remain intact. The Unchained Monk also gains Style Strikes — special techniques that combine with flurry attacks for unique effects like toppling strikes and leg sweeps.
                  
                  Elemental Fist, Ki Strike, and Purity of Body are all present in improved forms. The Unchained Monk's overall power level is significantly higher than the original, and it is generally recommended over the original monk for players who want to play a martial artist focused on unarmed combat.
                  """,
                  source: "Pathfinder Unchained", isPremium: true),

            .make("Rogue (Unchained)",
                  hitDie: "d8",
                  skillRanks: 8,
                  bab: "Medium",
                  fort: "Poor",
                  ref: "Good",
                  will: "Poor",
                  classSkills: ["Acrobatics", "Appraise", "Bluff", "Climb", "Craft", "Diplomacy", "Disable Device", "Disguise", "Escape Artist", "Intimidate", "Knowledge (dungeoneering)", "Knowledge (local)", "Linguistics", "Perception", "Perform", "Profession", "Sense Motive", "Sleight of Hand", "Stealth", "Swim", "Use Magic Device"],
                  summary: "A revised rogue with guaranteed sneak attack against debilitated foes and more impactful talents.",
                  desc: """
                  The Unchained Rogue addresses the original rogue's main weakness: sneak attack reliability. The Unchained version gains Debilitating Injury, which automatically applies one of three conditions (Bewildered, Disoriented, or Hampered) to any creature they sneak attack, making follow-up attacks easier.
                  
                  Finesse Training replaces the need for the Weapon Finesse feat — at 1st level, the unchained rogue automatically gains weapon finesse and the ability to add Dexterity to damage with a chosen light weapon. Danger Sense replaces trap sense and expands to provide broader initiative bonuses and situational awareness improvements.
                  
                  Rogue's Edge provides mastery at specific skills, allowing the rogue to unlock special benefits for skills they've maxed out — abilities unavailable to other classes. The overall power level of the Unchained Rogue is significantly higher than the original, and it is generally recommended for players who want to play a skill-based striker.
                  """,
                  source: "Pathfinder Unchained", isPremium: true),

            .make("Summoner (Unchained)",
                  hitDie: "d8",
                  skillRanks: 2,
                  bab: "Medium",
                  fort: "Poor",
                  ref: "Poor",
                  will: "Good",
                  classSkills: ["Craft", "Fly", "Handle Animal", "Knowledge (arcana)", "Knowledge (planes)", "Linguistics", "Profession", "Ride", "Spellcraft", "Use Magic Device"],
                  summary: "A revised summoner with a separate eidolon spell list and a more balanced power level.",
                  desc: """
                  The Unchained Summoner was designed to address the balance concerns of the original summoner, primarily the eidolon's extreme power and the summoner's access to the full spell list. The unchained version separates the summoner and eidolon onto different power tracks.
                  
                  The eidolon now uses a dedicated eidolon spell list that is less comprehensive than before, and the eidolon's evolution point system has been rebalanced. Evolutions work similarly to before but with adjusted costs and effects. The summoner still merges with the eidolon at high levels.
                  
                  The unchained summoner's own spell list has been trimmed and now focuses more on conjuration and planar magic. Summon Monster as a spell-like ability remains, providing battlefield control through summoned creatures. The overall result is a class that remains powerful and unique while being less capable of dominating encounters through the eidolon alone.
                  """,
                  source: "Pathfinder Unchained", isPremium: true),

            // // MARK: - Ultimate Intrigue

            .make("Vigilante",
                  hitDie: "d8",
                  skillRanks: 6,
                  bab: "Medium",
                  fort: "Poor",
                  ref: "Good",
                  will: "Good",
                  classSkills: ["Acrobatics", "Bluff", "Craft", "Diplomacy", "Disable Device", "Disguise", "Escape Artist", "Intimidate", "Knowledge (local)", "Knowledge (nobility)", "Perception", "Perform", "Profession", "Sense Motive", "Sleight of Hand", "Stealth", "Use Magic Device"],
                  summary: "A dual-identity hero who presents a public face while pursuing justice as a masked avenger.",
                  desc: """
                  The vigilante maintains two separate identities — a social identity (a merchant, nobleman, or other public figure) and a vigilante identity (a masked hero or villain). Switching identities takes a minute and grants access to entirely different class features.
                  
                  In vigilante identity, the vigilante gains Vigilante Talents — a broad array of abilities ranging from combat tricks to social manipulation to supernatural powers. Many archetypes shift the vigilante toward different combat styles (avenger uses weapons, stalker focuses on sneak attacks and supernatural stealth).
                  
                  In social identity, the vigilante is effectively invisible — they gain a social bonus that makes them unrecognizable even to people who know their vigilante self. Startling Appearance allows the vigilante to emerge from hiding and apply a penalty on an enemy's attack rolls. The dual identity creates interesting roleplay opportunities and mechanical flexibility.
                  """,
                  source: "Ultimate Intrigue", isPremium: true),

            // // MARK: - Ultimate Wilderness

            .make("Shifter",
                  hitDie: "d10",
                  skillRanks: 4,
                  bab: "Full",
                  fort: "Good",
                  ref: "Good",
                  will: "Poor",
                  classSkills: ["Acrobatics", "Climb", "Craft", "Fly", "Handle Animal", "Knowledge (geography)", "Knowledge (nature)", "Perception", "Profession", "Ride", "Stealth", "Survival", "Swim"],
                  summary: "A wild shapechanging warrior who permanently bonds with aspects of the animal kingdom.",
                  desc: """
                  The shifter is a martial class that specializes in permanent, reliable wild shape rather than the druid's spell-based transformation. Shifters can maintain their forms almost indefinitely and gain access to multiple aspects — partial transformations that grant specific animal traits.
                  
                  Shifter's Fury allows the shifter to make additional natural attacks while in shifted form, scaling with level. Chimeric Aspect at higher levels allows the shifter to combine traits from multiple aspects simultaneously, creating hybrid forms with claws, flight, and enhanced senses all active at once.
                  
                  Wild Shape functions differently from the druid: the shifter changes specific body parts rather than the whole body. Claws of the beast, tiger aspect, and falcon aspect all grant specific physical bonuses while leaving the shifter's overall form mostly humanoid. At the apex, the shifter's Final Form allows a full beast shape with all gained aspects active simultaneously.
                  """,
                  source: "Ultimate Wilderness", isPremium: true),

        ]

        for cls in classes {
            try await db.insertClass(cls)
        }
    }
}

// MARK: - ClassEntry factory
private extension ClassEntry {
    static func make(
        _ title: String,
        hitDie: String,
        skillRanks: Int,
        bab: String,
        fort: String,
        ref: String,
        will: String,
        classSkills: [String],
        summary: String,
        desc: String,
        source: String = "Core Rulebook",
        isPremium: Bool = false
    ) -> ClassEntry {
        ClassEntry(
            id: UUID(),
            title: title,
            summary: summary,
            isPremium: isPremium,
            hitDie: hitDie,
            skillRanks: skillRanks,
            baseAttackBonus: bab,
            fortSave: fort,
            refSave: ref,
            willSave: will,
            classSkills: classSkills,
            description: desc,
            source: source
        )
    }
}