import Foundation

// NOTE: Magus class is seeded in SeedClasses.swift.
// The Witch class (also in Ultimate Magic) is already seeded in SeedClasses.swift.
// This file seeds Ultimate Magic spells only.

// MARK: - SpellEntry factory (Ultimate Magic)
private extension SpellEntry {
    static func make(
        _ title: String,
        school: String,
        levels: String,
        castingTime: String,
        components: String,
        range: String,
        duration: String,
        savingThrow: String,
        sr: Bool,
        summary: String,
        desc: String,
        source: String = "Core Rulebook",
        isPremium: Bool = false
    ) -> SpellEntry {
        SpellEntry(
            id: UUID(),
            title: title,
            summary: summary,
            isPremium: isPremium,
            school: school,
            levels: levels,
            castingTime: castingTime,
            components: components,
            range: range,
            duration: duration,
            savingThrow: savingThrow,
            spellResistance: sr,
            description: desc,
            source: source
        )
    }
}

extension SeedDataBuilder {
    func seedUltimateMagic() async throws {
        try await seedUltimateMagicSpells()
    }

    private func seedUltimateMagicSpells() async throws {
        let spells: [SpellEntry] = [

            // MARK: - Ultimate Magic Spells

            .make("Ablative Barrier",
                  school: "Abjuration",
                  levels: "sorcerer/wizard 2",
                  castingTime: "1 standard action",
                  components: "V, S, M (a piece of shell)",
                  range: "Touch",
                  duration: "1 hour/level",
                  savingThrow: "Will negates (harmless)",
                  sr: false,
                  summary: "Layered force armor absorbs 5 damage per layer (3 layers) before being depleted.",
                  desc: "You surround the target with layers of force, each capable of absorbing 5 points of damage from any source. The spell creates three such layers. Each time a layer absorbs 5 points of damage, it is destroyed. Once all three layers are gone, the spell ends.",
                  source: "Ultimate Magic",
                  isPremium: true),

            .make("Absorb Toxicity",
                  school: "Transmutation",
                  levels: "druid 3, ranger 3, witch 3",
                  castingTime: "1 standard action",
                  components: "V, S",
                  range: "Personal",
                  duration: "1 minute/level",
                  savingThrow: "None",
                  sr: false,
                  summary: "Become immune to disease and poison, absorbing them into your body to pass on via touch.",
                  desc: "You become immune to disease and poison for the duration of this spell. Any diseases or poisons you come into contact with (or that were already affecting you) are absorbed into your body. You can deliver an absorbed disease or poison to another creature with a successful touch attack. The creature touched must succeed at a saving throw (at the original DC) or be affected.",
                  source: "Ultimate Magic",
                  isPremium: true),

            .make("Acid Pit",
                  school: "Conjuration",
                  levels: "sorcerer/wizard 4, summoner 3",
                  castingTime: "1 standard action",
                  components: "V, S, M (drop of acid), F (tiny shovel worth 10 gp)",
                  range: "Medium (100 ft. + 10 ft./level)",
                  duration: "1 round/level + 1 round",
                  savingThrow: "Reflex negates; see text",
                  sr: false,
                  summary: "Creates a pit filled with acid that deals 2d6 acid damage per round to any creature inside.",
                  desc: "This spell functions as create pit, except the pit is filled with a highly corrosive acid. The acid deals 2d6 points of acid damage per round to any creature in the pit. The acid disappears when the pit closes at the end of the spell's duration. A creature that falls into the pit must make a Reflex save or take damage immediately.",
                  source: "Ultimate Magic",
                  isPremium: true),

            .make("Alchemical Tinkering",
                  school: "Transmutation",
                  levels: "sorcerer/wizard 2",
                  castingTime: "1 standard action",
                  components: "V, S",
                  range: "Touch",
                  duration: "1 minute/level",
                  savingThrow: "Will negates (object)",
                  sr: false,
                  summary: "Transform one alchemical item into another alchemical item of the same or lesser value.",
                  desc: "You transform one alchemical item into another alchemical item of equal or lesser gp value. The new item must be chosen when the spell is cast, and the transformation is permanent for the spell's duration, reverting when the spell ends. The new item must be a mundane alchemical item.",
                  source: "Ultimate Magic",
                  isPremium: true),

            .make("Alter Musical Instrument",
                  school: "Illusion",
                  levels: "bard 1",
                  castingTime: "1 standard action",
                  components: "V, S",
                  range: "Touch",
                  duration: "1 hour/level",
                  savingThrow: "Will disbelief",
                  sr: false,
                  summary: "Makes a musical instrument sound like a different type of instrument.",
                  desc: "With a touch, you make a musical instrument sound like a completely different instrument of your choice. Listeners who succeed at a Will save realize the sound is not authentic, but the instrument otherwise produces the full range of sounds of the new type. This does not change the instrument's appearance.",
                  source: "Ultimate Magic",
                  isPremium: true),

            .make("Amplify Elixir",
                  school: "Transmutation",
                  levels: "alchemist 2",
                  castingTime: "1 standard action",
                  components: "V, S",
                  range: "Personal",
                  duration: "1 round/level",
                  savingThrow: "None",
                  sr: false,
                  summary: "The next extract you or an ally imbibes is amplified, extending its duration or increasing its effect.",
                  desc: "You empower all potions and extracts consumed during the spell's duration. The next extract or potion imbibed by you or an ally has either its duration doubled or its variable numeric effects (such as hit points healed or damage dealt) increased by 50%. You choose which benefit to apply when the extract is consumed.",
                  source: "Ultimate Magic",
                  isPremium: true),

            .make("Anarchic Storm",
                  school: "Evocation",
                  levels: "cleric 5, druid 5",
                  castingTime: "1 standard action",
                  components: "V, S, DF",
                  range: "20-ft. radius",
                  duration: "1 round/level",
                  savingThrow: "Fortitude partial; see text",
                  sr: true,
                  summary: "Chaotic-aligned rain deals 2d6 damage to lawful creatures and sickens them; half damage to others.",
                  desc: "You call down a storm of anarchic energy in a 20-foot-radius spread centered on you. The storm deals 2d6 points of damage per round to lawful-aligned creatures (Fortitude half). Chaotic-aligned creatures are unaffected. Other creatures take half damage. Lawful creatures that fail their Fortitude save are also sickened for 1 round. The storm moves with you.",
                  source: "Ultimate Magic",
                  isPremium: true),

            .make("Aqueous Orb",
                  school: "Conjuration",
                  levels: "druid 3, sorcerer/wizard 3",
                  castingTime: "1 standard action",
                  components: "V, S, M (a drop of water and a glass bead)",
                  range: "Medium (100 ft. + 10 ft./level)",
                  duration: "1 round/level",
                  savingThrow: "Reflex negates",
                  sr: false,
                  summary: "A rolling sphere of water engulfs and drowns creatures in its path, dealing 2d6 nonlethal damage.",
                  desc: "You create a rolling ball of water 10 feet in diameter that moves in a direction you designate. The orb deals 2d6 points of nonlethal damage to any creature it moves through (Reflex negates). A creature that fails its save is engulfed. Engulfed creatures must hold their breath or begin drowning. The ball cannot move into areas smaller than 10 feet in any dimension.",
                  source: "Ultimate Magic",
                  isPremium: true),

            .make("Arcane Concordance",
                  school: "Evocation",
                  levels: "wizard 5",
                  castingTime: "1 standard action",
                  components: "V, S, M (a spent wand)",
                  range: "Personal",
                  duration: "1 round/level",
                  savingThrow: "None",
                  sr: false,
                  summary: "Allies in a 10-foot emanation can apply metamagic to one arcane spell per round without increasing the spell level.",
                  desc: "You create a 10-foot-radius emanation of arcane power centered on you. Allies within this area who cast arcane spells may apply a metamagic feat they possess to one spell per round without increasing the spell's effective level or casting time. You choose which metamagic feat is available when you cast this spell.",
                  source: "Ultimate Magic",
                  isPremium: true),

            .make("Assume Appearance",
                  school: "Illusion",
                  levels: "bard 2, sorcerer/wizard 2, witch 2",
                  castingTime: "1 standard action",
                  components: "V, S, M (a piece of hair, nail, or blood from the target individual)",
                  range: "Personal",
                  duration: "1 hour/level (D)",
                  savingThrow: "None",
                  sr: false,
                  summary: "Take on the precise appearance of a specific individual whose hair, nail, or blood you possess.",
                  desc: "You assume the appearance of a specific individual from whom you have obtained a biological sample (hair, nail clipping, or blood). This functions as disguise self, except the disguise exactly replicates the target individual. Observers who know the individual gain a +4 bonus on Will saves to disbelieve the illusion.",
                  source: "Ultimate Magic",
                  isPremium: true),

            .make("Aura of the Unremarkable",
                  school: "Enchantment",
                  levels: "bard 2, inquisitor 2, sorcerer/wizard 3",
                  castingTime: "1 standard action",
                  components: "V, S",
                  range: "20-ft. emanation",
                  duration: "Concentration + 1 round/level",
                  savingThrow: "Will negates",
                  sr: true,
                  summary: "Creatures in the area seem unimportant; attackers must succeed at a Will save to target you.",
                  desc: "You create an aura that makes you and nearby allies appear completely ordinary and unimportant. Any creature that wishes to attack you or an ally within 20 feet must succeed at a Will save or be unable to target you (though they may still act normally in other ways). Once a creature successfully saves, it is immune to this spell for 24 hours.",
                  source: "Ultimate Magic",
                  isPremium: true),

            .make("Battering Blast",
                  school: "Evocation",
                  levels: "sorcerer/wizard 3",
                  castingTime: "1 standard action",
                  components: "V, S",
                  range: "Close (25 ft. + 5 ft./2 levels)",
                  duration: "Instantaneous",
                  savingThrow: "None",
                  sr: true,
                  summary: "Force orb deals 1d6/2 levels (max 5d6) and bull rushes target with CMB +10 vs CMD.",
                  desc: "You unleash a ball of force at a target. You must succeed on a ranged touch attack. If it hits, the target takes 1d6 points of damage per two caster levels (maximum 5d6) and is bull rushed. You make a bull rush combat maneuver check using your caster level + your Intelligence, Wisdom, or Charisma modifier (whichever is highest) + 10 vs. the target's CMD.",
                  source: "Ultimate Magic",
                  isPremium: true),

            .make("Bleed For Your Master",
                  school: "Necromancy",
                  levels: "summoner 2, witch 2",
                  castingTime: "1 standard action",
                  components: "V, S",
                  range: "30 feet",
                  duration: "1 round",
                  savingThrow: "Fortitude negates",
                  sr: true,
                  summary: "Redirect damage from one creature to your summoned creature or familiar.",
                  desc: "When a creature within 30 feet takes damage, you can use this spell to redirect some or all of that damage to your eidolon, summoned creature, or familiar instead. The targeted creature may negate this effect with a Fortitude save. The redirected damage cannot exceed the creature's remaining hit points.",
                  source: "Ultimate Magic",
                  isPremium: true),

            .make("Blessing of Fervor",
                  school: "Transmutation",
                  levels: "cleric 4",
                  castingTime: "1 standard action",
                  components: "V, S, DF",
                  range: "Close (25 ft. + 5 ft./2 levels)",
                  duration: "1 round/level",
                  savingThrow: "Fortitude negates (harmless)",
                  sr: true,
                  summary: "Each affected ally may choose one of several combat benefits each round: extra attack, free movement, +2 AC/Reflex, or swift spell.",
                  desc: "With this powerful blessing, you call your allies to move and act with haste. Each round on its turn, each affected creature may choose one of the following benefits: make one extra attack at its highest bonus, move up to its speed as a swift action, gain +2 to AC and Reflex saves, or cast one spell as a swift action (if it has a casting time of 1 standard action or less).",
                  source: "Ultimate Magic",
                  isPremium: true),

            .make("Blood Transcription",
                  school: "Divination",
                  levels: "wizard 2",
                  castingTime: "1 minute",
                  components: "V, S",
                  range: "Touch",
                  duration: "Permanent",
                  savingThrow: "None",
                  sr: false,
                  summary: "Consume a dead spellcaster's blood to add one of their spells to your spellbook.",
                  desc: "By consuming at least 1 hit point worth of blood from a recently deceased arcane spellcaster (dead no longer than 24 hours), you can access one of the spells in that caster's memory. You learn one random spell known by the deceased spellcaster that is of a level you can cast. This spell is added to your spellbook.",
                  source: "Ultimate Magic",
                  isPremium: true),

            .make("Bloody Claws",
                  school: "Transmutation",
                  levels: "druid 4, ranger 4",
                  castingTime: "1 standard action",
                  components: "V, S, DF",
                  range: "Touch",
                  duration: "1 minute/level",
                  savingThrow: "Fortitude negates (harmless)",
                  sr: true,
                  summary: "The target's natural weapons cause 1d4 bleed damage on every hit.",
                  desc: "You cause the target's claws, bite, or other natural weapons to deal bleed damage. Each time the target hits a creature with one of its natural attacks, it also deals 1d4 points of bleed damage. Bleed damage can be stopped by a DC 15 Heal check or any spell that cures hit point damage.",
                  source: "Ultimate Magic",
                  isPremium: true),

            .make("Boneshaker",
                  school: "Necromancy",
                  levels: "cleric 3, witch 3",
                  castingTime: "1 standard action",
                  components: "V, S",
                  range: "Medium (100 ft. + 10 ft./level)",
                  duration: "1 round",
                  savingThrow: "Fortitude half",
                  sr: true,
                  summary: "Manipulate the bones of a target for 2d6 + 1/level damage (Fortitude half).",
                  desc: "You seize control of the skeletal structure of a living or undead creature and use it as a weapon against its owner. The target takes 2d6 points of damage + 1 point per caster level (maximum +10) as its own bones grind and twist within its body. A successful Fortitude save halves this damage. Undead creatures take the same amount of damage and receive the same save.",
                  source: "Ultimate Magic",
                  isPremium: true),

            .make("Brand",
                  school: "Transmutation",
                  levels: "inquisitor 0",
                  castingTime: "1 round",
                  components: "V, S, DF",
                  range: "Touch",
                  duration: "Permanent",
                  savingThrow: "Fortitude negates",
                  sr: true,
                  summary: "Leave a permanent mark on a creature or object (Will negates).",
                  desc: "You cause a permanent brand to appear on the touched creature. The brand can be any shape or symbol you desire and appears on any exposed portion of skin. The brand is permanent and cannot be hidden by mundane means, though it can be concealed by magic. Remove curse or break enchantment can remove the brand.",
                  source: "Ultimate Magic",
                  isPremium: true),

            .make("Brightest Night",
                  school: "Transmutation",
                  levels: "druid 5, ranger 4",
                  castingTime: "1 standard action",
                  components: "V, S, DF",
                  range: "Touch",
                  duration: "1 hour/level",
                  savingThrow: "Fortitude negates (harmless)",
                  sr: true,
                  summary: "Grant a creature darkvision 60 ft., low-light vision, and +4 Perception in darkness.",
                  desc: "The touched creature gains darkvision 60 feet. If it already has darkvision, the range of its darkvision increases by 60 feet instead. Additionally, the target gains low-light vision and a +4 bonus on Perception checks made in areas of darkness or dim light.",
                  source: "Ultimate Magic",
                  isPremium: true),

            .make("Call Animal",
                  school: "Enchantment",
                  levels: "druid 1, ranger 1",
                  castingTime: "1 round",
                  components: "V, S, DF",
                  range: "Long (400 ft. + 40 ft./level)",
                  duration: "1 hour/level",
                  savingThrow: "None",
                  sr: false,
                  summary: "Summon one animal of your choice that travels overland to reach your location.",
                  desc: "This spell calls one animal of a kind you choose (subject to GM approval) to your location. The animal must be native to your environment and within range. It travels toward you via the most direct route and arrives in 1d4 rounds if within range. On arrival, the animal acts friendly toward you but is not under your control.",
                  source: "Ultimate Magic",
                  isPremium: true),

            .make("Campfire Wall",
                  school: "Evocation",
                  levels: "bard 3, druid 2, ranger 2, sorcerer/wizard 3",
                  castingTime: "1 standard action",
                  components: "V, S, M (ash from a campfire)",
                  range: "Close (25 ft. + 5 ft./2 levels)",
                  duration: "2 hours/level",
                  savingThrow: "None",
                  sr: true,
                  summary: "Creates a ring of fire 10-ft radius, 20 ft. high; 1d6 fire to those passing through; repels vermin and animals.",
                  desc: "You create a low wall of fire in a 10-foot-radius ring, 20 feet high, centered on an existing fire source. Any creature passing through the wall takes 1d6 points of fire damage. Animals and vermin with fewer Hit Dice than your caster level cannot willingly pass through the wall. The wall sheds light equivalent to a torch.",
                  source: "Ultimate Magic",
                  isPremium: true),

            .make("Cast Out",
                  school: "Abjuration",
                  levels: "inquisitor 3",
                  castingTime: "1 standard action",
                  components: "V, S, DF",
                  range: "Touch",
                  duration: "Instantaneous",
                  savingThrow: "Will negates",
                  sr: true,
                  summary: "Expel a possessing entity from a creature; deals 3d6 + Wis modifier damage to the expelled entity.",
                  desc: "With a touch, you attempt to drive a possessing or controlling entity out of a host creature. The possessing entity must succeed at a Will save or be expelled. An expelled entity takes 3d6 points of damage + 1 point per caster level (maximum +15) and is stunned for 1 round. If the entity fails, it is expelled from the host and cannot attempt to possess that creature again for 24 hours.",
                  source: "Ultimate Magic",
                  isPremium: true),

            .make("Calcific Touch",
                  school: "Transmutation",
                  levels: "sorcerer/wizard 4",
                  castingTime: "1 standard action",
                  components: "V, S",
                  range: "Touch",
                  duration: "1 round/level",
                  savingThrow: "Fortitude partial",
                  sr: true,
                  summary: "Slows target on each hit (Fort negates); accumulating effects can temporarily petrify.",
                  desc: "Your touch gradually turns flesh to stone. Each time you hit with a melee touch attack, the target becomes slowed (as the slow spell) for 1 round unless it succeeds at a Fortitude save. Multiple applications stack; a creature that accumulates 3 or more rounds of slow effect is petrified for 1d4 rounds instead.",
                  source: "Ultimate Magic",
                  isPremium: true),

            .make("Chain of Perdition",
                  school: "Conjuration",
                  levels: "cleric 3, sorcerer/wizard 3",
                  castingTime: "1 standard action",
                  components: "V, S, DF",
                  range: "Close (25 ft. + 5 ft./2 levels)",
                  duration: "1 round/level",
                  savingThrow: "Reflex partial",
                  sr: true,
                  summary: "Spectral chain entangles a target, dealing 1d6 damage per round; can be used to trip or disarm.",
                  desc: "You create a spectral chain that lashes out at one target. On a successful ranged touch attack, the chain entangles the target (Reflex negates entangle, but still takes damage). The target takes 1d6 points of force damage per round while entangled. As a move action, you can attempt a trip or disarm maneuver against the entangled target using your caster level + spellcasting ability modifier.",
                  source: "Ultimate Magic",
                  isPremium: true),
        ]

        for spell in spells {
            try await db.insertSpell(spell)
        }
    }
}
