import Foundation

extension SeedDataBuilder {
    func seedMonsters() async throws {
        let monsters: [MonsterEntry] = [

            // MARK: - CR 1/4

            .make("Bat", cr: "1/8", type: "Animal", size: "Diminutive", alignment: "N",
                  hp: "1 (1d8–3)", ac: 16, speed: "5 ft., fly 40 ft. (good)",
                  attacks: "Bite –1 (1d3–4)",
                  specialAbilities: "Blindsense 20 ft., low-light vision",
                  environment: "Temperate and tropical forests",
                  summary: "A small nocturnal flying mammal that navigates by echolocation.",
                  desc: "Bats are small, nocturnal mammals that roost in caves, hollow trees, and abandoned structures. They navigate almost exclusively by blindsense, emitting high-pitched squeaks and interpreting the echoes. Though harmless individually, swarms of bats can pose a genuine threat to travelers caught in confined spaces."),

            .make("Cat", cr: "1/4", type: "Animal", size: "Tiny", alignment: "N",
                  hp: "2 (1d8–2)", ac: 14, speed: "30 ft.",
                  attacks: "Claws –2 (1d2–4 plus grab)",
                  specialAbilities: "Low-light vision, scent",
                  environment: "Temperate and tropical plains",
                  summary: "A small, agile feline predator common as a household pet.",
                  desc: "Cats are nimble, independent predators that have adapted to life alongside humanoids. They are accomplished hunters of small prey such as birds and rodents. Domestic cats tolerate their owners but remain fundamentally wild animals, and feral cats quickly revert to hunting instincts."),

            .make("Dire Rat", cr: "1/3", type: "Animal", size: "Small", alignment: "N",
                  hp: "5 (1d8+1)", ac: 13, speed: "40 ft., climb 20 ft.",
                  attacks: "Bite +1 (1d4 plus disease)",
                  specialAbilities: "Disease (filth fever, DC 11), low-light vision, scent",
                  environment: "Any",
                  summary: "An aggressive, dog-sized rat that carries dangerous diseases.",
                  desc: "Dire rats are aggressive and territorial rodents roughly the size of a small dog. They infest sewers, dungeons, and refuse heaps, gnawing through almost any material to reach food or nesting sites. Their bites carry filth fever, making even a single dire rat a threat to the unwary."),

            .make("Dog", cr: "1/3", type: "Animal", size: "Small", alignment: "N",
                  hp: "6 (1d8+2)", ac: 13, speed: "40 ft.",
                  attacks: "Bite +2 (1d4+1)",
                  specialAbilities: "Low-light vision, scent",
                  environment: "Temperate plains",
                  summary: "A loyal and capable domesticated canine used for hunting and companionship.",
                  desc: "Dogs have been bred by humanoids for thousands of years into countless shapes and temperaments. Most are friendly toward those they know and alert to strangers. Their keen senses of smell and hearing make them valuable as guards and scouts."),

            .make("Eagle", cr: "1/2", type: "Animal", size: "Small", alignment: "N",
                  hp: "4 (1d8)", ac: 14, speed: "10 ft., fly 80 ft. (average)",
                  attacks: "2 talons +3 (1d4), bite +3 (1d4)",
                  specialAbilities: "Low-light vision",
                  environment: "Temperate mountains",
                  summary: "A large bird of prey with sharp talons and exceptional eyesight.",
                  desc: "Eagles soar on thermals high above open terrain, scanning for prey with their extraordinary vision. They strike swiftly, snatching small animals in powerful talons before carrying them to a high perch to feed. Eagles are highly territorial and will drive off other large birds near their nests."),

            .make("Goblin", cr: "1/3", type: "Humanoid (goblinoid)", size: "Small", alignment: "NE",
                  hp: "6 (1d8+1)", ac: 16, speed: "30 ft.",
                  attacks: "Short sword +2 (1d4), or shortbow +4 (1d4)",
                  specialAbilities: "Darkvision 60 ft., goblin fast (move action to avoid AoO)",
                  environment: "Temperate forest and plains",
                  summary: "A small, green-skinned humanoid driven by cruelty and cunning.",
                  desc: "Goblins are childishly cruel, cowardly humanoids who compensate for their weakness with numbers and ambush tactics. They dwell in warrens beneath hills or ruins, raiding nearby farms and travelers under cover of darkness. Their rapid movements and small size make them surprisingly difficult to corner."),

            .make("Kobold", cr: "1/4", type: "Humanoid (reptilian)", size: "Small", alignment: "LE",
                  hp: "5 (1d8+1)", ac: 15, speed: "30 ft.",
                  attacks: "Spear +1 (1d6–1), or sling +3 (1d3–1)",
                  specialAbilities: "Darkvision 60 ft., light sensitivity",
                  environment: "Temperate underground",
                  summary: "A small, cunning reptilian humanoid that excels at trap-laying.",
                  desc: "Kobolds are timid, weak creatures who survive through numbers, cunning, and their legendary skill at constructing traps. They worship dragons as divine ancestors and will go to great lengths to curry favor with any nearby draconic entity. Kobold warrens are honeycombéd with hidden pits, collapsing ceilings, and triggered crossbows."),

            .make("Monkey", cr: "1/4", type: "Animal", size: "Tiny", alignment: "N",
                  hp: "3 (1d8–1)", ac: 14, speed: "30 ft., climb 30 ft.",
                  attacks: "Bite –1 (1d3–4)",
                  specialAbilities: "Low-light vision",
                  environment: "Warm forests",
                  summary: "An agile, small primate found in warm forests.",
                  desc: "Monkeys are curious, social animals that spend most of their lives in the forest canopy. They move with remarkable speed through trees and are quick to flee from larger predators. Their nimble hands make them adept at manipulation, and they will investigate interesting objects with enthusiasm."),

            .make("Rat", cr: "1/8", type: "Animal", size: "Tiny", alignment: "N",
                  hp: "1 (1d8–2)", ac: 14, speed: "15 ft., climb 15 ft., swim 15 ft.",
                  attacks: "Bite –3 (1d3–4)",
                  specialAbilities: "Low-light vision, scent",
                  environment: "Any",
                  summary: "A small, adaptable rodent found in virtually every environment.",
                  desc: "Rats are among the most successful mammals in the world, thriving in sewers, granaries, and wilderness alike. They are primarily scavengers and rarely attack unless cornered. Rats breed rapidly and can overwhelm food stores if left unchecked."),

            .make("Raven", cr: "1/6", type: "Animal", size: "Tiny", alignment: "N",
                  hp: "3 (1d8–1)", ac: 14, speed: "10 ft., fly 40 ft. (average)",
                  attacks: "Bite +5 (1d3–4)",
                  specialAbilities: "Low-light vision",
                  environment: "Temperate forests",
                  summary: "An intelligent black bird known for mimicry and problem-solving.",
                  desc: "Ravens are among the most intelligent birds, capable of mimicking speech, using simple tools, and recognizing individual faces. They are highly social within their groups but aggressive toward other ravens outside the flock. Their all-black plumage and intelligence have made them symbols of mystery and ill omen in many cultures."),

            .make("Riding Dog", cr: "1", type: "Animal", size: "Medium", alignment: "N",
                  hp: "13 (2d8+4)", ac: 13, speed: "40 ft.",
                  attacks: "Bite +3 (1d6+3)",
                  specialAbilities: "Low-light vision, scent",
                  environment: "Temperate plains",
                  summary: "A large, trained dog capable of serving as a mount for Small riders.",
                  desc: "Riding dogs are large, powerful canines selectively bred for strength and a calm temperament under saddle. They are common mounts for halflings and gnomes, and are prized by scouts and rangers for their tracking abilities. A well-trained riding dog is fiercely loyal and will defend its rider to the death."),

            .make("Skeleton (Human)", cr: "1/3", type: "Undead", size: "Medium", alignment: "NE",
                  hp: "4 (1d8)", ac: 16, speed: "30 ft.",
                  attacks: "2 claws +0 (1d4+1)",
                  specialAbilities: "DR 5/bludgeoning, immunity to cold, undead traits",
                  environment: "Any",
                  summary: "An animated human skeleton driven by necromantic energy to attack the living.",
                  desc: "Human skeletons are among the most commonly raised undead, created by necromancers who require cheap, disposable soldiers. They feel no pain, no fatigue, and no fear, attacking relentlessly until destroyed or ordered to stop. Skeletons crumble to dust when their animating magic dissipates."),

            .make("Viper (Small)", cr: "1/2", type: "Animal", size: "Small", alignment: "N",
                  hp: "4 (1d8)", ac: 13, speed: "20 ft., climb 20 ft., swim 20 ft.",
                  attacks: "Bite +2 (1d3–1 plus poison)",
                  specialAbilities: "Poison (Con damage, DC 10), low-light vision, scent",
                  environment: "Temperate and tropical forests",
                  summary: "A small venomous snake capable of delivering a dangerous bite.",
                  desc: "Small vipers are ambush predators that rely on camouflage and patience to catch prey. They deliver venom through fangs that fold flat when the mouth is closed. Most vipers are not aggressive toward creatures too large to eat, but will strike defensively if threatened or cornered."),

            // MARK: - CR 1/2

            .make("Giant Centipede", cr: "1/2", type: "Vermin", size: "Small", alignment: "N",
                  hp: "5 (1d8+1)", ac: 14, speed: "40 ft., climb 40 ft.",
                  attacks: "Bite +1 (1d3–1 plus poison)",
                  specialAbilities: "Poison (Dex damage, DC 13), darkvision 60 ft.",
                  environment: "Temperate and tropical underground",
                  summary: "A fast-moving multi-legged vermin with a poisonous bite.",
                  desc: "Giant centipedes are swift, aggressive predators that hunt any creature small enough to subdue. They are found in caves, rotting logs, and deep undergrowth. Their bite injects a venom that paralyzes muscles, making even small centipedes dangerous to low-level adventurers."),

            .make("Gnoll", cr: "1", type: "Humanoid (gnoll)", size: "Medium", alignment: "CE",
                  hp: "11 (2d8+2)", ac: 15, speed: "30 ft.",
                  attacks: "Battleaxe +3 (1d8+2) or shortbow +1 (1d6)",
                  specialAbilities: "Darkvision 60 ft.",
                  environment: "Warm plains and deserts",
                  summary: "A hyena-headed humanoid raider that lives in nomadic war-bands.",
                  desc: "Gnolls are savage humanoids who resemble upright hyenas. They organize themselves into loose tribal bands that range across savannas and deserts, raiding settlements and taking slaves for labor or sacrifice to dark powers. Gnolls are physically imposing and genuinely fearsome in combat."),

            .make("Orc", cr: "1/3", type: "Humanoid (orc)", size: "Medium", alignment: "CE",
                  hp: "6 (1d8+2)", ac: 13, speed: "30 ft.",
                  attacks: "Falchion +4 (2d4+4) or javelin +1 (1d6+3)",
                  specialAbilities: "Darkvision 60 ft., ferocity",
                  environment: "Temperate hills and mountains",
                  summary: "A fierce, violent humanoid with protruding tusks and a brutal culture.",
                  desc: "Orcs are aggressive, powerful humanoids who celebrate strength and hold weakness in contempt. They organize into warbands ruled by the strongest fighter, who holds power until a stronger challenger defeats them. Orc ferocity allows them to fight on when most creatures would fall."),

            .make("Stirge", cr: "1/2", type: "Magical Beast", size: "Tiny", alignment: "N",
                  hp: "5 (1d10)", ac: 16, speed: "10 ft., fly 40 ft. (average)",
                  attacks: "Touch +7 (attach)",
                  specialAbilities: "Attach, blood drain (1d4 Con), darkvision 60 ft., low-light vision",
                  environment: "Temperate and tropical marshes and forests",
                  summary: "A mosquito-like flying beast that drains blood from its victims.",
                  desc: "Stirges are bat-winged creatures with a long, hollow proboscis that they drive through armor to reach flesh. Once attached, a stirge drains blood rapidly, dropping off only when engorged or slain. They roost in large colonies and swarm prey in numbers that can overwhelm even experienced warriors."),

            .make("Wolf", cr: "1", type: "Animal", size: "Medium", alignment: "N",
                  hp: "13 (2d8+4)", ac: 14, speed: "50 ft.",
                  attacks: "Bite +2 (1d6+1 plus trip)",
                  specialAbilities: "Low-light vision, scent, trip",
                  environment: "Cold and temperate forests and plains",
                  summary: "A pack-hunting canine predator with a powerful trip attack.",
                  desc: "Wolves are highly social predators that coordinate complex hunting strategies within their packs. A lone wolf is cautious, but a pack will take on prey many times its size. Wolves are capable of pulling down large animals by targeting legs and flanks, exhausting their quarry before moving in for the kill."),

            .make("Zombie (Human)", cr: "1/2", type: "Undead", size: "Medium", alignment: "NE",
                  hp: "12 (2d8+3)", ac: 12, speed: "30 ft.",
                  attacks: "Slam +4 (1d6+4)",
                  specialAbilities: "DR 5/slashing, undead traits",
                  environment: "Any",
                  summary: "A shambling animated corpse that mindlessly obeys its creator's commands.",
                  desc: "Zombies are the most basic of undead constructs, formed when a necromancer animates a fresh or preserved corpse. They retain no memory or personality from life and exist solely to follow orders and attack the living. Their resilience to ordinary damage makes them surprisingly dangerous despite their slowness."),

            // MARK: - CR 1

            .make("Crocodile", cr: "2", type: "Animal", size: "Large", alignment: "N",
                  hp: "22 (3d8+9)", ac: 14, speed: "20 ft., swim 30 ft.",
                  attacks: "Bite +6 (1d8+6 plus grab) or tail slap +6 (1d12+6)",
                  specialAbilities: "Hold breath, low-light vision",
                  environment: "Warm rivers and marshes",
                  summary: "A massive aquatic reptile that drags prey beneath the water to drown.",
                  desc: "Crocodiles are ambush predators that lurk just below the water surface, exploding upward with fearsome speed when prey comes close. They grip prey in their jaws and perform a death roll to disorient and drown it. Ancient and adapted to extreme environments, they have changed little over millions of years."),

            .make("Dire Bat", cr: "2", type: "Animal", size: "Large", alignment: "N",
                  hp: "22 (4d8+4)", ac: 14, speed: "20 ft., fly 40 ft. (good)",
                  attacks: "Bite +5 (1d8+4)",
                  specialAbilities: "Blindsense 40 ft., low-light vision",
                  environment: "Temperate and tropical caves",
                  summary: "A massive bat with a wingspan exceeding 15 feet.",
                  desc: "Dire bats are enormous, aggressive cousins of common bats that nest in large cave complexes and underground ruins. They navigate entirely by blindsense and are capable of catching medium-sized prey on the wing. A colony of dire bats disturbed in their roost can fill a cavern with a storm of leathery wings and snapping jaws."),

            .make("Giant Spider", cr: "1", type: "Vermin", size: "Medium", alignment: "N",
                  hp: "16 (3d8+3)", ac: 14, speed: "30 ft., climb 30 ft.",
                  attacks: "Bite +2 (1d6 plus poison)",
                  specialAbilities: "Poison (Str damage, DC 14), darkvision 60 ft., tremorsense 60 ft., web (+5 ranged)",
                  environment: "Temperate forests and underground",
                  summary: "A man-sized spider that uses venom and webs to capture prey.",
                  desc: "Giant spiders are among the most common large predators of dungeon environments. They build extensive webs across passages and chambers, waiting motionless for prey to become entangled. Their venom weakens prey quickly, and they wrap struggling victims in silk before dragging them to a secure location."),

            .make("Goblin Dog", cr: "1", type: "Magical Beast", size: "Medium", alignment: "N",
                  hp: "9 (2d10–2)", ac: 12, speed: "50 ft.",
                  attacks: "Bite +2 (1d6+1 plus allergic reaction)",
                  specialAbilities: "Allergic reaction (DC 11 Fort or 1 Dex damage, itching), darkvision 60 ft., scent",
                  environment: "Temperate and tropical plains and hills",
                  summary: "A hairless, repulsive canine used as a mount and attack beast by goblins.",
                  desc: "Goblin dogs are mangy, hairless quadrupeds with disproportionately large heads and patchy, oily skin. Their skin secretes a substance that causes itching and irritation on contact, making them unpleasant to grapple. Despite their repulsive appearance, goblins keep them as mounts and beloved pets."),

            .make("Horse", cr: "1", type: "Animal", size: "Large", alignment: "N",
                  hp: "15 (2d8+6)", ac: 13, speed: "50 ft.",
                  attacks: "2 hooves +3 (1d6+3)",
                  specialAbilities: "Low-light vision, scent",
                  environment: "Temperate plains",
                  summary: "A strong, fast equine used widely as a mount and beast of burden.",
                  desc: "Horses are herd animals bred and domesticated throughout the civilized world as mounts, draft animals, and livestock. Trained war horses are more aggressive and can be directed to attack in combat. Wild horses live in herds led by a dominant stallion and will flee from most predators."),

            .make("Hyena", cr: "1", type: "Animal", size: "Medium", alignment: "N",
                  hp: "10 (2d8+2)", ac: 13, speed: "50 ft.",
                  attacks: "Bite +3 (1d6+3 plus trip)",
                  specialAbilities: "Low-light vision, scent, trip",
                  environment: "Warm plains and deserts",
                  summary: "A powerful scavenger and pack hunter with crushing jaws.",
                  desc: "Hyenas are opportunistic predators and scavengers that live in large social groups called clans. Their bone-crushing jaws can break through the toughest hides and shells, and they will fight tenaciously over food. Despite their reputation as mere scavengers, hyenas are effective pack hunters capable of taking down large prey."),

            .make("Mite", cr: "1/4", type: "Fey", size: "Small", alignment: "NE",
                  hp: "3 (1d6)", ac: 13, speed: "20 ft., climb 20 ft.",
                  attacks: "Dagger –1 (1d3–2), or javelin +1 (1d4–2)",
                  specialAbilities: "Darkvision 120 ft., spell-like abilities (doom 1/day), vermin empathy",
                  environment: "Temperate and cold underground",
                  summary: "A tiny, mean-spirited fey cousin to the svirfneblin that covets insects and filth.",
                  desc: "Mites are wretched, unsightly fey who dwell in the deepest underground passages and warrens. They are violently jealous of their territorial boundaries and will attack anything that intrudes. They keep giant vermin as pets and companions, considering the creatures to be allies and family."),

            .make("Tengu", cr: "1/2", type: "Humanoid (tengu)", size: "Medium", alignment: "N",
                  hp: "9 (2d8)", ac: 15, speed: "30 ft.",
                  attacks: "Wakizashi +1 (1d6), or bite +1 (1d3)",
                  specialAbilities: "Gifted linguist, low-light vision, swordtrained",
                  environment: "Temperate forests",
                  summary: "A crow-headed humanoid with a gift for language and swordsmanship.",
                  desc: "Tengu are avian humanoids descended from celestial ravens, bearing glossy black feathers, sharp beaks, and an uncanny facility with spoken language. They are drawn to shiny objects and novelty. Many tengu become wanderers, mercenaries, or scholars, leveraging their linguistic gifts and keen intelligence."),

            .make("Troglodyte", cr: "1", type: "Humanoid (reptilian)", size: "Medium", alignment: "CE",
                  hp: "13 (2d8+4)", ac: 16, speed: "30 ft.",
                  attacks: "Club +2 (1d6+1), 2 claws +2 (1d4+1), bite +2 (1d4+1)",
                  specialAbilities: "Darkvision 90 ft., stench (DC 13, 10 rounds, sickened)",
                  environment: "Underground",
                  summary: "A foul-smelling reptilian humanoid that lurks in underground caves.",
                  desc: "Troglodytes are primitive cave-dwelling reptilians with powerful limbs and a nauseating musk that they use as a weapon. Their natural armor is surprisingly tough, and they are capable melee combatants despite their lack of sophisticated tactics. They worship dark gods and conduct brutal rituals in their underground temples."),

            // MARK: - CR 2

            .make("Boar", cr: "2", type: "Animal", size: "Medium", alignment: "N",
                  hp: "18 (2d8+9)", ac: 14, speed: "40 ft.",
                  attacks: "Gore +4 (1d8+6)",
                  specialAbilities: "Ferocity, low-light vision, scent",
                  environment: "Temperate forests",
                  summary: "A large, aggressive wild pig with dangerous tusks and fierce tenacity.",
                  desc: "Boars are aggressive omnivores that will charge almost any intruder into their territory. Their tusks can disembowel a wolf, and their ferocity allows them to fight on even when mortally wounded. Wild boars travel alone or in small family groups and are widely hunted for their excellent meat."),

            .make("Bugbear", cr: "2", type: "Humanoid (goblinoid)", size: "Medium", alignment: "CE",
                  hp: "16 (3d8+3)", ac: 17, speed: "30 ft.",
                  attacks: "Morningstar +5 (1d8+3), or javelin +3 (1d6+3)",
                  specialAbilities: "Darkvision 60 ft., scent, stalker",
                  environment: "Temperate mountains and forests",
                  summary: "A large, stealthy goblinoid that preys on weaker creatures through ambush.",
                  desc: "Bugbears are the largest and most dangerous of the goblinoid races, combining the cunning of their smaller kin with genuine physical power. They are predators first, preferring to stalk prey silently and attack from ambush. Bugbears have a deep love of cruelty and often keep goblin tribes as laborers and food sources."),

            .make("Deinonychus", cr: "3", type: "Animal", size: "Medium", alignment: "N",
                  hp: "26 (4d8+8)", ac: 15, speed: "60 ft.",
                  attacks: "2 talons +5 (1d8+2 plus grab), 2 claws +5 (1d4+2), bite +5 (2d6+2)",
                  specialAbilities: "Low-light vision, pounce, scent",
                  environment: "Warm forests and plains",
                  summary: "A swift feathered dinosaur that attacks with slashing talons and a bone-crushing bite.",
                  desc: "Deinonychuses are fast, intelligent pack hunters that coordinate attacks on prey much larger than themselves. They pin prey with oversized sickle-shaped talons while delivering a killing bite. Fond of ambush, they are among the most dangerous dinosaurs that adventurers might encounter."),

            .make("Dire Wolf", cr: "3", type: "Animal", size: "Large", alignment: "N",
                  hp: "37 (5d8+15)", ac: 14, speed: "50 ft.",
                  attacks: "Bite +7 (1d8+10 plus trip)",
                  specialAbilities: "Low-light vision, scent, trip",
                  environment: "Cold and temperate forests",
                  summary: "A massive prehistoric wolf with enormous jaws and pack intelligence.",
                  desc: "Dire wolves are the apex canine predators of many regions, standing nearly as tall at the shoulder as a pony. They hunt in packs and bring down prey with coordinated flanking and tripping attacks. Ancient and relentless, dire wolves will pursue prey for miles, wearing it down before moving in."),

            .make("Giant Frog", cr: "1", type: "Animal", size: "Medium", alignment: "N",
                  hp: "11 (2d8+2)", ac: 12, speed: "30 ft., swim 30 ft.",
                  attacks: "Tongue +1 (grab), bite +1 (1d6+1)",
                  specialAbilities: "Low-light vision, pull (tongue, 5 ft.), swallow whole",
                  environment: "Temperate and tropical marshes",
                  summary: "An oversized frog that snatches prey with its long, sticky tongue.",
                  desc: "Giant frogs are ambush predators that float motionless among lily pads or crouch at the water's edge waiting for prey. Their enormous sticky tongues can reach surprising distances, yanking victims off their feet. Large giant frogs can swallow medium-sized prey whole."),

            .make("Leopard", cr: "2", type: "Animal", size: "Medium", alignment: "N",
                  hp: "19 (3d8+6)", ac: 15, speed: "30 ft., climb 20 ft.",
                  attacks: "Bite +6 (1d6+3), 2 claws +6 (1d3+3)",
                  specialAbilities: "Low-light vision, pounce, rake (2 claws, 1d3+3), scent",
                  environment: "Warm forests and plains",
                  summary: "A sleek spotted big cat that excels at climbing and ambush attacks.",
                  desc: "Leopards are solitary, elusive predators that stalk prey through a variety of terrain. They are exceptional climbers and frequently drag kills up into trees to protect them from larger scavengers. Their spotted coats provide excellent camouflage in dappled forest light."),

            .make("Lizardfolk", cr: "1", type: "Humanoid (reptilian)", size: "Medium", alignment: "N",
                  hp: "11 (2d8+2)", ac: 15, speed: "30 ft., swim 15 ft.",
                  attacks: "Claws +2 (1d4+2), bite +2 (1d4+2), or club +2 (1d6+2)",
                  specialAbilities: "Hold breath",
                  environment: "Temperate and warm marshes",
                  summary: "A primitive reptilian humanoid that dwells in swamps and river deltas.",
                  desc: "Lizardfolk are marsh-dwelling reptilians who live in small tribal communities centered around food gathering and clan defense. They are not inherently hostile but are intensely territorial and will attack those who threaten their villages without warning. Lizardfolk have a deeply practical worldview and little interest in abstract concepts."),

            .make("Shark (Medium)", cr: "1", type: "Animal", size: "Medium", alignment: "N",
                  hp: "13 (3d8)", ac: 13, speed: "swim 60 ft.",
                  attacks: "Bite +3 (1d6+1)",
                  specialAbilities: "Blindsense 30 ft., keen scent, low-light vision",
                  environment: "Cold and temperate aquatic",
                  summary: "A streamlined ocean predator that detects blood in the water from enormous distances.",
                  desc: "Medium sharks are efficient, remorseless predators built for speed and bite force. They are attracted to blood and movement in water, investigating disturbances with increasing aggression. Though they rarely attack without provocation, a shark that has tasted blood becomes a determined and dangerous foe."),

            .make("Spider Swarm", cr: "1", type: "Vermin (swarm)", size: "Diminutive", alignment: "N",
                  hp: "9 (2d8)", ac: 17, speed: "20 ft., climb 20 ft.",
                  attacks: "Swarm (1d6 plus poison plus distraction)",
                  specialAbilities: "Distraction (DC 11), poison (Str damage, DC 11), swarm traits, tremorsense 30 ft., darkvision 60 ft.",
                  environment: "Temperate and tropical forests and underground",
                  summary: "A seething mass of thousands of tiny venomous spiders.",
                  desc: "Spider swarms form when thousands of spiderlings emerge from a hatching and move as a unified mass in search of prey. They can flow through tiny cracks, under doors, and around almost any obstacle. Their collective venom delivers a surprisingly effective dose and their sheer numbers make them difficult to drive off."),

            .make("Wererat", cr: "2", type: "Humanoid (human, shapechanger)", size: "Medium", alignment: "LE",
                  hp: "26 (4d8+8)", ac: 16, speed: "30 ft.",
                  attacks: "Short sword +5 (1d6+1), or bite +5 (1d4+1 plus lycanthropy)",
                  specialAbilities: "Change shape, DR 10/silver, lycanthropy (DC 14), low-light vision, scent",
                  environment: "Urban",
                  summary: "A human afflicted with lycanthropy who can transform into a giant rat.",
                  desc: "Wererats are cunning lycanthropes who prefer urban environments, infiltrating criminal organizations and using their rat form to spy and travel through city sewer systems. In their human guise they appear unremarkable, betraying their nature only through nervous, twitchy behavior. They spread their curse deliberately to build networks of loyal infected servants."),

            .make("Wolverine", cr: "2", type: "Animal", size: "Medium", alignment: "N",
                  hp: "25 (3d8+12)", ac: 14, speed: "30 ft., climb 10 ft.",
                  attacks: "2 claws +4 (1d6+2), bite +4 (1d4+2)",
                  specialAbilities: "Low-light vision, rage, scent",
                  environment: "Cold forests",
                  summary: "A ferocious mustelid that attacks with berserk fury regardless of its own injuries.",
                  desc: "Wolverines are among the most aggressive animals pound for pound, known to drive bears and mountain lions away from kills many times their size. When threatened or hungry, wolverines fly into a savage rage that increases their already-formidable combat ability. They are solitary, wide-ranging predators respected and feared throughout northern regions."),

            // MARK: - CR 3

            .make("Ankheg", cr: "3", type: "Magical Beast", size: "Large", alignment: "N",
                  hp: "28 (3d10+12)", ac: 18, speed: "30 ft., burrow 20 ft.",
                  attacks: "Bite +7 (2d6+7 plus grab)",
                  specialAbilities: "Acid spray (4d4 acid, 30 ft. line, DC 14, recharge 6 hrs), darkvision 60 ft., low-light vision, tremorsense 60 ft.",
                  environment: "Temperate and warm plains and hills",
                  summary: "A giant burrowing insect that spits acid and grabs prey from below.",
                  desc: "Ankhegs are giant arthropods that burrow beneath farmland and plains, sensing prey through vibration before erupting from the ground to attack. They can spit a powerful stream of acid to soften resistance before closing with their crushing mandibles. Farmers and ranchers dread ankhegs for the livestock and crops they destroy."),

            .make("Cockatrice", cr: "3", type: "Magical Beast", size: "Small", alignment: "N",
                  hp: "27 (6d10–6)", ac: 14, speed: "20 ft., fly 60 ft. (poor)",
                  attacks: "Bite +9 (1d4–2 plus petrification)",
                  specialAbilities: "Petrification (DC 13 Fort or permanently petrified), darkvision 60 ft., low-light vision",
                  environment: "Temperate and warm plains",
                  summary: "A rooster-headed reptile whose bite turns flesh to stone.",
                  desc: "The cockatrice is a small but deeply feared magical beast whose saliva carries a powerful petrification agent. A single bite from these foul-tempered creatures can doom a warrior to an eternity as a garden ornament. Travelers in cockatrice territory carry basilisk oil as a prophylactic against the creature's bite."),

            .make("Ghoul", cr: "1", type: "Undead", size: "Medium", alignment: "CE",
                  hp: "13 (2d8+4)", ac: 14, speed: "30 ft.",
                  attacks: "Bite +3 (1d6+1 plus disease plus paralysis), 2 claws +3 (1d3+1 plus paralysis)",
                  specialAbilities: "Ghoul fever (DC 13 Fort), paralysis (DC 13 Fort, 1d4+1 rounds), darkvision 60 ft., undead traits",
                  environment: "Any land",
                  summary: "A feral undead creature that feeds on corpses and paralyzes the living.",
                  desc: "Ghouls are undead creatures who retain a mockery of intelligence but are consumed by an insatiable hunger for flesh. They haunt graveyards, battlefields, and dungeon ossuaries, gnawing on corpses and attacking any living creature they encounter. Their paralytic saliva makes them far more dangerous than their humble statistics suggest."),

            .make("Giant Fire Beetle", cr: "1/3", type: "Vermin", size: "Small", alignment: "N",
                  hp: "4 (1d8)", ac: 12, speed: "30 ft., fly 30 ft. (poor)",
                  attacks: "Bite +1 (1d4)",
                  specialAbilities: "Darkvision 60 ft., glowing glands (light 10 ft., 1d6 days after death)",
                  environment: "Temperate and tropical forests",
                  summary: "A large beetle with bioluminescent glands prized by dungeon delvers.",
                  desc: "Giant fire beetles are nocturnal vermin that use their glowing glands for communication and to attract mates. They are not particularly aggressive and generally flee from large creatures unless cornered. Their light-producing organs retain their glow for up to a day and a half after death, making them valuable to miners and dungeon explorers."),

            .make("Hell Hound", cr: "3", type: "Outsider (evil, extraplanar, fire, lawful)", size: "Medium", alignment: "LE",
                  hp: "22 (3d10+6)", ac: 16, speed: "40 ft.",
                  attacks: "Bite +6 (1d8+3 plus 1d6 fire)",
                  specialAbilities: "Darkvision 60 ft., immunity to fire, scent, vulnerability to cold, breath weapon (10 ft. cone of fire, 2d6, DC 13)",
                  environment: "Lawful evil planes",
                  summary: "A fire-breathing, devil-bound hound that hunts escaped souls across the planes.",
                  desc: "Hell hounds are fiendish canines that serve as guardians, trackers, and executioners for powerful devils. Their coats are jet black and radiate intense heat. They breathe a short cone of fire and their bites leave burning wounds. Powerful sorcerers occasionally summon hell hounds as guardians, though the creatures serve only from compulsion."),

            .make("Hippogriff", cr: "2", type: "Magical Beast", size: "Large", alignment: "N",
                  hp: "25 (3d10+9)", ac: 14, speed: "40 ft., fly 100 ft. (average)",
                  attacks: "2 talons +7 (1d6+4), bite +7 (1d8+4)",
                  specialAbilities: "Low-light vision, scent",
                  environment: "Temperate hills and mountains",
                  summary: "A majestic lion-eagle hybrid prized as a flying mount.",
                  desc: "Hippogriffs are large predators with the forebodis of an eagle and the hindquarters of a horse. They nest on rocky cliff faces and hunt across a wide range, attacking horses with particular ferocity. Tamed hippogriffs make exceptional aerial mounts and fetch extraordinary prices in markets where they are available."),

            .make("Ogre", cr: "3", type: "Humanoid (giant)", size: "Large", alignment: "CE",
                  hp: "30 (4d8+12)", ac: 17, speed: "30 ft.",
                  attacks: "Greatclub +8 (2d8+7), or javelin +1 (1d8+5)",
                  specialAbilities: "Darkvision 60 ft., low-light vision",
                  environment: "Temperate hills and mountains",
                  summary: "A large, brutish giant with tremendous physical strength and a violent temper.",
                  desc: "Ogres are enormous bullies who prey on anything weaker than themselves, which is most things. They are not particularly intelligent and tend to solve every problem with brute force. Ogres live in simple caves or ruins, accumulating piles of bones, stolen goods, and half-eaten food. They are frequently dominated or employed by more powerful giants."),

            .make("Sea Hag", cr: "4", type: "Monstrous Humanoid (aquatic)", size: "Medium", alignment: "CE",
                  hp: "38 (7d10)", ac: 14, speed: "30 ft., swim 40 ft.",
                  attacks: "2 claws +8 (1d4+3)",
                  specialAbilities: "Evil eye (1/day, DC 16), horrific appearance (DC 14 Fort or 2d6 Str/Con damage), amphibious",
                  environment: "Temperate and cold aquatic and coastlines",
                  summary: "A hideous aquatic witch who uses dark magic to drive victims to despair.",
                  desc: "Sea hags are malevolent aquatic creatures of terrible ugliness who dwell in coastal caves and sunken ruins. The sight of a sea hag's true face is literally dangerous, capable of draining the life from the weak-willed. They delight in corrupting fishermen and sailors with curses and bargains that always favor the hag."),

            .make("Vampire Spawn", cr: "4", type: "Undead", size: "Medium", alignment: "NE",
                  hp: "22 (4d8+4)", ac: 14, speed: "30 ft.",
                  attacks: "2 slams +5 (1d4+2 plus energy drain)",
                  specialAbilities: "Blood drain, energy drain (DC 14), fast healing 2, gaseous form, spider climb, DR 5/silver, cold/electricity resistance 10, undead traits",
                  environment: "Any",
                  summary: "A lesser vampire bound in servitude to its more powerful vampire lord.",
                  desc: "Vampire spawn are created when a true vampire drains a mortal to death without completing the full ritual that would create a new vampire lord. They are bound absolutely to their creator, unable to resist direct commands. Spawn retain some memories of their living existence, which makes their servitude all the more torturous."),

            .make("Werewolf", cr: "2", type: "Humanoid (human, shapechanger)", size: "Medium", alignment: "CE",
                  hp: "34 (4d8+16)", ac: 17, speed: "30 ft.",
                  attacks: "Longsword +5 (1d8+3), or bite +5 (1d6+3 plus lycanthropy)",
                  specialAbilities: "Change shape, DR 10/silver, lycanthropy (DC 15), low-light vision, scent",
                  environment: "Any",
                  summary: "A humanoid afflicted with the curse of lycanthropy who transforms into a powerful wolf.",
                  desc: "Werewolves are the most feared and widespread of all lycanthropes. In human form they appear normal, often unaware of their condition for years after contracting it. The transformation is painful and complete, producing a powerful wolf-hybrid with supernatural resilience. Many werewolves struggle against their nature while others embrace it fully."),

            .make("Will-o'-Wisp", cr: "6", type: "Aberration (air)", size: "Small", alignment: "CE",
                  hp: "40 (9d8)", ac: 29, speed: "fly 50 ft. (perfect)",
                  attacks: "Shock +12 (2d8 electricity)",
                  specialAbilities: "Immunity to magic (partial), natural invisibility, feed (on fear/despair), darkvision 60 ft.",
                  environment: "Temperate marshes",
                  summary: "A malevolent ball of light that lures travelers into treacherous swamps.",
                  desc: "Will-o'-wisps are ancient, malicious entities that feed on the emotional energy of dying creatures. They manifest as floating, flickering lights in a variety of colors that mimic torches or campfires, luring travelers into bogs and quicksand. They are nearly invulnerable to most magical attacks, making them extraordinarily dangerous despite their size."),

            // MARK: - CR 4

            .make("Centaur", cr: "3", type: "Monstrous Humanoid", size: "Large", alignment: "CG",
                  hp: "26 (4d10+4)", ac: 14, speed: "50 ft.",
                  attacks: "2 hooves +4 (1d6+3), lance +4 (2d6+3), or composite longbow +3 (1d8)",
                  specialAbilities: "Darkvision 60 ft.",
                  environment: "Temperate and warm plains and forests",
                  summary: "A proud half-human, half-horse creature with skill in combat and archery.",
                  desc: "Centaurs are ancient beings who occupy a position between civilization and wild nature, belonging wholly to neither. They form nomadic tribes that roam open plains and forest margins, following the migrations of prey animals. Though they often appear threatening to travelers, many centaur tribes are genuinely honorable and will trade peacefully."),

            .make("Gargoyle", cr: "4", type: "Monstrous Humanoid (earth)", size: "Medium", alignment: "CE",
                  hp: "42 (5d10+15)", ac: 16, speed: "40 ft., fly 60 ft. (average)",
                  attacks: "2 claws +8 (1d6+3), bite +8 (1d4+3), gore +8 (1d4+3)",
                  specialAbilities: "DR 10/magic, darkvision 60 ft., freeze (statue)",
                  environment: "Any warm land",
                  summary: "A winged stone-skinned predator that poses as architectural decoration.",
                  desc: "Gargoyles are intelligent, malicious creatures of living stone who perch motionlessly on buildings and ruins to disguise themselves as decorative statuary. When prey approaches, they reveal themselves in a sudden explosive assault. Their stone hides resist most weapons, and they can sustain significant damage before being brought down."),

            .make("Giant Wasp", cr: "3", type: "Vermin", size: "Large", alignment: "N",
                  hp: "18 (3d8+6)", ac: 14, speed: "20 ft., fly 60 ft. (good)",
                  attacks: "Sting +4 (1d6+3 plus poison)",
                  specialAbilities: "Poison (Dex paralysis, DC 14), darkvision 60 ft.",
                  environment: "Temperate forests",
                  summary: "A horse-sized wasp with a paralyzing sting used to stock its nest with living prey.",
                  desc: "Giant wasps are terrifying aerial predators that hunt in loose groups, paralysing prey with their stingers and dragging it back to underground nests. They lay eggs in their still-living victims, which the hatching larvae consume from within. Their large compound eyes and rapid flight make them difficult to avoid once they begin a pursuit."),

            .make("Green Hag", cr: "5", type: "Monstrous Humanoid", size: "Medium", alignment: "NE",
                  hp: "58 (9d10+9)", ac: 22, speed: "30 ft., swim 30 ft.",
                  attacks: "2 claws +11 (1d4+5 plus weakness)",
                  specialAbilities: "Spell-like abilities, weakness (2d6 Str, DC 16), mimicry, darkvision 90 ft., amphibious",
                  environment: "Cold and temperate marshes and forests",
                  summary: "A malevolent witch of terrifying ugliness who drains the strength from her victims.",
                  desc: "Green hags are ancient, hateful creatures who delight in misery and ruin. They disguise themselves as attractive women to lure victims close before revealing their true forms and draining their strength. Green hags form covens with other hags, multiplying their already-formidable magical power through dark rituals."),

            .make("Minotaur", cr: "4", type: "Monstrous Humanoid", size: "Large", alignment: "CE",
                  hp: "45 (6d10+12)", ac: 14, speed: "30 ft.",
                  attacks: "Greataxe +9 (3d6+6) or gore +9 (1d6+4)",
                  specialAbilities: "Darkvision 60 ft., natural cunning, powerful charge (gore, 2d6+8), scent",
                  environment: "Underground",
                  summary: "A bull-headed giant of immense strength that never gets lost in a maze.",
                  desc: "Minotaurs are fierce, proud creatures with the bodies of large humans and the heads of bulls. They possess an supernatural sense of direction in labyrinthine environments and delight in establishing elaborate maze-lairs in which they hunt intruders. Minotaur culture prizes cunning and fury in equal measure."),

            .make("Owlbear", cr: "4", type: "Magical Beast", size: "Large", alignment: "N",
                  hp: "47 (5d10+20)", ac: 15, speed: "30 ft.",
                  attacks: "2 claws +9 (1d6+5 plus grab), bite +9 (1d6+5)",
                  specialAbilities: "Darkvision 60 ft., low-light vision, scent",
                  environment: "Temperate forests",
                  summary: "A terrifying fusion of owl and bear that is aggressive beyond all reason.",
                  desc: "Owlbears are thought to be the creation of some long-dead wizard who combined the ferocity of a bear with the predatory instincts of an owl. The experiment, whatever its original purpose, escaped to establish itself as a genuine apex predator in temperate forests. Owlbears attack everything they encounter with a fury that seems almost personal."),

            .make("Troll (Young)", cr: "3", type: "Humanoid (giant)", size: "Large", alignment: "CE",
                  hp: "30 (4d8+12)", ac: 13, speed: "30 ft.",
                  attacks: "2 claws +5 (1d6+3), bite +5 (1d6+3)",
                  specialAbilities: "Darkvision 60 ft., low-light vision, rend (2 claws, 1d6+4), regeneration 5 (acid or fire), scent",
                  environment: "Cold mountains",
                  summary: "A smaller troll that already exhibits the terrifying regenerative abilities of its kind.",
                  desc: "Young trolls are nearly as dangerous as adults, regenerating injuries almost as quickly as they are dealt. They are aggressive and territorial, attacking most creatures on sight. Only fire and acid can permanently stop a troll's regeneration, a fact that experienced adventurers keep firmly in mind."),

            .make("Yeth Hound", cr: "3", type: "Outsider (evil, extraplanar)", size: "Large", alignment: "NE",
                  hp: "30 (4d10+8)", ac: 18, speed: "40 ft., fly 60 ft. (good)",
                  attacks: "Bite +8 (2d8+6)",
                  specialAbilities: "Bay (DC 14 Will or panicked), DR 10/silver, darkvision 60 ft., flight",
                  environment: "Neutral evil planes",
                  summary: "A terrifying outsider hound whose howl causes supernatural panic.",
                  desc: "Yeth hounds are extraplanar predators that serve powerful evil entities as hunters and executioners. Their supernatural howl can freeze even brave warriors in their tracks with paralyzing fear. They fly without wings, moving through the air with eerie, silent grace, and their bite wounds do not bleed, making the act of fighting them unnervingly clinical."),

            // MARK: - CR 5

            .make("Barghest", cr: "4", type: "Outsider (evil, extraplanar, lawful, shapechanger)", size: "Medium", alignment: "LE",
                  hp: "33 (6d10)", ac: 17, speed: "30 ft.",
                  attacks: "Bite +8 (1d6+3), 2 claws +8 (1d4+3)",
                  specialAbilities: "Change shape (goblin or wolf), feed (soul consumption to grow), pass without trace, spell-like abilities, darkvision 60 ft.",
                  environment: "Lawful evil planes",
                  summary: "A fiendish shapechanger that infiltrates goblin tribes to devour souls.",
                  desc: "Barghests are outsiders sent to the Material Plane to feed on mortal souls, growing in power with each spirit consumed. They disguise themselves as large wolves or as goblins, leading tribes and manipulating situations to create opportunities for slaughter. As they grow, they advance in power until they can return to their home plane as full Greater Barghests."),

            .make("Basilisk", cr: "5", type: "Magical Beast", size: "Medium", alignment: "N",
                  hp: "52 (7d10+14)", ac: 16, speed: "20 ft.",
                  attacks: "Bite +10 (2d6+6)",
                  specialAbilities: "Darkvision 60 ft., low-light vision, petrifying gaze (DC 15 Fort or permanently petrified)",
                  environment: "Warm and temperate deserts and underground",
                  summary: "An eight-legged lizard with a gaze that turns flesh to stone.",
                  desc: "The basilisk is a legendary predator feared throughout civilized lands for its petrifying gaze. A creature that meets its eyes is transformed to stone, and the basilisk's lair is typically ringed with the stony remains of its past victims. Ointment made from basilisk blood can reverse petrification, making basilisk hunting a lucrative if lethal profession."),

            .make("Bulette", cr: "7", type: "Magical Beast", size: "Huge", alignment: "N",
                  hp: "84 (9d10+36)", ac: 22, speed: "40 ft., burrow 20 ft.",
                  attacks: "Bite +13 (2d8+8), 2 claws +13 (2d6+8)",
                  specialAbilities: "Darkvision 60 ft., low-light vision, scent, leap, tremorsense 60 ft.",
                  environment: "Temperate hills and plains",
                  summary: "A massive armored predator that burrows through earth to erupt beneath prey.",
                  desc: "The bulette, often called the landshark, is one of the most feared predators in any region it inhabits. Its heavily armored hide deflects most weapons, and its powerful legs allow it to leap great distances to reach prey. Bulettes consume nearly anything organic and are responsible for the destruction of entire farming communities."),

            .make("Cyclops", cr: "5", type: "Humanoid (giant)", size: "Large", alignment: "CN",
                  hp: "60 (8d8+24)", ac: 16, speed: "30 ft.",
                  attacks: "Greatclub +12 (2d6+9) or rock +8 (2d6+9)",
                  specialAbilities: "Darkvision 60 ft., limited precognition (1/day, reroll die roll), low-light vision",
                  environment: "Warm coastlines and mountains",
                  summary: "A single-eyed giant with a limited precognitive ability from its unique gaze.",
                  desc: "Cyclopes are giant solitary creatures with a single large eye that grants them a limited prophetic vision. In ages past they maintained a great empire through this gift, but long decades of degeneracy and inbreeding have reduced most to lonely savages. Modern cyclopes are melancholic and violent, mourning a greatness they dimly remember."),

            .make("Giant Scorpion", cr: "3", type: "Vermin", size: "Large", alignment: "N",
                  hp: "40 (7d8+7)", ac: 16, speed: "50 ft.",
                  attacks: "2 claws +6 (1d6+3 plus grab), sting +6 (1d6+3 plus poison)",
                  specialAbilities: "Constrict (1d6+3), darkvision 60 ft., poison (Con damage, DC 18)",
                  environment: "Warm and temperate deserts and underground",
                  summary: "A car-sized scorpion with crushing claws and a lethal venomous sting.",
                  desc: "Giant scorpions are apex predators of hot, arid environments. They hunt by vibration, grabbing prey with powerful claws and delivering a venomous sting to the captive creature. Their venom attacks the constitution directly, capable of slaying even a healthy warrior who receives multiple stings in rapid succession."),

            .make("Lamia", cr: "6", type: "Magical Beast", size: "Large", alignment: "CE",
                  hp: "67 (9d10+18)", ac: 20, speed: "40 ft.",
                  attacks: "2 claws +13 (1d4+5 plus Wisdom drain), touch +13 (Wisdom drain)",
                  specialAbilities: "Darkvision 60 ft., low-light vision, spell-like abilities, Wisdom drain (2d4)",
                  environment: "Warm deserts",
                  summary: "A lion-bodied seductress with a serpentine lower body who drains wisdom.",
                  desc: "Lamias appear as beautiful women from the waist up merging into powerful leonine bodies below. They lure prey with illusory beauty and then drain their victims' minds, leaving them pliable and hollow. Lamias rule desert tribes through a combination of supernatural charisma and the constant threat of their wisdom-stealing touch."),

            .make("Manticore", cr: "5", type: "Magical Beast", size: "Large", alignment: "LE",
                  hp: "57 (6d10+24)", ac: 17, speed: "30 ft., fly 50 ft. (clumsy)",
                  attacks: "2 claws +8 (2d4+5), bite +8 (1d8+5)",
                  specialAbilities: "Darkvision 60 ft., low-light vision, tail spikes (24 spikes, +8 ranged, 1d8+2, 180 ft.)",
                  environment: "Warm hills and marshes",
                  summary: "A lion-bodied, bat-winged monster with a human face and a spike-shooting tail.",
                  desc: "Manticores are vicious creatures that combine features of multiple animals into a whole greater than the sum of its parts. They hunt from the air, softening prey with volleys of tail spikes before diving in for the kill. Manticores speak a crude form of Common and sometimes parley with potential prey, though usually only to make the hunting more interesting."),

            .make("Mummy", cr: "5", type: "Undead", size: "Medium", alignment: "LE",
                  hp: "60 (8d8+24)", ac: 20, speed: "20 ft.",
                  attacks: "Slam +14 (1d8+10 plus mummy rot)",
                  specialAbilities: "Despair (DC 16 Will or paralyzed 1d4 rounds), DR 5/—, mummy rot (DC 16 Con damage), darkvision 60 ft., undead traits, vulnerability to fire",
                  environment: "Any land",
                  summary: "A bandaged undead guardian of ancient tombs that spreads a desiccating curse.",
                  desc: "Mummies are undead guardians created through elaborate preservation rituals to defend tombs and sacred places. They are wrapped in preserved linen and carry the accumulated hatred of their long vigil against the living. Their touch spreads mummy rot, a disease that rapidly desiccates flesh and is difficult to cure without magical intervention."),

            .make("Troll", cr: "5", type: "Humanoid (giant)", size: "Large", alignment: "CE",
                  hp: "63 (6d8+36)", ac: 16, speed: "30 ft.",
                  attacks: "2 claws +9 (1d6+6 plus rend), bite +9 (1d6+6)",
                  specialAbilities: "Darkvision 60 ft., low-light vision, rend (2 claws, 1d6+9), regeneration 5 (acid or fire), scent",
                  environment: "Cold mountains",
                  summary: "A lanky giant with rubbery flesh that regenerates at a terrifying rate.",
                  desc: "Trolls are among the most feared of all giants, not for their intelligence (which is meager) but for their extraordinary regeneration. A troll hacked to pieces in one round will reassemble itself the next unless the pieces are destroyed with fire or acid. This makes them extraordinarily difficult to permanently slay, and many a dungeon party has been slaughtered by a troll they believed defeated."),

            // MARK: - CR 6

            .make("Bearded Devil (Barbazu)", cr: "6", type: "Outsider (devil, evil, extraplanar, lawful)", size: "Medium", alignment: "LE",
                  hp: "57 (6d10+24)", ac: 21, speed: "40 ft.",
                  attacks: "Glaive +10 (1d10+6 plus bleed), beard +10 (1d8+3 plus beard infection)",
                  specialAbilities: "Beard infection (DC 17, Fort), bleed (1d6), DR 10/good or silver, immunity to fire/poison, resistance to acid/cold 10, see in darkness",
                  environment: "Lawful evil planes",
                  summary: "A devil warrior with a writhing, infectious beard and a serrated glaive.",
                  desc: "Bearded devils are the brutal shock troops of Hell's armies, warriors who exist to kill and to train other soldiers in the art of killing. Their beards are animate masses of wiry filaments tipped with hooks, and the wounds they inflict resist healing through infernal magic. They are aggressive, contemptuous of weakness, and completely loyal to their pit fiend commanders."),

            .make("Chimera", cr: "7", type: "Magical Beast", size: "Large", alignment: "CE",
                  hp: "85 (9d10+36)", ac: 19, speed: "30 ft., fly 50 ft. (poor)",
                  attacks: "Bite +12 (2d6+5), gore +12 (1d8+5), 2 claws +12 (1d6+5)",
                  specialAbilities: "Darkvision 60 ft., low-light vision, scent, breath weapon (dragon type varies, 2/day)",
                  environment: "Temperate hills and mountains",
                  summary: "A three-headed monster combining a lion, a goat, and a dragon.",
                  desc: "The chimera is a legendary monster with a lion's forequarters, a goat's head growing from its back, and a dragon's head at the end of a scaled neck. Its dragon head can breathe fire, acid, cold, electricity, or poison depending on the individual. Chimeras are aggressive, territorial predators that lair in cave systems and mountain passes."),

            .make("Cloaker", cr: "5", type: "Aberration", size: "Large", alignment: "CN",
                  hp: "51 (6d8+24)", ac: 19, speed: "10 ft., fly 40 ft. (average)",
                  attacks: "Tail slap +8 (1d6+5), moan (DC 14 Will), engulf",
                  specialAbilities: "Darkvision 60 ft., engulf (1d6+5 plus suffocation), moan (DC 14 Will, effect varies), shadow shift",
                  environment: "Underground",
                  summary: "A manta-like aberration that mimics dungeon floors and swallows prey whole.",
                  desc: "Cloakers are manta-shaped aberrations that hang from ceilings or sprawl across floors of dungeons and caves, mimicking piles of old cloaks or sections of natural rock. When prey ventures close, they attack with a lashing tail and wrap their bodies around victims to engulf them. Their moan ability creates supernatural fear in those who hear it."),

            .make("Dire Lion", cr: "5", type: "Animal", size: "Large", alignment: "N",
                  hp: "60 (8d8+24)", ac: 15, speed: "40 ft.",
                  attacks: "2 claws +11 (1d6+5), bite +11 (1d8+5)",
                  specialAbilities: "Low-light vision, pounce, rake (2 claws, 1d6+5), scent",
                  environment: "Warm plains",
                  summary: "A massive prehistoric lion with devastating pounce and rake attacks.",
                  desc: "Dire lions are enormous predators that dwarf their mundane cousins. They hunt alone or in small groups, ambushing prey from tall grass with a terrifying pounce. A dire lion that brings down prey rolls it flat and uses its powerful rear claws to disembowel it before the creature can recover. They are apex predators with no natural enemies."),

            .make("Ettin", cr: "6", type: "Humanoid (giant)", size: "Large", alignment: "CE",
                  hp: "65 (10d8+20)", ac: 18, speed: "40 ft.",
                  attacks: "2 clubs +10/+5 (2d6+6)",
                  specialAbilities: "Low-light vision, two-weapon fighting (natural two heads), superior two-weapon fighting",
                  environment: "Cold and temperate hills and mountains",
                  summary: "A two-headed giant that can fight with two weapons simultaneously with great effect.",
                  desc: "Ettins are two-headed giants whose two personalities are usually in constant bickering argument but cooperate reasonably well in a fight. Each head controls one arm, allowing them to fight with two weapons more naturally than other giants. Ettins are among the most social of giant-kin, sometimes leading warbands of orcs or bugbears."),

            .make("Hill Giant", cr: "7", type: "Humanoid (giant)", size: "Large", alignment: "CE",
                  hp: "85 (10d8+40)", ac: 20, speed: "40 ft.",
                  attacks: "Greatclub +14/+9 (2d8+13) or rock +8 (2d6+8)",
                  specialAbilities: "Low-light vision, rock catching, rock throwing (120 ft.)",
                  environment: "Temperate hills",
                  summary: "The least of the true giants, a brutish creature that bullies everything smaller than itself.",
                  desc: "Hill giants are the smallest and most common of the true giants, dwelling in rocky highland regions and raiding the lowland farms and villages. They are slovenly, brutish, and cruel, organizing themselves into loose clans ruled by the largest individual. Hill giants sometimes ally with ogres or orcs when planning particularly ambitious raids."),

            .make("Medusa", cr: "7", type: "Monstrous Humanoid", size: "Medium", alignment: "LE",
                  hp: "76 (8d10+32)", ac: 15, speed: "30 ft.",
                  attacks: "Shortbow +11/+6 (1d6), dagger +8/+3 (1d4), snakes +8 (1d4 plus poison)",
                  specialAbilities: "Darkvision 60 ft., petrifying gaze (DC 16 Fort), poison (Str damage, DC 16)",
                  environment: "Temperate marshes and underground",
                  summary: "A snake-haired monster whose gaze permanently petrifies victims.",
                  desc: "Medusas appear as beautiful humans from a distance, with only the writhing mass of vipers where hair should be betraying their nature. Their gaze is among the most feared effects in the natural world — a single prolonged look results in permanent petrification. Medusas are vain and highly intelligent, often ruling domains of stone statues that were once adventurers."),

            .make("Mimic", cr: "4", type: "Aberration", size: "Medium", alignment: "N",
                  hp: "52 (7d8+21)", ac: 12, speed: "10 ft.",
                  attacks: "2 slams +8 (1d8+4 plus adhesive)",
                  specialAbilities: "Adhesive (DC 16 Str to break free), crush, darkvision 60 ft., mimic shape, immunity to acid",
                  environment: "Underground",
                  summary: "A shapeshifting predator that disguises itself as a chest or door to ambush prey.",
                  desc: "Mimics are strange creatures capable of reshaping their bodies to precisely imitate any object made of stone, metal, or wood. They most commonly adopt the form of treasure chests, knowing that adventurers will approach with less caution. Once a limb or weapon contacts their adhesive surface, the mimic reveals itself with violent speed."),

            .make("Shadow Demon", cr: "7", type: "Outsider (chaotic, demon, evil, extraplanar, incorporeal)", size: "Medium", alignment: "CE",
                  hp: "59 (9d10+9)", ac: 23, speed: "fly 40 ft. (perfect)",
                  attacks: "2 claws +12 (1d6 Str damage)",
                  specialAbilities: "Incorporeal, light vulnerability, shadow blend, DR 10/cold iron or good, immune to cold/fire/lightning",
                  environment: "Chaotic evil planes",
                  summary: "A demon of living shadow that drains strength from its victims.",
                  desc: "Shadow demons are incorporeal fiends who exist as animate malevolent darkness. They thrive in conditions of low light and become nearly invisible in shade or darkness. Their claws pass through armor to drain strength directly from their victims. Exposure to bright sunlight weakens them significantly."),

            .make("Vampire", cr: "9", type: "Undead (augmented humanoid)", size: "Medium", alignment: "NE",
                  hp: "93 (11d8+44)", ac: 24, speed: "30 ft.",
                  attacks: "Slam +13 (1d4+6 plus energy drain)",
                  specialAbilities: "Blood drain (1d4 Con drain), children of the night, create spawn, dominate (DC 18 Will), energy drain (2 levels, DC 18), gaseous form, spider climb, DR 10/magic and silver, fast healing 5, resistance to cold/electricity 10, undead traits",
                  environment: "Any",
                  summary: "An immortal undead predator that drains blood and dominates the minds of mortals.",
                  desc: "Vampires are the pinnacle of corporeal undead, retaining their intelligence and personality from life while gaining tremendous supernatural power. They are bound by significant weaknesses but possess an almost unparalleled combination of physical and mental abilities. The creation of a new vampire lord is always an event that reshapes the power dynamics of an entire region."),

            // MARK: - CR 7

            .make("Bone Devil (Osyluth)", cr: "9", type: "Outsider (devil, evil, extraplanar, lawful)", size: "Large", alignment: "LE",
                  hp: "105 (10d10+50)", ac: 25, speed: "40 ft., fly 60 ft. (average)",
                  attacks: "Bite +14 (2d6+7), 2 claws +14 (1d8+7), tail +14 (3d4+3 plus poison)",
                  specialAbilities: "Interrogation, see in darkness, DR 10/good, immunity to fire/poison, resistance to acid/cold 10, telepathy 100 ft.",
                  environment: "Lawful evil planes",
                  summary: "An interrogation specialist devil with a scorpion tail and fearsome claws.",
                  desc: "Bone devils serve Hell's bureaucracy as interrogators and spies, moving between the planes to extract information or carry out targeted assassinations. Their skeletal frames are deceptively resilient, and their scorpion-like tails deliver powerful venom. Osyluths are obsessively dedicated to the precise letter of any agreement, never lying outright but capable of extraordinary deception."),

            .make("Fire Giant", cr: "10", type: "Humanoid (giant)", size: "Large", alignment: "LE",
                  hp: "142 (15d8+75)", ac: 27, speed: "40 ft.",
                  attacks: "Greatsword +22/+17/+12 (3d6+13) or rock +16 (2d6+9)",
                  specialAbilities: "Immunity to fire, low-light vision, rock catching, rock throwing (60 ft.)",
                  environment: "Warm mountains",
                  summary: "A disciplined giant warrior with coal-black skin and immunity to fire.",
                  desc: "Fire giants are among the most dangerous of all giant-kin, combining military discipline with the raw physical power common to all giants. They inhabit volcanic regions and build fortress-cities of dark stone. Fire giant society is highly stratified and militaristic, and their warbands are a genuine match for organized armies."),

            .make("Frost Giant", cr: "9", type: "Humanoid (giant, cold)", size: "Large", alignment: "CE",
                  hp: "133 (14d8+70)", ac: 21, speed: "40 ft.",
                  attacks: "Greataxe +19/+14/+9 (3d6+13) or rock +13 (2d6+8)",
                  specialAbilities: "Immunity to cold, low-light vision, rock catching, rock throwing (120 ft.), vulnerability to fire",
                  environment: "Cold mountains",
                  summary: "A Viking-like ice giant with pale blue skin and a love of raiding.",
                  desc: "Frost giants are fierce raiders who dominate cold mountain regions, launching seasonal raids on lowland settlements. They value strength and combat prowess above all else, with their leaders typically being the most powerful warriors. Frost giants are immune to cold but vulnerable to fire, a weakness their enemies exploit whenever possible."),

            .make("Ghost", cr: "7", type: "Undead (augmented humanoid, incorporeal)", size: "Medium", alignment: "Any",
                  hp: "58 (9d8+18)", ac: 15, speed: "fly 30 ft. (perfect)",
                  attacks: "Corrupting touch +7 (7d6)",
                  specialAbilities: "Corrupting touch (7d6), frightful moan (DC 16 Will), malevolence (DC 16 Will), manifestation, rejuvenation, telekinesis, darkvision 60 ft., incorporeal",
                  environment: "Any",
                  summary: "The lingering spirit of the dead, tied to the mortal world by unfinished business.",
                  desc: "Ghosts are the restless spirits of the deceased, unable to pass on to the afterlife due to some powerful emotional attachment or unresolved purpose. They manifest in the locations of their deaths or in places significant to their lives. Ghosts are extraordinarily difficult to permanently destroy, reforming after defeat unless the underlying cause of their haunting is resolved."),

            .make("Girallon", cr: "6", type: "Magical Beast", size: "Large", alignment: "N",
                  hp: "69 (9d10+18)", ac: 16, speed: "40 ft., climb 40 ft.",
                  attacks: "4 claws +12 (1d4+4), bite +12 (1d6+4)",
                  specialAbilities: "Low-light vision, rend (2 claws, 2d4+6), scent",
                  environment: "Warm forests and hills",
                  summary: "A four-armed white ape of terrifying size and strength.",
                  desc: "Girallons are massive white-furred apes with four arms, each ending in powerful hands with retractable claws. They inhabit thick jungles and ancient ruins, frequently venerated by local tribes as sacred guardians. A girallon that grabs prey with multiple limbs can tear it apart with frightening speed."),

            .make("Oni (Ogre Mage)", cr: "8", type: "Outsider (giant, native, oni)", size: "Large", alignment: "LE",
                  hp: "104 (11d10+44)", ac: 20, speed: "40 ft., fly 60 ft. (good)",
                  attacks: "Greatsword +14/+9 (3d6+8) or longbow +9/+4 (2d6)",
                  specialAbilities: "Spell-like abilities (cone of cold, darkness, charm monster, change shape, fly, gaseous form, invisibility), regen 5 (fire/acid), darkvision 60 ft., low-light vision",
                  environment: "Cold and temperate mountains and hills",
                  summary: "A powerful giant-blooded outsider with significant magical abilities.",
                  desc: "Ogre mages are the most sophisticated and dangerous of oni, possessing a broad array of magical abilities that make them effective leaders of goblinoid armies and formidable individual opponents. They are long-lived and patient, often working toward goals that span decades. An ogre mage can regenerate from wounds that would kill lesser creatures."),

            .make("Wyvern", cr: "6", type: "Dragon", size: "Large", alignment: "N",
                  hp: "73 (7d12+28)", ac: 18, speed: "20 ft., fly 60 ft. (poor)",
                  attacks: "Sting +10 (1d6+4 plus poison), bite +10 (2d6+4), 2 talons +10 (2d6+4)",
                  specialAbilities: "Darkvision 60 ft., immunity to sleep and paralysis, low-light vision, poison (Con damage, DC 17)",
                  environment: "Warm hills and mountains",
                  summary: "A two-legged, venomous dragon-kin with a deadly tail stinger.",
                  desc: "Wyverns are distant cousins of true dragons, lacking their intelligence and breath weapons but compensating with powerful physical attacks and venomous tail stingers. They are territorial aerial predators that rule their assigned peaks with aggressive ferocity. Wyverns can be trained, though the process is dangerous, and serve as mounts for powerful warriors who can dominate them."),

            // MARK: - CR 8

            .make("Barbed Devil (Hamatula)", cr: "11", type: "Outsider (devil, evil, extraplanar, lawful)", size: "Medium", alignment: "LE",
                  hp: "138 (12d10+72)", ac: 26, speed: "30 ft.",
                  attacks: "2 claws +18 (2d8+7 plus fear and grab)",
                  specialAbilities: "Barbed hide (1d6+3 piercing to grappler), fear (DC 22 Will), constrictive grip, DR 10/good, immunity to fire/poison, see in darkness",
                  environment: "Lawful evil planes",
                  summary: "A devil covered in sharp barbs that impales those who attack or grapple with it.",
                  desc: "Hamatulas are the jailers and torturers of Hell, guarding its most precious prisoners with pitiless efficiency. Their bodies are covered in razor-sharp barbs that injure anyone who strikes or grapples them. Those who look upon a hamatula too long experience waves of supernatural fear. They are methodical and sadistic in equal measure."),

            .make("Night Hag", cr: "9", type: "Outsider (evil, extraplanar)", size: "Medium", alignment: "NE",
                  hp: "92 (8d10+48)", ac: 22, speed: "30 ft.",
                  attacks: "2 claws +13 (1d4+4 plus disease), bite +13 (2d6+4)",
                  specialAbilities: "Dream haunting, ethereal jaunt, heartstone, DR 10/cold iron and magic, immunity to cold/charm/sleep/fear, resistance to fire/electricity 10",
                  environment: "Neutral evil planes",
                  summary: "A terrifying fiendish hag that invades dreams to drive mortals to madness and death.",
                  desc: "Night hags are powerful outsiders who harvest the souls of mortals for trade in infernal markets. They use their dream haunting ability to torment sleeping victims over many nights, drawing out their suffering until they die in their sleep. Night hags collect soul gems as currency and have developed elaborate networks of trade among all the dark planes."),

            .make("Rakshasa", cr: "10", type: "Outsider (native, shapechanger)", size: "Medium", alignment: "LE",
                  hp: "115 (11d10+55)", ac: 25, speed: "40 ft.",
                  attacks: "2 claws +14 (1d4+2 plus detect thoughts), bite +14 (1d6+2)",
                  specialAbilities: "Change shape, detect thoughts (DC 18 Will), DR 15/good and piercing, immunity to mind-affecting effects (below 7th-level), all spell-like abilities",
                  environment: "Any",
                  summary: "A shapeshifting outsider of immense magical power that craves mastery over mortals.",
                  desc: "Rakshasas are ancient fiendish beings who reincarnate repeatedly across lifetimes of mortal flesh. They are master manipulators who use their shapechanging and mind-reading abilities to insert themselves into positions of power in mortal society. Their unique DR makes them extremely difficult to harm through mundane means."),

            .make("Stone Giant", cr: "8", type: "Humanoid (giant)", size: "Large", alignment: "N",
                  hp: "102 (12d8+48)", ac: 25, speed: "40 ft.",
                  attacks: "Greatclub +17/+12 (2d8+11) or rock +14 (2d8+7)",
                  specialAbilities: "Low-light vision, rock catching, rock throwing (180 ft.), stone camouflage",
                  environment: "Cold and temperate mountains",
                  summary: "A reclusive, stony-skinned giant with extraordinary rock-throwing precision.",
                  desc: "Stone giants are the most reclusive of all true giants, dwelling deep in mountain caves and rarely venturing into the lowlands. They revere stone and view themselves as its living embodiment. Stone giants are exceptional rock throwers, capable of hitting targets at remarkable distances with almost casual accuracy. They are not inherently malicious, but they guard their territories fiercely."),

            .make("Storm Giant", cr: "13", type: "Humanoid (giant)", size: "Huge", alignment: "CG",
                  hp: "230 (20d8+140)", ac: 28, speed: "50 ft., swim 40 ft.",
                  attacks: "Greatsword +26/+21/+16/+11 (4d6+15) or rock +20 (2d8+10)",
                  specialAbilities: "Immunity to electricity and cold, low-light vision, rock catching, rock throwing (200 ft.), spell-like abilities (call lightning, chain lightning, control weather, levitate), underwater mobility",
                  environment: "Warm mountains and aquatic",
                  summary: "The most powerful of all true giants, commanding storms and lightning.",
                  desc: "Storm giants are the mightiest of all giantkind, dwelling in isolated mountain peaks and undersea palaces. They have an affinity for storms and the sea, commanding lightning and weather as naturally as breathing. Storm giants are generally benevolent and take a long view of the world's events, occasionally serving as mediators in conflicts between lesser races."),

            // MARK: - CR 9

            .make("Aboleth", cr: "7", type: "Aberration (aquatic)", size: "Huge", alignment: "LE",
                  hp: "105 (14d8+42)", ac: 16, speed: "10 ft., swim 60 ft.",
                  attacks: "4 tentacles +12 (1d8+6 plus slime)",
                  specialAbilities: "Enslave (DC 17 Will), mucus cloud (DC 20), slime (DC 20, skin becomes transparent, must stay wet), spell-like abilities, telepathy 300 ft., darkvision 60 ft.",
                  environment: "Underground aquatic",
                  summary: "An ancient, tentacled aberration of staggering psionic power and sinister intellect.",
                  desc: "Aboleths are among the oldest intelligent beings on the planet, their memory stretching back to before the age of the gods. They view all other creatures as either slaves or food. Their mucus can transform flesh into a slimy membrane that must stay constantly wet, allowing aboleths to maintain control over enslaved air-breathing creatures. They dwell in sunless underground lakes."),

            .make("Froghemoth", cr: "13", type: "Aberration", size: "Huge", alignment: "N",
                  hp: "161 (14d8+98)", ac: 19, speed: "20 ft., swim 30 ft.",
                  attacks: "4 tentacles +19 (2d6+8 plus grab), bite +19 (4d6+8), tongue +14 (grab, 30 ft.)",
                  specialAbilities: "Electricity resistance 20, swallow whole (2d6+8 bludgeon plus 1d6 acid, AC 16, 16 hp), amphibious, darkvision 60 ft.",
                  environment: "Temperate marshes",
                  summary: "A massive alien frog-beast with tentacles, a sticky tongue, and an insatiable appetite.",
                  desc: "Froghemoths are clearly not of this world, their alien physiology suggesting an origin on a distant plane or perhaps from beyond the stars. They are ambush predators of terrifying size, lurking in deep swamps with only their eyestalks visible above the waterline. A froghemoth's appetite is matched only by its resilience."),

            .make("Glabrezu", cr: "13", type: "Outsider (chaotic, demon, evil, extraplanar)", size: "Huge", alignment: "CE",
                  hp: "186 (12d10+120)", ac: 27, speed: "40 ft.",
                  attacks: "2 pincers +19 (2d8+8 plus grab), 2 claws +19 (1d6+8), bite +19 (1d8+8)",
                  specialAbilities: "Spell-like abilities (power word stun, reverse gravity, confusion, etc.), DR 10/good, immunity to electricity/poison, resistance to acid/cold/fire 10, true seeing, telepathy 100 ft.",
                  environment: "Chaotic evil planes",
                  summary: "A four-armed demon lord that grants wishes as a trap for mortals.",
                  desc: "Glabrezus are treachery demons who specialize in corrupting mortals through the granting of wishes. They approach desperate humans in the guise of friendly outsiders, offering to grant desires in exchange for small favors that escalate into ruinous corruption. In their true form they are enormous four-armed demons of extraordinary power."),

            // MARK: - CR 10

            .make("Clay Golem", cr: "10", type: "Construct", size: "Large", alignment: "N",
                  hp: "96 (12d10+30)", ac: 22, speed: "30 ft.",
                  attacks: "2 slams +14 (2d10+7)",
                  specialAbilities: "Berserk (10% chance, attacks nearest), DR 10/adamantine, immunity to magic (most spells), haste (after taking fire or electricity damage), cursed wound (healed only by cure spells, no natural healing)",
                  environment: "Any",
                  summary: "A lumbering construct of shaped clay animated by ancient magical processes.",
                  desc: "Clay golems are massive constructs created by powerful clerics and wizards to serve as tireless, unkillable guardians. Their clay bodies are inscribed with magical runes that power their animation. Clay golems have a disturbing tendency to go berserk when damaged, attacking the nearest creature regardless of allegiance."),

            .make("Retriever", cr: "11", type: "Construct (extraplanar)", size: "Huge", alignment: "CE",
                  hp: "144 (12d10+78)", ac: 22, speed: "50 ft.",
                  attacks: "4 claws +18 (2d6+9), bite +18 (2d8+9)",
                  specialAbilities: "Eye rays (fire/cold/electricity/petrifaction, 100 ft., DC 20), find target (tracks any creature it has been set to find), DR 10/good",
                  environment: "Chaotic evil planes",
                  summary: "A massive spider-like construct built by demons to hunt and retrieve targets.",
                  desc: "Retrievers are enormous mechanical spiders crafted by the demon princes to track and return specific targets, alive or dead. Once given a target, a retriever will cross planes, oceans, and continents without rest until it locates and returns its quarry. Their multiple eye rays make them versatile and extremely difficult combatants."),

            .make("Stone Golem (Lesser)", cr: "11", type: "Construct", size: "Large", alignment: "N",
                  hp: "107 (14d10+30)", ac: 26, speed: "20 ft.",
                  attacks: "2 slams +17 (2d10+9)",
                  specialAbilities: "DR 10/adamantine, immunity to magic (most), slow (DC 17, as spell), haste (after taking cold damage)",
                  environment: "Any",
                  summary: "A massive construct carved from solid stone, nearly immune to magic.",
                  desc: "Stone golems are among the most durable of all constructs, their stone bodies providing enormous natural armor and their magical immunity making them nearly impossible to harm through spells. They are created by powerful wizards and noble houses as the ultimate guardians, placed in vaults and important rooms to eliminate intruders. A stone golem's slow attack can cripple even experienced adventurers."),

            // MARK: - CR 11

            .make("Horned Devil (Cornugon)", cr: "16", type: "Outsider (devil, evil, extraplanar, lawful)", size: "Large", alignment: "LE",
                  hp: "217 (15d10+135)", ac: 35, speed: "30 ft., fly 50 ft. (average)",
                  attacks: "Spiked chain +22/+17/+12 (2d6+14 plus stun), 2 claws +22 (2d6+9 plus 1d6 fire), bite +22 (2d8+9 plus poison), tail +17 (2d6+4)",
                  specialAbilities: "Fear (DC 25 Will), poison (Str damage, DC 27), stun (DC 26 Fort), DR 15/good and silver, immunity to fire/poison, regeneration 5 (good weapons/spells), see in darkness, telepathy 100 ft.",
                  environment: "Lawful evil planes",
                  summary: "A massive winged devil general that commands armies in Hell's hierarchy.",
                  desc: "Cornugons are among the most powerful of true devils, serving as commanders and generals in Hell's disciplined legions. Their spiked chains are weapons of exquisite cruelty, and their stun ability can drop opponents before they can react. Horned devils are favored generals of the archdevils, trusted with missions that require both power and discretion."),

            // MARK: - CR 12

            .make("Lich", cr: "12", type: "Undead (augmented humanoid)", size: "Medium", alignment: "NE",
                  hp: "111 (13d8+52)", ac: 26, speed: "30 ft.",
                  attacks: "Touch +11 (1d8+5 plus paralyzing touch)",
                  specialAbilities: "Paralyzing touch (DC 18 Fort), fear aura (DC 18 Will), DR 15/bludgeoning and magic, immunity to cold/electricity and undead traits, phylactery (rejuvenation), channel resistance +4, damage reduction, spells as 13th-level wizard",
                  environment: "Any land",
                  summary: "A powerful undead archmage who has sacrificed mortality for immortality and power.",
                  desc: "Liches are spellcasters who have willingly undergone a horrifying ritual of transformation to achieve immortality through undeath. They store their life essence in a hidden phylactery, returning to unlife even if their bodies are destroyed. Liches pursue long-term magical research and power accumulation with the patience available only to those who cannot die."),

            .make("Remorhaz", cr: "7", type: "Magical Beast", size: "Huge", alignment: "N",
                  hp: "80 (7d10+42)", ac: 20, speed: "30 ft., burrow 20 ft.",
                  attacks: "Bite +15 (2d8+12 plus grab)",
                  specialAbilities: "Swallow whole (2d8+8 fire plus 8 fire damage per round, AC 15, 8 hp), heat (fire damage to attackers in melee), darkvision 60 ft., tremorsense 60 ft.",
                  environment: "Cold mountains",
                  summary: "A massive centipede-like predator whose body burns with intense heat.",
                  desc: "Remorphazes are enormous white-furred predators with superheated bodies that generate intense warmth despite living in polar environments. Their undersides glow with internal heat that melts ice and snow, and attacking them in melee risks severe burns. They can swallow prey whole, where internal heat finishes what the bite began."),

            // MARK: - CR 13

            .make("Adult Red Dragon", cr: "13", type: "Dragon (fire)", size: "Huge", alignment: "CE",
                  hp: "184 (16d12+80)", ac: 29, speed: "40 ft., fly 200 ft. (poor)",
                  attacks: "Bite +22 (2d8+12), 2 claws +22 (2d6+8), 2 wings +20 (1d8+4), tail +20 (2d6+12)",
                  specialAbilities: "Breath weapon (50 ft. cone of fire, 14d10, DC 24 Ref), crush, frightful presence (DC 22 Will), fire immunity, spell-like abilities, spells as 7th-level sorcerer, locate object, darkvision 60 ft., blindsense 60 ft.",
                  environment: "Warm mountains",
                  summary: "A supremely powerful fire-breathing dragon of immense pride and cruelty.",
                  desc: "Adult red dragons are among the most feared creatures on the Material Plane. They are supremely arrogant, viewing all other creatures as subjects, slaves, or food. Their hoards are legendary in size, and they defend them with apocalyptic fury. Red dragons demand tribute from nearby settlements and destroy those who refuse without hesitation."),

            .make("Demilich", cr: "14", type: "Undead", size: "Tiny", alignment: "NE",
                  hp: "136 (21d8+42)", ac: 23, speed: "fly 30 ft. (perfect)",
                  attacks: "Touch +18 (soul trap, DC 20 Will)",
                  specialAbilities: "Soul trap (DC 20 Will), avoidance, perfect incorporeality, immunity (all spells up to 8th), turn resistance +20, 80% spell failure for spells above 8th level, darkvision 60 ft.",
                  environment: "Any land",
                  summary: "A withered lich skull of incredible power that traps souls in its gem teeth.",
                  desc: "A demilich forms when an ancient lich withdraws its consciousness from the physical world, leaving behind only its skull, which transforms over centuries into a gem-encrusted artifact of terrifying power. Demiliches have transcended most physical vulnerabilities and exist in a state of power that makes them nearly unkillable. Their soul-trapping ability can eliminate enemies instantaneously."),

            .make("Iron Golem", cr: "13", type: "Construct", size: "Large", alignment: "N",
                  hp: "129 (18d10+35)", ac: 30, speed: "20 ft.",
                  attacks: "2 slams +24 (2d10+11)",
                  specialAbilities: "Breath weapon (10 ft. cube of poison gas, 1d4 Con/round, DC 19), DR 15/adamantine, immunity to magic (nearly all), haste (after electricity exposure)",
                  environment: "Any",
                  summary: "A massive construct of enchanted iron with a poisonous breath weapon.",
                  desc: "Iron golems are among the most powerful of all golems, constructed from thousands of pounds of solid iron and animated by powerful magic sealed within a small furnace heart. They are virtually immune to physical and magical attacks. Their poison breath can incapacitate entire groups of adventurers, and only the most powerful weapons can penetrate their iron hides."),

            // MARK: - CR 15

            .make("Adult Gold Dragon", cr: "15", type: "Dragon (fire)", size: "Huge", alignment: "LG",
                  hp: "248 (19d12+114)", ac: 31, speed: "60 ft., fly 200 ft. (poor), swim 60 ft.",
                  attacks: "Bite +26 (2d8+13), 2 claws +26 (2d6+9), 2 wings +24 (1d8+4), tail +24 (2d6+13)",
                  specialAbilities: "Breath weapon (50 ft. cone of fire DC 26 or 40 ft. cone of weakening gas DC 26), crush, frightful presence (DC 24 Will), fire immunity, luck bonus, detect evil, alter self, divine arcana, spells as 9th-level sorcerer",
                  environment: "Warm plains and hills",
                  summary: "The greatest of all metallic dragons, a champion of justice and wisdom.",
                  desc: "Adult gold dragons are among the most powerful forces of good in the world. They are deeply moral beings who take an active role in opposing evil and protecting mortals. Gold dragons often take humanoid form to live among other species for years, studying them and learning to understand their joys and sorrows before revealing their true nature."),

            .make("Elder Earth Elemental", cr: "11", type: "Outsider (earth, elemental, extraplanar)", size: "Huge", alignment: "N",
                  hp: "136 (13d10+65)", ac: 22, speed: "20 ft., burrow 20 ft.",
                  attacks: "2 slams +19 (2d10+10 plus earth mastery)",
                  specialAbilities: "Earth mastery (+1 attack/damage when both on ground), push (slam, free action), DR 10/—, darkvision 60 ft., immunity to acid, elemental traits",
                  environment: "Elemental Plane of Earth",
                  summary: "A massive animate earth entity of enormous physical power.",
                  desc: "Elder earth elementals are immense beings of living stone that move with surprising speed through solid rock as though it were water. On the Material Plane they are called up by powerful spellcasters as defenders or as forces of destruction. They are single-minded in purpose and extraordinarily difficult to permanently destroy."),

            // MARK: - CR 17

            .make("Ancient Red Dragon", cr: "19", type: "Dragon (fire)", size: "Gargantuan", alignment: "CE",
                  hp: "336 (24d12+168)", ac: 37, speed: "40 ft., fly 250 ft. (clumsy)",
                  attacks: "Bite +33 (4d8+18), 2 claws +33 (4d6+12), 2 wings +31 (2d8+6), tail +31 (4d6+18)",
                  specialAbilities: "Breath weapon (60 ft. cone of fire, 20d10, DC 32 Ref), crush, tail sweep, frightful presence (DC 30 Will, 300 ft.), fire immunity, spell-like abilities, spells as 13th-level sorcerer",
                  environment: "Warm mountains",
                  summary: "A titanic red dragon whose hoard and arrogance are legendary across the world.",
                  desc: "Ancient red dragons are catastrophically powerful beings whose very presence warps local weather and ecology. Their hoards are measured in tons of gold and centuries of accumulated tribute. Nations build their foreign policy around avoiding the notice of ancient red dragons, and a wyrm of this age that decides to attack a major city represents an event that reshapes history."),

            .make("Pit Fiend", cr: "20", type: "Outsider (devil, evil, extraplanar, lawful)", size: "Large", alignment: "LE",
                  hp: "290 (20d10+180)", ac: 38, speed: "40 ft., fly 60 ft. (average)",
                  attacks: "2 claws +29 (2d8+13/19–20 plus grab), 2 wings +29 (2d6+6), bite +29 (4d6+6 plus poison), tail +29 (2d8+6 plus grab)",
                  specialAbilities: "Constrict (2d8+19), poison (Con damage, DC 33), fear aura (DC 31 Will), DR 15/good and silver, immunity to fire/poison, regeneration 5 (good weapons/spells), see in darkness, spell-like abilities, summon (DC 25, various devils), telepathy 100 ft.",
                  environment: "Lawful evil planes",
                  summary: "The most powerful of all true devils, a ruler in Hell's eternal hierarchy.",
                  desc: "Pit fiends are the undisputed rulers among true devils, answering only to the archdevils themselves. They are military commanders, political masterminds, and weapons of apocalyptic power all in one form. A pit fiend's arrival on the Material Plane is treated as a world-ending event by most mortal nations, requiring the combined might of armies and powerful spellcasters to counter."),

            // MARK: - CR 20

            .make("Balor", cr: "20", type: "Outsider (chaotic, demon, evil, extraplanar)", size: "Huge", alignment: "CE",
                  hp: "362 (25d10+225)", ac: 36, speed: "40 ft., fly 90 ft. (poor)",
                  attacks: "+1 vorpal longsword +35/+30/+25/+20 (3d6+14/17–20 plus 1d6 fire) and +1 flaming whip +35 (1d4+7 plus entangle plus 1d6 fire)",
                  specialAbilities: "Death throes (20d6 fire, DC 31 Ref), DR 15/cold iron and good, immunity to electricity/fire/poison, unholy aura, vorpal longsword, whip (entangle, free bull rush to 100 ft.), summon demons, spell-like abilities",
                  environment: "Chaotic evil planes",
                  summary: "The most terrible of all demons, a lord of the Abyss wreathed in fire.",
                  desc: "Balors are among the mightiest of all demons, generals of the demonic hordes and lords of entire layers of the Abyss. Their very presence scorches the air, and their death throes unleash a catastrophic explosion of infernal energy. The destruction of a balor is considered a major victory even by the most powerful mortal heroes."),

            .make("Kraken", cr: "18", type: "Magical Beast (aquatic)", size: "Gargantuan", alignment: "CE",
                  hp: "290 (20d10+180)", ac: 32, speed: "swim 30 ft.",
                  attacks: "2 tentacle rakes +28 (2d8+15/19–20 plus grab), 6 arms +28 (1d8+10 plus grab), bite +28 (4d8+10)",
                  specialAbilities: "Constrict (2d8+20 or 1d8+15), ink cloud (100 ft., DC 28 Fort or blinded), jet (280 ft., DC 28 Ref), spell-like abilities (control weather, dominate animal, control winds, etc.), darkvision 60 ft., low-light vision",
                  environment: "Cold and temperate deep oceans",
                  summary: "A legendary sea monster of immense size that can destroy entire ships.",
                  desc: "Krakens are the most feared creatures of the deep ocean, enormous cephalopods of supernatural intelligence that regard ships and their crews as meals. They are immeasurably old and patient, rising from the deepest trenches when they choose to hunt. Sailors whisper of entire merchant fleets that vanished overnight when a kraken decided it was hungry."),

            .make("Tarrasque", cr: "25", type: "Magical Beast", size: "Colossal", alignment: "N",
                  hp: "525 (30d10+360)", ac: 40, speed: "40 ft.",
                  attacks: "Bite +43 (4d8+17/15–20 plus grab), 2 claws +43 (1d12+17), 2 gores +43 (1d10+17), tail slap +43 (3d8+8), 2 horns +43 (1d10+17)",
                  specialAbilities: "Carapace (reflect ranged), frightful presence (DC 27 Will, 300 ft.), regeneration 40 (no weakness), rush (charge 1/minute), swallow whole (AC 20, 52 hp), DR 15/epic, immunity to fire/poison/disease/energy drain/ability damage, SR 36",
                  environment: "Any",
                  summary: "The most destructive creature in existence, an unstoppable engine of annihilation.",
                  desc: "The tarrasque is unique — there is only one, and its awakening is the stuff of apocalyptic prophecy. It moves through civilized lands like a natural disaster, consuming everything and cannot be permanently slain by conventional means. Whole cities have been evacuated and armies annihilated trying to slow its advance. Only the most powerful magic can force it back into its long slumber."),

        ]

        for monster in monsters {
            try await db.insertMonster(monster)
        }
    }
}
