import Foundation

extension SeedDataBuilder {
    func seedNPCCodex() async throws {
        let npcs: [MonsterEntry] = [

            // MARK: - CR 1/2

            .make("Acolyte",
                  cr: "1/2",
                  type: "Humanoid (human)",
                  size: "Medium",
                  alignment: "N",
                  hp: "6 (1d8+2)",
                  ac: 15,
                  speed: "30 ft.",
                  attacks: "Light mace +1 (1d6+1), or light crossbow +1 (1d8)",
                  specialAbilities: "Channel energy 1d6 3/day (DC 10), domain powers, spells prepared (0th: guidance, light, stabilize; 1st: bless, cure light wounds)",
                  environment: "Any settlement",
                  summary: "A newly ordained divine servant of a local temple, trained in the basics of divine magic and healing.",
                  desc: "Acolytes are junior clergy who have received formal religious training but have yet to prove themselves in the wider world. They serve local temples and shrines, conducting minor ceremonies, tending to the sick and poor, and supporting higher-ranking priests in rituals. In an emergency, an acolyte can provide basic healing and divine support, though their power is limited compared to a fully ordained cleric. Many acolytes aspire to greater ranks within their faith; others are content with the spiritual rewards of quiet service.",
                  source: "NPC Codex",
                  isPremium: true),

            .make("Hedge Witch",
                  cr: "1/2",
                  type: "Humanoid (human)",
                  size: "Medium",
                  alignment: "N",
                  hp: "6 (1d6+3)",
                  ac: 12,
                  speed: "30 ft.",
                  attacks: "Dagger +0 (1d4)",
                  specialAbilities: "Hex (evil eye, –2 to rolls, DC 11 Will negates), familiar (cat), spells prepared (0th: detect magic, guidance, read magic; 1st: charm person, cure light wounds, sleep)",
                  environment: "Rural settlements and forest edges",
                  summary: "A self-taught village wise-woman who barters charms and curses from a ramshackle woodland cottage.",
                  desc: "Hedge witches occupy a curious social position in rural communities: feared for their hexes, valued for their poultices and love charms, and consulted when children fall ill and the local priest is three days' travel away. Their knowledge is a mix of genuine patron-granted magic, folk herbalism, and theatrical superstition. A hedge witch's familiar is her most trusted companion — part magical conduit, part household pet, and part source of the unsettling rumors that keep villagers cautious about crossing her.",
                  source: "NPC Codex",
                  isPremium: true),

            .make("Wandering Monk",
                  cr: "1/2",
                  type: "Humanoid (human)",
                  size: "Medium",
                  alignment: "LN",
                  hp: "8 (1d8+4)",
                  ac: 15,
                  speed: "30 ft.",
                  attacks: "Unarmed strike +2 (1d6+1), or shuriken +2 (1d2+1)",
                  specialAbilities: "Flurry of blows, stunning fist 1/day (DC 11 Fort or stunned), AC bonus +1 (Wis), unarmed strike, improved unarmed strike",
                  environment: "Roads, monasteries, and wilderness",
                  summary: "A monk traveling a self-imposed road of training and self-discovery before returning to their order.",
                  desc: "Wandering monks take to the road by tradition or by discipline, spending years walking distant paths before settling into the community of their monastery. The journey is the lesson: patience, adaptability, and self-reliance. A wandering monk typically takes odd jobs as a guard or messenger, asking only for food and a dry place to sleep. They are not aggressive but will not be bullied, and can be startlingly effective in combat when pushed to defend themselves.",
                  source: "NPC Codex",
                  isPremium: true),

            // MARK: - CR 1

            .make("Town Guard",
                  cr: "1",
                  type: "Humanoid (human)",
                  size: "Medium",
                  alignment: "LN",
                  hp: "19 (2d10+8)",
                  ac: 18,
                  speed: "20 ft.",
                  attacks: "Longsword +5 (1d8+3), or heavy shield bash +5 (1d4+3)",
                  specialAbilities: "Power Attack (–1 attack/+2 damage), bonus combat feat, armor training 0",
                  environment: "Towns and cities",
                  summary: "A professional city watchman equipped with sword and shield, trained to keep the peace and repel common threats.",
                  desc: "Town guards are the backbone of urban security in most settled areas. They patrol market squares, staff city gates, and respond to disturbances ranging from drunken brawls to the occasional demon incursion. Most guards are former soldiers or farm laborers who found steady work in the watch. They know the city's streets, faces, and trouble spots better than almost anyone else, and clever adventurers cultivate good relationships with the watch rather than antagonizing them. A few guards nurse ambitions of knighthood; the majority want a pension and a quiet old age.",
                  source: "NPC Codex",
                  isPremium: true),

            .make("Village Shaman",
                  cr: "1",
                  type: "Humanoid (human)",
                  size: "Medium",
                  alignment: "N",
                  hp: "15 (2d8+6)",
                  ac: 13,
                  speed: "30 ft.",
                  attacks: "Sickle +1 (1d6), or sling +2 (1d4)",
                  specialAbilities: "Wild shape 1/day (Small or Medium animal), animal companion (wolf), spontaneous summon nature's ally, nature bond, spells prepared (0th: create water, guidance, mending, purify food and drink; 1st: cure light wounds, entangle, faerie fire)",
                  environment: "Wilderness villages and tribal communities",
                  summary: "A druidic holy person who serves as spiritual guide, healer, and weather-watcher for an isolated rural community.",
                  desc: "Village shamans hold a different role than urban priests — they are the community's interface with the living world, responsible for blessing plantings, reading omens in weather and animal behavior, and mediating disputes with the spirits of place. Their magic is practical and tied to the land: healing wounds, purifying water, calling animals for the hunt. When threats arise, the shaman fights with the animals they have bonded with and the wild magic of the land. Outsiders often underestimate shamans, expecting rural folk wisdom rather than genuine divine power.",
                  source: "NPC Codex",
                  isPremium: true),

            // MARK: - CR 2

            .make("Street Rogue",
                  cr: "2",
                  type: "Humanoid (human)",
                  size: "Medium",
                  alignment: "CN",
                  hp: "16 (3d8+3)",
                  ac: 15,
                  speed: "30 ft.",
                  attacks: "Short sword +4 (1d6+1), or dagger +4 (1d4+1)",
                  specialAbilities: "Sneak attack +2d6, trapfinding, evasion, rogue talent (finesse rogue), trap sense +1",
                  environment: "Urban slums and market districts",
                  summary: "A small-time criminal who survives by stealing, running cons, and knowing when to run.",
                  desc: "Street rogues are the foot soldiers of the urban underworld: pickpockets, cutpurses, low-level enforcers, and casual burglars who learned their trade on the streets rather than from any guild. They know every shortcut in their neighborhood, who to bribe and who to avoid, and which taverns turn a blind eye to the contents of your pockets. Most street rogues live day to day, spending their gains on food, gambling, and occasional luxuries. A few harbor real ambitions of moving up in a thieves' guild; others prefer their independence, even if it means more risk.",
                  source: "NPC Codex",
                  isPremium: true),

            // MARK: - CR 3

            .make("Battle Cleric",
                  cr: "3",
                  type: "Humanoid (human)",
                  size: "Medium",
                  alignment: "LG",
                  hp: "30 (4d8+12)",
                  ac: 19,
                  speed: "20 ft.",
                  attacks: "Warhammer +6 (1d8+3), or light crossbow +4 (1d8)",
                  specialAbilities: "Channel energy 2d6 5/day (DC 13), spontaneous cure spells, domain powers (War: weapon focus bonus feat, Battle Rage +2 touch), spells prepared (2nd: bull's strength, cure moderate wounds; 1st: bless, divine favor, shield of faith; 0th: guidance, light, stabilize, virtue)",
                  environment: "Temples, military camps, and dungeons",
                  summary: "A martial priest who balances healing and front-line combat, serving their deity with sword and spell alike.",
                  desc: "Battle clerics are the divine counterpart to fighters — trained to take a place in the front line while keeping their allies alive with channel energy and targeted cures. They serve as chaplains in armies, advance guards for crusading orders, and backup muscle for adventuring parties that lack dedicated martial support. Their divine connection gives them access to powerful combat-enhancing spells like divine favor and bull's strength, making them formidable combatants who can also turn the tide with a timely heal.",
                  source: "NPC Codex",
                  isPremium: true),

            .make("War Wizard",
                  cr: "3",
                  type: "Humanoid (human)",
                  size: "Medium",
                  alignment: "N",
                  hp: "15 (4d6)",
                  ac: 13,
                  speed: "30 ft.",
                  attacks: "Quarterstaff +2 (1d6), or ranged touch +4",
                  specialAbilities: "Arcane bond (ring), spells prepared (2nd: flaming sphere, scorching ray; 1st: magic missile, shield, sleep; 0th: acid splash, detect magic, light, ray of frost), school specialization (evocation)",
                  environment: "Military camps, towers, and dungeon expeditions",
                  summary: "A wizard trained specifically in offensive evocation magic who sells their destructive expertise to armies and expeditions.",
                  desc: "War wizards specialize in the same way that soldiers specialize — they drill the battle spells until casting them is reflexive, study formations and chokepoints the way strategists study maps, and learn to function under pressure when everything is on fire. They are not scholars of magic for its own sake; they are weapons in scholarly form. Armies that can afford war wizards value them enormously; those that cannot spend considerable energy trying to neutralize the enemy's wizard before the battle is joined.",
                  source: "NPC Codex",
                  isPremium: true),

            .make("Scout Ranger",
                  cr: "3",
                  type: "Humanoid (human)",
                  size: "Medium",
                  alignment: "N",
                  hp: "26 (4d10+4)",
                  ac: 16,
                  speed: "30 ft.",
                  attacks: "Composite longbow +7 (1d8+2), or shortsword +5 (1d6+2)",
                  specialAbilities: "Favored enemy (humanoid +2), animal companion (hawk), track, wild empathy, combat style (archery: Rapid Shot), spells prepared (1st: longstrider)",
                  environment: "Wilderness, borders, and frontier settlements",
                  summary: "A wilderness tracker and archer who serves as a scout, border warden, or bounty hunter.",
                  desc: "Scout rangers operate in the spaces between civilization and wilderness, tracking threats before they reach settlement walls and eliminating them with efficient archery from ambush. They work alone or in small groups, relying on their environment as much as their weapons. Their animal companions serve as early warning systems, message carriers, and hunting partners. Most scout rangers develop a regional expertise — the forest road between two cities, the mountain pass, the river delta — and know their territory better than any map.",
                  source: "NPC Codex",
                  isPremium: true),

            // MARK: - CR 5

            .make("Mercenary Captain",
                  cr: "5",
                  type: "Humanoid (human)",
                  size: "Medium",
                  alignment: "N",
                  hp: "57 (6d10+24)",
                  ac: 21,
                  speed: "20 ft.",
                  attacks: "+1 longsword +11/+6 (1d8+6), or heavy crossbow +7 (1d10)",
                  specialAbilities: "Armor training 1, weapon training (heavy blades +1), bonus combat feats (Weapon Focus, Weapon Specialization, Power Attack, Cleave), bravery +2",
                  environment: "Battlefields, city garrisons, and warlord camps",
                  summary: "A veteran soldier who leads a company of hired fighters through a combination of experience, tactical acumen, and sheer intimidation.",
                  desc: "Mercenary captains have survived enough battles to know that most of them are decided before the first sword is drawn — by logistics, positioning, and knowing when to retreat. They hire for skill and discipline, not enthusiasm, and they maintain that discipline with a combination of fair pay, clear expectations, and the occasional example-making of those who break ranks. A good mercenary captain makes their company the most reliable option in a crowded market by never taking contracts they cannot fulfill and never leaving a job half-done.",
                  source: "NPC Codex",
                  isPremium: true),

            .make("Enchantress",
                  cr: "5",
                  type: "Humanoid (human)",
                  size: "Medium",
                  alignment: "CN",
                  hp: "19 (6d6–6)",
                  ac: 14,
                  speed: "30 ft.",
                  attacks: "Dagger +3 (1d4), or ranged touch +5",
                  specialAbilities: "Bloodline (fey): laughing touch 7/day (target provokes AoO for 1 round), woodland stride; fascinate (DC 17 Will), spells known including charm person, hideous laughter, suggestion, dominate person; spells spontaneous",
                  environment: "Noble courts, urban districts, and fey borderlands",
                  summary: "A sorcerer of fey blood who uses enchantment magic to bend the will of those around her.",
                  desc: "Enchantresses move through society like fish through water — always in motion, always beautiful, rarely where you expect them to be. Their fey bloodline manifests as an uncanny magnetism that goes beyond normal Charisma, something slightly off about the eyes that makes people want to do as they suggest. Some enchantresses use this gift for genuine good: negotiating treaties, resolving conflicts without bloodshed, protecting vulnerable people from predatory powers. Others exploit it shamelessly, accumulating wealth, secrets, and influence with cheerful amorality.",
                  source: "NPC Codex",
                  isPremium: true),

            // MARK: - CR 7

            .make("High Priest",
                  cr: "7",
                  type: "Humanoid (human)",
                  size: "Medium",
                  alignment: "LG",
                  hp: "52 (8d8+16)",
                  ac: 20,
                  speed: "20 ft.",
                  attacks: "+1 heavy mace +9/+4 (1d8+4)",
                  specialAbilities: "Channel energy 4d6 7/day (DC 16), domain powers, spontaneous cure spells, spells prepared (4th: divine power; 3rd: cure serious wounds, dispel magic, prayer; 2nd: bull's strength, cure moderate wounds ×2, hold person; 1st: bless ×2, divine favor, shield of faith; 0th: detect magic, guidance, light, resistance, stabilize)",
                  environment: "Major temples and cathedral cities",
                  summary: "A senior religious leader with significant political influence and powerful divine magic at their command.",
                  desc: "High priests sit at the intersection of spiritual authority and temporal power. They oversee large congregations, manage temple finances and politics, adjudicate disputes according to religious law, and serve as the primary channel between their deity's will and the mortal world. Their divine magic is formidable, and their political connections more so. Adventurers who earn a high priest's favor gain access to powerful healing, resurrection magic, and the considerable weight of the church's social capital. Those who earn their enmity face something more dangerous than any dungeon.",
                  source: "NPC Codex",
                  isPremium: true),

            // MARK: - CR 8

            .make("Guild Master Rogue",
                  cr: "8",
                  type: "Humanoid (human)",
                  size: "Medium",
                  alignment: "NE",
                  hp: "46 (9d8+5)",
                  ac: 19,
                  speed: "30 ft.",
                  attacks: "+1 rapier +11/+6 (1d6+2/18–20), or hand crossbow +9 (1d4+1)",
                  specialAbilities: "Sneak attack +5d6, improved uncanny dodge, trap sense +3, evasion, master strike (DC 19 Fort or paralyzed/unconscious/dead), rogue talents: bleeding attack, crippling strike, stand up, slippery mind",
                  environment: "Urban criminal organizations",
                  summary: "A criminal mastermind who controls a network of thieves, assassins, and fences through a combination of charisma, blackmail, and strategic violence.",
                  desc: "Guild masters did not reach their position through violence alone — though they certainly used it when necessary. They reached it through an almost supernatural ability to see what others want and what they fear, and to use both. Their organization is a machine for converting information into leverage and leverage into profit. They know the city's secrets better than the city watch, maintain deniable relationships with half the merchants in the district, and have enough blackmail material on the right magistrates to keep their operations running through most political storms.",
                  source: "NPC Codex",
                  isPremium: true),

            .make("Court Wizard",
                  cr: "8",
                  type: "Humanoid (human)",
                  size: "Medium",
                  alignment: "LN",
                  hp: "27 (9d6–9)",
                  ac: 15,
                  speed: "30 ft.",
                  attacks: "Staff of fire +4 (1d6), or ranged touch +5",
                  specialAbilities: "Arcane bond (familiar: raven), school specialization (divination: forewarned +4, diviner's fortune), spells prepared (5th: contact other plane, teleport; 4th: arcane eye, greater invisibility; 3rd: dispel magic, fireball, fly; 2nd: detect thoughts, mirror image, scorching ray; 1st: alarm, identify, magic missile, shield; 0th: detect magic, light, mage hand, prestidigitation)",
                  environment: "Noble courts and royal palaces",
                  summary: "A wizard retained by a noble house or royal court to provide magical intelligence, counsel, and battlefield support.",
                  desc: "Court wizards are as much political figures as magical ones. Their position requires them to navigate the treacherous waters of noble politics while providing genuine magical capability that justifies their access and expense. The smart ones specialize in divination: knowing things before anyone else, predicting enemy movements, detecting lies in treaty negotiations. This knowledge is worth more to a ruler than any number of battle-spells, and it keeps the wizard's position secure even after the battles are done. Court wizards who last more than a decade are universally dangerous, regardless of their apparent gentility.",
                  source: "NPC Codex",
                  isPremium: true),

            // MARK: - CR 9

            .make("Barbarian Warchief",
                  cr: "9",
                  type: "Humanoid (human)",
                  size: "Medium",
                  alignment: "CE",
                  hp: "115 (10d12+50)",
                  ac: 18,
                  speed: "40 ft.",
                  attacks: "+2 greataxe +16/+11 (1d12+10/×3) while raging; +14/+9 normal",
                  specialAbilities: "Rage 4/day (20 rounds, +6 Str/Con while raging), DR 2/—, trap sense +3, uncanny dodge, improved uncanny dodge, rage powers: renewed vigor, intimidating glare, powerful blow",
                  environment: "Wilderness and tribal territories",
                  summary: "A ferocious tribal leader who has unified disparate warrior bands through overwhelming personal combat ability and force of will.",
                  desc: "Warchiefs earn their titles through deeds, not birth. They have won more challenges than anyone cares to count, survived wounds that should have killed them three times over, and accumulated enough battle-trophies to build a small house. Their authority rests entirely on continued demonstration of superiority — in most barbarian cultures, any warrior strong enough to defeat the warchief is entitled to take the title. This creates chieftains who are constantly searching for the next challenge, the next victory, the next proof that they are exactly as terrifying as their reputation claims.",
                  source: "NPC Codex",
                  isPremium: true),

            .make("Holy Champion",
                  cr: "9",
                  type: "Humanoid (human)",
                  size: "Medium",
                  alignment: "LG",
                  hp: "80 (10d10+25)",
                  ac: 24,
                  speed: "20 ft.",
                  attacks: "+2 longsword +16/+11 (1d8+7) plus smite; +14/+9 normal",
                  specialAbilities: "Smite evil 4/day (+5 attack/+10 damage vs. evil), lay on hands 5d6 7/day (or smite 4 uses), divine grace (+5 saves), aura of courage (allies immune to fear within 10 ft.), divine bond (weapon: +2 flaming), mercy (fatigued, sickened)",
                  environment: "Crusades, holy sites, and dungeons",
                  summary: "A veteran paladin whose divine power and combat mastery make them a beacon of hope for their allies and a terror to the forces of evil.",
                  desc: "Holy champions have dedicated their entire adult lives to the extermination of evil, and it shows. The fire in their eyes when they face a demon is not the controlled burn of duty but the white heat of genuine hatred refined through a decade of practice. Their divine bond has transformed their weapon into an instrument of sacred destruction; their mercy abilities allow them to heal conditions as well as hit points when they lay on hands. Those who travel with a holy champion often find themselves unaccountably more brave — and those who oppose evil alongside them understand why.",
                  source: "NPC Codex",
                  isPremium: true),

            // MARK: - CR 13

            .make("Archmage",
                  cr: "13",
                  type: "Humanoid (human)",
                  size: "Medium",
                  alignment: "N",
                  hp: "49 (14d6)",
                  ac: 20,
                  speed: "30 ft.",
                  attacks: "Staff of the magi +7 (1d6) or ranged touch +8",
                  specialAbilities: "Arcane bond (staff of the magi), school specialization (universalist), spells prepared (7th: limited wish, plane shift; 6th: disintegrate, greater dispel magic, true seeing; 5th: cone of cold, dominate person, feeblemind, telekinesis; 4th: dimension door, greater invisibility, stoneskin, wall of fire; 3rd: dispel magic, fireball ×2, fly, tongues; 2nd: detect thoughts, mirror image ×2, resist energy; 1st: charm person, magic missile ×3, shield; 0th: detect magic, light, mage hand, prestidigitation), arcane discoveries: fast study, beyond morality",
                  environment: "Towers of power and extraplanar academies",
                  summary: "A wizard of extraordinary power who has unlocked the deep structure of magic and can bend reality with casual precision.",
                  desc: "Archmages are not merely powerful spellcasters — they have crossed a threshold of magical understanding that changes their relationship to magic itself. Spells are not tools to them but expressions of a language they now speak natively. An archmage can identify most spells by watching the caster's hands, understand the underlying mechanics of any magical effect in moments, and counterspell by instinct rather than analysis. They are typically old, frequently eccentric, and almost always more dangerous than they appear — an archmage who dresses like a farmer is still an archmage.",
                  source: "NPC Codex",
                  isPremium: true),

            // MARK: - CR 14

            .make("Grandmaster Thief",
                  cr: "14",
                  type: "Humanoid (human)",
                  size: "Medium",
                  alignment: "NE",
                  hp: "71 (15d8)",
                  ac: 23,
                  speed: "30 ft.",
                  attacks: "+3 short sword +16/+11/+6 (1d6+4/19–20), or hand crossbow +13 (1d4+2)",
                  specialAbilities: "Sneak attack +8d6, master strike (DC 22), improved uncanny dodge, evasion, slippery mind, advanced talents: deadly sneak, hide in plain sight, master of disguise; rogue talents: bleeding attack, crippling strike, skill mastery (Disable Device, Perception, Stealth, Sleight of Hand)",
                  environment: "Urban centers and thieves' guilds",
                  summary: "A legendary criminal whose reputation for pulling off impossible heists is matched only by their ruthlessness in eliminating threats to their continued freedom.",
                  desc: "The grandmaster thief has stolen from kings and left them puzzled about what was taken. They have broken into vaults that ten lesser criminals studied for years. They know every guard rotation in the city, the weight of every lock by feel, and the exact price of every secret in the district. Their master strike ability means a single sneak attack can end a life outright — but they rarely use that option, preferring to leave behind a puzzle rather than a corpse. Corpses attract attention; mysteries do not.",
                  source: "NPC Codex",
                  isPremium: true),

            // MARK: - CR 15

            .make("Warlord",
                  cr: "15",
                  type: "Humanoid (human)",
                  size: "Medium",
                  alignment: "LN",
                  hp: "144 (16d10+64)",
                  ac: 27,
                  speed: "20 ft.",
                  attacks: "+3 greatsword +25/+20/+15 (2d6+14/17–20)",
                  specialAbilities: "Armor mastery (DR 5/— while in full plate), weapon mastery (greatsword: always confirms crits, cannot be disarmed), armor training 4, weapon training (heavy blades +4, pole arms +2), greater weapon focus, greater weapon specialization, combat feats: Vital Strike, Improved Critical, Iron Will, Lightning Reflexes",
                  environment: "Battlefields and military fortresses",
                  summary: "A supreme martial commander whose personal combat ability is matched only by their genius for large-scale tactical operations.",
                  desc: "Warlords operate at the highest level of mortal martial achievement. They have led armies to victory against seemingly impossible odds, broken elite cavalry with infantry square formations they personally designed, and held mountain passes with a hundred soldiers against a thousand. Their personal combat ability is legend: the greatsword in their hands becomes a weapon of almost supernatural precision, confirming every critical hit with the mechanical certainty of long practice. Their armies fight harder knowing the Warlord is present — and their enemies fight harder knowing the Warlord is against them.",
                  source: "NPC Codex",
                  isPremium: true),

            // MARK: - CR 17

            .make("Legendary Bard",
                  cr: "17",
                  type: "Humanoid (human)",
                  size: "Medium",
                  alignment: "CG",
                  hp: "99 (18d8+18)",
                  ac: 22,
                  speed: "30 ft.",
                  attacks: "+4 rapier +18/+13/+8 (1d6+6/18–20)",
                  specialAbilities: "Bardic performance 43 rounds/day (inspire courage +4, inspire greatness, inspire heroics, mass suggestion, dirge of doom, frightening tune, deadly performance), lore master 3/day, jack-of-all-trades (all skills trained), spells known (6th: find the path, mass suggestion; 5th: greater heroism, mind fog; 4th: dominate person, freedom of movement; 3rd: haste, see invisibility; 2nd: glitterdust, mirror image; 1st: charm person, cure light wounds; 0th: all 0th-level bard spells), versatile performance (string, oratory, comedy)",
                  environment: "Royal courts, great theaters, and legendary venues",
                  summary: "A performer of unsurpassed skill whose bardic magic has reached legendary heights, capable of inspiring heroic feats and breaking enemy morale with equal ease.",
                  desc: "The legendary bard has transcended performance and become an institution. Songs they wrote thirty years ago are still sung in taverns across three kingdoms. Nobles compete for their presence at important events; enemies pay assassins to prevent their attendance at sieges. Their bardic magic at this level crosses into something more than inspiration — deadly performance can literally kill with art, frightening tune sends armies to rout, and mass suggestion rewrites the motivations of entire crowds. The legendary bard moves through the world as a force of nature in silk, leaving changed lives and unforgettable memories behind.",
                  source: "NPC Codex",
                  isPremium: true),
        ]

        for npc in npcs {
            try await db.insertMonster(npc)
        }
    }
}
