import Foundation

// Rage of Elements (Premium)
extension SeedDataBuilder {
    func seedRageOfElements() async throws {
        let spells: [SpellEntry] = [
            .make("Hydraulic Push", rank: 1, traditions: "arcane, primal",
                  actions: "2 actions",
                  traits: "Attack, Evocation, Water",
                  range: "60 feet", targets: "1 creature or object",
                  summary: "You call forth a powerful jet of water that pushes a creature.",
                  desc: "You call forth a powerful blast of pressurized water that bludgeons a target and knocks it back. Make a spell attack roll. On a hit, the target takes 3d6 bludgeoning damage and is pushed 5 feet away from you. On a critical hit, the target takes double damage and is pushed 10 feet.",
                  heightened: "(+1) The damage increases by 2d6.",
                  source: "Rage of Elements", isPremium: true),

            .make("Gust of Wind", rank: 1, traditions: "arcane, primal",
                  actions: "2 actions",
                  traits: "Air, Evocation",
                  area: "60-foot line",
                  duration: "until the start of your next turn", savingThrow: "Fortitude",
                  summary: "A blast of wind pushes creatures and disperses vapors.",
                  desc: "A powerful wind blows in the area in a direction you choose. Each creature in the area must attempt a Fortitude save. Failure: The creature is knocked prone. If the creature is flying, it gets a critical failure instead. Critical Failure: The creature is pushed 30 feet in the direction of the wind, knocked prone, and takes 2d6 bludgeoning damage. The wind disperses fog, mist, and similar vapors in the area.",
                  source: "Rage of Elements", isPremium: true),

            .make("Burning Hands", rank: 1, traditions: "arcane, primal",
                  actions: "2 actions",
                  traits: "Evocation, Fire",
                  area: "15-foot cone",
                  savingThrow: "basic Reflex",
                  summary: "You send a gout of flame from your hands to engulf your foes.",
                  desc: "Gouts of flame rush from your hands. Each creature in the area takes 2d6 fire damage.",
                  heightened: "(+1) The damage increases by 2d6.",
                  source: "Rage of Elements", isPremium: true),

            .make("Breath Fire", rank: 2, traditions: "arcane, primal",
                  actions: "2 actions",
                  traits: "Evocation, Fire",
                  area: "30-foot cone",
                  savingThrow: "basic Reflex",
                  summary: "You exhale a powerful cone of flame.",
                  desc: "You breathe out a tongue of flame in a wide cone. Each creature in the area takes 5d6 fire damage with a basic Reflex save.",
                  heightened: "(+1) The damage increases by 2d6.",
                  source: "Rage of Elements", isPremium: true),

            .make("Quench", rank: 2, traditions: "primal",
                  actions: "2 actions",
                  traits: "Abjuration, Water",
                  range: "120 feet",
                  area: "20-foot burst",
                  summary: "You extinguish fires and counter fire effects in an area.",
                  desc: "You snuff out fires and stifle the effects of fire magic in the area. Non-magical fires in the area are automatically extinguished. Creatures in the area with persistent fire damage can immediately attempt a flat check to end the persistent damage with a +2 bonus. Fire spells in the area are counteracted.",
                  heightened: "(+1) The counteract level increases by 1.",
                  source: "Rage of Elements", isPremium: true),

            .make("Wall of Wind", rank: 3, traditions: "arcane, primal",
                  actions: "3 actions",
                  traits: "Air, Evocation",
                  range: "120 feet",
                  duration: "1 minute",
                  summary: "You create a wall of howling wind that deflects projectiles.",
                  desc: "You create a barrier of fierce winds up to 60 feet long and 30 feet high. The wall is 5 feet thick. Ranged attacks with physical ammunition that pass through the wall automatically miss. Gases, including creatures in gaseous form, can't pass through the wall. A creature attempting to fly through the wall must attempt a Fortitude save or be pushed back 10 feet.",
                  source: "Rage of Elements", isPremium: true),

            .make("Stinking Cloud", rank: 3, traditions: "arcane, primal",
                  actions: "2 actions",
                  traits: "Conjuration, Poison",
                  range: "120 feet", area: "20-foot burst",
                  duration: "1 minute", savingThrow: "Fortitude",
                  summary: "You conjure a bank of nauseating fog.",
                  desc: "You create a cloud of putrid, nauseating vapors. Each creature in the area when the cloud appears or that enters the cloud must attempt a Fortitude save. Success: The creature is sickened 1. Failure: The creature is sickened 2. Critical Failure: The creature is sickened 2 and slowed 1 for 1 round. A creature that leaves the cloud and returns must save again.",
                  source: "Rage of Elements", isPremium: true),

            .make("Elemental Zone", rank: 5, traditions: "arcane, primal",
                  actions: "3 actions",
                  traits: "Conjuration, Air, Earth, Fire, Water",
                  range: "120 feet", area: "20-foot burst",
                  duration: "1 minute",
                  summary: "You suffuse an area with elemental energy of your choice.",
                  desc: "You create a zone suffused with elemental power. Choose air, earth, fire, or water when you cast this spell. The zone gains effects based on your choice. Air: Creatures in the zone are buffeted by wind, becoming concealed. Earth: The ground becomes difficult terrain. Fire: Creatures that enter or start their turn in the zone take 4d6 fire damage (basic Reflex). Water: The zone fills with water, making it difficult terrain and allowing creatures to swim.",
                  heightened: "(+1) Fire damage increases by 1d6.",
                  source: "Rage of Elements", isPremium: true),

            .make("Cone of Cold", rank: 5, traditions: "arcane, primal",
                  actions: "2 actions",
                  traits: "Cold, Evocation",
                  area: "60-foot cone",
                  savingThrow: "basic Reflex",
                  summary: "You unleash a blast of icy cold in a wide cone.",
                  desc: "Icy cold rushes forth from your hands. Each creature in the area takes 12d6 cold damage.",
                  heightened: "(+1) The damage increases by 2d6.",
                  source: "Rage of Elements", isPremium: true),

            .make("Cloudkill", rank: 5, traditions: "arcane, primal",
                  actions: "3 actions",
                  traits: "Death, Necromancy, Poison",
                  range: "120 feet", area: "20-foot burst",
                  duration: "1 minute", savingThrow: "basic Fortitude",
                  summary: "You conjure a poisonous cloud that moves and deals damage.",
                  desc: "You conjure a poisonous cloud. Each creature in the area takes 6d8 poison damage. You can Sustain the Spell to move the cloud 10 feet in a direction you choose each round. A creature that enters the cloud or starts its turn there takes the damage again.",
                  heightened: "(+1) The damage increases by 1d8.",
                  source: "Rage of Elements", isPremium: true),

            .make("Stone Tell", rank: 6, traditions: "divine, primal",
                  actions: "2 actions",
                  traits: "Divination, Earth",
                  duration: "10 minutes",
                  summary: "You speak with stones, learning what they have witnessed.",
                  desc: "You can communicate with natural and worked stone. Stone can tell you about creatures that have passed over or near it, what is covered or concealed behind it, and other details it has perceived. The stone's perspective, perception, and knowledge may limit the information it can provide.",
                  source: "Rage of Elements", isPremium: true),

            .make("Elemental Annihilation Wave", rank: 7, traditions: "arcane, primal",
                  actions: "2 actions",
                  traits: "Air, Earth, Evocation, Fire, Water",
                  area: "30-foot cone or 60-foot line",
                  savingThrow: "basic Reflex",
                  summary: "You unleash a devastating wave of combined elemental power.",
                  desc: "You gather elemental energy from all around you and release it in a devastating wave. Choose a cone or a line when you cast this spell. Each creature in the area takes 14d6 damage with a basic Reflex save. You choose the damage type from among acid, bludgeoning, cold, electricity, or fire when you cast the spell.",
                  heightened: "(+1) The damage increases by 2d6.",
                  source: "Rage of Elements", isPremium: true),

            .make("Volcanic Eruption", rank: 7, traditions: "arcane, primal",
                  actions: "2 actions",
                  traits: "Earth, Evocation, Fire",
                  range: "120 feet", area: "10-foot radius, 80-foot tall cylinder",
                  savingThrow: "Reflex",
                  summary: "You cause a volcanic eruption to burst forth from the ground.",
                  desc: "The ground shakes and splits, disgorging a column of magma. Each creature in the area takes 10d6 fire damage and 4d12 bludgeoning damage, with a Reflex save. The area becomes difficult terrain from hardened lava. Critical Success: The creature is unaffected. Success: Half damage. Failure: Full damage, and 2d6 persistent fire damage. Critical Failure: Double damage, and 4d6 persistent fire damage.",
                  source: "Rage of Elements", isPremium: true),

            .make("Interplanar Teleport", rank: 7, traditions: "arcane, divine, occult, primal",
                  actions: "10 minutes",
                  traits: "Conjuration, Teleportation",
                  range: "touch", targets: "you and up to 4 willing creatures",
                  summary: "You transport yourself and companions to another plane of existence.",
                  desc: "You and your targets are instantaneously transported to any plane of existence you know. You arrive at the exact location on the target plane that you visualize, as long as you have been there before. If you attempt to travel to a location you have only heard of, you arrive 1d20 x 25 miles from the target location.",
                  source: "Rage of Elements", isPremium: true),

            .make("Planar Seal", rank: 7, traditions: "arcane, divine, occult, primal",
                  actions: "2 actions",
                  traits: "Abjuration",
                  range: "120 feet", area: "60-foot burst",
                  duration: "1 day",
                  summary: "You seal an area against extraplanar travel.",
                  desc: "You create a seal over an area that prevents extraplanar movement. For the duration, creatures within the area can't use teleportation or other abilities that move them between planes. Creatures from other planes can't enter the area via planar travel. Summoning spells automatically fail if the summoned creature would appear inside the area.",
                  source: "Rage of Elements", isPremium: true),

            .make("Horrid Wilting", rank: 8, traditions: "arcane, primal",
                  actions: "2 actions",
                  traits: "Necromancy, Negative",
                  range: "500 feet", area: "30-foot burst",
                  savingThrow: "basic Fortitude",
                  summary: "You drain moisture from living creatures, dealing massive damage.",
                  desc: "You pull the moisture from the bodies of creatures in the area. Each creature in the area takes 17d10 negative damage. Plants and creatures with the water trait get a -2 circumstance penalty to their saving throws.",
                  heightened: "(+1) The damage increases by 2d10.",
                  source: "Rage of Elements", isPremium: true),

            .make("Earthquake", rank: 8, traditions: "arcane, primal",
                  actions: "2 actions",
                  traits: "Earth, Evocation",
                  range: "500 feet", area: "60-foot burst",
                  duration: "1 round", savingThrow: "Reflex",
                  summary: "You shake the ground with tremendous seismic force.",
                  desc: "You shake the ground catastrophically. Each creature on the ground in the area must attempt a Reflex save. Critical Success: Unaffected. Success: The creature falls prone. Failure: The creature falls prone and takes 6d6 bludgeoning damage. Critical Failure: As failure, plus the creature is stunned 1 and is trapped in a fissure. Structures in the area take 50 damage.",
                  source: "Rage of Elements", isPremium: true),
        ]

        let feats: [FeatEntry] = [
            .make("Elemental Blast", level: 1, featType: "Kineticist",
                  traits: "Impulse, Kineticist, Primal",
                  summary: "You shape elemental energy into a powerful blast.",
                  benefit: "You unleash a blast of elemental energy. You can make a melee or ranged impulse attack. Choose an element you can channel. The blast deals 1d8 damage of a type determined by your element (fire deals fire damage, water deals cold damage, earth deals bludgeoning damage, air deals electricity damage). The damage increases by 1d8 at 5th, 9th, 13th, and 17th levels.",
                  source: "Rage of Elements", isPremium: true),

            .make("Aura Shaping", level: 1, featType: "Kineticist",
                  traits: "Kineticist",
                  summary: "You shape your kinetic aura to exclude allies from harmful effects.",
                  benefit: "When you use an impulse that affects an area within your kinetic aura, you can exclude a number of squares from the area equal to your Constitution modifier (minimum 1). This allows you to protect allies from your own elemental effects.",
                  source: "Rage of Elements", isPremium: true),

            .make("Base Kinesis", level: 1, featType: "Kineticist",
                  traits: "Impulse, Kineticist, Primal",
                  summary: "You perform a simple act of elemental manipulation.",
                  benefit: "You can perform a basic elemental manipulation using your kinetic gate. The specific effect depends on your element: Air lets you create a gust or cushion of wind. Earth lets you move loose earth or stone. Fire lets you light or extinguish small flames. Water lets you move or shape a small amount of water. The manipulation is limited to a range of 30 feet and a volume of 1 cubic foot.",
                  source: "Rage of Elements", isPremium: true),

            .make("Channel Elements", level: 1, featType: "Kineticist",
                  traits: "Kineticist, Primal",
                  summary: "You open your kinetic gate to channel elemental energy.",
                  benefit: "You open your kinetic gate, allowing elemental matter and energy to flow. Your kinetic aura activates, extending to a 10-foot emanation around you. While your kinetic aura is active, you gain access to your impulse abilities. You can Channel Elements as a single action at the start of your turn.",
                  source: "Rage of Elements", isPremium: true),

            .make("Extract Element", level: 1, featType: "Kineticist",
                  traits: "Impulse, Kineticist, Primal",
                  summary: "You draw elemental energy out of a creature, weakening it.",
                  benefit: "You extract elemental matter from a creature within range. The target takes 1d4 damage of the type associated with the element you extract (for instance, fire damage for fire). If the creature has a trait matching your element, it takes 1d4 additional damage and is enfeebled 1 until the end of your next turn.",
                  source: "Rage of Elements", isPremium: true),

            .make("Hardwood Armor", level: 1, featType: "Kineticist",
                  traits: "Impulse, Kineticist, Plant, Primal, Wood",
                  summary: "You shape hardwood around your body as protective armor.",
                  benefit: "You cause hardwood to wrap around your body, forming armor. The armor grants you a +3 item bonus to AC, has a Dexterity cap of +2, a check penalty of -1, and a Speed penalty of -5 feet. The armor lasts until you dismiss it or your kinetic aura deactivates.",
                  source: "Rage of Elements", isPremium: true),

            .make("Igneogenesis", level: 1, featType: "Kineticist",
                  traits: "Impulse, Kineticist, Primal",
                  summary: "You create a small volcanic object from elemental fire and earth.",
                  benefit: "You summon a chunk ofite,ite being volcanicite created from a fusion of fire and earth. You create a 5-foot cube of volcanic rock in an unoccupied space on the ground within 30 feet. The rock has AC 10, Hardness 5, and 20 Hit Points. It provides cover to creatures behind it.",
                  source: "Rage of Elements", isPremium: true),

            .make("Ocean's Balm", level: 4, featType: "Kineticist",
                  traits: "Healing, Impulse, Kineticist, Primal, Water",
                  prerequisites: "water kinetic gate",
                  summary: "You heal a creature with soothing elemental water.",
                  benefit: "You channel healing water into a willing creature within your kinetic aura. The target regains 3d8 Hit Points and gains a +1 status bonus to Fortitude saves for 1 round. You can use this impulse only once per 10 minutes. The healing increases to 4d8 at 7th level, 5d8 at 9th level, 6d8 at 11th level, and continues increasing by 1d8 every 2 levels thereafter.",
                  source: "Rage of Elements", isPremium: true),

            .make("Cyclonic Blast", level: 6, featType: "Kineticist",
                  traits: "Air, Impulse, Kineticist, Primal",
                  prerequisites: "air kinetic gate",
                  summary: "You hurl a spinning cyclone of elemental air at your foes.",
                  benefit: "You send forth a concentrated cyclone in a 30-foot line. Each creature in the area takes 4d6 bludgeoning damage and 2d6 electricity damage with a basic Reflex save. On a critical failure, the creature is also pushed 10 feet away from you. The bludgeoning damage increases by 1d6 at 8th level and every 2 levels thereafter.",
                  source: "Rage of Elements", isPremium: true),

            .make("Thermal Nimbus", level: 6, featType: "Kineticist",
                  traits: "Fire, Impulse, Kineticist, Primal",
                  prerequisites: "fire kinetic gate",
                  summary: "You surround yourself with a shimmering nimbus of elemental heat.",
                  benefit: "You surround yourself with an aura of intense heat. For 1 minute, any creature that enters your kinetic aura or starts its turn there takes 2d6 fire damage with a basic Reflex save. You and creatures you designate when you activate this ability are immune to this damage. The damage increases by 1d6 at 9th level and every 3 levels thereafter.",
                  source: "Rage of Elements", isPremium: true),
        ]

        for entry in spells { try await db.insertSpell(entry) }
        for entry in feats { try await db.insertFeat(entry) }
    }
}
