import Foundation

extension SeedDataBuilder {
    func seedMonsters3() async throws {
        let monsters: [MonsterEntry] = [

            // MARK: - Magical Beasts & Creatures

            .make("Griffon", level: 4,
                  creatureType: "Beast", size: "Large",
                  traits: "Beast",
                  hp: "60", ac: 21, fort: 12, ref: 11, will: 8,
                  speed: "25 feet, fly 60 feet",
                  attacks: "Beak +14 (2d8+5 piercing), Talon +14 (2d6+5 slashing; Agile)",
                  specialAbilities: "Low-Light Vision; Scent; Pounce",
                  summary: "A fierce eagle-lion hybrid that fiercely defends its territory from the skies.",
                  desc: "Griffons are majestic predators that combine the body of a lion with the head and wings of a great eagle. They nest in high mountain peaks and hunt across vast territories, prizing horseflesh above all other prey. Taming a griffon requires exceptional skill and patience.",
                  source: "Monster Core", isPremium: true),

            .make("Hippogriff", level: 2,
                  creatureType: "Beast", size: "Large",
                  traits: "Beast",
                  hp: "30", ac: 17, fort: 9, ref: 8, will: 5,
                  speed: "25 feet, fly 60 feet",
                  attacks: "Beak +10 (1d10+3 piercing), Talon +10 (1d6+3 slashing; Agile)",
                  specialAbilities: "Low-Light Vision; Scent; Buck DC 17",
                  summary: "A horse-eagle hybrid more easily domesticated than its griffon cousin.",
                  desc: "Hippogriffs are the offspring of griffons and horses, combining equine hindquarters with an eagle's forequarters. They are easier to train as mounts than griffons and are prized by cavalries and adventurers alike.",
                  source: "Monster Core", isPremium: true),

            .make("Pegasus", level: 3,
                  creatureType: "Beast", size: "Large",
                  traits: "Beast, Celestial",
                  hp: "40", ac: 18, fort: 9, ref: 10, will: 8,
                  speed: "40 feet, fly 80 feet",
                  attacks: "Hoof +11 (1d8+4 bludgeoning), Wing +11 (1d6+4 bludgeoning)",
                  specialAbilities: "Darkvision; Gallop; Buck DC 18",
                  summary: "A celestial winged horse known for its grace, speed, and innate goodness.",
                  desc: "Pegasi are noble winged horses with a celestial heritage that grants them an innate sense of good and evil. They roam wild in high mountain meadows and will only accept riders of virtuous character. A pegasus bond is forged through trust, never through force.",
                  source: "Monster Core", isPremium: true),

            .make("Wyvern", level: 6,
                  creatureType: "Dragon", size: "Large",
                  traits: "Dragon",
                  hp: "95", ac: 24, fort: 14, ref: 14, will: 11,
                  speed: "20 feet, fly 60 feet",
                  attacks: "Jaws +16 (2d8+7 piercing), Claw +16 (2d6+7 slashing; Agile), Stinger +16 (2d6+7 piercing plus wyvern venom)",
                  specialAbilities: "Darkvision; Wyvern Venom (DC 23 Fortitude; 5d6 poison, Clumsy 1); Powerful Dive",
                  summary: "A venomous two-legged dragon with a deadly barbed tail.",
                  desc: "Wyverns are aggressive, territorial draconic predators distinguished from true dragons by their lack of forelegs and breath weapons. They rely instead on a venom-laden tail stinger that can fell prey many times their size. Wyverns are notoriously ill-tempered and nearly impossible to domesticate.",
                  source: "Monster Core", isPremium: true),

            .make("Manticore", level: 6,
                  creatureType: "Beast", size: "Large",
                  traits: "Beast",
                  hp: "95", ac: 22, fort: 15, ref: 13, will: 11,
                  speed: "25 feet, fly 40 feet",
                  attacks: "Jaws +15 (2d8+7 piercing), Claw +15 (2d6+7 slashing; Agile), Tail Spikes +14 (1d10+5 piercing; range increment 30 feet)",
                  specialAbilities: "Darkvision; Scent; Tail Spike Volley (ranged area attack, 1d10+5 piercing, up to 4 spikes)",
                  summary: "A lion-bodied beast with a human face, bat wings, and a tail of deadly spikes.",
                  desc: "Manticores are cruel and cunning predators that combine a lion's body with bat-like wings and a tail studded with venomous spikes. Their disturbingly human-like faces mask a savage, predatory intelligence. They delight in tormenting prey before the kill.",
                  source: "Monster Core", isPremium: true),

            .make("Basilisk", level: 5,
                  creatureType: "Beast", size: "Medium",
                  traits: "Beast",
                  hp: "70", ac: 22, fort: 14, ref: 9, will: 11,
                  speed: "20 feet",
                  attacks: "Jaws +14 (2d8+6 piercing)",
                  specialAbilities: "Darkvision; Petrifying Gaze (DC 21 Fortitude; creature is slowed 1, on critical failure petrified)",
                  summary: "An eight-legged reptile whose gaze can turn creatures to stone.",
                  desc: "Basilisks are squat, eight-legged reptilian creatures whose eyes can petrify living beings. They dwell in caves and rocky wastelands, leaving a trail of eerily lifelike statues that were once their victims. Averting one's gaze is essential when facing a basilisk.",
                  source: "Monster Core", isPremium: true),

            .make("Cockatrice", level: 3,
                  creatureType: "Beast", size: "Small",
                  traits: "Beast",
                  hp: "36", ac: 19, fort: 8, ref: 10, will: 7,
                  speed: "20 feet, fly 40 feet",
                  attacks: "Beak +12 (1d8+3 piercing plus cockatrice venom)",
                  specialAbilities: "Darkvision; Cockatrice Venom (DC 19 Fortitude; slowed 1, on critical failure petrified)",
                  summary: "A small rooster-like creature whose venomous bite can petrify the unwary.",
                  desc: "Cockatrices are bizarre avian creatures resembling roosters with bat wings and serpentine tails. Their bite carries a petrifying venom that gradually turns victims to stone. Despite their small size, they are surprisingly aggressive and territorial.",
                  source: "Monster Core", isPremium: true),

            .make("Chimera", level: 8,
                  creatureType: "Beast", size: "Large",
                  traits: "Beast",
                  hp: "135", ac: 27, fort: 17, ref: 15, will: 13,
                  speed: "25 feet, fly 50 feet",
                  attacks: "Dragon Jaws +19 (2d6+8 piercing plus 2d6 fire), Lion Jaws +19 (2d10+8 piercing), Goat Horns +19 (2d10+8 bludgeoning), Claw +19 (2d8+8 slashing; Agile)",
                  specialAbilities: "Darkvision; Breath Weapon (30-foot cone, 7d6 fire, DC 26 basic Reflex, 1d4 rounds recharge); Triple Attack",
                  summary: "A terrifying three-headed hybrid of dragon, lion, and goat.",
                  desc: "Chimeras are monstrous beasts with the heads of a dragon, a lion, and a goat set upon a leonine body with draconic wings. Each head has its own temperament, and chimeras are notoriously unpredictable. Their dragon head can unleash a devastating breath weapon.",
                  source: "Monster Core", isPremium: true),

            .make("Hydra", level: 7,
                  creatureType: "Beast", size: "Huge",
                  traits: "Beast",
                  hp: "120", ac: 24, fort: 17, ref: 14, will: 12,
                  speed: "25 feet, swim 25 feet",
                  attacks: "Jaws +16 (2d6+7 piercing; Reach 10 feet; one per head)",
                  specialAbilities: "Darkvision; Multiple Heads (5); Head Regrowth (two new heads per severed, prevented by acid or fire); Attack of Opportunity",
                  summary: "A multi-headed serpentine beast that regrows two heads for each one severed.",
                  desc: "Hydras are massive, multi-headed reptilian predators that lurk in swamps, lakes, and coastal caves. Their most fearsome ability is head regrowth: sever one head and two more grow in its place unless the wound is cauterized with fire or acid. A five-headed hydra is the most commonly encountered variety.",
                  source: "Monster Core", isPremium: true),

            .make("Sphinx", level: 8,
                  creatureType: "Beast", size: "Large",
                  traits: "Beast",
                  hp: "135", ac: 25, fort: 16, ref: 14, will: 17,
                  speed: "35 feet, fly 40 feet",
                  attacks: "Claw +18 (2d8+8 slashing; Agile)",
                  specialAbilities: "Darkvision; Bardic Lore; Riddle (DC 28 Recall Knowledge or Will; creatures that fail are subject to the sphinx's judgment); Warding Glyph",
                  summary: "An enigmatic lion-bodied creature with a human face that poses deadly riddles.",
                  desc: "Sphinxes are intelligent, lion-bodied creatures with humanoid faces who guard ancient sites and sacred knowledge. They pose riddles to those who wish to pass, and those who answer incorrectly may face their wrath. Sphinxes possess vast knowledge spanning countless ages.",
                  source: "Monster Core", isPremium: true),

            .make("Gorgon", level: 8,
                  creatureType: "Beast", size: "Large",
                  traits: "Beast",
                  hp: "130", ac: 27, fort: 17, ref: 13, will: 13,
                  speed: "30 feet",
                  attacks: "Horn +19 (2d12+8 piercing), Hoof +19 (2d6+8 bludgeoning)",
                  specialAbilities: "Darkvision; Breath Weapon (30-foot cone, DC 26 Fortitude; petrifying gas, slowed 1 on failure, petrified on critical failure); Trample",
                  summary: "An iron-scaled bull whose breath turns living creatures to stone.",
                  desc: "Gorgons are fearsome iron-scaled bulls that can exhale clouds of petrifying gas. Not to be confused with medusas, gorgons are bestial creatures driven by territorial aggression rather than intelligence. Their iron-hard hide makes them incredibly difficult to injure.",
                  source: "Monster Core", isPremium: true),

            .make("Harpy", level: 4,
                  creatureType: "Beast", size: "Medium",
                  traits: "Beast",
                  hp: "55", ac: 19, fort: 10, ref: 12, will: 9,
                  speed: "20 feet, fly 60 feet",
                  attacks: "Talon +12 (2d6+3 slashing), Club +12 (1d6+3 bludgeoning)",
                  specialAbilities: "Darkvision; Captivating Song (DC 20 Will; fascinated and moves toward the harpy)",
                  summary: "A winged humanoid whose enchanting song lures victims to their doom.",
                  desc: "Harpies are malicious winged humanoids whose supernaturally beautiful songs lure travelers to their deaths. They nest on high cliffs and rocky coastlines, using their songs to draw victims into treacherous terrain where they can be easily dispatched.",
                  source: "Monster Core", isPremium: true),

            .make("Minotaur", level: 4,
                  creatureType: "Beast", size: "Large",
                  traits: "Beast, Humanoid",
                  hp: "55", ac: 21, fort: 12, ref: 9, will: 7,
                  speed: "25 feet",
                  attacks: "Greataxe +14 (2d12+6 slashing; Sweep), Horn +14 (2d8+6 piercing)",
                  specialAbilities: "Darkvision; Natural Cunning (never gets lost in mazes); Powerful Charge (2d8+6 plus Push)",
                  summary: "A hulking bull-headed humanoid that stalks the corridors of labyrinthine lairs.",
                  desc: "Minotaurs are massive bull-headed humanoids that inhabit sprawling labyrinths and underground complexes. They possess an uncanny sense of direction that makes them impossible to lose in any maze. Minotaurs are savage combatants who charge headlong into battle.",
                  source: "Monster Core", isPremium: true),

            .make("Owlbear", level: 4,
                  creatureType: "Beast", size: "Large",
                  traits: "Beast",
                  hp: "65", ac: 21, fort: 13, ref: 10, will: 9,
                  speed: "25 feet",
                  attacks: "Beak +14 (1d10+6 piercing), Talon +14 (1d10+6 slashing; Agile)",
                  specialAbilities: "Low-Light Vision; Scent; Gnaw; Screech (DC 21 Will; frightened 1, frightened 2 on critical failure)",
                  summary: "A ferocious hybrid of bear and owl renowned for its territorial screech.",
                  desc: "Owlbears are notoriously violent magical beasts that combine the features of a bear and a giant owl. They are fiercely territorial and attack intruders on sight, announcing their presence with a bloodcurdling screech. Owlbears are among the most commonly encountered magical beasts in temperate forests.",
                  source: "Monster Core", isPremium: true),

            .make("Rust Monster", level: 4,
                  creatureType: "Beast", size: "Medium",
                  traits: "Beast",
                  hp: "55", ac: 20, fort: 12, ref: 10, will: 8,
                  speed: "35 feet",
                  attacks: "Antennae +12 (touch; Rust)",
                  specialAbilities: "Darkvision; Metal Scent; Rust (a metal item touched must succeed at a DC 20 Fortitude save or gain the broken condition); Antenna Disarm",
                  summary: "An insectoid creature that corrodes and devours metal on contact.",
                  desc: "Rust monsters are the bane of armored adventurers everywhere. These bizarre insectoid creatures feed exclusively on metal, which they corrode into rust with a touch of their feathery antennae. A rust monster can reduce a suit of full plate to a pile of flakes in moments.",
                  source: "Monster Core", isPremium: true),

            .make("Gargoyle", level: 5,
                  creatureType: "Beast", size: "Medium",
                  traits: "Beast, Earth",
                  hp: "70", ac: 22, fort: 13, ref: 10, will: 11,
                  speed: "25 feet, fly 40 feet",
                  attacks: "Claw +14 (2d6+5 slashing; Agile), Jaws +14 (2d8+5 piercing)",
                  specialAbilities: "Darkvision; Clinging Stone (can cling to stone surfaces); Stone Camouflage (DC 24 Perception to notice while motionless)",
                  summary: "A stone-skinned winged predator that disguises itself as architectural statuary.",
                  desc: "Gargoyles are cunning stone-skinned predators that perch motionless on buildings and cliff faces, perfectly mimicking carved statuary until prey wanders within reach. They are patient hunters that can remain still for days. Their stone bodies grant them exceptional resilience.",
                  source: "Monster Core", isPremium: true),

            .make("Mimic", level: 4,
                  creatureType: "Beast", size: "Medium",
                  traits: "Beast",
                  hp: "60", ac: 21, fort: 12, ref: 8, will: 10,
                  speed: "10 feet",
                  attacks: "Pseudopod +13 (2d8+5 bludgeoning plus Grab)",
                  specialAbilities: "Darkvision; Shapechanger (can assume the shape of a Medium object); Adhesive (grabbed creatures require DC 21 Athletics to Escape); Object Lesson",
                  summary: "A shapeshifting creature that disguises itself as mundane objects to ambush prey.",
                  desc: "Mimics are predatory shapeshifters that assume the forms of treasure chests, doors, and other mundane objects to lure unsuspecting adventurers. Their adhesive coating traps anyone who touches them, and their powerful pseudopods batter victims into submission. They are the reason seasoned adventurers poke everything with a stick first.",
                  source: "Monster Core", isPremium: true),

            .make("Roper", level: 10,
                  creatureType: "Beast", size: "Large",
                  traits: "Beast",
                  hp: "175", ac: 29, fort: 20, ref: 15, will: 19,
                  speed: "10 feet, climb 10 feet",
                  attacks: "Jaws +22 (2d12+10 piercing), Strand +22 (reach 50 feet; Grab)",
                  specialAbilities: "Darkvision; Strand (50-foot reach, pulls grabbed creatures 25 feet closer); Reactive Lash (Attack of Opportunity with strand); Vulnerability to Fire",
                  summary: "A cave-dwelling ambush predator that snares victims with long, sticky strands.",
                  desc: "Ropers are cunning subterranean predators that resemble stalagmites when motionless. They lash out with long, sticky strands to ensnare prey from up to 50 feet away, reeling victims into their gnashing maws. Ropers are surprisingly intelligent and sometimes negotiate with powerful creatures.",
                  source: "Monster Core", isPremium: true),

            .make("Otyugh", level: 4,
                  creatureType: "Beast", size: "Large",
                  traits: "Beast",
                  hp: "55", ac: 19, fort: 13, ref: 8, will: 8,
                  speed: "20 feet",
                  attacks: "Tentacle +13 (1d10+5 bludgeoning plus Grab; Reach 10 feet), Jaws +13 (2d6+5 piercing plus filth fever)",
                  specialAbilities: "Darkvision; Filth Fever (DC 21 Fortitude; sickened 1); Stench (30 feet, DC 19 Fortitude; sickened 1)",
                  summary: "A foul tentacled scavenger that lurks in refuse pits and sewers.",
                  desc: "Otyughs are grotesque, three-legged scavengers that dwell in sewers, refuse heaps, and dungeon middens. Their tentacles end in spiked, leaf-shaped appendages that can grasp prey and haul it toward their filth-encrusted maws. Despite their repulsive habits, some dungeon dwellers tolerate otyughs as waste disposal.",
                  source: "Monster Core", isPremium: true),

            .make("Gibbering Mouther", level: 5,
                  creatureType: "Ooze", size: "Medium",
                  traits: "Ooze",
                  hp: "80", ac: 18, fort: 14, ref: 10, will: 9,
                  speed: "10 feet, swim 20 feet",
                  attacks: "Jaws +14 (2d8+3 piercing plus Grab)",
                  specialAbilities: "Darkvision; Gibbering (30 feet, DC 21 Will; confused for 1 round); Ground Manipulation (20 feet; terrain becomes difficult terrain); All-Around Vision",
                  summary: "A maddening mass of mouths and eyes that babbles incoherently to confuse prey.",
                  desc: "Gibbering mouthers are horrific masses of protoplasm covered in slavering mouths and blinking eyes. Their constant, maddening babble can overwhelm the minds of nearby creatures. The ground around them warps and softens, making escape nearly impossible.",
                  source: "Monster Core", isPremium: true),

            .make("Will-o'-Wisp", level: 8,
                  creatureType: "Aberration", size: "Small",
                  traits: "Aberration",
                  hp: "100", ac: 27, fort: 11, ref: 20, will: 17,
                  speed: "fly 50 feet",
                  attacks: "Shock +19 (2d6+8 electricity)",
                  specialAbilities: "Darkvision; Glow (20-foot bright light, can extinguish as a free action); Feed on Fear (regains HP when a nearby creature is dying or frightened); Immunities: magic (see below); Magic Immunity (immune to all spells except magic missile, maze, and faerie fire)",
                  summary: "A malevolent floating ball of light that feeds on the fear of the dying.",
                  desc: "Will-o'-wisps are sinister, glowing orbs that haunt swamps, bogs, and dark forests. They lure travelers off safe paths with their lights, then feed on the fear and suffering of their victims as they die. Their near-total immunity to magic makes them exceptionally dangerous opponents.",
                  source: "Monster Core", isPremium: true),

            .make("Sea Serpent", level: 13,
                  creatureType: "Beast", size: "Gargantuan",
                  traits: "Beast, Aquatic",
                  hp: "230", ac: 33, fort: 24, ref: 21, will: 20,
                  speed: "20 feet, swim 60 feet",
                  attacks: "Jaws +27 (4d10+14 piercing; Reach 20 feet), Tail +27 (3d10+14 bludgeoning; Reach 30 feet)",
                  specialAbilities: "Darkvision; Spine Rake; Capsize (DC 33 Athletics or Fortitude to avoid); Swallow Whole (3d6+10 bludgeoning, Rupture 30)",
                  summary: "A colossal aquatic serpent capable of capsizing ships and swallowing prey whole.",
                  desc: "Sea serpents are among the most feared creatures of the deep ocean. These enormous serpentine beasts can capsize ships with a flick of their tails and swallow humanoids whole. Sailors regard them as omens of doom, and entire maritime trade routes have been rerouted to avoid their hunting grounds.",
                  source: "Monster Core", isPremium: true),

            .make("Aboleth", level: 12,
                  creatureType: "Aberration", size: "Huge",
                  traits: "Aberration, Aquatic",
                  hp: "220", ac: 32, fort: 23, ref: 18, will: 24,
                  speed: "10 feet, swim 60 feet",
                  attacks: "Tentacle +24 (2d8+12 bludgeoning plus slime; Reach 15 feet)",
                  specialAbilities: "Darkvision; Mucus Cloud (30 feet, DC 32 Fortitude; creature can breathe underwater but no longer air); Dominate (DC 32 Will; as dominate spell); Illusory Projection",
                  summary: "An ancient aquatic aberration that dominates minds and reshapes flesh with its slime.",
                  desc: "Aboleths are among the oldest sentient creatures in existence, predating most civilizations by millions of years. These aquatic horrors possess powerful psychic abilities that allow them to dominate lesser minds and reshape living flesh. Their slime transforms air-breathing creatures into aquatic thralls dependent on the aboleth for survival.",
                  source: "Monster Core", isPremium: true),

            .make("Froghemoth", level: 13,
                  creatureType: "Beast", size: "Huge",
                  traits: "Beast",
                  hp: "230", ac: 31, fort: 25, ref: 20, will: 18,
                  speed: "20 feet, swim 30 feet",
                  attacks: "Jaws +26 (3d12+10 piercing plus Grab; Reach 10 feet), Tentacle +26 (2d10+10 bludgeoning plus Grab; Agile, Reach 15 feet), Tongue +26 (Reach 30 feet; Pull)",
                  specialAbilities: "Darkvision; Swallow Whole (2d10+8 bludgeoning, Rupture 24); Electric Torpor (electricity damage slows the froghemoth); Barbed Tentacles",
                  summary: "A massive amphibian predator with a lashing tongue and barbed tentacles.",
                  desc: "Froghemoths are enormous amphibious predators with four barbed tentacles, a whip-like tongue, and three eyes atop stalks. They lurk in deep swamps and underground lakes, using their tongues to reel in prey from great distances. Curiously, electricity slows them rather than harming them normally.",
                  source: "Monster Core", isPremium: true),

            // MARK: - Constructs

            .make("Animated Armor", level: 2,
                  creatureType: "Construct", size: "Medium",
                  traits: "Construct, Mindless",
                  hp: "30", ac: 18, fort: 9, ref: 6, will: 4,
                  speed: "20 feet",
                  attacks: "Longsword +10 (1d8+4 slashing; Versatile P)",
                  specialAbilities: "Darkvision; Immunities: bleed, death effects, disease, fatigued, healing, mental, necromancy, nonlethal attacks, paralyzed, poison, sickened, unconscious; Construct Armor (hardness 6)",
                  summary: "A suit of armor animated by magic to serve as a tireless guardian.",
                  desc: "Animated armor is a common magical construct created to guard rooms, halls, and vaults. These suits of armor move with eerie purpose, following their creator's instructions to the letter. They are mindless and cannot be reasoned with or intimidated.",
                  source: "Monster Core", isPremium: true),

            .make("Shield Guardian", level: 7,
                  creatureType: "Construct", size: "Large",
                  traits: "Construct",
                  hp: "130", ac: 25, fort: 17, ref: 12, will: 13,
                  speed: "25 feet",
                  attacks: "Fist +18 (2d8+8 bludgeoning)",
                  specialAbilities: "Darkvision; Construct Immunities; Guardian Shield (shield master from damage, absorbing half); Spell Storing (can store one spell up to 4th level); Master Link",
                  summary: "A powerful construct bound to an amulet-wearing master whom it protects at all costs.",
                  desc: "Shield guardians are sophisticated constructs created to protect a specific master who wears a linked control amulet. The guardian can absorb damage meant for its master and even store a spell for later use. Should the amulet change hands, the guardian's loyalty shifts to the new wearer.",
                  source: "Monster Core", isPremium: true),

            .make("Flesh Golem", level: 8,
                  creatureType: "Construct", size: "Large",
                  traits: "Construct, Mindless",
                  hp: "135", ac: 24, fort: 18, ref: 12, will: 14,
                  speed: "25 feet",
                  attacks: "Fist +19 (2d10+8 bludgeoning)",
                  specialAbilities: "Darkvision; Construct Immunities; Golem Antimagic; Berserk (when reduced below half HP, DC 5 flat check each round to go berserk); Electricity Healed (electricity damage heals the golem); Vulnerability to Fire",
                  summary: "A hulking construct stitched together from humanoid corpses and animated by lightning.",
                  desc: "Flesh golems are grotesque constructs assembled from the body parts of multiple humanoid corpses. They are animated through electrical impulses and can absorb lightning to heal their wounds. A flesh golem that takes too much damage risks going berserk, attacking everything in sight.",
                  source: "Monster Core", isPremium: true),

            .make("Stone Golem", level: 11,
                  creatureType: "Construct", size: "Large",
                  traits: "Construct, Mindless",
                  hp: "200", ac: 30, fort: 22, ref: 16, will: 19,
                  speed: "20 feet",
                  attacks: "Fist +24 (2d10+12 bludgeoning)",
                  specialAbilities: "Darkvision; Construct Immunities; Golem Antimagic; Slow (DC 28 Fortitude; slowed 1 for 1 minute); Hardness 10; Vulnerable to Shatter",
                  summary: "A massive stone construct that can slow enemies with its heavy blows.",
                  desc: "Stone golems are imposing constructs carved from solid rock and animated through powerful magic. They move with deceptive speed for their bulk and their strikes carry a supernatural weight that slows victims. Their golem antimagic makes most spells useless against them.",
                  source: "Monster Core", isPremium: true),

            .make("Clay Golem", level: 10,
                  creatureType: "Construct", size: "Large",
                  traits: "Construct, Mindless",
                  hp: "175", ac: 26, fort: 21, ref: 14, will: 17,
                  speed: "20 feet",
                  attacks: "Fist +23 (2d10+10 bludgeoning plus cursed wound)",
                  specialAbilities: "Darkvision; Construct Immunities; Golem Antimagic; Cursed Wound (wounds dealt cannot be healed magically unless DC 29 counteract check); Berserk; Quicken (haste for 1 round when affected by certain magic)",
                  summary: "A clay construct whose cursed strikes prevent magical healing.",
                  desc: "Clay golems are constructs molded from enchanted clay that hardens to supernatural toughness. Their most insidious ability is their cursed wound: injuries dealt by a clay golem resist all magical healing. They can occasionally be quickened by certain spells, becoming terrifyingly fast for a brief moment.",
                  source: "Monster Core", isPremium: true),

            .make("Iron Golem", level: 13,
                  creatureType: "Construct", size: "Large",
                  traits: "Construct, Mindless",
                  hp: "235", ac: 34, fort: 25, ref: 18, will: 22,
                  speed: "20 feet",
                  attacks: "Fist +28 (3d10+12 bludgeoning)",
                  specialAbilities: "Darkvision; Construct Immunities; Golem Antimagic; Breath Weapon (30-foot cone, poison gas, DC 33 Fortitude; 4d6 poison plus sickened 1); Hardness 15; Iron Body (resistant to most physical damage)",
                  summary: "The most powerful common golem, forged from iron and armed with poisonous breath.",
                  desc: "Iron golems are among the most powerful and feared constructs in existence. Forged from massive quantities of iron and animated by the most potent golem-creation rituals, they can exhale clouds of poisonous gas and shrug off blows that would fell lesser creatures. Only the wealthiest and most skilled artificers can create them.",
                  source: "Monster Core", isPremium: true),

            // MARK: - More Undead

            .make("Wraith", level: 6,
                  creatureType: "Undead", size: "Medium",
                  traits: "Undead, Incorporeal",
                  hp: "60 (negative healing)", ac: 23, fort: 11, ref: 16, will: 15,
                  speed: "fly 40 feet",
                  attacks: "Spectral Hand +16 (2d8+4 negative; Finesse)",
                  specialAbilities: "Darkvision; Incorporeal; Drain Life (on hit, DC 22 Fortitude or drained 1); Sunlight Powerlessness; Spawn Wraith (creatures killed rise as wraiths)",
                  summary: "An incorporeal undead born of evil that drains the life from the living.",
                  desc: "Wraiths are hateful incorporeal undead born from the shades of mortals who were consumed by evil in life. Their touch saps the life force of living creatures, and those slain by a wraith rise as lesser wraiths under its command. Sunlight renders them nearly powerless.",
                  source: "Monster Core", isPremium: true),

            .make("Specter", level: 7,
                  creatureType: "Undead", size: "Medium",
                  traits: "Undead, Incorporeal",
                  hp: "70 (negative healing)", ac: 24, fort: 12, ref: 17, will: 16,
                  speed: "fly 40 feet",
                  attacks: "Spectral Hand +17 (2d8+5 negative; Finesse)",
                  specialAbilities: "Darkvision; Incorporeal; Drain Life (DC 24 Fortitude or drained 1); Frightful Presence (30 feet, DC 23 Will); Sunlight Powerlessness",
                  summary: "A powerful incorporeal spirit that radiates terror and drains life energy.",
                  desc: "Specters are incorporeal undead that retain fragments of their former intelligence, making them more cunning than common wraiths. They project an aura of supernatural dread and can drain the life force of the living with a touch. Specters are often bound to the site of their death.",
                  source: "Monster Core", isPremium: true),

            .make("Mummy Guardian", level: 6,
                  creatureType: "Undead", size: "Medium",
                  traits: "Undead",
                  hp: "80 (negative healing)", ac: 23, fort: 14, ref: 10, will: 15,
                  speed: "20 feet",
                  attacks: "Fist +16 (2d6+7 bludgeoning plus mummy rot)",
                  specialAbilities: "Darkvision; Mummy Rot (DC 22 Fortitude; disease, drained 1, slowed 1); Despair Aura (30 feet, DC 22 Will; frightened 1); Vulnerable to Fire",
                  summary: "A preserved corpse bound by ancient rituals to guard a tomb for eternity.",
                  desc: "Mummy guardians are undead created through ancient preservation rituals to serve as eternal sentinels. Their touch carries a terrible rotting disease, and their mere presence fills mortals with supernatural dread. Fire is their greatest weakness, as their preserved wrappings ignite easily.",
                  source: "Monster Core", isPremium: true),

            .make("Banshee", level: 11,
                  creatureType: "Undead", size: "Medium",
                  traits: "Undead, Incorporeal",
                  hp: "160 (negative healing)", ac: 28, fort: 18, ref: 20, will: 23,
                  speed: "fly 60 feet",
                  attacks: "Hand +23 (2d12+8 negative; Finesse)",
                  specialAbilities: "Darkvision; Incorporeal; Wail (DC 31 Fortitude; creatures within 30 feet that fail drop to 0 HP, those that critically fail die); Terrifying Glance (DC 28 Will; frightened 2)",
                  summary: "An incorporeal spirit whose deadly wail can slay all who hear it.",
                  desc: "Banshees are the incorporeal spirits of elves or half-elves who died with overwhelming grief or rage. Their most devastating ability is their wail, a supernaturally potent scream that can outright kill anyone who hears it. Even those who survive the wail are left shaken to their core.",
                  source: "Monster Core", isPremium: true),

            .make("Dullahan", level: 8,
                  creatureType: "Undead", size: "Medium",
                  traits: "Undead",
                  hp: "115 (negative healing)", ac: 27, fort: 17, ref: 16, will: 17,
                  speed: "20 feet",
                  attacks: "Keen Bastard Sword +20 (2d8+8 slashing; Keen), Head +20 (2d6+8 bludgeoning; thrown 30 feet)",
                  specialAbilities: "Darkvision; Frightful Presence (30 feet, DC 25 Will); Summon Steed (nightmare mount); Head Toss (thrown head attack); Doom (DC 25 Will; doomed 1, doomed 2 on critical failure)",
                  summary: "A headless undead horseman that heralds doom with its severed head.",
                  desc: "Dullahans are terrifying headless undead riders that carry their own severed heads. They appear as omens of death, and their gaze can mark victims for doom. A dullahan can summon a nightmare steed and hurls its own head as a devastating ranged weapon.",
                  source: "Monster Core", isPremium: true),

            .make("Lich", level: 17,
                  creatureType: "Undead", size: "Medium",
                  traits: "Undead",
                  hp: "295 (negative healing, rejuvenation)", ac: 39, fort: 27, ref: 28, will: 32,
                  speed: "25 feet",
                  attacks: "Hand +32 (5d8 negative plus paralyzing touch; Finesse, Magical)",
                  specialAbilities: "Darkvision; Rejuvenation (returns in 1d10 days if soul cage intact); Paralyzing Touch (DC 36 Fortitude; paralyzed 1 round, 4 rounds on critical failure); Frightful Presence (60 feet, DC 34 Will); Drain Soul Cage; Spellcasting (arcane prepared, up to 9th-level spells)",
                  summary: "An immensely powerful undead spellcaster who achieved immortality through a soul cage.",
                  desc: "Liches are the most feared of all undead spellcasters, having achieved a form of immortality by binding their soul to a specially prepared phylactery called a soul cage. As long as the soul cage endures, the lich reforms after destruction. They are master arcanists with centuries of accumulated magical knowledge.",
                  source: "Monster Core", isPremium: true),

            .make("Bodak", level: 9,
                  creatureType: "Undead", size: "Medium",
                  traits: "Undead",
                  hp: "120 (negative healing)", ac: 28, fort: 17, ref: 17, will: 20,
                  speed: "20 feet",
                  attacks: "Fist +19 (2d10+6 negative)",
                  specialAbilities: "Darkvision; Death Gaze (30 feet, DC 28 Fortitude; 5d6 negative, drained 1 on failure); Sunlight Vulnerability (takes 10 damage per round in sunlight); Draining Presence (30 feet, DC 26 Will; drained 1)",
                  summary: "An undead creature whose deathly gaze can slay the living outright.",
                  desc: "Bodaks are undead horrors created when a mortal is exposed to the essence of the Abyss. Their sunken eyes radiate a death gaze that can drain the life force of any living creature that meets their stare. They shun sunlight, which causes them intense pain.",
                  source: "Monster Core", isPremium: true),

            .make("Skeleton Lord", level: 5,
                  creatureType: "Undead", size: "Medium",
                  traits: "Undead",
                  hp: "55 (negative healing)", ac: 22, fort: 10, ref: 13, will: 12,
                  speed: "25 feet",
                  attacks: "Longsword +14 (1d8+5 slashing; Versatile P), Shield Bash +14 (1d6+5 bludgeoning)",
                  specialAbilities: "Darkvision; Undead Immunities; Command Undead (can command lesser undead within 30 feet); Shield Block; Attack of Opportunity",
                  summary: "An intelligent skeletal warrior that commands lesser undead in battle.",
                  desc: "Unlike mindless skeletons, skeleton lords retain their intelligence and combat prowess from life. They often serve as lieutenants to necromancers or lead small bands of lesser undead. Their tactical acumen and ability to command other undead make them far more dangerous than common skeletons.",
                  source: "Monster Core", isPremium: true),

            .make("Vampire Spawn", level: 4,
                  creatureType: "Undead", size: "Medium",
                  traits: "Undead, Vampire",
                  hp: "50 (negative healing; coffin bound)", ac: 21, fort: 11, ref: 13, will: 12,
                  speed: "25 feet, climb 25 feet",
                  attacks: "Jaws +13 (2d6+5 piercing plus Drink Blood), Claw +13 (2d4+5 slashing; Agile)",
                  specialAbilities: "Darkvision; Vampire Weaknesses (sunlight, running water, garlic, stake through heart); Drink Blood; Mist Form; Coffin Bound",
                  summary: "A newly turned vampire still bound to the will of its creator.",
                  desc: "Vampire spawn are freshly turned vampires who remain under the thrall of their creator. They retain most vampiric powers but lack the independence and cunning of true vampires. A vampire spawn freed from its master's control may eventually grow into a full vampire.",
                  source: "Monster Core", isPremium: true),

            .make("Vampire Count", level: 7,
                  creatureType: "Undead", size: "Medium",
                  traits: "Undead, Vampire",
                  hp: "120 (negative healing; coffin bound)", ac: 26, fort: 14, ref: 17, will: 17,
                  speed: "25 feet, climb 25 feet",
                  attacks: "Jaws +17 (2d8+8 piercing plus Drink Blood), Claw +17 (2d6+8 slashing; Agile)",
                  specialAbilities: "Darkvision; Vampire Weaknesses (sunlight, running water, garlic, stake through heart); Drink Blood; Dominate (DC 24 Will); Children of the Night; Mist Form; Change Shape (bat or wolf)",
                  summary: "A powerful vampire noble who commands lesser undead and dominates mortal minds.",
                  desc: "Vampire counts are aristocratic undead who have survived for centuries by feeding on humanoid blood. They maintain the appearance of life while directing the undead and other monsters from the shadows. Their ability to dominate minds makes them dangerous manipulators.",
                  source: "Monster Core", isPremium: true),

            // MARK: - Oozes

            .make("Gelatinous Cube", level: 3,
                  creatureType: "Ooze", size: "Huge",
                  traits: "Ooze, Mindless",
                  hp: "55", ac: 10, fort: 11, ref: 3, will: 3,
                  speed: "15 feet",
                  attacks: "Cube Face +11 (1d6+3 acid plus Engulf)",
                  specialAbilities: "Motion Sense 60 feet; Transparent (DC 20 Perception to notice); Engulf (DC 19 Reflex; 2d6 acid and paralyzed); Immunities: acid, critical hits, mental, precision, unconscious, visual",
                  summary: "A nearly invisible cube of acidic jelly that silently engulfs creatures in dungeon corridors.",
                  desc: "Gelatinous cubes are large, transparent oozes that fill dungeon corridors almost perfectly, making them nearly impossible to detect until it is too late. They dissolve organic matter with powerful acid, leaving behind only metal and stone. Many a careless adventurer has walked straight into one.",
                  source: "Monster Core", isPremium: true),

            .make("Gray Ooze", level: 4,
                  creatureType: "Ooze", size: "Medium",
                  traits: "Ooze, Mindless",
                  hp: "65", ac: 12, fort: 13, ref: 6, will: 5,
                  speed: "10 feet, climb 10 feet",
                  attacks: "Pseudopod +13 (1d6+4 bludgeoning plus 1d6 acid plus Grab)",
                  specialAbilities: "Motion Sense 60 feet; Acid (destroys metal and organic material on contact); Metal Erosion (metal weapons that strike it take acid damage); Immunities: acid, critical hits, mental, precision, unconscious, visual",
                  summary: "A stone-colored ooze that dissolves metal and flesh with corrosive acid.",
                  desc: "Gray oozes are amorphous masses of stone-colored protoplasm that blend perfectly with dungeon floors and cave walls. They secrete a potent acid that dissolves both metal and organic material. Striking a gray ooze with a metal weapon is risky, as the acid quickly corrodes blades and armor.",
                  source: "Monster Core", isPremium: true),

            .make("Black Pudding", level: 7,
                  creatureType: "Ooze", size: "Huge",
                  traits: "Ooze, Mindless",
                  hp: "115", ac: 15, fort: 17, ref: 9, will: 9,
                  speed: "20 feet, climb 20 feet",
                  attacks: "Pseudopod +18 (2d8+7 bludgeoning plus 2d6 acid plus Grab)",
                  specialAbilities: "Motion Sense 60 feet; Corrosive Mass (2d6 acid to creatures and objects touching it); Split (when hit by slashing or piercing, splits into two oozes); Immunities: acid, critical hits, mental, precision, unconscious, visual",
                  summary: "A massive black ooze that corrodes everything it touches and splits when cut.",
                  desc: "Black puddings are among the most dangerous oozes, capable of dissolving nearly any material with their highly corrosive acid. Slashing or piercing attacks cause them to split into smaller but still dangerous puddings. They are drawn to vibration and heat, mindlessly engulfing anything organic in their path.",
                  source: "Monster Core", isPremium: true),

            .make("Ochre Jelly", level: 5,
                  creatureType: "Ooze", size: "Large",
                  traits: "Ooze, Mindless",
                  hp: "85", ac: 13, fort: 14, ref: 8, will: 7,
                  speed: "15 feet, climb 10 feet",
                  attacks: "Pseudopod +14 (1d8+6 bludgeoning plus 1d4 acid plus Grab)",
                  specialAbilities: "Motion Sense 60 feet; Acid; Split (slashing or electricity causes it to split); Constrict (1d8+3 bludgeoning plus 1d4 acid); Immunities: acid, critical hits, electricity, mental, precision, unconscious, visual",
                  summary: "A large yellow ooze that splits when exposed to slashing attacks or electricity.",
                  desc: "Ochre jellies are large, yellow-orange oozes that squeeze through cracks and crevices in pursuit of prey. Like black puddings, they can split into smaller copies when subjected to slashing or electrical damage. They are a common hazard in dungeons and underground waterways.",
                  source: "Monster Core", isPremium: true),

            // MARK: - Fey

            .make("Dryad", level: 3,
                  creatureType: "Fey", size: "Medium",
                  traits: "Fey, Plant",
                  hp: "40", ac: 19, fort: 8, ref: 11, will: 12,
                  speed: "25 feet",
                  attacks: "Branch +10 (1d8+3 bludgeoning)",
                  specialAbilities: "Low-Light Vision; Tree Dependent (bound to a specific tree, sickened when far away); Tree Meld (merge into bonded tree); Charm (DC 21 Will); Speak with Plants",
                  summary: "A gentle fey spirit bound to a specific tree in an ancient forest.",
                  desc: "Dryads are fey spirits intrinsically bound to a specific tree. They protect the forest surrounding their bonded tree and can charm intruders into leaving peacefully. A dryad whose tree is destroyed sickens and eventually dies, making them fierce defenders of their woodland homes.",
                  source: "Monster Core", isPremium: true),

            .make("Pixie", level: 4,
                  creatureType: "Fey", size: "Tiny",
                  traits: "Fey",
                  hp: "45", ac: 20, fort: 9, ref: 13, will: 13,
                  speed: "15 feet, fly 45 feet",
                  attacks: "Shortsword +13 (1d6+3 piercing; Agile, Finesse)",
                  specialAbilities: "Low-Light Vision; Primal Innate Spells (DC 23); Invisibility (at will); Dispel Magic; Entangle; Dancing Lights; Detect Magic; Polymorph Pranks",
                  summary: "A tiny, mischievous winged fey with potent innate magic and a love of pranks.",
                  desc: "Pixies are tiny winged fey known for their mischievous nature and surprisingly powerful innate magic. They can turn invisible at will and delight in playing pranks on travelers. Despite their playful demeanor, pixies fiercely protect their forest homes from those who would despoil nature.",
                  source: "Monster Core", isPremium: true),

            .make("Satyr", level: 4,
                  creatureType: "Fey", size: "Medium",
                  traits: "Fey",
                  hp: "55", ac: 20, fort: 11, ref: 12, will: 11,
                  speed: "35 feet",
                  attacks: "Dagger +13 (1d4+5 piercing; Agile, Finesse, Versatile S), Shortbow +13 (1d6+3 piercing; range 60 feet)",
                  specialAbilities: "Low-Light Vision; Fleet (ignores difficult terrain in forests); Panpipes (DC 21 Will; fascinated, sleep, or frightened depending on melody); Sylvan Wine",
                  summary: "A goat-legged fey reveler whose enchanting panpipes bend the will of listeners.",
                  desc: "Satyrs are carefree fey with the upper body of a humanoid and the legs of a goat. They are fond of wine, music, and revelry, and their enchanting panpipes can fascinate, frighten, or lull listeners to sleep. Satyrs prefer to avoid combat but are capable fighters when cornered.",
                  source: "Monster Core", isPremium: true),

            .make("Redcap", level: 5,
                  creatureType: "Fey", size: "Small",
                  traits: "Fey",
                  hp: "65", ac: 22, fort: 12, ref: 13, will: 12,
                  speed: "40 feet",
                  attacks: "Scythe +14 (2d10+5 slashing; Deadly d10, Trip), Boot Stomp +14 (1d6+5 bludgeoning; Agile)",
                  specialAbilities: "Low-Light Vision; Iron Boots; Blood Soak (must soak cap in blood every 3 days or weaken); Quick Sprint (60-foot Stride as a single action); Deadly Cleave",
                  summary: "A vicious small fey that dyes its cap in the blood of its victims.",
                  desc: "Redcaps are murderous fey that resemble small, wiry old men wearing iron boots and caps dyed red with blood. They must regularly soak their caps in fresh blood to maintain their power. Despite their small size, redcaps wield oversized scythes and are shockingly fast and strong.",
                  source: "Monster Core", isPremium: true),

            .make("Nymph", level: 7,
                  creatureType: "Fey", size: "Medium",
                  traits: "Fey",
                  hp: "100", ac: 25, fort: 13, ref: 16, will: 18,
                  speed: "25 feet, swim 25 feet",
                  attacks: "Branch +15 (1d8+5 bludgeoning)",
                  specialAbilities: "Low-Light Vision; Nymph's Beauty (30 feet, DC 25 Will; fascinated on failure, permanently blinded on critical failure); Primal Innate Spells (DC 25; charm, heal, tree shape); Speak with Animals; Tied to the Land",
                  summary: "A breathtakingly beautiful fey whose mere appearance can blind onlookers.",
                  desc: "Nymphs are fey of transcendent beauty tied to a specific natural feature such as a pond, grove, or waterfall. Their supernatural beauty is so overwhelming that merely looking upon one can leave mortals fascinated or even permanently blinded. Nymphs are powerful primal spellcasters who defend their domains with subtle magic.",
                  source: "Monster Core", isPremium: true),
        ]

        for monster in monsters {
            try await db.insertMonster(monster)
        }
    }
}
