import Foundation

private extension FeatEntry {
    static func make(
        _ title: String,
        featType: String,
        prerequisites: String,
        benefit: String,
        normal: String = "",
        special: String = "",
        summary: String,
        source: String = "Core Rulebook",
        isPremium: Bool = false
    ) -> FeatEntry {
        FeatEntry(
            id: seededUUID(title + source),
            title: title,
            summary: summary,
            isPremium: isPremium,
            prerequisites: prerequisites,
            benefit: benefit,
            normal: normal,
            special: special,
            featType: featType,
            source: source
        )
    }
}

extension SeedDataBuilder {
    func seedFeats() async throws {
        let feats: [FeatEntry] = [

            // MARK: - Combat Feats

            .make("Agile Maneuvers",
                  featType: "Combat",
                  prerequisites: "",
                  benefit: "Use your Dexterity modifier in place of your Strength modifier when determining your CMB.",
                  summary: "Use Dexterity instead of Strength for combat maneuver bonus calculations."),

            .make("Blind-Fight",
                  featType: "Combat",
                  prerequisites: "",
                  benefit: "In melee, every time you miss because of concealment (see Combat), you can reroll your miss chance percentile roll one time to see if you actually hit. An invisible attacker gets no advantages related to hitting you in melee. That is, you don't lose your Dexterity bonus to Armor Class, and the attacker doesn't get the usual +2 bonus for being invisible. The invisible attacker's bonuses do still apply for ranged attacks, however. You do not need to make Acrobatics skill checks to move at full speed while blinded.",
                  summary: "Reroll miss chances from concealment and negate invisibility bonuses in melee."),

            .make("Catch Off-Guard",
                  featType: "Combat",
                  prerequisites: "",
                  benefit: "You do not suffer any penalties for using an improvised melee weapon. Unarmed opponents are flat-footed against any attacks you make with an improvised melee weapon.",
                  summary: "Wield improvised melee weapons without penalty and catch unarmed foes flat-footed."),

            .make("Combat Expertise",
                  featType: "Combat",
                  prerequisites: "Int 13",
                  benefit: "You can choose to take a –1 penalty on melee attack rolls and combat maneuver checks to gain a +1 dodge bonus to your Armor Class. When your base attack bonus reaches +4, and every +4 thereafter, the penalty increases by –1 and the dodge bonus increases by +1. You can only choose to use this feat when you declare that you are making an attack or a full-attack action with a melee weapon.",
                  normal: "You cannot take a penalty on attack rolls to gain a bonus to Armor Class.",
                  summary: "Trade melee attack accuracy for a dodge bonus to AC."),

            .make("Combat Reflexes",
                  featType: "Combat",
                  prerequisites: "",
                  benefit: "You may make a number of additional attacks of opportunity per round equal to your Dexterity bonus. With this feat, you may also make attacks of opportunity while flat-footed.",
                  normal: "A character without this feat can make only one attack of opportunity per round and can't make attacks of opportunity while flat-footed.",
                  summary: "Make additional attacks of opportunity equal to your Dexterity modifier."),

            .make("Cleave",
                  featType: "Combat",
                  prerequisites: "Str 13, Power Attack, base attack bonus +1",
                  benefit: "As a standard action, you can make a single attack at your full base attack bonus against a foe within reach. If you hit, you deal damage normally and can make an additional attack (using your full base attack bonus) against a foe that is adjacent to the first and also within reach. You can only make one additional attack per round with this feat. When you use this feat, you take a –2 penalty to your Armor Class until your next turn.",
                  normal: "You can make only one attack per standard action.",
                  summary: "Strike one foe then make a free attack against an adjacent enemy."),

            .make("Critical Focus",
                  featType: "Combat",
                  prerequisites: "Base attack bonus +9",
                  benefit: "You receive a +4 circumstance bonus on attack rolls made to confirm critical hits.",
                  summary: "Gain +4 on attack rolls when confirming critical hits."),

            .make("Dazzling Display",
                  featType: "Combat",
                  prerequisites: "Weapon Focus, proficiency with weapon",
                  benefit: "While wielding the weapon in which you have Weapon Focus, you can perform a bewildering show of prowess as a full-round action. Make an Intimidate check to demoralize all foes within 30 feet who can see your display.",
                  summary: "Demoralize all nearby foes with a single intimidating display."),

            .make("Deadly Aim",
                  featType: "Combat",
                  prerequisites: "Dex 13, base attack bonus +1",
                  benefit: "You can choose to take a –1 penalty on all ranged attack rolls to gain a +2 bonus on all ranged damage rolls. When your base attack bonus reaches +4, and every +4 thereafter, the penalty increases by –1 and the bonus to damage increases by +2. You must choose to use this feat before making an attack roll, and its effects last until your next turn.",
                  normal: "You cannot take a penalty on attack rolls to gain a bonus on damage rolls.",
                  summary: "Trade ranged attack accuracy for bonus ranged damage."),

            .make("Deflect Arrows",
                  featType: "Combat",
                  prerequisites: "Dex 13, Improved Unarmed Strike",
                  benefit: "You must have at least one hand free (holding nothing) to use this feat. Once per round when you would normally be hit with an attack from a ranged weapon, you may deflect it so that you take no damage from it. You must be aware of the attack and not flat-footed. Unusually massive ranged weapons (such as boulders or ballista bolts) and ranged attacks generated by spell effects can't be deflected.",
                  normal: "A character without this feat is hit by ranged attacks normally.",
                  summary: "Once per round, deflect one ranged weapon attack that would hit you."),

            .make("Disruptive",
                  featType: "Combat",
                  prerequisites: "6th-level fighter",
                  benefit: "The DC to cast spells defensively increases by 4 for all enemies that are within your threatened area. This increase to casting spells defensively applies only if you are aware of the enemy's location and are capable of taking an attack of opportunity.",
                  summary: "Increase the DC for enemies to cast defensively within your threatened area."),

            .make("Double Slice",
                  featType: "Combat",
                  prerequisites: "Dex 15, Two-Weapon Fighting",
                  benefit: "Add your Strength bonus to damage rolls made with your off-hand weapon.",
                  normal: "You normally add only half of your Strength bonus to damage rolls made with a weapon in your off hand.",
                  summary: "Add your full Strength bonus to off-hand weapon damage rolls."),

            .make("Exotic Weapon Proficiency",
                  featType: "Combat",
                  prerequisites: "Base attack bonus +1",
                  benefit: "You make attack rolls with the selected exotic weapon normally.",
                  normal: "A character who uses a weapon with which they are not proficient takes a –4 penalty on attack rolls.",
                  special: "You can gain this feat multiple times. Each time you take the feat, it applies to a new type of exotic weapon.",
                  summary: "Become proficient with one exotic weapon of your choice."),

            .make("Far Shot",
                  featType: "Combat",
                  prerequisites: "Point-Blank Shot",
                  benefit: "You only suffer a –1 penalty per full range increment between you and your target when using a ranged weapon.",
                  normal: "You suffer –2 penalty per full range increment between you and your target.",
                  summary: "Halve the range increment penalty for ranged attacks."),

            .make("Great Cleave",
                  featType: "Combat",
                  prerequisites: "Str 13, Cleave, Power Attack, base attack bonus +4",
                  benefit: "As a standard action, you can make a single attack at your full base attack bonus against a foe within reach. If you hit, you deal damage normally and can make an additional attack (using your full base attack bonus) against a foe that is adjacent to the previous foe and also within reach. You can make these additional attacks as long as you continue to hit foes. You take a –2 penalty to your AC until your next turn.",
                  summary: "Chain Cleave attacks as long as each hit connects with adjacent foes."),

            .make("Greater Bull Rush",
                  featType: "Combat",
                  prerequisites: "Improved Bull Rush, Power Attack, Str 13, base attack bonus +6",
                  benefit: "You receive a +2 bonus on checks made to bull rush a foe. This bonus stacks with the bonus granted by Improved Bull Rush. Whenever you bull rush an opponent, his movement does not provoke attacks of opportunity. If you bull rush an opponent into a wall or other solid object, he takes 1d6 points of damage.",
                  summary: "Improve bull rush checks and deal damage when pushing enemies into walls."),

            .make("Greater Disarm",
                  featType: "Combat",
                  prerequisites: "Combat Expertise, Improved Disarm, Int 13, base attack bonus +6",
                  benefit: "You receive a +2 bonus on checks made to disarm a foe. This bonus stacks with the bonus granted by Improved Disarm. Whenever you disarm an opponent, the weapon lands in a square of your choice within your reach.",
                  summary: "Improve disarm checks and choose where disarmed weapons land."),

            .make("Greater Feint",
                  featType: "Combat",
                  prerequisites: "Combat Expertise, Improved Feint, Int 13, base attack bonus +6",
                  benefit: "Whenever you use feint to cause a foe to lose his Dexterity bonus, he loses that bonus until the beginning of your next turn, in addition to losing his Dexterity bonus against your next attack.",
                  summary: "A successful feint denies the target's Dex bonus until the start of your next turn."),

            .make("Greater Grapple",
                  featType: "Combat",
                  prerequisites: "Improved Grapple, Improved Unarmed Strike, Dex 13, base attack bonus +6",
                  benefit: "You receive a +2 bonus on checks made to grapple a foe. This bonus stacks with the bonus granted by Improved Grapple. Once you have grappled a creature, maintaining the grapple is a move action. This feat allows you to make two grapple checks each round (to move, harm, or pin your opponent), but you are not required to make two checks.",
                  summary: "Improve grapple checks and maintain grapples as a move action."),

            .make("Greater Overrun",
                  featType: "Combat",
                  prerequisites: "Improved Overrun, Power Attack, Str 13, base attack bonus +6",
                  benefit: "You receive a +2 bonus on checks made to overrun a foe. This bonus stacks with the bonus granted by Improved Overrun. Whenever you overrun an opponent, that opponent cannot choose to avoid you. If you overrun an opponent in this way, that opponent is also knocked prone at the end of your movement.",
                  summary: "Improve overrun checks and knock prone any opponent you overrun."),

            .make("Greater Sunder",
                  featType: "Combat",
                  prerequisites: "Improved Sunder, Power Attack, Str 13, base attack bonus +6",
                  benefit: "You receive a +2 bonus on checks made to sunder armor or weapons. This bonus stacks with the bonus granted by Improved Sunder. Whenever you sunder to destroy an item, any excess damage is applied to the item's wielder.",
                  summary: "Improve sunder checks and deal excess damage to the item's wielder."),

            .make("Greater Trip",
                  featType: "Combat",
                  prerequisites: "Combat Expertise, Improved Trip, Int 13, base attack bonus +6",
                  benefit: "You receive a +2 bonus on checks made to trip a foe. This bonus stacks with the bonus granted by Improved Trip. Whenever you trip an opponent, that opponent provokes attacks of opportunity.",
                  summary: "Improve trip checks and trigger attacks of opportunity when you trip foes."),

            .make("Greater Two-Weapon Fighting",
                  featType: "Combat",
                  prerequisites: "Dex 19, Improved Two-Weapon Fighting, Two-Weapon Fighting, base attack bonus +11",
                  benefit: "You get a third attack with your off-hand weapon, albeit at a –10 penalty.",
                  summary: "Make a third off-hand weapon attack at a –10 penalty."),

            .make("Greater Vital Strike",
                  featType: "Combat",
                  prerequisites: "Improved Vital Strike, Vital Strike, base attack bonus +16",
                  benefit: "When you use the attack action, you can make one attack at your highest base attack bonus that deals four times the normal number of weapon damage dice.",
                  summary: "Deal four times normal weapon damage dice on a single attack action."),

            .make("Improved Bull Rush",
                  featType: "Combat",
                  prerequisites: "Str 13, Power Attack, base attack bonus +1",
                  benefit: "You do not provoke an attack of opportunity when performing a bull rush combat maneuver. In addition, you receive a +2 bonus on checks made to bull rush a foe. You also receive a +2 bonus to your Combat Maneuver Defense whenever an opponent tries to bull rush you.",
                  normal: "You provoke an attack of opportunity when performing a bull rush combat maneuver.",
                  summary: "Bull rush without provoking and gain bonuses to bull rush checks."),

            .make("Improved Critical",
                  featType: "Combat",
                  prerequisites: "Proficient with weapon, base attack bonus +8",
                  benefit: "When using the weapon you selected, your threat range is doubled.",
                  normal: "The threat range is as listed in the weapon description.",
                  special: "You can gain Improved Critical multiple times. The effects do not stack. Each time you take the feat, it applies to a new type of weapon. This effect doesn't stack with any other effect that expands the threat range of a weapon.",
                  summary: "Double the threat range of your chosen weapon."),

            .make("Improved Disarm",
                  featType: "Combat",
                  prerequisites: "Combat Expertise, Int 13",
                  benefit: "You do not provoke an attack of opportunity when performing a disarm combat maneuver. In addition, you receive a +2 bonus on checks made to disarm a foe. You also receive a +2 bonus to your Combat Maneuver Defense whenever an opponent tries to disarm you.",
                  normal: "You provoke an attack of opportunity when performing a disarm combat maneuver.",
                  summary: "Disarm without provoking and gain bonuses to disarm checks."),

            .make("Improved Feint",
                  featType: "Combat",
                  prerequisites: "Combat Expertise, Int 13",
                  benefit: "You can make a Bluff check to feint in combat as a move action.",
                  normal: "Feinting in combat is a standard action.",
                  summary: "Feint as a move action instead of a standard action."),

            .make("Improved Grapple",
                  featType: "Combat",
                  prerequisites: "Dex 13, Improved Unarmed Strike",
                  benefit: "You do not provoke an attack of opportunity when performing a grapple combat maneuver. In addition, you receive a +2 bonus on checks made to grapple a foe. You also receive a +2 bonus to your Combat Maneuver Defense whenever an opponent tries to grapple you.",
                  normal: "You provoke an attack of opportunity when performing a grapple combat maneuver.",
                  summary: "Grapple without provoking and gain bonuses to grapple checks."),

            .make("Improved Initiative",
                  featType: "Combat",
                  prerequisites: "",
                  benefit: "You get a +4 bonus on initiative checks.",
                  summary: "Gain a +4 bonus on initiative checks."),

            .make("Improved Overrun",
                  featType: "Combat",
                  prerequisites: "Str 13, Power Attack, base attack bonus +1",
                  benefit: "You do not provoke an attack of opportunity when performing an overrun combat maneuver. In addition, you receive a +2 bonus on checks made to overrun a foe. You also receive a +2 bonus to your Combat Maneuver Defense whenever an opponent tries to overrun you. You cannot choose to avoid an overrunning character.",
                  normal: "You provoke an attack of opportunity when performing an overrun combat maneuver.",
                  summary: "Overrun without provoking and gain bonuses to overrun checks."),

            .make("Improved Shield Bash",
                  featType: "Combat",
                  prerequisites: "Shield Proficiency",
                  benefit: "When you perform a shield bash, you may still apply the shield's shield bonus to your AC.",
                  normal: "Without this feat, a character that performs a shield bash loses the shield's bonus to AC until his next turn.",
                  summary: "Retain your shield's AC bonus when using it to shield bash."),

            .make("Improved Sunder",
                  featType: "Combat",
                  prerequisites: "Str 13, Power Attack, base attack bonus +1",
                  benefit: "You do not provoke an attack of opportunity when performing a sunder combat maneuver. In addition, you receive a +2 bonus on checks made to sunder armor or weapons. You also receive a +2 bonus to your Combat Maneuver Defense whenever an opponent tries to sunder your equipment.",
                  normal: "You provoke an attack of opportunity when performing a sunder combat maneuver.",
                  summary: "Sunder without provoking and gain bonuses to sunder checks."),

            .make("Improved Trip",
                  featType: "Combat",
                  prerequisites: "Combat Expertise, Int 13",
                  benefit: "You do not provoke an attack of opportunity when performing a trip combat maneuver. In addition, you receive a +2 bonus on checks made to trip a foe. You also receive a +2 bonus to your Combat Maneuver Defense whenever an opponent tries to trip you.",
                  normal: "You provoke an attack of opportunity when performing a trip combat maneuver.",
                  summary: "Trip without provoking and gain bonuses to trip checks."),

            .make("Improved Two-Weapon Fighting",
                  featType: "Combat",
                  prerequisites: "Dex 17, Two-Weapon Fighting, base attack bonus +6",
                  benefit: "In addition to the standard single extra attack you get with an off-hand weapon, you get a second attack with it, albeit at a –5 penalty.",
                  normal: "Without this feat, you can only get a single extra attack with an off-hand weapon.",
                  summary: "Gain a second off-hand weapon attack at a –5 penalty."),

            .make("Improved Unarmed Strike",
                  featType: "Combat",
                  prerequisites: "",
                  benefit: "You are considered to be armed even when unarmed—you do not provoke attacks of opportunity when you attack foes while unarmed. Your unarmed strikes can deal lethal or nonlethal damage.",
                  normal: "Without this feat, you are considered unarmed when attacking with an unarmed strike, and you can deal only nonlethal damage with such an attack.",
                  summary: "Make armed unarmed strikes that deal lethal damage without provoking."),

            .make("Improved Vital Strike",
                  featType: "Combat",
                  prerequisites: "Vital Strike, base attack bonus +11",
                  benefit: "When you use the attack action, you can make one attack at your highest base attack bonus that deals three times the normal number of weapon damage dice.",
                  summary: "Deal three times normal weapon damage dice on a single attack action."),

            .make("Improvised Weapon Mastery",
                  featType: "Combat",
                  prerequisites: "Catch Off-Guard or Throw Anything, base attack bonus +8",
                  benefit: "You do not suffer any penalties for using an improvised weapon. Increase the amount of damage dealt by the improvised weapon by one step (as if the weapon were designed for a creature one size category larger than you) to a maximum of 1d8. The improvised weapon has a critical threat range of 19–20 and a critical multiplier of ×2.",
                  summary: "Master improvised weapons and treat them as manufactured weapons with improved stats."),

            .make("Lunge",
                  featType: "Combat",
                  prerequisites: "Base attack bonus +6",
                  benefit: "You can increase the reach of your melee attacks by 5 feet until the end of your turn by taking a –2 penalty to your AC until your next turn. You must decide to use this ability before any attacks are made.",
                  summary: "Temporarily extend your melee reach by 5 feet at the cost of AC."),

            .make("Manyshot",
                  featType: "Combat",
                  prerequisites: "Dex 17, Point-Blank Shot, Rapid Shot, base attack bonus +6",
                  benefit: "When making a full-attack action with a bow, your first attack fires two arrows. If the attack hits, both arrows hit. Apply precision-based damage (such as sneak attack) and critical hits to only one of the arrows. No bonuses or penalties that apply to individual arrows (such as from feats) apply to both arrows.",
                  normal: "A single attack fires only one arrow.",
                  summary: "Fire two arrows simultaneously with your first bow attack in a full attack."),

            .make("Martial Weapon Proficiency",
                  featType: "Combat",
                  prerequisites: "",
                  benefit: "You make attack rolls with the selected martial weapon normally.",
                  normal: "A character who uses a weapon with which they are not proficient takes a –4 penalty on attack rolls.",
                  special: "You can gain this feat multiple times. Each time you take the feat, it applies to a new type of martial weapon.",
                  summary: "Become proficient with one martial weapon of your choice."),

            .make("Medusa's Wrath",
                  featType: "Combat",
                  prerequisites: "Improved Unarmed Strike, Gorgon's Fist, Scorpion Style, base attack bonus +11",
                  benefit: "Whenever you use the full-attack action and make at least one unarmed strike, you can make two additional unarmed strikes at your highest base attack bonus. These bonus attacks must be made against a dazed, flat-footed, paralyzed, staggered, stunned, or unconscious foe.",
                  summary: "Make two extra unarmed attacks against incapacitated foes in a full attack."),

            .make("Mounted Archery",
                  featType: "Combat",
                  prerequisites: "Mounted Combat",
                  benefit: "The penalty you take when using a ranged weapon while mounted is halved: –2 instead of –4 if your mount is taking a double move, and –4 instead of –8 if your mount is running.",
                  summary: "Halve the attack penalty for using ranged weapons while mounted."),

            .make("Mounted Combat",
                  featType: "Combat",
                  prerequisites: "Ride 1 rank",
                  benefit: "Once per round when your mount is hit in combat, you may attempt a Ride check (DC equals the result of the opponent's attack roll) to negate the hit. The hit is negated if your Ride check result is greater than the opponent's attack roll.",
                  summary: "Once per round, negate a hit against your mount with a Ride check."),

            .make("Opening Volley",
                  featType: "Combat",
                  prerequisites: "",
                  benefit: "Whenever you deal damage with a ranged attack, you gain a +4 circumstance bonus on your next melee attack roll against that opponent. This bonus must be used before the end of your next turn.",
                  summary: "Gain a +4 bonus on your next melee attack after hitting with a ranged attack."),

            .make("Overhand Chop",
                  featType: "Combat",
                  prerequisites: "Base attack bonus +1",
                  benefit: "When you make a single attack (with the attack or charge action) with a two-handed weapon, you add double your Strength modifier to damage rolls instead of the normal 1.5x.",
                  summary: "Add double your Strength modifier to damage on a single two-handed attack."),

            .make("Penetrating Strike",
                  featType: "Combat",
                  prerequisites: "Weapon Focus, 12th-level fighter",
                  benefit: "Your weapons deal half damage to objects and creatures with damage reduction. Damage reduction is only halved; it is not negated.",
                  summary: "Your attacks deal half damage to creatures and objects with damage reduction."),

            .make("Pin Down",
                  featType: "Combat",
                  prerequisites: "Combat Reflexes, base attack bonus +11",
                  benefit: "Whenever an opponent attempts to move out of a square you threaten, you can make an attack of opportunity against that opponent. If you hit, you deal no damage, but the opponent cannot move out of the square for the rest of its turn. Abilities that prevent attacks of opportunity negate this effect.",
                  summary: "Make attacks of opportunity to prevent enemies from leaving squares you threaten."),

            .make("Pinpoint Targeting",
                  featType: "Combat",
                  prerequisites: "Dex 19, Improved Precise Shot, Point-Blank Shot, Precise Shot, base attack bonus +16",
                  benefit: "As a standard action, make a single ranged attack. The target does not benefit from cover or concealment. This feat has no effect against a target that has total cover or total concealment.",
                  summary: "Make a single ranged attack that ignores cover and concealment."),

            .make("Point-Blank Shot",
                  featType: "Combat",
                  prerequisites: "",
                  benefit: "You get a +1 bonus on attack and damage rolls with ranged weapons at ranges of up to 30 feet.",
                  summary: "Gain +1 on attack and damage rolls with ranged weapons within 30 feet."),

            .make("Power Attack",
                  featType: "Combat",
                  prerequisites: "Str 13, base attack bonus +1",
                  benefit: "You can choose to take a –1 penalty on all melee attack rolls and combat maneuver checks to gain a +2 bonus on all melee damage rolls. This bonus to damage is increased by half (+50%) if you are making an attack with a two-handed weapon, a one-handed weapon using two hands, or a primary natural weapon that adds 1.5x your Strength modifier on damage rolls. This bonus to damage is halved (–50%) if you are making an attack with an off-hand weapon or secondary natural weapon. When your base attack bonus reaches +4, and every +4 thereafter, the penalty increases by –1 and the bonus to damage increases by +2. You must choose to use this feat before making an attack roll.",
                  normal: "You gain no bonus on damage rolls for making such a sacrifice.",
                  special: "If you have the Cleave feat, the penalty also applies to Cleave attack rolls.",
                  summary: "Trade melee attack accuracy for bonus melee damage."),

            .make("Precise Shot",
                  featType: "Combat",
                  prerequisites: "Point-Blank Shot",
                  benefit: "You can shoot or throw ranged weapons at an opponent engaged in melee without taking the standard –4 penalty on your attack roll.",
                  summary: "Shoot into melee without the standard –4 attack penalty."),

            .make("Quick Draw",
                  featType: "Combat",
                  prerequisites: "Base attack bonus +1",
                  benefit: "You can draw a weapon as a free action instead of as a move action. You can draw a hidden weapon (see the Sleight of Hand skill) as a move action. A character who has selected this feat may throw weapons at his full normal rate of attacks (much like a character with a bow).",
                  normal: "Without this feat, you may draw a weapon as a move action, or (if your base attack bonus is +1 or higher) as a free action as part of movement.",
                  summary: "Draw weapons as a free action and throw them at full attack rate."),

            .make("Rapid Reload",
                  featType: "Combat",
                  prerequisites: "Weapon Proficiency (crossbow type chosen)",
                  benefit: "The time required for you to reload your chosen type of crossbow is reduced to a free action (for a hand or light crossbow) or a move action (for a heavy crossbow). Reloading a crossbow still provokes attacks of opportunity.",
                  normal: "A character without this feat needs a move action to reload a hand or light crossbow, or a full-round action to reload a heavy crossbow.",
                  special: "You can gain Rapid Reload multiple times. Each time you take the feat, it applies to a new type of crossbow.",
                  summary: "Reload crossbows significantly faster than normal."),

            .make("Rapid Shot",
                  featType: "Combat",
                  prerequisites: "Dex 13, Point-Blank Shot",
                  benefit: "When making a full-attack action with a ranged weapon, you can fire one additional time this round. All of your attack rolls take a –2 penalty when using Rapid Shot.",
                  summary: "Make one extra ranged attack per round at a –2 penalty to all attacks."),

            .make("Ride-By Attack",
                  featType: "Combat",
                  prerequisites: "Ride 1 rank, Mounted Combat",
                  benefit: "When you are mounted and use the charge action, you may move and attack as if with a standard charge and then continue moving. Your total movement for the round can't exceed double your mounted speed. You and your mount do not provoke an attack of opportunity from the opponent that you attack.",
                  summary: "Charge while mounted, attack, and keep moving without provoking."),

            .make("Saving Shield",
                  featType: "Combat",
                  prerequisites: "Shield Proficiency",
                  benefit: "Whenever an adjacent ally is the target of an attack, you can, as an immediate action, grant that ally a +2 shield bonus to AC. You must be wielding a light shield, heavy shield, or tower shield to use this feat.",
                  summary: "Grant an adjacent ally a +2 shield bonus to AC as an immediate action."),

            .make("Shield Focus",
                  featType: "Combat",
                  prerequisites: "Shield Proficiency, base attack bonus +1",
                  benefit: "Increase the AC bonus from your shield by 1.",
                  summary: "Your shield grants 1 additional point of AC."),

            .make("Shield Master",
                  featType: "Combat",
                  prerequisites: "Improved Shield Bash, Shield Proficiency, Shield Slam, Two-Weapon Fighting, base attack bonus +11",
                  benefit: "You do not suffer any penalties on attack rolls made with a shield while you are wielding another weapon. Add your shield's enhancement bonus to attacks and damage rolls made with the shield as if it were a weapon enhancement bonus.",
                  summary: "Attack with shields without penalty and apply shield enhancement bonuses to damage."),

            .make("Shield Slam",
                  featType: "Combat",
                  prerequisites: "Improved Shield Bash, Shield Proficiency, Two-Weapon Fighting, base attack bonus +6",
                  benefit: "Any time you make a shield bash, you can also make a free bull rush attack (substituting your shield bash attack roll for the bull rush check). This bull rush does not provoke an attack of opportunity. Opponents that cannot be bull rushed cannot be affected by this feat.",
                  summary: "Make a free bull rush attempt with every successful shield bash."),

            .make("Shot on the Run",
                  featType: "Combat",
                  prerequisites: "Dex 13, Dodge, Mobility, Point-Blank Shot, base attack bonus +4",
                  benefit: "As a full-round action, you can move up to your speed and make a single ranged attack at any point during your movement.",
                  summary: "Move your full speed and make a ranged attack at any point during movement."),

            .make("Siege Engineer",
                  featType: "Combat",
                  prerequisites: "Proficiency with all martial weapons or Knowledge (engineering) 5 ranks",
                  benefit: "You are considered to be proficient with all siege weapons. When you are crew chief on a siege weapon, you increase its crew by 1. You can load a direct-fire siege weapon as a standard action rather than as a full-round action.",
                  summary: "Operate siege weapons with full proficiency and improved efficiency."),

            .make("Snatch Arrows",
                  featType: "Combat",
                  prerequisites: "Dex 15, Deflect Arrows, Improved Unarmed Strike",
                  benefit: "When using the Deflect Arrows feat you may catch the weapon instead of just deflecting it. Thrown weapons can be used in melee or thrown back immediately (as a free action) at the original attacker using the same attack bonus with which the weapon was thrown.",
                  summary: "Catch deflected ranged weapons and immediately throw them back."),

            .make("Spellbreaker",
                  featType: "Combat",
                  prerequisites: "Disruptive, 10th-level fighter",
                  benefit: "If an enemy casts a spell within your threatened area and you make an attack of opportunity against that enemy, you can make the attack of opportunity after the enemy completes the casting but before the spell takes effect. If you damage the enemy, the spell is ruined.",
                  summary: "Make attacks of opportunity after spell casting to ruin spells on a hit."),

            .make("Spirited Charge",
                  featType: "Combat",
                  prerequisites: "Ride 1 rank, Mounted Combat, Ride-By Attack",
                  benefit: "When mounted and using the charge action, you deal double damage with a melee weapon (or triple damage with a lance).",
                  summary: "Deal double damage (triple with a lance) when charging while mounted."),

            .make("Squire",
                  featType: "Combat",
                  prerequisites: "Base attack bonus +5, proficient in medium armor",
                  benefit: "You have a squire who can help you maintain your equipment. After a rest period of 8 hours, your squire helps you don and doff armor so that donning armor takes only 5 rounds (or 1 round for medium or lighter non-metal armor) and doffing takes only 1 round. In addition, your squire can provide flanking (but not aid another) when adjacent to an opponent.",
                  summary: "Gain a squire who speeds armor donning and can assist in flanking."),

            .make("Stand Still",
                  featType: "Combat",
                  prerequisites: "Combat Reflexes",
                  benefit: "When a foe provokes an attack of opportunity by moving through your adjacent squares, you can make a combat maneuver check as your attack of opportunity. If successful, the enemy cannot move for the rest of his turn. An enemy can still take the rest of his actions, but cannot move.",
                  summary: "Use attacks of opportunity to stop enemies moving through your space."),

            .make("Step Up",
                  featType: "Combat",
                  prerequisites: "Base attack bonus +1",
                  benefit: "Whenever an adjacent foe attempts to take a 5-foot step away from you, you may also make a 5-foot step as an immediate action so long as you end up adjacent to the foe that triggered this ability.",
                  summary: "Follow an enemy who takes a 5-foot step away from you as an immediate action."),

            .make("Strike Back",
                  featType: "Combat",
                  prerequisites: "Base attack bonus +11",
                  benefit: "You can ready an action to make a melee attack against any foe that attacks you in melee, even if the foe is outside your reach.",
                  summary: "Ready attacks against foes who strike you in melee, even beyond reach."),

            .make("Sundering Strike",
                  featType: "Combat",
                  prerequisites: "Improved Sunder, Power Attack, base attack bonus +9",
                  benefit: "Whenever you confirm a critical hit with a melee attack, you can sunder your opponent's armor or shield as a free action. This sunder attempt does not provoke an attack of opportunity.",
                  summary: "Sunder an opponent's armor or shield for free when you confirm a critical hit."),

            .make("Throw Anything",
                  featType: "Combat",
                  prerequisites: "",
                  benefit: "You do not suffer any penalties for using an improvised ranged weapon. You receive a +1 circumstance bonus on attack rolls made with thrown splash weapons.",
                  summary: "Throw improvised ranged weapons without penalty and gain +1 with splash weapons."),

            .make("Tower Shield Proficiency",
                  featType: "Combat",
                  prerequisites: "Shield Proficiency",
                  benefit: "You can use a tower shield and suffer only the normal penalties.",
                  normal: "A character who is using a shield with which they are not proficient takes the shield's armor check penalty on attack rolls and on all skill checks that involve moving.",
                  summary: "Use a tower shield without nonproficiency penalties."),

            .make("Trample",
                  featType: "Combat",
                  prerequisites: "Ride 1 rank, Mounted Combat",
                  benefit: "When you attempt to overrun an opponent while mounted, your target may not choose to avoid you. Your mount may make one hoof attack against any target you knock down, gaining the standard +4 bonus on attack rolls against prone targets.",
                  summary: "Force opponents to face your mounted overrun and allow your mount to attack downed foes."),

            .make("Two-Weapon Defense",
                  featType: "Combat",
                  prerequisites: "Dex 15, Two-Weapon Fighting",
                  benefit: "When wielding a double weapon or two weapons (not including natural weapons or unarmed strikes), you gain a +1 shield bonus to your AC. When you are fighting defensively or using the total defense action, this shield bonus increases to +2.",
                  summary: "Gain a shield bonus to AC while fighting with two weapons."),

            .make("Two-Weapon Fighting",
                  featType: "Combat",
                  prerequisites: "Dex 15",
                  benefit: "Your penalties on attack rolls for fighting with two weapons are reduced. The penalty for your primary hand lessens by 2 and the one for your off hand lessens by 6.",
                  normal: "If you wield a second weapon in your off hand, you can get one extra attack per round with that weapon. When fighting in this way you suffer a –6 penalty with your regular attack or attacks with your primary hand and a –10 penalty to the attack with your off hand.",
                  summary: "Reduce the attack penalties for fighting with a weapon in each hand."),

            .make("Two-Weapon Rend",
                  featType: "Combat",
                  prerequisites: "Dex 17, Double Slice, Improved Two-Weapon Fighting, Two-Weapon Fighting, base attack bonus +11",
                  benefit: "If you hit an opponent with both your primary hand weapon and your off-hand weapon, you deal an additional 1d10 points of damage plus 1.5 times your Strength modifier. You can only deal this additional damage once per round.",
                  summary: "Deal bonus damage once per round when hitting with both your weapons."),

            .make("Unseat",
                  featType: "Combat",
                  prerequisites: "Str 13, Mounted Combat, Ride-By Attack, Spirited Charge, Power Attack, Ride 1 rank, base attack bonus +1",
                  benefit: "When mounted, if you strike an opponent with a lance and the result of your attack roll exceeds your opponent's CMD by 5 or more, you can make a free combat maneuver check to attempt to unseat your opponent (if he is also mounted).",
                  summary: "Unseat a mounted opponent for free after a powerful lance hit."),

            .make("Vital Strike",
                  featType: "Combat",
                  prerequisites: "Base attack bonus +6",
                  benefit: "When you use the attack action, you can make one attack at your highest base attack bonus that deals twice the normal number of weapon damage dice.",
                  summary: "Deal twice normal weapon damage dice on a single attack action."),

            .make("Weapon Finesse",
                  featType: "Combat",
                  prerequisites: "",
                  benefit: "With a light weapon, elven curve blade, rapier, whip, or spiked chain made for a creature of your size category, you may use your Dexterity modifier instead of your Strength modifier on attack rolls. If you carry a shield, its armor check penalty applies to your attack rolls.",
                  special: "Natural weapons are considered light weapons.",
                  summary: "Use Dexterity instead of Strength on attack rolls with light and finessable weapons."),

            .make("Weapon Focus",
                  featType: "Combat",
                  prerequisites: "Proficiency with selected weapon, base attack bonus +1",
                  benefit: "You gain a +1 bonus on all attack rolls you make using the selected weapon.",
                  special: "You can gain this feat multiple times. Its effects do not stack. Each time you take the feat, it applies to a new type of weapon.",
                  summary: "Gain a +1 bonus on attack rolls with your chosen weapon."),

            .make("Weapon Specialization",
                  featType: "Combat",
                  prerequisites: "Proficiency with selected weapon, Weapon Focus with selected weapon, 4th-level fighter",
                  benefit: "You gain a +2 bonus on all damage rolls you make using the selected weapon.",
                  special: "You can gain this feat multiple times. Its effects do not stack. Each time you take the feat, it applies to a new type of weapon.",
                  summary: "Gain a +2 bonus on damage rolls with your chosen weapon."),

            .make("Whirlwind Attack",
                  featType: "Combat",
                  prerequisites: "Dex 13, Int 13, Combat Expertise, Dodge, Mobility, Spring Attack, base attack bonus +4",
                  benefit: "When you use the full-attack action, you can give up your regular attacks and instead make one melee attack at your highest base attack bonus against each opponent within reach.",
                  summary: "Attack every enemy within reach once as a full-attack action."),

            // MARK: - Metamagic Feats

            .make("Dazing Spell",
                  featType: "Metamagic",
                  prerequisites: "",
                  benefit: "You can modify a spell to daze a creature damaged by the spell. A dazing spell causes a creature to become dazed for a number of rounds equal to the original level of the spell. A successful Fortitude save negates the daze effect. Spells that do not inflict damage do not benefit from this feat. Increasing the spell's level by +3.",
                  summary: "Modify a damaging spell to also daze targets for rounds equal to the spell's base level."),

            .make("Disruptive Spell",
                  featType: "Metamagic",
                  prerequisites: "",
                  benefit: "You can modify a spell to disrupt creatures' ability to cast spells. Creatures that are dealt damage by a disruptive spell must make a concentration check (DC 10 + twice the disruptive spell's level + spellcasting ability modifier) to cast any spell until the end of their next turn. Increasing the spell's level by +1.",
                  summary: "Modify a spell so damage forces concentration checks for spellcasting."),

            .make("Ectoplasmic Spell",
                  featType: "Metamagic",
                  prerequisites: "",
                  benefit: "You can modify a spell to allow it to affect incorporeal and ethereal creatures normally. An ectoplasmic spell uses up a spell slot one level higher than the spell's actual level.",
                  summary: "Allow your spells to affect incorporeal and ethereal creatures normally."),

            .make("Empower Spell",
                  featType: "Metamagic",
                  prerequisites: "",
                  benefit: "All variable, numeric effects of an empowered spell are increased by half, including bonuses to those rolls. An empowered spell uses up a spell slot two levels higher than the spell's actual level. Saving throws and opposed rolls are not affected.",
                  summary: "Increase all variable numeric spell effects by 50%."),

            .make("Enlarge Spell",
                  featType: "Metamagic",
                  prerequisites: "",
                  benefit: "An enlarged spell has its range doubled. Spells whose ranges are not defined by distance do not benefit from this feat. An enlarged spell uses up a spell slot one level higher than the spell's actual level.",
                  summary: "Double a spell's range at the cost of one spell level."),

            .make("Extend Spell",
                  featType: "Metamagic",
                  prerequisites: "",
                  benefit: "An extended spell lasts twice as long as normal. A spell with a duration of concentration, instantaneous, or permanent is not affected by this feat. An extended spell uses up a spell slot one level higher than the spell's actual level.",
                  summary: "Double a spell's duration at the cost of one spell level."),

            .make("Intensified Spell",
                  featType: "Metamagic",
                  prerequisites: "",
                  benefit: "An intensified spell increases the maximum number of damage dice by 5 levels. You must be able to cast the spell at its original level to use this feat. An intensified spell uses up a spell slot one level higher than the spell's actual level.",
                  summary: "Increase a damage spell's maximum dice cap by 5 caster levels."),

            .make("Lingering Spell",
                  featType: "Metamagic",
                  prerequisites: "",
                  benefit: "The area of an instantaneous spell persists for 1 additional round after it is cast. Creatures that are within the affected area when the spell is cast, as well as those who enter the area on the following round, are subject to the spell's effects. A lingering spell uses up a spell slot one level higher than the spell's actual level.",
                  summary: "Instantaneous area spells persist for one additional round."),

            .make("Maximize Spell",
                  featType: "Metamagic",
                  prerequisites: "",
                  benefit: "All variable, numeric effects of a spell modified by this feat are maximized. Saving throws and opposed rolls are not affected. A maximized spell uses up a spell slot three levels higher than the spell's actual level.",
                  summary: "Maximize all variable numeric effects of a spell."),

            .make("Merciful Spell",
                  featType: "Metamagic",
                  prerequisites: "",
                  benefit: "The spell deals nonlethal damage instead of lethal damage. If the spell inflicts effects in addition to damage, those effects are unaffected. A merciful spell uses up a spell slot of the same level as the actual spell.",
                  summary: "Modify a spell to deal nonlethal damage instead of lethal damage."),

            .make("Persistent Spell",
                  featType: "Metamagic",
                  prerequisites: "",
                  benefit: "Whenever a creature affected by a persistent spell succeeds on its saving throw against the spell, it must make the save again 1 round later at the same DC. It only has to succeed on this second save to shake off the effects of the spell. A persistent spell uses up a spell slot two levels higher than the spell's actual level.",
                  summary: "Force targets who succeed on saves to make a second save one round later."),

            .make("Quicken Spell",
                  featType: "Metamagic",
                  prerequisites: "",
                  benefit: "Casting a quickened spell is a swift action. You can perform another action, even casting another spell, in the same round as you cast a quickened spell. A spell whose casting time is more than 1 round or 1 full-round action cannot be quickened. A quickened spell uses up a spell slot four levels higher than the spell's actual level.",
                  summary: "Cast a spell as a swift action, allowing another action in the same round."),

            .make("Reach Spell",
                  featType: "Metamagic",
                  prerequisites: "",
                  benefit: "You can alter a spell with a range of touch, close, or medium to increase its range to the next range category. A reach spell uses up a spell slot one level higher than the spell's actual level for each step of the range you increase.",
                  summary: "Increase a spell's range category by one step per spell level increase."),

            .make("Selective Spell",
                  featType: "Metamagic",
                  prerequisites: "Spellcraft 10 ranks",
                  benefit: "When casting a selective spell with an area effect and a duration of instantaneous, you can choose a number of targets in the area up to your casting ability modifier. These targets are excluded from the effects of your spell. A selective spell uses up a spell slot one level higher than the spell's actual level.",
                  summary: "Exclude a number of targets from an instantaneous area spell."),

            .make("Silent Spell",
                  featType: "Metamagic",
                  prerequisites: "",
                  benefit: "A silent spell can be cast without verbal components. A silent spell uses up a spell slot one level higher than the spell's actual level. Spells without verbal components are not affected.",
                  summary: "Cast a spell without its verbal components."),

            .make("Sorcerous Strike",
                  featType: "Metamagic",
                  prerequisites: "Sorcerer 1",
                  benefit: "When you cast a spell and make a successful melee touch attack as part of the spell, you can spend a swift action to channel a small portion of the spell's power into the attack. The strike deals 1d6 additional points of damage for every spell level of the spell.",
                  summary: "Channel spell energy into a touch spell attack for bonus damage."),

            .make("Spell Penetration",
                  featType: "General",
                  prerequisites: "",
                  benefit: "You get a +2 bonus on caster level checks made to overcome a creature's spell resistance.",
                  summary: "Gain +2 on caster level checks to overcome spell resistance."),

            .make("Still Spell",
                  featType: "Metamagic",
                  prerequisites: "",
                  benefit: "A stilled spell can be cast without somatic components. A stilled spell uses up a spell slot one level higher than the spell's actual level. Spells without somatic components are not affected.",
                  summary: "Cast a spell without its somatic components."),

            .make("Thanatopic Spell",
                  featType: "Metamagic",
                  prerequisites: "Spell Focus (necromancy), Knowledge (religion) 6 ranks",
                  benefit: "A thanatopic spell pierces defenses and immunities to death effects, negative levels, and energy drain, affecting even undead and constructs with such effects. A thanatopic spell uses up a spell slot two levels higher than the spell's actual level.",
                  summary: "Allow necromantic spells to bypass immunity to death effects and negative levels."),

            .make("Threnodic Spell",
                  featType: "Metamagic",
                  prerequisites: "Spell Focus (necromancy), Knowledge (religion) 6 ranks",
                  benefit: "A threnodic spell uses negative energy to substitute for the spell's normal component of life-draining power. It affects undead creatures as though they were alive, ignoring their immunity to mind-affecting effects. A threnodic spell uses up a spell slot two levels higher than the spell's actual level.",
                  summary: "Allow mind-affecting spells to affect undead as if they were living creatures."),

            .make("Thundering Spell",
                  featType: "Metamagic",
                  prerequisites: "",
                  benefit: "You can modify a spell to cause those damaged by the spell to become deafened. A successful Fortitude save negates the deafening effect. Spells that do not inflict damage do not benefit from this feat. A thundering spell uses up a spell slot one level higher than the spell's actual level.",
                  summary: "Modify a damaging spell to also deafen its targets."),

            .make("Toppling Spell",
                  featType: "Metamagic",
                  prerequisites: "",
                  benefit: "The impact of your force spell is strong enough to knock the target prone. If the target takes damage, fails its saving throw, or is moved by your force spell, make a trip combat maneuver check against the target, using your caster level plus your spellcasting ability modifier as your CMB. A toppling spell only affects spells with the force descriptor. A toppling spell uses up a spell slot one level higher than the spell's actual level.",
                  summary: "Force spells attempt to trip targets as a free effect."),

            .make("Widen Spell",
                  featType: "Metamagic",
                  prerequisites: "",
                  benefit: "You can alter a burst, emanation, line, or spread-shaped spell to increase its area. Any numeric measurements of the spell's area increase by 100%. A widened spell uses up a spell slot three levels higher than the spell's actual level.",
                  summary: "Double the area of a burst, emanation, line, or spread spell."),

            // MARK: - Item Creation Feats

            .make("Brew Potion",
                  featType: "Item Creation",
                  prerequisites: "Caster level 3rd",
                  benefit: "You can create a potion of any 3rd-level or lower spell that you know and that targets one or more creatures or objects. Brewing a potion takes 2 hours if its base price is 250 gp or less, otherwise brewing a potion takes 1 day for each 1,000 gp in its base price. When you create a potion, you set the caster level, which must be sufficient to cast the spell in question and no higher than your own level.",
                  summary: "Craft potions of spells up to 3rd level that target creatures or objects."),

            .make("Craft Magic Arms and Armor",
                  featType: "Item Creation",
                  prerequisites: "Caster level 5th",
                  benefit: "You can create magic weapons, armor, or shields. Enhancing a weapon, suit of armor, or shield takes 1 day for each 1,000 gp in the price of its magical features. To enhance a weapon, you must use up raw materials costing half of this total price.",
                  summary: "Craft magic weapons, armor, and shields."),

            .make("Craft Rod",
                  featType: "Item Creation",
                  prerequisites: "Caster level 9th",
                  benefit: "You can create magic rods. Crafting a rod takes 1 day for each 1,000 gp in its base price. To craft a rod, you must use up raw materials costing half of its base price.",
                  summary: "Craft magical rods."),

            .make("Craft Staff",
                  featType: "Item Creation",
                  prerequisites: "Caster level 11th",
                  benefit: "You can create a magic staff. Crafting a staff takes 1 day for each 1,000 gp in its base price. To craft a staff, you must use up raw materials costing half of its base price. A newly created staff has 10 charges.",
                  summary: "Craft magical staves with 10 charges."),

            .make("Craft Wand",
                  featType: "Item Creation",
                  prerequisites: "Caster level 5th",
                  benefit: "You can create a wand of any 4th-level or lower spell that you know. Crafting a wand takes 1 day for each 1,000 gp in its base price. To craft a wand, you must use up raw materials costing half of its base price. A newly created wand has 50 charges.",
                  summary: "Craft wands of spells up to 4th level with 50 charges."),

            .make("Craft Wondrous Item",
                  featType: "Item Creation",
                  prerequisites: "Caster level 3rd",
                  benefit: "You can create a wide variety of magic wondrous items. Crafting a wondrous item takes 1 day for each 1,000 gp in its price. To create a wondrous item, you must use up raw materials costing half of its base price.",
                  summary: "Craft wondrous magical items of virtually any type."),

            .make("Forge Ring",
                  featType: "Item Creation",
                  prerequisites: "Caster level 7th",
                  benefit: "You can create magic rings. Crafting a ring takes 1 day for each 1,000 gp in its base price. To forge a ring, you must use up raw materials costing half of its base price.",
                  summary: "Craft magical rings."),

            .make("Inscribe Rune",
                  featType: "Item Creation",
                  prerequisites: "Master craftsman or caster level 3rd",
                  benefit: "You can create magic runes that duplicate any divine spell effect with a duration longer than instantaneous. You must know the spell to be inscribed, or make a Spellcraft check equal to DC 20 + the spell's level. Inscribing a rune takes 1 day for each 1,000 gp in its price.",
                  summary: "Inscribe magical runes that duplicate divine spell effects."),

            .make("Scribe Scroll",
                  featType: "Item Creation",
                  prerequisites: "Caster level 1st",
                  benefit: "You can create a scroll of any spell that you know. Scribing a scroll takes 2 hours if its base price is 250 gp or less, otherwise scribing a scroll takes 1 day for each 1,000 gp in its base price. To scribe a scroll, you must use up raw materials costing half of its base price.",
                  summary: "Scribe scrolls of any spell you know."),

            // MARK: - General Feats

            .make("Acrobatic",
                  featType: "General",
                  prerequisites: "",
                  benefit: "You get a +2 bonus on all Acrobatics and Fly skill checks. If you have 10 or more ranks in one of these skills, the bonus increases to +4 for that skill.",
                  summary: "Gain bonuses to Acrobatics and Fly skill checks."),

            .make("Acrobatic Steps",
                  featType: "General",
                  prerequisites: "Dex 15, Nimble Moves",
                  benefit: "You can move through up to 10 feet of difficult terrain each round as if it were normal terrain.",
                  summary: "Move through 10 feet of difficult terrain as normal terrain each round."),

            .make("Alertness",
                  featType: "General",
                  prerequisites: "",
                  benefit: "You get a +2 bonus on all Perception and Sense Motive skill checks. If you have 10 or more ranks in one of these skills, the bonus increases to +4 for that skill.",
                  summary: "Gain bonuses to Perception and Sense Motive skill checks."),

            .make("Animal Affinity",
                  featType: "General",
                  prerequisites: "",
                  benefit: "You get a +2 bonus on all Handle Animal and Ride skill checks. If you have 10 or more ranks in one of these skills, the bonus increases to +4 for that skill.",
                  summary: "Gain bonuses to Handle Animal and Ride skill checks."),

            .make("Arcane Armor Mastery",
                  featType: "General",
                  prerequisites: "Arcane Armor Training, Medium Armor Proficiency, caster level 7th",
                  benefit: "As a swift action, reduce the arcane spell failure chance due to the armor you are wearing by 20% for any spells you cast this round.",
                  summary: "Reduce arcane spell failure from armor by 20% as a swift action."),

            .make("Arcane Armor Training",
                  featType: "General",
                  prerequisites: "Light Armor Proficiency, caster level 3rd",
                  benefit: "As a swift action, reduce the arcane spell failure chance due to the armor you are wearing by 10% for any spells you cast this round.",
                  summary: "Reduce arcane spell failure from armor by 10% as a swift action."),

            .make("Arcane Shield",
                  featType: "General",
                  prerequisites: "Arcane caster level 10th",
                  benefit: "As an immediate action, you can grant yourself a shield bonus to AC equal to the level of the spell you sacrifice. This bonus lasts until the beginning of your next turn.",
                  summary: "Sacrifice a spell as an immediate action to gain a shield bonus to AC."),

            .make("Arcane Strike",
                  featType: "General",
                  prerequisites: "Ability to cast arcane spells",
                  benefit: "As a swift action, you can imbue your weapons with a fraction of your power. For 1 round, your weapons deal +1 damage and are treated as magic for overcoming damage reduction. For every 5 caster levels you possess, this bonus increases by +1.",
                  summary: "Imbue your weapons with arcane energy as a swift action for bonus damage."),

            .make("Athletic",
                  featType: "General",
                  prerequisites: "",
                  benefit: "You get a +2 bonus on all Climb and Swim skill checks. If you have 10 or more ranks in one of these skills, the bonus increases to +4 for that skill.",
                  summary: "Gain bonuses to Climb and Swim skill checks."),

            .make("Augment Summoning",
                  featType: "General",
                  prerequisites: "Spell Focus (conjuration)",
                  benefit: "Each creature you conjure with any summon spell gains a +4 enhancement bonus to Strength and Constitution for the duration of the spell that summoned it.",
                  summary: "Summoned creatures gain +4 Strength and +4 Constitution."),

            .make("Combat Casting",
                  featType: "General",
                  prerequisites: "",
                  benefit: "You get a +4 bonus on concentration checks made to cast a spell or use a spell-like ability when casting on the defensive or while grappled.",
                  summary: "Gain +4 on concentration checks when casting defensively or while grappled."),

            .make("Command Undead",
                  featType: "General",
                  prerequisites: "Channel negative energy class feature",
                  benefit: "As a standard action, you can use one of your uses of channel negative energy to enslave undead within 30 feet. Undead receive a Will save to negate the effect. The DC for this Will save is equal to 10 + 1/2 your cleric level + your Charisma modifier. Undead that fail their saves fall under your control, obeying your commands to the best of their ability.",
                  summary: "Channel negative energy to control nearby undead."),

            .make("Deceitful",
                  featType: "General",
                  prerequisites: "",
                  benefit: "You get a +2 bonus on all Bluff and Disguise skill checks. If you have 10 or more ranks in one of these skills, the bonus increases to +4 for that skill.",
                  summary: "Gain bonuses to Bluff and Disguise skill checks."),

            .make("Deft Hands",
                  featType: "General",
                  prerequisites: "",
                  benefit: "You get a +2 bonus on all Disable Device and Sleight of Hand skill checks. If you have 10 or more ranks in one of these skills, the bonus increases to +4 for that skill.",
                  summary: "Gain bonuses to Disable Device and Sleight of Hand skill checks."),

            .make("Diehard",
                  featType: "General",
                  prerequisites: "Endurance",
                  benefit: "When your hit point total is below 0, but you are not dead, you automatically stabilize. You do not need to make a Constitution check each round to avoid losing additional hit points. You may choose to act as if you were disabled, rather than dying. You must make this decision as soon as you are reduced to negative hit points.",
                  normal: "A character without this feat who is reduced to negative hit points is unconscious and dying.",
                  summary: "Automatically stabilize when dying and act while at negative hit points."),

            .make("Dodge",
                  featType: "General",
                  prerequisites: "Dex 13",
                  benefit: "You gain a +1 dodge bonus to your AC. A condition that makes you lose your Dexterity bonus to AC also makes you lose the benefits of this feat.",
                  summary: "Gain a +1 dodge bonus to Armor Class."),

            .make("Elemental Channel",
                  featType: "General",
                  prerequisites: "Channel energy class feature",
                  benefit: "Choose one type of elemental subtype (air, earth, fire, or water). When you channel energy, you can choose to channel it in the form of that element, affecting all creatures of the elemental subtype instead of the living or undead.",
                  summary: "Channel energy to affect elemental creatures of the chosen subtype."),

            .make("Endurance",
                  featType: "General",
                  prerequisites: "",
                  benefit: "You gain a +4 bonus on the following checks and saves: Swim checks made to resist nonlethal damage from exhaustion; Constitution checks made to continue running; Constitution checks made to avoid nonlethal damage from a forced march; Constitution checks made to hold your breath; Constitution checks made to avoid nonlethal damage from starvation or thirst; Fortitude saves made to avoid nonlethal damage from hot or cold environments; and Fortitude saves made to resist damage from suffocation. You may sleep in light or medium armor without becoming fatigued.",
                  summary: "Gain +4 on checks and saves to resist physical hardship and sleep in armor."),

            .make("Eschew Materials",
                  featType: "General",
                  prerequisites: "",
                  benefit: "You can cast any spell with a material component costing 1 gp or less without needing that component.",
                  summary: "Cast spells with inexpensive material components without needing them."),

            .make("Extra Channel",
                  featType: "General",
                  prerequisites: "Channel energy class feature",
                  benefit: "You can channel energy two additional times per day.",
                  special: "You can gain Extra Channel multiple times. Its effects stack.",
                  summary: "Channel energy two additional times per day."),

            .make("Extra Ki",
                  featType: "General",
                  prerequisites: "Ki pool class feature",
                  benefit: "Your ki pool increases by 2.",
                  special: "You can gain Extra Ki multiple times. Its effects stack.",
                  summary: "Increase your ki pool by 2 points."),

            .make("Extra Lay On Hands",
                  featType: "General",
                  prerequisites: "Lay on hands class feature",
                  benefit: "You can use your lay on hands ability two additional times per day.",
                  special: "You can gain Extra Lay On Hands multiple times. Its effects stack.",
                  summary: "Use lay on hands two additional times per day."),

            .make("Extra Mercy",
                  featType: "General",
                  prerequisites: "Lay on hands class feature, mercy class feature",
                  benefit: "Select one additional mercy for which you qualify. You can use that mercy when you use your lay on hands ability.",
                  special: "You can gain Extra Mercy multiple times. Each time you do, you select a new mercy.",
                  summary: "Add one additional mercy to your lay on hands ability."),

            .make("Extra Performance",
                  featType: "General",
                  prerequisites: "Bardic performance class feature",
                  benefit: "You can use bardic performance for 6 additional rounds per day.",
                  special: "You can gain Extra Performance multiple times. Its effects stack.",
                  summary: "Gain 6 additional rounds of bardic performance per day."),

            .make("Extra Rage",
                  featType: "General",
                  prerequisites: "Rage class feature",
                  benefit: "You can rage for 6 additional rounds per day.",
                  special: "You can gain Extra Rage multiple times. Its effects stack.",
                  summary: "Rage for 6 additional rounds per day."),

            .make("Fleet",
                  featType: "General",
                  prerequisites: "",
                  benefit: "While you are wearing light or no armor, your base speed increases by 5 feet. You lose the benefits of this feat if you carry a medium or heavy load.",
                  special: "You can take this feat multiple times. The effects stack.",
                  summary: "Increase your base speed by 5 feet while wearing light or no armor."),

            .make("Great Fortitude",
                  featType: "General",
                  prerequisites: "",
                  benefit: "You get a +2 bonus on all Fortitude saving throws.",
                  summary: "Gain a +2 bonus on all Fortitude saving throws."),

            .make("Greater Spell Focus",
                  featType: "General",
                  prerequisites: "Spell Focus",
                  benefit: "Add +1 to the Difficulty Class for all saving throws against spells from the school of magic you select. This bonus stacks with the bonus from Spell Focus.",
                  special: "You can gain this feat multiple times. Its effects do not stack. Each time you take the feat, it applies to a new school of magic.",
                  summary: "Add +1 to save DCs for spells of your chosen school (stacks with Spell Focus)."),

            .make("Greater Spell Penetration",
                  featType: "General",
                  prerequisites: "Spell Penetration",
                  benefit: "You get a +2 bonus on caster level checks made to overcome a creature's spell resistance. This bonus stacks with the one from Spell Penetration.",
                  summary: "Gain an additional +2 on caster level checks to overcome spell resistance."),

            .make("Improved Channel",
                  featType: "General",
                  prerequisites: "Channel energy class feature",
                  benefit: "Add 2 to the DC of saving throws made to resist the effects of your channel energy ability.",
                  summary: "Increase the save DC of your channel energy ability by 2."),

            .make("Improved Counterspell",
                  featType: "General",
                  prerequisites: "",
                  benefit: "When counterspelling, you may use a spell of the same school that is one or more spell levels higher than the target spell.",
                  normal: "Without this feat, you may only counter a spell with the exact spell or with dispel magic.",
                  summary: "Counterspell using any spell from the same school that is a higher level."),

            .make("Improved Familiar",
                  featType: "General",
                  prerequisites: "Ability to acquire a new familiar, compatible alignment, sufficiently high level",
                  benefit: "When choosing a familiar, the creatures listed in the table below are also available to you. You may choose a familiar with an alignment up to one step away from your own on each alignment axis.",
                  summary: "Gain access to more powerful or exotic creature types as familiars."),

            .make("Improved Great Fortitude",
                  featType: "General",
                  prerequisites: "Great Fortitude",
                  benefit: "Once per day, you may reroll a Fortitude saving throw. You must decide to use this ability before the results are revealed. You must take the second roll, even if it is worse.",
                  summary: "Once per day, reroll a Fortitude saving throw."),

            .make("Improved Iron Will",
                  featType: "General",
                  prerequisites: "Iron Will",
                  benefit: "Once per day, you may reroll a Will saving throw. You must decide to use this ability before the results are revealed. You must take the second roll, even if it is worse.",
                  summary: "Once per day, reroll a Will saving throw."),

            .make("Improved Lightning Reflexes",
                  featType: "General",
                  prerequisites: "Lightning Reflexes",
                  benefit: "Once per day, you may reroll a Reflex saving throw. You must decide to use this ability before the results are revealed. You must take the second roll, even if it is worse.",
                  summary: "Once per day, reroll a Reflex saving throw."),

            .make("Iron Will",
                  featType: "General",
                  prerequisites: "",
                  benefit: "You get a +2 bonus on all Will saving throws.",
                  summary: "Gain a +2 bonus on all Will saving throws."),

            .make("Leadership",
                  featType: "General",
                  prerequisites: "Character level 7th",
                  benefit: "Having this feat enables the character to attract loyal companions and devoted followers, subordinates who assist her. See the Leadership table to determine what sort of cohort and how many followers you can recruit.",
                  summary: "Attract a cohort and followers based on your Leadership score."),

            .make("Lightning Reflexes",
                  featType: "General",
                  prerequisites: "",
                  benefit: "You get a +2 bonus on all Reflex saving throws.",
                  summary: "Gain a +2 bonus on all Reflex saving throws."),

            .make("Magical Aptitude",
                  featType: "General",
                  prerequisites: "",
                  benefit: "You get a +2 bonus on all Spellcraft and Use Magic Device skill checks. If you have 10 or more ranks in one of these skills, the bonus increases to +4 for that skill.",
                  summary: "Gain bonuses to Spellcraft and Use Magic Device skill checks."),

            .make("Master Craftsman",
                  featType: "General",
                  prerequisites: "5 ranks in any Craft or Profession skill",
                  benefit: "Choose one Craft or Profession skill in which you possess at least 5 ranks. You receive a +2 bonus on your chosen Craft or Profession skill. Ranks in your chosen skill count as your caster level for the purposes of qualifying for the Craft Magic Arms and Armor and Craft Wondrous Item feats. You can create magic items using these feats, substituting your ranks in the chosen skill for your total caster level.",
                  summary: "Use Craft or Profession skill ranks as caster levels for item creation feats."),

            .make("Mobility",
                  featType: "General",
                  prerequisites: "Dex 13, Dodge",
                  benefit: "You get a +4 dodge bonus to Armor Class against attacks of opportunity caused when you move out of or within a threatened area. A condition that makes you lose your Dexterity bonus to Armor Class also makes you lose dodge bonuses. Dodge bonuses stack with each other, unlike most types of bonuses.",
                  summary: "Gain +4 AC against attacks of opportunity provoked by movement."),

            .make("Natural Spell",
                  featType: "General",
                  prerequisites: "Wis 13, wild shape class feature",
                  benefit: "You can complete the verbal and somatic components of spells while in a wild shape form. You substitute various noises and gestures for the normal verbal and somatic components of a spell.",
                  summary: "Cast spells with verbal and somatic components while using wild shape."),

            .make("Nimble Moves",
                  featType: "General",
                  prerequisites: "Dex 13",
                  benefit: "Whenever you move, you may move through up to 5 feet of difficult terrain each round as if it were normal terrain.",
                  summary: "Move through 5 feet of difficult terrain as normal terrain each round."),

            .make("Persuasive",
                  featType: "General",
                  prerequisites: "",
                  benefit: "You get a +2 bonus on all Diplomacy and Intimidate skill checks. If you have 10 or more ranks in one of these skills, the bonus increases to +4 for that skill.",
                  summary: "Gain bonuses to Diplomacy and Intimidate skill checks."),

            .make("Run",
                  featType: "General",
                  prerequisites: "",
                  benefit: "When running, you move five times your normal speed (if wearing medium, light, or no armor and carrying no more than a medium load) or four times your speed (if wearing heavy armor or carrying a heavy load). If you make a jump after a running start, you gain a +4 bonus on your Acrobatics check. While running, you retain your Dexterity bonus to your Armor Class.",
                  normal: "You move four times your speed while running (if wearing medium, light, or no armor and carrying no more than a medium load) or three times your speed (if wearing heavy armor or carrying a heavy load).",
                  summary: "Run faster and retain your Dexterity bonus to AC while running."),

            .make("Self-Sufficient",
                  featType: "General",
                  prerequisites: "",
                  benefit: "You get a +2 bonus on all Heal and Survival skill checks. If you have 10 or more ranks in one of these skills, the bonus increases to +4 for that skill.",
                  summary: "Gain bonuses to Heal and Survival skill checks."),

            .make("Selective Channeling",
                  featType: "General",
                  prerequisites: "Cha 13, channel energy class feature",
                  benefit: "When you channel energy, you can choose a number of targets in the area up to your Charisma modifier. These targets are not affected by your channeled energy.",
                  summary: "Exclude a number of creatures from the effects of your channeled energy."),

            .make("Shield Proficiency",
                  featType: "General",
                  prerequisites: "",
                  benefit: "When you use a shield, the shield's armor check penalty only applies to Strength– and Dexterity-based skills.",
                  normal: "When you are using a shield with which you are not proficient, you take the shield's armor check penalty on attack rolls and on all skill checks that involve moving.",
                  summary: "Use shields without attack roll penalties from nonproficiency."),

            .make("Skill Focus",
                  featType: "General",
                  prerequisites: "",
                  benefit: "You get a +3 bonus on all checks involving the chosen skill. If you have 10 or more ranks in that skill, this bonus increases to +6.",
                  special: "You can gain this feat multiple times. Its effects do not stack. Each time you take the feat, it applies to a new skill.",
                  summary: "Gain +3 (or +6 with 10+ ranks) on checks with your chosen skill."),

            .make("Sociable",
                  featType: "General",
                  prerequisites: "Cha 13",
                  benefit: "When you attempt a Diplomacy check to improve a creature's attitude, you can also assist an adjacent ally as a free action, granting them a +2 bonus on Diplomacy checks for 1 hour.",
                  summary: "Grant an ally a +2 Diplomacy bonus while making your own Diplomacy checks."),

            .make("Spell Focus",
                  featType: "General",
                  prerequisites: "",
                  benefit: "Add +1 to the Difficulty Class for all saving throws against spells from the school of magic you select.",
                  special: "You can gain this feat multiple times. Its effects do not stack. Each time you take the feat, it applies to a new school of magic.",
                  summary: "Add +1 to save DCs for all spells of your chosen school."),

            .make("Spell Mastery",
                  featType: "General",
                  prerequisites: "1st-level wizard",
                  benefit: "Each time you take this feat, choose a number of spells that you already know equal to your Intelligence modifier. From that point on, you can prepare these spells without referring to a spellbook.",
                  summary: "Prepare a select group of spells from memory without a spellbook."),

            .make("Spring Attack",
                  featType: "General",
                  prerequisites: "Dex 13, Dodge, Mobility, base attack bonus +4",
                  benefit: "As a full-round action, you can move up to your speed and make a single melee attack without provoking any attacks of opportunity from the target of your attack. You can move both before and after the attack, but you must move at least 5 feet before the attack and the total distance that you move cannot be greater than your speed.",
                  summary: "Move and make a melee attack without provoking an attack of opportunity from your target."),

            .make("Stealthy",
                  featType: "General",
                  prerequisites: "",
                  benefit: "You get a +2 bonus on all Escape Artist and Stealth skill checks. If you have 10 or more ranks in one of these skills, the bonus increases to +4 for that skill.",
                  summary: "Gain bonuses to Escape Artist and Stealth skill checks."),

            .make("Toughness",
                  featType: "General",
                  prerequisites: "",
                  benefit: "You gain +3 hit points. For every Hit Die you possess beyond 3, you gain an additional +1 hit point. If you have more than 3 Hit Dice, you gain +1 hit points whenever you gain a Hit Die (such as when you gain a level).",
                  summary: "Gain +3 hit points, plus +1 per Hit Die beyond 3."),

            .make("Turn Undead",
                  featType: "General",
                  prerequisites: "Channel positive energy class feature",
                  benefit: "You can, as a standard action, use one of your uses of channel positive energy to cause all undead in 30 feet of you to flee, as if panicked. Undead receive a Will save to negate the effect. The DC for this Will save is equal to 10 + 1/2 your cleric level + your Charisma modifier. Undead that fail their saves are turned and must flee from you.",
                  summary: "Channel positive energy to cause undead to flee in panic."),

            .make("Wind Stance",
                  featType: "General",
                  prerequisites: "Dex 15, Dodge, base attack bonus +6",
                  benefit: "If you move more than 5 feet this turn, you gain 20% concealment against ranged attacks until the start of your next turn.",
                  summary: "Gain 20% concealment against ranged attacks whenever you move more than 5 feet."),
        ]

        for feat in feats {
            try await db.insertFeat(feat)
        }
    }
}
