import Foundation

extension SeedDataBuilder {
    func seedMonsters() async throws {
        let monsters: [MonsterEntry] = [

            // MARK: - Animals

            .make("Cat", level: -2,
                  creatureType: "Animal", size: "Tiny",
                  traits: "Animal",
                  hp: "6", ac: 15, fort: 4, ref: 7, will: 3,
                  speed: "20 feet",
                  attacks: "Claws +7 (1d4-4 slashing; Agile, Finesse)",
                  specialAbilities: "Low-Light Vision; Scent (imprecise, 30 feet)",
                  summary: "A small agile feline.",
                  desc: "Cats are small, stealthy predators that have been domesticated by humanoid civilizations for thousands of years. They are prized as companions and pest controllers, using their sharp claws and keen senses to hunt rodents and other small prey. Despite their small size, cats are surprisingly effective hunters with excellent night vision.",
                  source: "Monster Core", isPremium: true),

            .make("Rat", level: -2,
                  creatureType: "Animal", size: "Tiny",
                  traits: "Animal",
                  hp: "6", ac: 15, fort: 3, ref: 7, will: 1,
                  speed: "20 feet",
                  attacks: "Jaws +7 (1d4-4 piercing; Agile, Finesse)",
                  specialAbilities: "Low-Light Vision; Scent (imprecise, 30 feet); Filth Fever (DC 14 Fortitude)",
                  summary: "A common vermin found in sewers and alleyways.",
                  desc: "Rats are ubiquitous rodents that thrive in urban environments, feeding on refuse and stored food. They are notorious carriers of disease, spreading filth fever and other illnesses through their bites. Swarms of rats can overwhelm even seasoned adventurers through sheer numbers.",
                  source: "Monster Core", isPremium: true),

            .make("Dog", level: -1,
                  creatureType: "Animal", size: "Small",
                  traits: "Animal",
                  hp: "8", ac: 15, fort: 5, ref: 7, will: 3,
                  speed: "30 feet",
                  attacks: "Jaws +7 (1d4+1 piercing)",
                  specialAbilities: "Low-Light Vision; Scent (imprecise, 30 feet)",
                  summary: "A loyal domesticated canine companion.",
                  desc: "Dogs are loyal companions that have served alongside humanoids for millennia as guards, hunters, and faithful friends. They come in a wide variety of breeds, from small lap dogs to large working animals. Their keen sense of smell and pack instincts make them reliable allies in the wild.",
                  source: "Monster Core", isPremium: true),

            .make("Goblin Dog", level: 1,
                  creatureType: "Animal", size: "Medium",
                  traits: "Animal",
                  hp: "16", ac: 14, fort: 7, ref: 6, will: 4,
                  speed: "35 feet",
                  attacks: "Jaws +9 (1d6+3 piercing plus goblin pox)",
                  specialAbilities: "Low-Light Vision; Scent (imprecise, 30 feet); Goblin Pox (DC 17 Fortitude); Allergic Reaction",
                  summary: "A mangy, ill-tempered beast favored as a mount by goblins.",
                  desc: "Goblin dogs are wiry, rat-like canines with coarse fur and a foul disposition. Despite their name, they are not actually dogs at all but rather a distinct species of vermin-like beast that goblins have domesticated as mounts and war animals. Their bites carry goblin pox, a painful and debilitating disease.",
                  source: "Monster Core", isPremium: true),

            .make("Horse", level: 2,
                  creatureType: "Animal", size: "Large",
                  traits: "Animal",
                  hp: "32", ac: 17, fort: 9, ref: 7, will: 5,
                  speed: "40 feet",
                  attacks: "Hoof +9 (1d6+4 bludgeoning)",
                  specialAbilities: "Low-Light Vision; Scent (imprecise, 30 feet); Gallop",
                  summary: "A large domesticated animal used for riding and labor.",
                  desc: "Horses are powerful herbivores that have been domesticated for riding, hauling, and warfare across Golarion. A well-trained horse is an invaluable companion for overland travel. Warhorses are specially bred and trained to remain calm in battle and can be formidable combatants in their own right.",
                  source: "Monster Core", isPremium: true),

            .make("Boar", level: 2,
                  creatureType: "Animal", size: "Medium",
                  traits: "Animal",
                  hp: "30", ac: 18, fort: 9, ref: 7, will: 5,
                  speed: "30 feet",
                  attacks: "Tusk +10 (1d8+4 piercing)",
                  specialAbilities: "Low-Light Vision; Scent (imprecise, 30 feet); Ferocity; Boar Charge",
                  summary: "A stocky wild pig with sharp tusks and a fierce temper.",
                  desc: "Boars are aggressive, stocky wild pigs found in forests and hills across Golarion. They are notoriously ill-tempered and will charge at perceived threats with their razor-sharp tusks. A wounded boar is especially dangerous, as its ferocity allows it to keep fighting even after sustaining grievous injuries.",
                  source: "Monster Core", isPremium: true),

            .make("Bear", level: 3,
                  creatureType: "Animal", size: "Large",
                  traits: "Animal",
                  hp: "45", ac: 18, fort: 10, ref: 7, will: 7,
                  speed: "30 feet",
                  attacks: "Jaws +12 (1d10+5 piercing), Claw +12 (1d8+5 slashing; Agile)",
                  specialAbilities: "Low-Light Vision; Scent (imprecise, 30 feet); Mauler; Grab",
                  summary: "A powerful omnivorous predator found in forests and mountains.",
                  desc: "Bears are large, powerful omnivores that roam forests, mountains, and tundra throughout the world. While generally not aggressive unless provoked or protecting their cubs, a bear in combat is a terrifying opponent. They can pin prey with their massive paws and deliver devastating bites with their powerful jaws.",
                  source: "Monster Core", isPremium: true),

            .make("Crocodile", level: 2,
                  creatureType: "Animal", size: "Large",
                  traits: "Animal",
                  hp: "30", ac: 18, fort: 10, ref: 6, will: 5,
                  speed: "20 feet, swim 25 feet",
                  attacks: "Jaws +11 (1d10+4 piercing; Grab), Tail +9 (1d6+4 bludgeoning)",
                  specialAbilities: "Low-Light Vision; Aquatic Ambush; Death Roll; Deep Breath",
                  summary: "A large reptilian ambush predator lurking in swamps and rivers.",
                  desc: "Crocodiles are patient ambush predators that lurk just beneath the surface of rivers, swamps, and marshes. They strike with explosive speed, clamping down on prey with their powerful jaws before dragging victims underwater. Their deadly death roll can dismember even large creatures caught in their grip.",
                  source: "Monster Core", isPremium: true),

            .make("Hyena", level: 1,
                  creatureType: "Animal", size: "Medium",
                  traits: "Animal",
                  hp: "20", ac: 16, fort: 7, ref: 7, will: 4,
                  speed: "35 feet",
                  attacks: "Jaws +9 (1d8+3 piercing; Knockdown)",
                  specialAbilities: "Low-Light Vision; Scent (imprecise, 30 feet); Pack Attack",
                  summary: "A cunning pack hunter of the savannas and deserts.",
                  desc: "Hyenas are tenacious pack hunters found across savannas, deserts, and scrublands. They are social predators that coordinate their attacks to bring down prey much larger than themselves. Their powerful jaws can crush bone, and their eerie laughing calls carry for miles across the open plains.",
                  source: "Monster Core", isPremium: true),

            .make("Lion", level: 3,
                  creatureType: "Animal", size: "Large",
                  traits: "Animal",
                  hp: "45", ac: 19, fort: 10, ref: 9, will: 6,
                  speed: "30 feet",
                  attacks: "Jaws +12 (1d10+5 piercing; Grab), Claw +12 (1d8+5 slashing; Agile)",
                  specialAbilities: "Low-Light Vision; Scent (imprecise, 30 feet); Pounce; Sneak Attack 1d6; Pack Attack",
                  summary: "A majestic apex predator that hunts in coordinated prides.",
                  desc: "Lions are the undisputed rulers of the savanna, hunting in organized prides to take down large prey. A lion's powerful pounce can knock enemies to the ground, and they coordinate with their pride-mates to flank and overwhelm foes. Male lions sport impressive manes that make them appear even larger and more intimidating.",
                  source: "Monster Core", isPremium: true),

            .make("Wolf", level: 1,
                  creatureType: "Animal", size: "Medium",
                  traits: "Animal",
                  hp: "20", ac: 15, fort: 7, ref: 7, will: 4,
                  speed: "35 feet",
                  attacks: "Jaws +9 (1d6+3 piercing; Knockdown)",
                  specialAbilities: "Low-Light Vision; Scent (imprecise, 30 feet); Pack Attack",
                  summary: "A cunning pack predator that hunts cooperatively with its packmates.",
                  desc: "Wolves are intelligent pack hunters found in forests, plains, and mountains throughout the world. They communicate through howls and body language, coordinating hunts with remarkable efficiency. A lone wolf is a minor threat, but a coordinated pack can bring down prey many times their individual size.",
                  source: "Monster Core", isPremium: true),

            .make("Dire Wolf", level: 3,
                  creatureType: "Animal", size: "Large",
                  traits: "Animal",
                  hp: "46", ac: 19, fort: 10, ref: 9, will: 6,
                  speed: "35 feet",
                  attacks: "Jaws +12 (1d8+5 piercing; Knockdown, Grab)",
                  specialAbilities: "Low-Light Vision; Scent (imprecise, 30 feet); Pack Attack; Worry",
                  summary: "A massive, prehistoric wolf far larger and more ferocious than its common kin.",
                  desc: "Dire wolves are enormous prehistoric predators that dwarf their common cousins. Standing nearly as tall as a horse at the shoulder, these fearsome beasts hunt in packs and can bring down even the largest prey. Their powerful jaws can lock onto victims and shake them violently, inflicting terrible wounds.",
                  source: "Monster Core", isPremium: true),

            .make("Giant Spider", level: 1,
                  creatureType: "Animal", size: "Medium",
                  traits: "Animal",
                  hp: "17", ac: 14, fort: 6, ref: 8, will: 4,
                  speed: "25 feet, climb 25 feet",
                  attacks: "Fangs +9 (1d6+2 piercing plus giant spider venom)",
                  specialAbilities: "Darkvision; Web Sense; Giant Spider Venom (DC 16 Fortitude); Web Trap",
                  summary: "A dog-sized arachnid that spins webs to trap its prey.",
                  desc: "Giant spiders are dog-sized arachnids that lurk in dark caves, forests, and ruins, spinning elaborate webs to ensnare unwary prey. Their venomous bite can paralyze victims, leaving them helpless while the spider wraps them in silk for later consumption. Many adventurers have met their end tangled in a giant spider's web.",
                  source: "Monster Core", isPremium: true),

            .make("Giant Centipede", level: 1,
                  creatureType: "Animal", size: "Small",
                  traits: "Animal",
                  hp: "16", ac: 16, fort: 8, ref: 6, will: 3,
                  speed: "25 feet, climb 25 feet",
                  attacks: "Mandibles +9 (1d6+1 piercing plus giant centipede venom)",
                  specialAbilities: "Darkvision; Giant Centipede Venom (DC 17 Fortitude)",
                  summary: "A venomous many-legged arthropod that lurks in dark places.",
                  desc: "Giant centipedes are aggressive predators that dwell in caves, ruins, and other dark, damp environments. They strike quickly with venomous mandibles, injecting a debilitating toxin that weakens and sickens their prey. Their segmented bodies allow them to squeeze through surprisingly narrow spaces in pursuit of a meal.",
                  source: "Monster Core", isPremium: true),

            .make("Giant Bat", level: 1,
                  creatureType: "Animal", size: "Medium",
                  traits: "Animal",
                  hp: "16", ac: 15, fort: 7, ref: 7, will: 5,
                  speed: "15 feet, fly 30 feet",
                  attacks: "Fangs +9 (1d6+3 piercing)",
                  specialAbilities: "Echolocation (precise, 40 feet); Low-Light Vision",
                  summary: "A large bat capable of carrying off small prey in its claws.",
                  desc: "Giant bats are nocturnal predators found in caves, ruins, and dense forests. They navigate using echolocation, making them deadly hunters even in total darkness. While they typically feed on insects and small animals, a hungry giant bat will not hesitate to attack humanoid-sized prey.",
                  source: "Monster Core", isPremium: true),

            .make("Giant Crab", level: 2,
                  creatureType: "Animal", size: "Medium",
                  traits: "Animal, Aquatic",
                  hp: "30", ac: 19, fort: 9, ref: 6, will: 5,
                  speed: "25 feet, swim 15 feet",
                  attacks: "Claw +10 (1d8+4 bludgeoning; Grab)",
                  specialAbilities: "Darkvision; Water Breathing; Constrict 1d6+3 bludgeoning",
                  summary: "A heavily armored crustacean with powerful crushing claws.",
                  desc: "Giant crabs are aggressive crustaceans found along coastlines, in tidal caves, and on the ocean floor. Their thick carapaces provide excellent natural armor, and their powerful claws can crush bone and metal alike. They are territorial creatures that attack anything that enters their domain.",
                  source: "Monster Core", isPremium: true),

            .make("Giant Wasp", level: 2,
                  creatureType: "Animal", size: "Medium",
                  traits: "Animal",
                  hp: "25", ac: 17, fort: 7, ref: 8, will: 5,
                  speed: "15 feet, fly 40 feet",
                  attacks: "Stinger +10 (1d8+2 piercing plus giant wasp venom)",
                  specialAbilities: "Darkvision; Giant Wasp Venom (DC 18 Fortitude); Implant Eggs",
                  summary: "An oversized wasp with a painful venomous sting.",
                  desc: "Giant wasps are aggressive, territorial insects that build massive papery nests in sheltered locations. Their venomous stingers deliver an agonizing toxin that can incapacitate even hardy adventurers. Some giant wasps implant their eggs in paralyzed victims, a horrifying fate that few survive.",
                  source: "Monster Core", isPremium: true),

            .make("Giant Scorpion", level: 3,
                  creatureType: "Animal", size: "Large",
                  traits: "Animal",
                  hp: "40", ac: 18, fort: 10, ref: 8, will: 6,
                  speed: "30 feet",
                  attacks: "Pincer +12 (1d8+5 bludgeoning; Grab), Stinger +12 (1d6+5 piercing plus giant scorpion venom)",
                  specialAbilities: "Darkvision; Tremorsense (imprecise, 60 feet); Giant Scorpion Venom (DC 18 Fortitude); Constrict 1d6+4 bludgeoning",
                  summary: "A massive arachnid armed with crushing pincers and a venomous tail.",
                  desc: "Giant scorpions are fearsome predators that inhabit deserts, badlands, and underground caverns. They detect prey through vibrations in the ground and strike with blinding speed. Their pincers can crush armor while their barbed tail delivers a potent venom that causes wracking pain and muscle spasms.",
                  source: "Monster Core", isPremium: true),

            .make("Shark", level: 2,
                  creatureType: "Animal", size: "Large",
                  traits: "Animal, Aquatic",
                  hp: "30", ac: 16, fort: 9, ref: 8, will: 4,
                  speed: "swim 40 feet",
                  attacks: "Jaws +11 (1d10+4 piercing)",
                  specialAbilities: "Scent (imprecise, 100 feet); Blood Scent; Aquatic",
                  summary: "A relentless ocean predator drawn to the scent of blood.",
                  desc: "Sharks are apex predators of the sea, patrolling coastal and open waters in search of prey. They can detect blood in the water from great distances and enter a feeding frenzy when wounded prey is nearby. Their rows of serrated teeth can tear through flesh and bone with ease.",
                  source: "Monster Core", isPremium: true),

            .make("Constrictor Snake", level: 1,
                  creatureType: "Animal", size: "Large",
                  traits: "Animal",
                  hp: "20", ac: 15, fort: 7, ref: 7, will: 4,
                  speed: "20 feet, climb 20 feet, swim 20 feet",
                  attacks: "Jaws +9 (1d8+3 piercing; Grab)",
                  specialAbilities: "Low-Light Vision; Scent (imprecise, 30 feet); Constrict 1d6+3 bludgeoning; Wrap in Coils",
                  summary: "A large snake that crushes prey in its powerful coils.",
                  desc: "Constrictor snakes are large, non-venomous serpents that kill their prey by wrapping around them and squeezing with tremendous force. Found in tropical forests and swamps, they are ambush predators that drop from trees or strike from concealment. Once a constrictor has its coils around a victim, escape becomes nearly impossible.",
                  source: "Monster Core", isPremium: true),

            // MARK: - Humanoids

            .make("Kobold Scout", level: -1,
                  creatureType: "Humanoid", size: "Small",
                  traits: "Humanoid, Kobold",
                  hp: "8", ac: 16, fort: 3, ref: 6, will: 2,
                  speed: "25 feet",
                  attacks: "Crossbow +6 (1d8 piercing; Range Increment 120 feet), Shortsword +6 (1d6-1 piercing; Agile, Finesse, Versatile S)",
                  specialAbilities: "Darkvision; Sneak Attack 1d6; Hurried Retreat",
                  summary: "A stealthy kobold skirmisher that relies on traps and ambushes.",
                  desc: "Kobold scouts are the eyes and ears of their warrens, venturing forth to map tunnels, spot intruders, and set traps. They prefer ambush tactics and will flee rather than fight a fair battle. Their small size and natural stealth make them surprisingly effective at avoiding detection in underground environments.",
                  source: "Monster Core", isPremium: true),

            .make("Goblin Warrior", level: -1,
                  creatureType: "Humanoid", size: "Small",
                  traits: "Goblin, Humanoid",
                  hp: "6", ac: 16, fort: 5, ref: 5, will: 3,
                  speed: "25 feet",
                  attacks: "Dogslicer +7 (1d6 slashing; Agile, Backstabber, Finesse)",
                  specialAbilities: "Darkvision",
                  summary: "A scrappy goblin fighter armed with a crude dogslicer blade.",
                  desc: "Goblin warriors are the rank-and-file combatants of goblin tribes, armed with their signature dogslicers and a reckless disregard for personal safety. They prefer to attack in groups, swarming enemies with numbers rather than skill. Despite their chaotic nature, they can be surprisingly cunning when cornered.",
                  source: "Monster Core", isPremium: true),

            .make("Goblin Pyro", level: 1,
                  creatureType: "Humanoid", size: "Small",
                  traits: "Goblin, Humanoid",
                  hp: "15", ac: 14, fort: 5, ref: 6, will: 4,
                  speed: "25 feet",
                  attacks: "Torch +6 (1d4+1 fire), Alchemist's Fire +8 (1d8 fire plus 1 persistent fire plus 1 splash fire; Range Increment 20 feet)",
                  specialAbilities: "Darkvision; Fire Fascination; Goblin Scuttle",
                  summary: "A fire-obsessed goblin that hurls alchemical bombs at its foes.",
                  desc: "Goblin pyros are fire-obsessed arsonists who have embraced their species' well-known love of flames. They carry torches, alchemist's fire, and anything else that burns, gleefully setting ablaze everything they can. Other goblins both revere and fear pyros, knowing that their fiery enthusiasm is as dangerous to allies as it is to enemies.",
                  source: "Monster Core", isPremium: true),

            .make("Hobgoblin Soldier", level: 2,
                  creatureType: "Humanoid", size: "Medium",
                  traits: "Goblin, Hobgoblin, Humanoid",
                  hp: "30", ac: 19, fort: 8, ref: 6, will: 5,
                  speed: "25 feet",
                  attacks: "Longsword +10 (1d8+4 slashing), Shortbow +8 (1d6 piercing; Range Increment 60 feet)",
                  specialAbilities: "Darkvision; Formation; Shield Block",
                  summary: "A disciplined hobgoblin warrior trained in military formations.",
                  desc: "Hobgoblin soldiers are the backbone of hobgoblin legions, trained from youth in military discipline and tactical formations. Unlike their goblin cousins, hobgoblins are methodical and organized combatants who fight in tight ranks with shield and sword. They are at their most dangerous when fighting alongside their comrades in formation.",
                  source: "Monster Core", isPremium: true),

            .make("Hobgoblin General", level: 5,
                  creatureType: "Humanoid", size: "Medium",
                  traits: "Goblin, Hobgoblin, Humanoid",
                  hp: "68", ac: 23, fort: 12, ref: 10, will: 9,
                  speed: "25 feet",
                  attacks: "Greatsword +15 (1d12+7 slashing; Versatile P), Composite Longbow +13 (1d8+3 piercing; Deadly d10, Range Increment 100 feet, Volley 30 feet)",
                  specialAbilities: "Darkvision; General's Cry; Formation; Tactical Direction",
                  summary: "A seasoned hobgoblin commander who leads legions into battle.",
                  desc: "Hobgoblin generals are veteran military leaders who have risen through the ranks through a combination of martial prowess and tactical brilliance. They command entire legions and can rally their troops with powerful battle cries. A hobgoblin general's tactical direction makes every soldier under their command more effective in battle.",
                  source: "Monster Core", isPremium: true),

            .make("Bugbear Brute", level: 3,
                  creatureType: "Humanoid", size: "Medium",
                  traits: "Goblin, Humanoid",
                  hp: "45", ac: 18, fort: 11, ref: 8, will: 6,
                  speed: "25 feet",
                  attacks: "Bastard Sword +12 (1d8+6 slashing; Two-Hand d12)",
                  specialAbilities: "Darkvision; Scent (imprecise, 30 feet); Sneak Attack 1d6; Mauler",
                  summary: "A hulking goblinoid ambush predator that strikes from the shadows.",
                  desc: "Bugbear brutes are the largest of the goblinoid races, combining considerable strength with a terrifying talent for stealth. They prefer to ambush their prey, striking from concealment to maximize the devastating impact of their first blow. Despite their brutish appearance, bugbears are cunning hunters who patiently stalk their targets.",
                  source: "Monster Core", isPremium: true),

            .make("Orc Brute", level: 1,
                  creatureType: "Humanoid", size: "Medium",
                  traits: "Humanoid, Orc",
                  hp: "21", ac: 15, fort: 8, ref: 5, will: 3,
                  speed: "25 feet",
                  attacks: "Greataxe +9 (1d12+4 slashing; Sweep)",
                  specialAbilities: "Darkvision; Ferocity",
                  summary: "A fierce orc warrior fueled by rage and brute strength.",
                  desc: "Orc brutes are the common warriors of orc war bands, relying on raw strength and ferocity rather than tactical finesse. They charge into battle with massive greataxes, their ferocity allowing them to keep fighting even after sustaining wounds that would fell lesser creatures. Orc brutes live for the thrill of combat.",
                  source: "Monster Core", isPremium: true),

            .make("Orc Warchanter", level: 3,
                  creatureType: "Humanoid", size: "Medium",
                  traits: "Humanoid, Orc",
                  hp: "45", ac: 17, fort: 10, ref: 7, will: 8,
                  speed: "25 feet",
                  attacks: "Greatclub +10 (1d10+4 bludgeoning; Backswing, Sweep)",
                  specialAbilities: "Darkvision; Ferocity; Warchant (10-foot emanation, allies gain +1 status bonus to attack rolls)",
                  summary: "An orc battle-singer whose war chants empower allied warriors.",
                  desc: "Orc warchanters are primal spellcasters who weave magic through thunderous battle songs. Their warchants bolster the morale and fighting prowess of nearby orc warriors, turning an already dangerous war band into a truly devastating force. Warchanters are respected figures in orc society, second only to war chiefs and clan leaders.",
                  source: "Monster Core", isPremium: true),

            .make("Gnoll Hunter", level: 2,
                  creatureType: "Humanoid", size: "Medium",
                  traits: "Gnoll, Humanoid",
                  hp: "30", ac: 17, fort: 7, ref: 8, will: 6,
                  speed: "25 feet",
                  attacks: "Battle Axe +10 (1d8+4 slashing; Sweep), Shortbow +8 (1d6 piercing; Range Increment 60 feet)",
                  specialAbilities: "Darkvision; Pack Attack; Rugged Travel",
                  summary: "A hyena-headed humanoid who hunts in savage packs.",
                  desc: "Gnoll hunters are the scouts and trackers of gnoll war bands, ranging far from camp to locate prey and enemies alike. They are tireless pursuers who can lope across rough terrain with ease, running down their quarry over long distances. Like their hyena companions, gnoll hunters prefer to attack in packs, flanking and overwhelming their targets.",
                  source: "Monster Core", isPremium: true),

            .make("Gnoll Sergeant", level: 4,
                  creatureType: "Humanoid", size: "Medium",
                  traits: "Gnoll, Humanoid",
                  hp: "55", ac: 21, fort: 10, ref: 10, will: 8,
                  speed: "25 feet",
                  attacks: "Scimitar +13 (1d6+6 slashing; Forceful, Sweep), Shortbow +11 (1d6+2 piercing; Range Increment 60 feet)",
                  specialAbilities: "Darkvision; Pack Attack; Bark Orders; Rugged Travel",
                  summary: "A veteran gnoll leader who coordinates pack tactics in battle.",
                  desc: "Gnoll sergeants are experienced war leaders who direct the hunting packs in combat with barked commands and snarled threats. They are more disciplined than rank-and-file gnolls and can coordinate devastating flanking maneuvers. A gnoll sergeant's leadership transforms a disorganized mob into a lethal hunting party.",
                  source: "Monster Core", isPremium: true),

            .make("Lizardfolk Scout", level: 1,
                  creatureType: "Humanoid", size: "Medium",
                  traits: "Humanoid, Lizardfolk",
                  hp: "20", ac: 16, fort: 6, ref: 7, will: 5,
                  speed: "25 feet, swim 20 feet",
                  attacks: "Jaws +8 (1d6+3 piercing), Flint Spear +8 (1d6+3 piercing)",
                  specialAbilities: "Deep Breath; Terrain Advantage (swamp)",
                  summary: "A reptilian humanoid who patrols the swamps and waterways.",
                  desc: "Lizardfolk scouts are the sentinels of their communities, patrolling the borders of their swampy territories to watch for intruders and threats. They are expert swimmers who can hold their breath for extended periods, allowing them to set underwater ambushes. Lizardfolk scouts fight to protect their people rather than for conquest or plunder.",
                  source: "Monster Core", isPremium: true),

            .make("Troglodyte", level: 1,
                  creatureType: "Humanoid", size: "Medium",
                  traits: "Humanoid, Troglodyte",
                  hp: "25", ac: 14, fort: 8, ref: 4, will: 4,
                  speed: "25 feet",
                  attacks: "Jaws +9 (1d6+3 piercing), Club +9 (1d6+3 bludgeoning)",
                  specialAbilities: "Darkvision; Stench (aura, 30 feet, DC 17 Fortitude)",
                  summary: "A foul-smelling reptilian cave dweller with a nauseating stench.",
                  desc: "Troglodytes are primitive reptilian humanoids that dwell deep underground, emerging to raid surface settlements for food and supplies. They exude a nauseating stench that sickens most other creatures, a natural defense mechanism that makes fighting them at close quarters deeply unpleasant. Their communities are ruled by the strongest and most aggressive individuals.",
                  source: "Monster Core", isPremium: true),

            .make("Sahuagin", level: 2,
                  creatureType: "Humanoid", size: "Medium",
                  traits: "Humanoid, Sahuagin",
                  hp: "30", ac: 17, fort: 8, ref: 7, will: 5,
                  speed: "25 feet, swim 35 feet",
                  attacks: "Trident +10 (1d8+4 piercing), Claw +10 (1d6+4 slashing; Agile), Jaws +10 (1d6+4 piercing)",
                  specialAbilities: "Darkvision; Blood Scent; Shark Communion",
                  summary: "A vicious aquatic predator that raids coastal settlements.",
                  desc: "Sahuagin are malevolent aquatic humanoids that dwell in underwater cities and terrorize coastal communities. They worship sharks as sacred creatures and can communicate telepathically with these ocean predators, often coordinating attacks with shark allies. Sahuagin are driven by an insatiable hunger and a hatred of surface-dwelling civilizations.",
                  source: "Monster Core", isPremium: true),

            // MARK: - Undead

            .make("Zombie Shambler", level: 0,
                  creatureType: "Undead", size: "Medium",
                  traits: "Mindless, Undead",
                  hp: "20 (negative healing)", ac: 13, fort: 6, ref: 2, will: 3,
                  speed: "20 feet",
                  attacks: "Fist +7 (1d6+3 bludgeoning; Grab)",
                  specialAbilities: "Darkvision; Immunities: death effects, disease, mental, paralyzed, poison, unconscious; Slow; Rotting Aura",
                  summary: "A shambling undead corpse animated by dark necromantic magic.",
                  desc: "Zombie shamblers are the most common form of animated dead, created when necromantic energy suffuses a humanoid corpse. They are slow, mindless, and driven only by an insatiable hunger for living flesh. What they lack in speed and intelligence, they make up for in relentless persistence and surprising durability.",
                  source: "Monster Core", isPremium: true),

            .make("Zombie Brute", level: 2,
                  creatureType: "Undead", size: "Large",
                  traits: "Mindless, Undead",
                  hp: "40 (negative healing)", ac: 15, fort: 9, ref: 4, will: 5,
                  speed: "25 feet",
                  attacks: "Fist +12 (1d12+5 bludgeoning; Grab)",
                  specialAbilities: "Darkvision; Immunities: death effects, disease, mental, paralyzed, poison, unconscious; Slow; Rotting Aura",
                  summary: "A massive undead brute animated from a large creature's corpse.",
                  desc: "Zombie brutes are created from the corpses of large creatures such as ogres, trolls, or horses, resulting in towering undead monstrosities of tremendous strength. Their crushing blows can shatter shields and break bones with ease. Though still slow and mindless, their sheer size and power make them far more dangerous than common shamblers.",
                  source: "Monster Core", isPremium: true),

            .make("Skeleton Guard", level: 0,
                  creatureType: "Undead", size: "Medium",
                  traits: "Mindless, Undead",
                  hp: "4 (negative healing)", ac: 16, fort: 4, ref: 6, will: 3,
                  speed: "25 feet",
                  attacks: "Scimitar +7 (1d6+1 slashing; Forceful, Sweep), Shortbow +7 (1d6 piercing; Range Increment 60 feet)",
                  specialAbilities: "Darkvision; Immunities: death effects, disease, mental, paralyzed, poison, unconscious; Resistances: cold 5, electricity 5, fire 5, piercing 5, slashing 5",
                  summary: "An animated skeleton wielding weapons with eerie precision.",
                  desc: "Skeleton guards are the animated remains of humanoid warriors, raised by necromancers to serve as tireless sentinels and soldiers. Unlike zombies, skeletons retain some of their martial training, allowing them to wield weapons with surprising skill. Their bony frames are resistant to many forms of damage but vulnerable to bludgeoning strikes.",
                  source: "Monster Core", isPremium: true),

            .make("Skeleton Archer", level: 2,
                  creatureType: "Undead", size: "Medium",
                  traits: "Mindless, Undead",
                  hp: "20 (negative healing)", ac: 17, fort: 6, ref: 9, will: 5,
                  speed: "25 feet",
                  attacks: "Shortbow +10 (1d6+2 piercing; Deadly d10, Range Increment 60 feet), Shortsword +8 (1d6+2 piercing; Agile, Finesse, Versatile S)",
                  specialAbilities: "Darkvision; Immunities: death effects, disease, mental, paralyzed, poison, unconscious; Resistances: cold 5, electricity 5, fire 5, piercing 5, slashing 5",
                  summary: "A skeletal marksman that pins down foes with unerring volleys of arrows.",
                  desc: "Skeleton archers are undead warriors specifically animated to serve as ranged combatants, raining arrows down on the living from defensive positions. They retain enough martial memory to fire with deadly accuracy and can maintain sustained volleys without fatigue. Necromancers often station skeleton archers on walls and towers to defend their lairs.",
                  source: "Monster Core", isPremium: true),

            .make("Ghoul", level: 2,
                  creatureType: "Undead", size: "Medium",
                  traits: "Undead",
                  hp: "30", ac: 18, fort: 7, ref: 9, will: 7,
                  speed: "25 feet, burrow 5 feet",
                  attacks: "Jaws +10 (1d6+3 piercing plus ghoul fever and paralysis), Claw +10 (1d6+3 slashing plus paralysis; Agile)",
                  specialAbilities: "Darkvision; Ghoul Fever (DC 18 Fortitude); Paralysis (DC 18 Fortitude, 1 round); Consume Flesh; Swift Leap",
                  summary: "A ravenous undead that paralyzes prey with its claws before feasting.",
                  desc: "Ghouls are cunning undead driven by an insatiable hunger for humanoid flesh, particularly the flesh of the recently deceased. Their paralyzing touch immobilizes victims, leaving them helpless as the ghoul feeds. Unlike mindless zombies, ghouls retain their intelligence and can speak, plan, and even form communities in warrens beneath graveyards and crypts.",
                  source: "Monster Core", isPremium: true),

            .make("Ghast", level: 3,
                  creatureType: "Undead", size: "Medium",
                  traits: "Undead",
                  hp: "35", ac: 20, fort: 9, ref: 10, will: 8,
                  speed: "25 feet, burrow 5 feet",
                  attacks: "Jaws +12 (1d8+4 piercing plus ghast fever and paralysis), Claw +12 (1d6+4 slashing plus paralysis; Agile)",
                  specialAbilities: "Darkvision; Ghast Fever (DC 20 Fortitude); Paralysis (DC 20 Fortitude, 1 round, even elves); Stench (10-foot aura, DC 19 Fortitude); Consume Flesh; Swift Leap",
                  summary: "A more powerful ghoul whose nauseating stench can sicken the living.",
                  desc: "Ghasts are a more powerful variety of ghoul, distinguished by their nauseating stench and ability to paralyze even elves, who are normally immune to ghoul paralysis. They serve as leaders among ghoul packs, directing their lesser kin with cruel intelligence. Ghasts are often found commanding small warrens of ghouls in catacombs and underground lairs.",
                  source: "Monster Core", isPremium: true),

            .make("Wight", level: 3,
                  creatureType: "Undead", size: "Medium",
                  traits: "Undead",
                  hp: "45", ac: 20, fort: 10, ref: 8, will: 9,
                  speed: "25 feet",
                  attacks: "Claw +12 (1d6+4 slashing plus drain life)",
                  specialAbilities: "Darkvision; Drain Life (DC 17 Fortitude; on failed save, creature becomes drained 1 and wight gains 5 temporary HP); Final Spite; Wight Spawn",
                  summary: "An intelligent undead that drains the life force from the living.",
                  desc: "Wights are malevolent undead who retain the intelligence and memories they possessed in life, twisted by an overwhelming hatred of the living. Their touch drains the life force from victims, and those slain by a wight rise as lesser wight spawn under their killer's command. Wights often haunt the tombs and crypts where they were buried, guarding treasures they coveted in life.",
                  source: "Monster Core", isPremium: true),
        ]

        for monster in monsters {
            try await db.insertMonster(monster)
        }
    }
}
