import Foundation

extension SeedDataBuilder {
    func seedMonsters2() async throws {
        let monsters: [MonsterEntry] = [

            // MARK: - Dragons (Chromatic)

            .make("Young White Dragon", level: 5,
                  creatureType: "Dragon", size: "Large",
                  traits: "Dragon, Cold",
                  hp: "75", ac: 21, fort: 13, ref: 11, will: 9,
                  speed: "30 feet, fly 60 feet",
                  attacks: "Jaws +15 (2d8+6 piercing plus 1d6 cold; Reach 10 feet), Claw +15 (2d6+6 slashing; Agile, Reach 10 feet)",
                  specialAbilities: "Darkvision; Breath Weapon (30-foot cone, 7d6 cold, basic Reflex DC 20, recharge 1d4 rounds); Dragon Chill (aura 10 feet, 1d6 cold); Draconic Momentum",
                  summary: "A young white dragon is a feral predator that hunts across frozen tundra.",
                  desc: "White dragons are the most bestial and least intelligent of the chromatic dragons. Young whites are savage ambush predators that claim frigid territories and attack anything that wanders too close. They prefer to freeze prey with their breath before tearing into it.",
                  source: "Monster Core", isPremium: true),

            .make("Adult White Dragon", level: 11,
                  creatureType: "Dragon", size: "Huge",
                  traits: "Dragon, Cold",
                  hp: "185", ac: 30, fort: 21, ref: 19, will: 17,
                  speed: "40 feet, fly 80 feet, ice climb 30 feet",
                  attacks: "Jaws +24 (2d12+12 piercing plus 2d6 cold; Reach 15 feet), Claw +24 (2d10+12 slashing; Agile, Reach 10 feet), Tail +22 (2d10+10 bludgeoning; Reach 15 feet)",
                  specialAbilities: "Darkvision; Breath Weapon (40-foot cone, 12d6 cold, basic Reflex DC 29, recharge 1d4 rounds); Dragon Chill (aura 10 feet, 2d6 cold); Draconic Momentum; Frightful Presence (90 feet, DC 28 Will); Blizzard",
                  summary: "An adult white dragon commands icy territories and hunts with relentless ferocity.",
                  desc: "Adult white dragons have grown into powerful lords of frozen wastelands. Though still more feral than other dragons, they are cunning enough to set traps and exploit terrain. Their blizzard aura can blind and freeze entire groups of enemies.",
                  source: "Monster Core", isPremium: true),

            .make("Ancient White Dragon", level: 17,
                  creatureType: "Dragon", size: "Gargantuan",
                  traits: "Dragon, Cold",
                  hp: "330", ac: 38, fort: 29, ref: 27, will: 25,
                  speed: "40 feet, fly 120 feet, ice climb 40 feet",
                  attacks: "Jaws +33 (3d12+16 piercing plus 3d6 cold; Reach 20 feet), Claw +33 (3d10+16 slashing; Agile, Reach 15 feet), Tail +31 (3d10+14 bludgeoning; Reach 20 feet)",
                  specialAbilities: "Darkvision; Breath Weapon (50-foot cone, 17d6 cold, basic Reflex DC 37, recharge 1d4 rounds); Dragon Chill (aura 15 feet, 3d6 cold); Draconic Momentum; Frightful Presence (90 feet, DC 36 Will); Blizzard; Ice Shaping",
                  summary: "An ancient white dragon is a devastating force of primal winter.",
                  desc: "Ancient white dragons are among the oldest and most powerful of their kind, embodying the relentless fury of winter itself. They can reshape ice and snow at will, turning entire landscapes into frozen deathtraps. Few adventurers survive an encounter with one.",
                  source: "Monster Core", isPremium: true),

            .make("Young Black Dragon", level: 7,
                  creatureType: "Dragon", size: "Large",
                  traits: "Dragon, Acid",
                  hp: "115", ac: 25, fort: 15, ref: 16, will: 13,
                  speed: "30 feet, fly 60 feet, swim 30 feet",
                  attacks: "Jaws +18 (2d10+7 piercing plus 1d6 acid; Reach 10 feet), Claw +18 (2d6+7 slashing; Agile, Reach 10 feet), Tail +16 (2d8+5 bludgeoning; Reach 10 feet)",
                  specialAbilities: "Darkvision; Breath Weapon (60-foot line, 8d6 acid, basic Reflex DC 24, recharge 1d4 rounds); Frightful Presence (60 feet, DC 23 Will); Draconic Momentum",
                  summary: "A young black dragon lurks in swamps and bogs, dissolving prey with acid.",
                  desc: "Black dragons are cruel and sadistic, preferring to lair in fetid swamps and marshlands. Young black dragons delight in tormenting their prey before finishing it off. Their acid breath can dissolve flesh and metal alike.",
                  source: "Monster Core", isPremium: true),

            .make("Adult Black Dragon", level: 12,
                  creatureType: "Dragon", size: "Huge",
                  traits: "Dragon, Acid",
                  hp: "215", ac: 32, fort: 22, ref: 23, will: 19,
                  speed: "40 feet, fly 100 feet, swim 40 feet",
                  attacks: "Jaws +25 (3d10+10 piercing plus 2d6 acid; Reach 15 feet), Claw +25 (3d6+10 slashing; Agile, Reach 10 feet), Tail +23 (3d8+8 bludgeoning; Reach 15 feet)",
                  specialAbilities: "Darkvision; Breath Weapon (80-foot line, 13d6 acid, basic Reflex DC 31, recharge 1d4 rounds); Frightful Presence (90 feet, DC 30 Will); Draconic Momentum; Corrupt Water",
                  summary: "An adult black dragon is a patient, cruel predator that poisons entire swamp regions.",
                  desc: "Adult black dragons rule over vast stretches of swamp and bog, corrupting the water and driving out all who dare intrude. They are patient schemers who enjoy long campaigns of terror against nearby settlements. Their acidic breath erodes even magical protections.",
                  source: "Monster Core", isPremium: true),

            .make("Ancient Black Dragon", level: 18,
                  creatureType: "Dragon", size: "Gargantuan",
                  traits: "Dragon, Acid",
                  hp: "375", ac: 41, fort: 31, ref: 32, will: 27,
                  speed: "50 feet, fly 140 feet, swim 50 feet",
                  attacks: "Jaws +34 (3d12+14 piercing plus 4d6 acid; Reach 20 feet), Claw +34 (3d10+14 slashing; Agile, Reach 15 feet), Tail +32 (3d10+12 bludgeoning; Reach 20 feet)",
                  specialAbilities: "Darkvision; Breath Weapon (100-foot line, 18d6 acid, basic Reflex DC 39, recharge 1d4 rounds); Frightful Presence (90 feet, DC 38 Will); Draconic Momentum; Corrupt Water; Acid Pool",
                  summary: "An ancient black dragon is a nightmarish lord of decay and dissolution.",
                  desc: "Ancient black dragons are terrifying embodiments of corrosion and cruelty. Their mere presence warps the land around their lairs into toxic wastelands. They view all other creatures as playthings to torment and destroy at their leisure.",
                  source: "Monster Core", isPremium: true),

            .make("Young Green Dragon", level: 8,
                  creatureType: "Dragon", size: "Large",
                  traits: "Dragon, Poison",
                  hp: "135", ac: 26, fort: 17, ref: 16, will: 15,
                  speed: "30 feet, fly 80 feet, swim 30 feet",
                  attacks: "Jaws +19 (2d10+8 piercing plus 1d6 poison; Reach 10 feet), Claw +19 (2d8+8 slashing; Agile, Reach 10 feet), Tail +17 (2d8+6 bludgeoning; Reach 10 feet)",
                  specialAbilities: "Darkvision; Breath Weapon (30-foot cone, 9d6 poison, basic Fortitude DC 25, recharge 1d4 rounds); Frightful Presence (60 feet, DC 24 Will); Draconic Momentum; Woodland Stride",
                  summary: "A young green dragon is a cunning manipulator that prowls verdant forests.",
                  desc: "Green dragons are the most cunning and manipulative of the chromatic dragons. Young greens establish lairs in dense forests, weaving webs of intrigue among nearby settlements. They prefer to use deception and charm before resorting to violence.",
                  source: "Monster Core", isPremium: true),

            .make("Adult Green Dragon", level: 13,
                  creatureType: "Dragon", size: "Huge",
                  traits: "Dragon, Poison",
                  hp: "230", ac: 33, fort: 23, ref: 22, will: 21,
                  speed: "40 feet, fly 120 feet, swim 40 feet",
                  attacks: "Jaws +27 (3d10+12 piercing plus 2d6 poison; Reach 15 feet), Claw +27 (3d8+12 slashing; Agile, Reach 10 feet), Tail +25 (3d8+10 bludgeoning; Reach 15 feet)",
                  specialAbilities: "Darkvision; Breath Weapon (40-foot cone, 14d6 poison, basic Fortitude DC 33, recharge 1d4 rounds); Frightful Presence (90 feet, DC 32 Will); Draconic Momentum; Woodland Stride; Trackless Step",
                  summary: "An adult green dragon is a master schemer that dominates forest domains through guile.",
                  desc: "Adult green dragons are patient manipulators who build empires of influence in woodland realms. They prefer to gather minions and control communities from the shadows rather than engage in direct combat. When forced to fight, their poisonous breath is devastatingly effective.",
                  source: "Monster Core", isPremium: true),

            .make("Young Blue Dragon", level: 9,
                  creatureType: "Dragon", size: "Large",
                  traits: "Dragon, Electricity",
                  hp: "150", ac: 27, fort: 18, ref: 16, will: 17,
                  speed: "30 feet, fly 80 feet, burrow 15 feet",
                  attacks: "Jaws +20 (2d10+9 piercing plus 1d12 electricity; Reach 10 feet), Claw +20 (2d8+9 slashing; Agile, Reach 10 feet), Tail +18 (2d8+7 bludgeoning; Reach 10 feet)",
                  specialAbilities: "Darkvision; Breath Weapon (80-foot line, 10d12 electricity, basic Reflex DC 27, recharge 1d4 rounds); Frightful Presence (60 feet, DC 26 Will); Draconic Momentum; Sound Mimicry",
                  summary: "A young blue dragon is a vain, territorial predator that hunts across arid deserts.",
                  desc: "Blue dragons are orderly and vain, believing themselves to be the most superior of all dragons. Young blues establish lairs in desert caves and ruins, jealously guarding their growing hoards. They are deceptive hunters that can mimic voices to lure prey.",
                  source: "Monster Core", isPremium: true),

            .make("Adult Blue Dragon", level: 14,
                  creatureType: "Dragon", size: "Huge",
                  traits: "Dragon, Electricity",
                  hp: "250", ac: 35, fort: 25, ref: 22, will: 23,
                  speed: "40 feet, fly 120 feet, burrow 20 feet",
                  attacks: "Jaws +28 (3d10+13 piercing plus 2d12 electricity; Reach 15 feet), Claw +28 (3d8+13 slashing; Agile, Reach 10 feet), Tail +26 (3d8+11 bludgeoning; Reach 15 feet)",
                  specialAbilities: "Darkvision; Breath Weapon (100-foot line, 14d12 electricity, basic Reflex DC 34, recharge 1d4 rounds); Frightful Presence (90 feet, DC 33 Will); Draconic Momentum; Sound Mimicry; Desert Thirst; Mirage",
                  summary: "An adult blue dragon commands vast desert territories with imperious authority.",
                  desc: "Adult blue dragons rule their desert domains with absolute authority, demanding tribute from any who pass through. They create mirages to confuse travelers and lure them to their doom. Their lightning breath can strike targets at extreme range.",
                  source: "Monster Core", isPremium: true),

            .make("Young Red Dragon", level: 10,
                  creatureType: "Dragon", size: "Large",
                  traits: "Dragon, Fire",
                  hp: "175", ac: 29, fort: 21, ref: 18, will: 17,
                  speed: "40 feet, fly 100 feet",
                  attacks: "Jaws +23 (2d12+10 piercing plus 2d6 fire; Reach 10 feet), Claw +23 (2d10+10 slashing; Agile, Reach 10 feet), Tail +21 (2d10+8 bludgeoning; Reach 15 feet)",
                  specialAbilities: "Darkvision; Smoke Vision; Breath Weapon (40-foot cone, 11d6 fire, basic Reflex DC 29, recharge 1d4 rounds); Frightful Presence (60 feet, DC 28 Will); Draconic Momentum",
                  summary: "A young red dragon is a fearsome, fire-breathing tyrant that dominates through raw power.",
                  desc: "Red dragons are the most iconic and feared of all chromatic dragons. Young reds aggressively claim territory and brook no challenges to their authority. They burn entire villages to expand their hoards, reveling in destruction.",
                  source: "Monster Core", isPremium: true),

            .make("Ancient Red Dragon", level: 20,
                  creatureType: "Dragon", size: "Gargantuan",
                  traits: "Dragon, Fire",
                  hp: "450", ac: 45, fort: 37, ref: 31, will: 33,
                  speed: "60 feet, fly 180 feet",
                  attacks: "Jaws +37 (4d10+18 piercing plus 4d6 fire; Reach 20 feet, Magical), Claw +37 (4d8+18 slashing; Agile, Magical, Reach 15 feet), Tail +35 (4d10+16 bludgeoning; Magical, Reach 25 feet), Wing +35 (3d8+14 bludgeoning; Magical, Reach 20 feet)",
                  specialAbilities: "Darkvision; Smoke Vision; Breath Weapon (60-foot cone, 20d6 fire, basic Reflex DC 42, recharge 1d4 rounds); Draconic Frenzy; Frightful Presence (90 feet, DC 41 Will); Manipulate Flames; Volcanic Purge",
                  summary: "An ancient red dragon is a world-shaking force of fire and tyranny.",
                  desc: "Ancient red dragons are among the most powerful mortal creatures in existence, rivaling the mightiest of other beings. They rule vast territories from volcanic lairs, and their mere arrival can reshape the landscape. Entire nations have fallen to the wrath of a single ancient red dragon.",
                  source: "Monster Core", isPremium: true),

            // MARK: - Dragons (Metallic)

            .make("Young Gold Dragon", level: 12,
                  creatureType: "Dragon", size: "Large",
                  traits: "Dragon, Fire",
                  hp: "200", ac: 32, fort: 22, ref: 20, will: 22,
                  speed: "40 feet, fly 120 feet, swim 40 feet",
                  attacks: "Jaws +25 (2d12+12 piercing plus 2d6 fire; Reach 10 feet), Claw +25 (2d10+12 slashing; Agile, Reach 10 feet), Tail +23 (2d10+10 bludgeoning; Reach 15 feet)",
                  specialAbilities: "Darkvision; Breath Weapon (40-foot cone, 12d6 fire, basic Reflex DC 31, recharge 1d4 rounds); Weakening Breath (40-foot cone, DC 31 Fortitude or enfeebled 2); Frightful Presence (60 feet, DC 30 Will); Draconic Momentum",
                  summary: "A young gold dragon is a noble and powerful protector who opposes evil with righteous fire.",
                  desc: "Gold dragons are the most powerful and majestic of the metallic dragons, driven by a deep sense of justice. Young golds patrol their territory to root out evil and protect the innocent. They possess two breath weapons: one of fire and one that saps the strength of foes.",
                  source: "Monster Core", isPremium: true),

            .make("Adult Gold Dragon", level: 17,
                  creatureType: "Dragon", size: "Huge",
                  traits: "Dragon, Fire",
                  hp: "340", ac: 39, fort: 30, ref: 27, will: 30,
                  speed: "50 feet, fly 160 feet, swim 50 feet",
                  attacks: "Jaws +32 (3d12+16 piercing plus 3d6 fire; Reach 15 feet), Claw +32 (3d10+16 slashing; Agile, Reach 10 feet), Tail +30 (3d10+14 bludgeoning; Reach 20 feet)",
                  specialAbilities: "Darkvision; Breath Weapon (50-foot cone, 17d6 fire, basic Reflex DC 38, recharge 1d4 rounds); Weakening Breath (50-foot cone, DC 38 Fortitude or enfeebled 3); Frightful Presence (90 feet, DC 37 Will); Draconic Frenzy; Detect Alignment",
                  summary: "An adult gold dragon is a legendary champion of justice whose power rivals entire armies.",
                  desc: "Adult gold dragons are awe-inspiring paragons of virtue and power. They actively seek out great evils to destroy and often mentor younger heroes. Their very presence radiates an aura of majesty that can humble even the most hardened warriors.",
                  source: "Monster Core", isPremium: true),

            .make("Young Silver Dragon", level: 10,
                  creatureType: "Dragon", size: "Large",
                  traits: "Dragon, Cold",
                  hp: "175", ac: 29, fort: 20, ref: 18, will: 20,
                  speed: "30 feet, fly 100 feet",
                  attacks: "Jaws +23 (2d10+10 piercing plus 1d6 cold; Reach 10 feet), Claw +23 (2d8+10 slashing; Agile, Reach 10 feet), Tail +21 (2d8+8 bludgeoning; Reach 10 feet)",
                  specialAbilities: "Darkvision; Breath Weapon (30-foot cone, 10d6 cold, basic Reflex DC 29, recharge 1d4 rounds); Paralyzing Breath (30-foot cone, DC 29 Fortitude or slowed 2); Frightful Presence (60 feet, DC 28 Will); Draconic Momentum; Cloud Walk",
                  summary: "A young silver dragon is a graceful protector that befriends humanoids and guards the skies.",
                  desc: "Silver dragons are the most social of the metallic dragons, often taking humanoid form to live among mortals. Young silvers actively seek friendships and alliances with good-aligned creatures. They prefer cold mountain peaks as their lairs and can walk upon clouds.",
                  source: "Monster Core", isPremium: true),

            .make("Adult Silver Dragon", level: 15,
                  creatureType: "Dragon", size: "Huge",
                  traits: "Dragon, Cold",
                  hp: "280", ac: 36, fort: 26, ref: 24, will: 26,
                  speed: "40 feet, fly 120 feet",
                  attacks: "Jaws +29 (3d10+14 piercing plus 2d6 cold; Reach 15 feet), Claw +29 (3d8+14 slashing; Agile, Reach 10 feet), Tail +27 (3d8+12 bludgeoning; Reach 15 feet)",
                  specialAbilities: "Darkvision; Breath Weapon (40-foot cone, 14d6 cold, basic Reflex DC 35, recharge 1d4 rounds); Paralyzing Breath (40-foot cone, DC 35 Fortitude or slowed 2); Frightful Presence (90 feet, DC 34 Will); Draconic Frenzy; Cloud Walk; Fog Cloud (at will)",
                  summary: "An adult silver dragon is a wise guardian who takes humanoid form to guide and protect mortal communities.",
                  desc: "Adult silver dragons maintain deep bonds with humanoid civilizations and often act as their hidden protectors. They are wise counselors who can summon fog to shield allies or cloak their movements. Their paralyzing breath can immobilize entire groups of enemies.",
                  source: "Monster Core", isPremium: true),

            // MARK: - Dragon Turtle

            .make("Dragon Turtle", level: 9,
                  creatureType: "Dragon", size: "Huge",
                  traits: "Dragon, Aquatic",
                  hp: "155", ac: 29, fort: 20, ref: 14, will: 16,
                  speed: "20 feet, swim 40 feet",
                  attacks: "Jaws +21 (2d12+12 piercing; Reach 10 feet), Claw +21 (2d8+12 slashing; Agile)",
                  specialAbilities: "Darkvision; Breath Weapon (60-foot cone of steam, 10d6 fire, basic Reflex DC 27, recharge 1d4 rounds; works underwater); Capsize; Shell Defense",
                  summary: "A dragon turtle is a massive aquatic predator that demands tribute from passing ships.",
                  desc: "Dragon turtles are immense, territorial creatures that dwell in deep oceans and large lakes. They surface to demand treasure from passing vessels, destroying those that refuse to pay. Their steam breath is equally deadly above and below the waterline.",
                  source: "Monster Core", isPremium: true),

            // MARK: - Giants

            .make("Hill Giant", level: 7,
                  creatureType: "Giant, Humanoid", size: "Large",
                  traits: "Giant, Humanoid",
                  hp: "130", ac: 22, fort: 17, ref: 11, will: 13,
                  speed: "35 feet",
                  attacks: "Greatclub +18 (2d10+10 bludgeoning; Backswing, Reach 10 feet), Rock +14 (2d6+10 bludgeoning; Range Increment 120 feet)",
                  specialAbilities: "Low-Light Vision; Rock Catching; Rock Throwing",
                  summary: "Hill giants are dim, gluttonous brutes who rely on raw strength and hurled boulders.",
                  desc: "Hill giants are the weakest and most common of true giants, but their immense size still makes them a serious threat. They are driven primarily by hunger and greed, raiding farms and settlements for food. They often bully smaller creatures into serving them.",
                  source: "Monster Core", isPremium: true),

            .make("Stone Giant", level: 8,
                  creatureType: "Giant, Humanoid", size: "Large",
                  traits: "Giant, Humanoid",
                  hp: "140", ac: 25, fort: 17, ref: 14, will: 15,
                  speed: "35 feet",
                  attacks: "Greatclub +19 (2d12+10 bludgeoning; Backswing, Reach 10 feet), Rock +19 (2d6+12 bludgeoning; Range Increment 120 feet)",
                  specialAbilities: "Low-Light Vision; Rock Catching; Rock Throwing; Big Swing",
                  summary: "Stone giants are reclusive artisans who dwell deep within mountain caves.",
                  desc: "Stone giants are skilled artisans and cave dwellers who prefer to be left alone. They carve intricate works of art from stone and tend to judge all other creatures by their artistic merit. When roused to battle, they hurl boulders with devastating accuracy.",
                  source: "Monster Core", isPremium: true),

            .make("Frost Giant", level: 9,
                  creatureType: "Giant, Humanoid", size: "Large",
                  traits: "Giant, Cold, Humanoid",
                  hp: "155", ac: 25, fort: 20, ref: 14, will: 16,
                  speed: "30 feet",
                  attacks: "Greataxe +21 (2d12+10 slashing; Reach 10 feet, Sweep), Rock +18 (2d6+12 bludgeoning; Range Increment 120 feet)",
                  specialAbilities: "Low-Light Vision; Rock Catching; Rock Throwing; Ice Stride; Cold Immunity; Fire Weakness 10",
                  summary: "Frost giants are fierce, warlike raiders who thrive in frozen lands.",
                  desc: "Frost giants are brutal warriors who value martial prowess above all else. They dwell in glacial fortresses and frozen mountain halls, launching raids on lowland settlements for plunder and slaves. Their immunity to cold allows them to thrive where few others can survive.",
                  source: "Monster Core", isPremium: true),

            .make("Fire Giant", level: 10,
                  creatureType: "Giant, Humanoid", size: "Large",
                  traits: "Giant, Fire, Humanoid",
                  hp: "175", ac: 28, fort: 21, ref: 16, will: 17,
                  speed: "30 feet",
                  attacks: "Greatsword +23 (2d12+12 slashing; Reach 10 feet, Versatile P), Rock +18 (2d8+12 bludgeoning; Range Increment 120 feet)",
                  specialAbilities: "Low-Light Vision; Rock Catching; Rock Throwing; Fire Immunity; Cold Weakness 10",
                  summary: "Fire giants are disciplined, militaristic smiths who forge weapons in volcanic strongholds.",
                  desc: "Fire giants are masterful smiths and disciplined soldiers who build great fortresses near volcanoes and lava flows. They maintain rigid hierarchies and wage organized campaigns of conquest. Their forges produce some of the finest weapons and armor found among giantkind.",
                  source: "Monster Core", isPremium: true),

            .make("Cloud Giant", level: 11,
                  creatureType: "Giant, Humanoid", size: "Huge",
                  traits: "Giant, Humanoid",
                  hp: "195", ac: 30, fort: 22, ref: 17, will: 20,
                  speed: "30 feet",
                  attacks: "Ranseur +24 (2d10+14 piercing; Disarm, Reach 15 feet), Fist +24 (2d8+14 bludgeoning; Agile, Reach 10 feet), Rock +22 (2d10+14 bludgeoning; Range Increment 120 feet)",
                  specialAbilities: "Low-Light Vision; Rock Catching; Rock Throwing; Wind Stride; Keen Smell",
                  summary: "Cloud giants are proud, aristocratic giants who dwell in sky castles high above the world.",
                  desc: "Cloud giants are regal beings who build magnificent castles on cloud banks and mountaintops. They consider themselves the natural aristocrats of giantkind and look down upon smaller races both literally and figuratively. Some are benevolent, while others are cruel tyrants.",
                  source: "Monster Core", isPremium: true),

            .make("Storm Giant", level: 13,
                  creatureType: "Giant, Humanoid", size: "Huge",
                  traits: "Giant, Electricity, Humanoid",
                  hp: "235", ac: 33, fort: 24, ref: 21, will: 22,
                  speed: "35 feet, swim 30 feet",
                  attacks: "Greatsword +27 (3d12+14 slashing; Reach 15 feet, Versatile P), Fist +27 (2d8+14 bludgeoning; Agile, Reach 10 feet), Lightning Bolt +25 (6d12 electricity; Range 120 feet)",
                  specialAbilities: "Low-Light Vision; Electricity Immunity; Rock Catching; Rock Throwing; Control Weather (at will); Lightning Bolt",
                  summary: "Storm giants are wise and powerful giants who command the fury of the storm.",
                  desc: "Storm giants are among the most powerful and intelligent of all giant-kind. They dwell in remote coastal fortresses and underwater palaces, generally content to live in isolation. When roused to action, they command the power of thunderstorms themselves, hurling bolts of lightning with devastating precision.",
                  source: "Monster Core", isPremium: true),

            // MARK: - Elementals (Air)

            .make("Small Air Elemental", level: 1,
                  creatureType: "Elemental", size: "Small",
                  traits: "Elemental, Air",
                  hp: "20", ac: 15, fort: 6, ref: 9, will: 5,
                  speed: "fly 40 feet",
                  attacks: "Gust +8 (1d6+2 bludgeoning; Finesse)",
                  specialAbilities: "Darkvision; Push (Gust); Wind Blast",
                  summary: "A small air elemental is a swirling vortex of wind and dust.",
                  desc: "Small air elementals are whirling masses of wind, dust, and debris drawn from the Plane of Air. They are quick and agile, darting through the sky to buffet foes with powerful gusts. They dissipate into a final gust of wind when destroyed.",
                  source: "Monster Core", isPremium: true),

            .make("Large Air Elemental", level: 5,
                  creatureType: "Elemental", size: "Large",
                  traits: "Elemental, Air",
                  hp: "70", ac: 20, fort: 11, ref: 14, will: 10,
                  speed: "fly 60 feet",
                  attacks: "Gust +14 (2d8+4 bludgeoning; Finesse, Reach 10 feet)",
                  specialAbilities: "Darkvision; Push (Gust); Whirlwind (3 actions, 15-foot radius, 4d6 bludgeoning, DC 22 Reflex)",
                  summary: "A large air elemental is a roaring cyclone of destructive wind.",
                  desc: "Large air elementals have enough power to form sustained cyclones capable of lifting creatures off the ground. They can generate whirlwinds that scatter groups of foes. Their swirling form makes them difficult to strike with conventional weapons.",
                  source: "Monster Core", isPremium: true),

            .make("Huge Air Elemental", level: 9,
                  creatureType: "Elemental", size: "Huge",
                  traits: "Elemental, Air",
                  hp: "135", ac: 27, fort: 17, ref: 21, will: 16,
                  speed: "fly 80 feet",
                  attacks: "Gust +21 (2d10+8 bludgeoning; Finesse, Reach 15 feet)",
                  specialAbilities: "Darkvision; Push (Gust); Whirlwind (3 actions, 20-foot radius, 6d6 bludgeoning, DC 27 Reflex); Swiftness",
                  summary: "A huge air elemental is a devastating tornado of elemental fury.",
                  desc: "Huge air elementals are towering vortexes capable of tearing apart buildings and flinging creatures hundreds of feet. Their whirlwinds can engulf entire groups, and they move with blinding speed. Few can outrun one once it has set its sights on prey.",
                  source: "Monster Core", isPremium: true),

            // MARK: - Elementals (Earth)

            .make("Small Earth Elemental", level: 1,
                  creatureType: "Elemental", size: "Small",
                  traits: "Elemental, Earth",
                  hp: "20", ac: 17, fort: 8, ref: 4, will: 5,
                  speed: "20 feet, burrow 20 feet",
                  attacks: "Fist +8 (1d6+3 bludgeoning)",
                  specialAbilities: "Darkvision; Earth Glide; Tremorsense (imprecise) 30 feet",
                  summary: "A small earth elemental is a squat mass of animated stone and soil.",
                  desc: "Small earth elementals are compact masses of rock, soil, and crystal animated by elemental energy. They move through solid earth as easily as a fish swims through water. Despite their small size, their stony fists hit with surprising force.",
                  source: "Monster Core", isPremium: true),

            .make("Large Earth Elemental", level: 5,
                  creatureType: "Elemental", size: "Large",
                  traits: "Elemental, Earth",
                  hp: "75", ac: 23, fort: 14, ref: 8, will: 10,
                  speed: "25 feet, burrow 25 feet",
                  attacks: "Fist +15 (2d8+8 bludgeoning; Reach 10 feet)",
                  specialAbilities: "Darkvision; Earth Glide; Tremorsense (imprecise) 60 feet; Crumble (reaction, reduce bludgeoning damage by 8)",
                  summary: "A large earth elemental is a lumbering mass of boulders that shakes the ground with each step.",
                  desc: "Large earth elementals are towering mounds of rock and packed earth that lumber forward with inexorable force. They can merge with the ground beneath them to travel unseen, bursting forth to ambush unsuspecting foes. Their rocky bodies shrug off many attacks.",
                  source: "Monster Core", isPremium: true),

            .make("Huge Earth Elemental", level: 9,
                  creatureType: "Elemental", size: "Huge",
                  traits: "Elemental, Earth",
                  hp: "145", ac: 28, fort: 21, ref: 13, will: 17,
                  speed: "25 feet, burrow 25 feet",
                  attacks: "Fist +21 (2d10+12 bludgeoning; Reach 15 feet)",
                  specialAbilities: "Darkvision; Earth Glide; Tremorsense (imprecise) 90 feet; Crumble (reaction, reduce bludgeoning damage by 12); Earthen Grasp",
                  summary: "A huge earth elemental is an immovable mountain of animated stone and crystal.",
                  desc: "Huge earth elementals are living avalanches of stone, crystal, and packed earth. Their tremorsense allows them to detect any creature touching the ground within a vast radius. They can trap foes in earthen prisons and shrug off devastating blows with their dense mineral bodies.",
                  source: "Monster Core", isPremium: true),

            // MARK: - Elementals (Fire)

            .make("Small Fire Elemental", level: 1,
                  creatureType: "Elemental", size: "Small",
                  traits: "Elemental, Fire",
                  hp: "16", ac: 16, fort: 6, ref: 8, will: 5,
                  speed: "40 feet",
                  attacks: "Tendril +8 (1d4+2 fire; Finesse)",
                  specialAbilities: "Darkvision; Fire Immunity; Cold Weakness 3; Burning Touch (1d4 persistent fire on critical hit)",
                  summary: "A small fire elemental is a flickering flame that darts about with malicious intent.",
                  desc: "Small fire elementals are dancing flames animated by elemental energy from the Plane of Fire. They set alight anything flammable they touch and can squeeze through the smallest cracks. Their bodies radiate intense heat that scorches nearby creatures.",
                  source: "Monster Core", isPremium: true),

            .make("Large Fire Elemental", level: 5,
                  creatureType: "Elemental", size: "Large",
                  traits: "Elemental, Fire",
                  hp: "65", ac: 20, fort: 12, ref: 13, will: 10,
                  speed: "50 feet",
                  attacks: "Tendril +14 (2d6+4 fire; Finesse, Reach 10 feet)",
                  specialAbilities: "Darkvision; Fire Immunity; Cold Weakness 5; Burning Touch (1d6 persistent fire on critical hit); Smoke Cloud (5-foot emanation, concealed)",
                  summary: "A large fire elemental is a roaring bonfire that leaves scorched earth in its wake.",
                  desc: "Large fire elementals are roaring infernos that can incinerate creatures caught in their path. They generate clouds of choking smoke that obscure vision and leave scorched earth wherever they travel. Their fiery tendrils can set entire buildings ablaze.",
                  source: "Monster Core", isPremium: true),

            .make("Huge Fire Elemental", level: 9,
                  creatureType: "Elemental", size: "Huge",
                  traits: "Elemental, Fire",
                  hp: "130", ac: 27, fort: 18, ref: 20, will: 16,
                  speed: "60 feet",
                  attacks: "Tendril +21 (2d10+6 fire; Finesse, Reach 15 feet)",
                  specialAbilities: "Darkvision; Fire Immunity; Cold Weakness 10; Burning Touch (2d6 persistent fire on critical hit); Smoke Cloud (10-foot emanation, concealed); Inferno Leap",
                  summary: "A huge fire elemental is a towering conflagration that incinerates everything in its path.",
                  desc: "Huge fire elementals are raging firestorms of elemental fury that can reduce stone to slag. They generate intense heat in a wide radius, and their inferno leap lets them crash down on foes in an explosion of flame. Few materials can withstand their sustained assault.",
                  source: "Monster Core", isPremium: true),

            // MARK: - Elementals (Water)

            .make("Small Water Elemental", level: 1,
                  creatureType: "Elemental", size: "Small",
                  traits: "Elemental, Water",
                  hp: "20", ac: 16, fort: 7, ref: 7, will: 5,
                  speed: "20 feet, swim 40 feet",
                  attacks: "Wave +8 (1d6+2 bludgeoning)",
                  specialAbilities: "Darkvision; Water-Bound (when not touching water, is slowed 1 and can't use reactions); Drench (extinguishes non-magical fires in a 5-foot emanation)",
                  summary: "A small water elemental is a rippling mass of animate water.",
                  desc: "Small water elementals are mobile pools of water animated by elemental energy. They can extinguish fires with a mere touch and flow through any opening that water could pass through. They are strongest when near a body of water.",
                  source: "Monster Core", isPremium: true),

            .make("Large Water Elemental", level: 5,
                  creatureType: "Elemental", size: "Large",
                  traits: "Elemental, Water",
                  hp: "75", ac: 21, fort: 13, ref: 11, will: 10,
                  speed: "25 feet, swim 50 feet",
                  attacks: "Wave +14 (2d8+6 bludgeoning; Reach 10 feet)",
                  specialAbilities: "Darkvision; Water-Bound; Drench (10-foot emanation); Vortex (3 actions, 15-foot radius, 4d6 bludgeoning, DC 22 Reflex)",
                  summary: "A large water elemental is a surging wave that crashes over and engulfs its enemies.",
                  desc: "Large water elementals are powerful surges of water that can engulf and drown creatures caught in their path. They generate whirlpools to pull enemies beneath the surface. Their fluid forms are difficult to damage with slashing and piercing weapons.",
                  source: "Monster Core", isPremium: true),

            .make("Huge Water Elemental", level: 9,
                  creatureType: "Elemental", size: "Huge",
                  traits: "Elemental, Water",
                  hp: "140", ac: 27, fort: 19, ref: 17, will: 16,
                  speed: "30 feet, swim 60 feet",
                  attacks: "Wave +21 (2d10+10 bludgeoning; Reach 15 feet)",
                  specialAbilities: "Darkvision; Water-Bound; Drench (15-foot emanation); Vortex (3 actions, 20-foot radius, 6d6 bludgeoning, DC 27 Reflex); Tsunami Surge",
                  summary: "A huge water elemental is a tidal wave of animate water capable of capsizing ships.",
                  desc: "Huge water elementals are living tsunamis that can sweep entire groups off their feet and drag them underwater. Their vortex can pull in creatures from a wide area, and their surges are powerful enough to capsize small vessels. They are nearly unstoppable near large bodies of water.",
                  source: "Monster Core", isPremium: true),

            // MARK: - Demons

            .make("Quasit", level: 1,
                  creatureType: "Fiend", size: "Tiny",
                  traits: "Fiend, Demon",
                  hp: "16", ac: 16, fort: 6, ref: 9, will: 7,
                  speed: "15 feet, fly 35 feet",
                  attacks: "Claw +8 (1d6-1 slashing plus 1d4 poison; Agile, Finesse)",
                  specialAbilities: "Darkvision; Abyssal Healing (regain 1 HP per round); Change Shape (bat, centipede, or toad); Shapechanger; Telepathy 100 feet",
                  summary: "A quasit is a tiny, shape-shifting demon that serves as a spy and corruptor.",
                  desc: "Quasits are minor demons that often serve as familiars or spies for more powerful fiends and mortal spellcasters. They delight in petty cruelty and corrupting mortals toward evil. Despite their small size, their venomous claws can debilitate the unwary.",
                  source: "Monster Core", isPremium: true),

            .make("Dretch", level: 1,
                  creatureType: "Fiend", size: "Small",
                  traits: "Fiend, Demon",
                  hp: "20", ac: 13, fort: 8, ref: 4, will: 4,
                  speed: "20 feet",
                  attacks: "Claw +7 (1d6+2 slashing), Jaws +7 (1d6+2 piercing)",
                  specialAbilities: "Darkvision; Fetid Cloud (10-foot aura, DC 14 Fortitude or sickened 1); Sloth; Telepathy 100 feet",
                  summary: "A dretch is a sluggish, wretched demon that wallows in filth and despair.",
                  desc: "Dretches are among the lowest demons, pitiful creatures formed from the souls of the slothful and wretched. They exude a disgusting stench that sickens those nearby. Though individually weak, they can overwhelm foes through sheer numbers when driven by a more powerful demon.",
                  source: "Monster Core", isPremium: true),

            .make("Incubus", level: 4,
                  creatureType: "Fiend", size: "Medium",
                  traits: "Fiend, Demon",
                  hp: "50", ac: 20, fort: 9, ref: 11, will: 13,
                  speed: "25 feet, fly 30 feet",
                  attacks: "Longsword +13 (1d8+6 slashing; Versatile P)",
                  specialAbilities: "Darkvision; Change Shape (humanoid form); Telepathy 100 feet; Seduce (DC 21 Will or fascinated); Betrayer's Gift (grant a wish with a hidden curse)",
                  summary: "An incubus is a seductive demon that manipulates mortals through desire and betrayal.",
                  desc: "Incubi are demons of lust and betrayal who assume attractive humanoid forms to infiltrate mortal society. They corrupt mortals by offering seemingly generous bargains that invariably carry hidden, devastating costs. Their silver tongues are often more dangerous than their blades.",
                  source: "Monster Core", isPremium: true),

            .make("Babau", level: 6,
                  creatureType: "Fiend", size: "Medium",
                  traits: "Fiend, Demon",
                  hp: "90", ac: 22, fort: 14, ref: 15, will: 12,
                  speed: "25 feet",
                  attacks: "Longspear +16 (1d8+7 piercing; Reach 10 feet), Jaws +16 (1d8+7 piercing), Claw +16 (1d6+7 slashing; Agile)",
                  specialAbilities: "Darkvision; At-Will Darkness; Grievous Wound (additional 1d6 bleed on critical hit); Sneak Attack 1d6; Telepathy 100 feet",
                  summary: "A babau is a lanky, murderous demon that revels in assassination and ambush.",
                  desc: "Babaus are gaunt, blood-red demons that serve as assassins and scouts for demon armies. They secrete a corrosive slime from their skin and delight in stalking prey through darkness. Their sneak attacks are particularly devastating when they catch enemies off guard.",
                  source: "Monster Core", isPremium: true),

            .make("Vrock", level: 9,
                  creatureType: "Fiend", size: "Large",
                  traits: "Fiend, Demon",
                  hp: "140", ac: 27, fort: 19, ref: 17, will: 16,
                  speed: "25 feet, fly 35 feet",
                  attacks: "Beak +21 (2d12+8 piercing; Reach 10 feet), Claw +21 (2d8+8 slashing; Agile, Reach 10 feet), Talon +19 (2d6+8 slashing)",
                  specialAbilities: "Darkvision; Spore Cloud (poison, 20-foot emanation, DC 27 Fortitude or enfeebled 1); Stunning Screech (60-foot burst, DC 27 Fortitude or stunned 2); Dance of Ruin; Telepathy 100 feet",
                  summary: "A vrock is a vulture-headed demon that spreads toxic spores and deafening shrieks.",
                  desc: "Vrocks are massive, vulture-like demons that serve as shock troops in demonic armies. They release clouds of toxic spores and emit stunning screeches that can incapacitate entire groups of foes. When multiple vrocks perform their dance of ruin together, the destruction is devastating.",
                  source: "Monster Core", isPremium: true),

            .make("Hezrou", level: 11,
                  creatureType: "Fiend", size: "Large",
                  traits: "Fiend, Demon",
                  hp: "185", ac: 28, fort: 22, ref: 18, will: 19,
                  speed: "30 feet, swim 30 feet",
                  attacks: "Jaws +24 (2d12+10 piercing plus Grab; Reach 10 feet), Claw +24 (2d8+10 slashing; Agile, Reach 10 feet)",
                  specialAbilities: "Darkvision; Stench Aura (30 feet, DC 27 Fortitude or sickened 1); Swallow Whole (2d12+6 bludgeoning, Escape DC 28); Telepathy 100 feet",
                  summary: "A hezrou is a massive, toad-like demon that exudes a nauseating stench.",
                  desc: "Hezrous are bloated, toad-like demons that serve as front-line brutes in the demonic ranks. Their revolting stench sickens all but the most resilient foes, and their powerful jaws can swallow creatures whole. They are often found guarding important sites in the Abyss.",
                  source: "Monster Core", isPremium: true),

            .make("Glabrezu", level: 13,
                  creatureType: "Fiend", size: "Large",
                  traits: "Fiend, Demon",
                  hp: "230", ac: 32, fort: 23, ref: 20, will: 23,
                  speed: "35 feet",
                  attacks: "Pincer +27 (2d10+12 bludgeoning plus Grab; Reach 15 feet), Claw +27 (2d6+12 slashing; Agile, Reach 10 feet), Jaws +27 (2d12+12 piercing; Reach 10 feet)",
                  specialAbilities: "Darkvision; Telepathy 100 feet; Temptation (offer a wish, DC 33 Will to resist the temptation); Captive Rake; Sudden Betrayal",
                  summary: "A glabrezu is a cunning, four-armed demon that corrupts mortals with false wishes.",
                  desc: "Glabrezus are massive, four-armed demons that specialize in tempting mortals with offers of power. Unlike most demons, they prefer manipulation to brute force, offering wishes that invariably lead to ruin. When forced to fight, their massive pincers can crush armored knights.",
                  source: "Monster Core", isPremium: true),

            .make("Nalfeshnee", level: 14,
                  creatureType: "Fiend", size: "Large",
                  traits: "Fiend, Demon",
                  hp: "255", ac: 33, fort: 24, ref: 21, will: 25,
                  speed: "30 feet, fly 40 feet",
                  attacks: "Jaws +28 (3d12+12 piercing; Reach 10 feet), Claw +28 (3d8+12 slashing; Agile, Reach 10 feet)",
                  specialAbilities: "Darkvision; Telepathy 100 feet; Unholy Nimbus (40-foot burst, 10d10 mental damage, DC 34 Will); Horror Nimbus (30-foot aura, DC 34 Will or frightened 2); Truesight",
                  summary: "A nalfeshnee is a bloated, boar-headed demon that judges the souls of the damned.",
                  desc: "Nalfeshnees are grotesque, corpulent demons that serve as judges in the Abyss, deciding which layers condemned souls are sent to. They emit bursts of unholy light that sear the minds of non-evil creatures. Despite their bloated appearance, they are deceptively fast in combat.",
                  source: "Monster Core", isPremium: true),

            .make("Marilith", level: 17,
                  creatureType: "Fiend", size: "Large",
                  traits: "Fiend, Demon",
                  hp: "340", ac: 39, fort: 28, ref: 30, will: 27,
                  speed: "40 feet, fly 40 feet",
                  attacks: "Longsword +32 (2d8+16 slashing; Magical, Reach 10 feet, Versatile P), Tail +32 (2d8+16 bludgeoning; Magical, Reach 10 feet, Grab)",
                  specialAbilities: "Darkvision; Telepathy 100 feet; Six Swords (wields six longswords simultaneously); Blade Flurry (3 actions, Strike with all six swords); Reactive Strikes; Greater Constrict (2d12+10 bludgeoning, DC 38 Fortitude)",
                  summary: "A marilith is a six-armed serpentine demon and one of the deadliest warriors in the Abyss.",
                  desc: "Mariliths are among the most powerful demons, serving as generals in demonic armies. Their six arms each wield a weapon with deadly skill, allowing them to unleash a storm of blades that few can survive. Their serpentine lower bodies constrict foes while their swords continue their onslaught.",
                  source: "Monster Core", isPremium: true),

            // MARK: - Devils

            .make("Lemure", level: -1,
                  creatureType: "Fiend", size: "Medium",
                  traits: "Fiend, Devil",
                  hp: "15", ac: 12, fort: 6, ref: 3, will: 4,
                  speed: "20 feet",
                  attacks: "Claw +5 (1d4+1 bludgeoning)",
                  specialAbilities: "Darkvision; Mindless; Immunities: mental; Weaknesses: holy 3; Resistances: fire 3, physical 3 (except silver)",
                  summary: "A lemure is a blob-like, wretched devil that is the least of all infernal kind.",
                  desc: "Lemures are the lowest form of devil, mindless masses of congealed flesh formed from mortal souls condemned to Hell. They blindly obey any devil that commands them and reform if not killed with holy or silver weapons. They serve as expendable labor and cannon fodder in infernal armies.",
                  source: "Monster Core", isPremium: true),

            .make("Imp", level: 1,
                  creatureType: "Fiend", size: "Tiny",
                  traits: "Fiend, Devil",
                  hp: "16", ac: 16, fort: 5, ref: 8, will: 7,
                  speed: "20 feet, fly 30 feet",
                  attacks: "Stinger +8 (1d4+1 piercing plus imp venom; Finesse)",
                  specialAbilities: "Darkvision; Change Shape (boar, giant spider, rat, or raven); Imp Venom (DC 16 Fortitude or 1d6 poison plus sickened 1); Invisibility (at will, self only); Telepathy 100 feet",
                  summary: "An imp is a tiny, cunning devil that serves as a spy and tempter of mortals.",
                  desc: "Imps are diminutive devils that serve as familiars, spies, and tempters for more powerful fiends and mortal spellcasters. They are cleverer than they appear and delight in leading mortals toward damnation through small, seemingly innocent suggestions. Their venomous stingers deliver a debilitating poison.",
                  source: "Monster Core", isPremium: true),

            .make("Spinagon", level: 2,
                  creatureType: "Fiend", size: "Small",
                  traits: "Fiend, Devil",
                  hp: "24", ac: 17, fort: 7, ref: 8, will: 7,
                  speed: "20 feet, fly 30 feet",
                  attacks: "Spine +9 (1d6+3 piercing; Range 30 feet), Claw +9 (1d4+3 slashing; Agile)",
                  specialAbilities: "Darkvision; Barbed Quills (creatures that grapple or hit with unarmed attacks take 1d4 piercing); Flame Spines (add 1d4 fire to spine attacks); Telepathy 100 feet",
                  summary: "A spinagon is a small, spiny devil that hurls flaming barbs at its enemies.",
                  desc: "Spinagons are small, winged devils covered in sharp spines. They serve as scouts and messengers in infernal armies, harassing enemies from the air with volleys of flaming spines. Their barbed bodies make them dangerous to grapple or strike with bare hands.",
                  source: "Monster Core", isPremium: true),

            .make("Bearded Devil", level: 5,
                  creatureType: "Fiend", size: "Medium",
                  traits: "Fiend, Devil",
                  hp: "70", ac: 22, fort: 13, ref: 11, will: 10,
                  speed: "35 feet",
                  attacks: "Glaive +15 (1d8+8 slashing; Deadly d8, Forceful, Reach 10 feet), Beard +15 (1d6+6 piercing plus infernal wound), Claw +15 (1d6+6 slashing; Agile)",
                  specialAbilities: "Darkvision; Infernal Wound (1d6 persistent bleed, DC 20 flat check to stop); Telepathy 100 feet; Reposition (Step after a successful glaive Strike)",
                  summary: "A bearded devil is a savage infernal soldier armed with a glaive and venomous beard.",
                  desc: "Bearded devils, also called barbazus, serve as foot soldiers in Hell's legions. Their namesake beards are prehensile appendages that deliver wounds which bleed profusely and resist magical healing. They fight with brutal discipline, repositioning constantly to maintain reach advantage.",
                  source: "Monster Core", isPremium: true),

            .make("Bone Devil", level: 12,
                  creatureType: "Fiend", size: "Large",
                  traits: "Fiend, Devil",
                  hp: "215", ac: 32, fort: 22, ref: 20, will: 21,
                  speed: "40 feet, fly 40 feet",
                  attacks: "Stinger +25 (3d8+11 piercing plus bone devil venom; Reach 10 feet), Claw +25 (3d6+11 slashing; Agile, Reach 10 feet)",
                  specialAbilities: "Darkvision; Telepathy 100 feet; Bone Devil Venom (DC 30 Fortitude or enfeebled 2 for 1 minute); Invisible (constant invisibility until it attacks); Frightful Presence (60 feet, DC 30 Will)",
                  summary: "A bone devil is a skeletal, invisible stalker that commands lesser devils with iron discipline.",
                  desc: "Bone devils, or osyluths, are skeletal horrors that serve as overseers and enforcers in Hell's hierarchy. They remain constantly invisible, stalking and monitoring other devils to ensure obedience. Their venomous tail stingers can cripple even the strongest warriors.",
                  source: "Monster Core", isPremium: true),

            .make("Erinyes", level: 12,
                  creatureType: "Fiend", size: "Medium",
                  traits: "Fiend, Devil",
                  hp: "200", ac: 32, fort: 21, ref: 23, will: 21,
                  speed: "25 feet, fly 40 feet",
                  attacks: "Flaming Longbow +25 (2d8+6 piercing plus 1d6 fire; Deadly d10, Range 100 feet, Volley 30 feet), Longsword +24 (2d8+10 slashing; Versatile P)",
                  specialAbilities: "Darkvision; Telepathy 100 feet; Rope of Entanglement (50 feet, Escape DC 28); Flames of Fury (add 2d6 fire to all attacks against a creature who damaged the erinyes this round)",
                  summary: "An erinyes is a beautiful, vengeful devil that hunts down oath-breakers with a flaming bow.",
                  desc: "Erinyes are fallen angels who now serve as Hell's bounty hunters, tracking down mortals who break pacts or escape their infernal obligations. They are strikingly beautiful yet utterly merciless, and their flaming bows can strike targets from extreme range. Their enchanted ropes bind fleeing quarry.",
                  source: "Monster Core", isPremium: true),

            .make("Pit Fiend", level: 20,
                  creatureType: "Fiend", size: "Large",
                  traits: "Fiend, Devil",
                  hp: "400", ac: 45, fort: 35, ref: 34, will: 35,
                  speed: "35 feet, fly 50 feet",
                  attacks: "Jaws +37 (4d10+17 piercing plus pit fiend venom; Magical, Reach 10 feet), Claw +37 (4d6+17 slashing; Agile, Magical, Reach 10 feet), Tail +37 (4d10+17 bludgeoning plus Improved Grab; Magical, Reach 10 feet), Wing +35 (4d6+11 slashing; Magical, Reach 15 feet)",
                  specialAbilities: "Darkvision; Telepathy 100 feet; Pit Fiend Venom (DC 40 Fortitude or drained 2); Frightful Presence (20 feet, DC 40 Will); Constrict (3d8+17 bludgeoning); Masterful Strategist; Power Word Stun; Fireball (at will, 8th rank)",
                  summary: "A pit fiend is the supreme commander of Hell's armies and one of the most powerful devils in existence.",
                  desc: "Pit fiends are the generals and governors of Hell, standing at the apex of devilkind below only the archdevils themselves. They are brilliant tacticians who command legions with ruthless efficiency. In combat, their venom can drain the life force from even the mightiest heroes, and their innate magic devastates entire battlefields.",
                  source: "Monster Core", isPremium: true),
        ]

        for monster in monsters {
            try await db.insertMonster(monster)
        }
    }
}
