import Foundation

// Dark Archive (Premium)
extension SeedDataBuilder {
    func seedDarkArchive() async throws {
        let spells: [SpellEntry] = [
            .make("Deja Vu", rank: 1, traditions: "arcane, occult",
                  actions: "2 actions",
                  traits: "Enchantment, Incapacitation, Mental",
                  range: "100 feet", targets: "1 creature",
                  duration: "2 rounds", savingThrow: "Will",
                  summary: "You force a creature to repeat its last action.",
                  desc: "You send a jolt of psychic energy that locks a creature into a loop of time. The target must attempt a Will save. On a failure, the target must repeat the same actions it took on its previous turn, in the same order. It must make the same choices available to it (such as the same Strikes or the same spells).",
                  source: "Dark Archive", isPremium: true),

            .make("Glimpse the Truth", rank: 1, traditions: "arcane, divine, occult",
                  actions: "1 action",
                  traits: "Divination, Revelation",
                  duration: "1 round",
                  summary: "You gain a brief flash of divine insight, letting you see through illusions.",
                  desc: "You glimpse beyond the veil of illusions. For the duration, you gain a +2 status bonus to Perception checks to disbelieve illusions, and if you roll a success on such a check, you get a critical success instead.",
                  source: "Dark Archive", isPremium: true),

            .make("Psi Bolt", rank: 1, traditions: "occult",
                  actions: "2 actions",
                  traits: "Evocation, Force, Mental",
                  range: "120 feet", targets: "1 creature",
                  savingThrow: "Will",
                  summary: "You hurl a bolt of pure psychic force at a foe.",
                  desc: "You launch a concentrated bolt of psychic energy at a target. The bolt deals 2d6 mental damage. The target attempts a Will save. Critical Success: The target is unaffected. Success: The target takes half damage. Failure: The target takes full damage. Critical Failure: The target takes double damage and is stunned 1.",
                  heightened: "(+1) The damage increases by 2d6.",
                  source: "Dark Archive", isPremium: true),

            .make("Telekinetic Projectile", rank: 1, traditions: "arcane, occult",
                  actions: "2 actions",
                  traits: "Attack, Cantrip, Evocation",
                  range: "30 feet", targets: "1 creature",
                  summary: "You hurl a loose, unattended object at a creature.",
                  desc: "You telekinetically hurl a loose, unattended object that is within range at a target. Make a spell attack roll against the target. If you hit, you deal bludgeoning, piercing, or slashing damage—as appropriate for the object you chose—equal to 1d6 plus your spellcasting ability modifier.",
                  heightened: "(+1) The damage increases by 1d6.",
                  source: "Dark Archive", isPremium: true),

            .make("Phantom Pain", rank: 1, traditions: "occult",
                  actions: "2 actions",
                  traits: "Illusion, Mental, Nonlethal",
                  range: "30 feet", targets: "1 creature",
                  duration: "1 minute", savingThrow: "Will",
                  summary: "You cause the target to feel overwhelming phantom pain.",
                  desc: "Illusory pain wracks the target, dealing 2d4 mental damage and 1d4 persistent mental damage. The target must attempt a Will save. Critical Success: The target is unaffected. Success: The target takes half damage and no persistent damage. Failure: The target takes full damage. Critical Failure: The target takes double damage.",
                  heightened: "(+1) The initial damage increases by 2d4 and the persistent damage increases by 1d4.",
                  source: "Dark Archive", isPremium: true),

            .make("Mindlink", rank: 1, traditions: "occult",
                  actions: "2 actions",
                  traits: "Divination, Linguistic, Mental",
                  range: "touch", targets: "1 willing creature",
                  duration: "10 minutes",
                  summary: "You forge a brief telepathic link with a willing creature.",
                  desc: "You forge a mental link with a willing target within range, allowing you to communicate telepathically for the duration. You and the target can share thoughts, emotions, and sensory impressions. The communication is two-way and can convey any concept you could express in words.",
                  source: "Dark Archive", isPremium: true),

            .make("Paranoia", rank: 2, traditions: "occult",
                  actions: "2 actions",
                  traits: "Enchantment, Incapacitation, Mental",
                  range: "30 feet", targets: "1 creature",
                  duration: "1 minute", savingThrow: "Will",
                  summary: "You cause a creature to see all others as enemies.",
                  desc: "You fill the target's mind with overwhelming paranoia. The target sees all creatures as enemies, even its allies. The target must attempt a Will save. Failure: The target treats all creatures it can perceive as enemies for the duration. It must attempt Strikes or use hostile actions against the nearest creature on each of its turns. Critical Failure: As failure, but the duration is 10 minutes.",
                  source: "Dark Archive", isPremium: true),

            .make("Telekinetic Maneuver", rank: 2, traditions: "arcane, occult",
                  actions: "2 actions",
                  traits: "Evocation, Force",
                  range: "60 feet", targets: "1 creature",
                  summary: "You use telekinetic force to perform a combat maneuver.",
                  desc: "With a rush of telekinetic power, you move a creature. You can attempt to Disarm, Shove, or Trip the target using a spell attack roll instead of an Athletics check.",
                  source: "Dark Archive", isPremium: true),

            .make("Rewrite Memory", rank: 3, traditions: "occult",
                  actions: "2 actions",
                  traits: "Divination, Mental",
                  range: "touch", targets: "1 willing or unconscious creature",
                  duration: "unlimited", savingThrow: "Will",
                  summary: "You alter the target's memories of a recent event.",
                  desc: "You reach into a creature's mind and rewrite its memories. You can alter the target's memories of a single event that happened within the last 24 hours and that lasted no longer than 10 minutes. You can make the target forget the event entirely, remember it differently, or recall fictional events that didn't happen. The target receives a Will save to resist.",
                  source: "Dark Archive", isPremium: true),

            .make("Hallucination", rank: 3, traditions: "arcane, occult",
                  actions: "2 actions",
                  traits: "Illusion, Incapacitation, Mental",
                  range: "30 feet", targets: "1 creature",
                  duration: "1 hour", savingThrow: "Will",
                  summary: "You fill the target's mind with false sensory input.",
                  desc: "The target perceives one object or creature as though it were another, or sees something that isn't there. You choose the nature of the hallucination when you cast the spell. The target must attempt a Will save. Failure: The target fully believes the hallucination for the duration. Critical Failure: As failure, and the target can't attempt to disbelieve the hallucination.",
                  source: "Dark Archive", isPremium: true),

            .make("Mindscape Door", rank: 3, traditions: "occult",
                  actions: "3 actions",
                  traits: "Illusion, Mental, Teleportation",
                  range: "touch", targets: "you and up to 4 willing creatures",
                  duration: "sustained up to 10 minutes",
                  summary: "You create a portal into a mindscape shared by participants.",
                  desc: "You open a doorway into a shared mental landscape. You and the targets enter a mindscape—a mental realm shaped by thought and emotion. Within the mindscape, participants can communicate freely, share ideas, and interact in ways impossible in the physical world. While in the mindscape, participants' bodies remain unconscious in the material world.",
                  source: "Dark Archive", isPremium: true),

            .make("Modify Memory", rank: 4, traditions: "occult",
                  actions: "2 actions",
                  traits: "Divination, Mental",
                  range: "30 feet", targets: "1 creature",
                  duration: "unlimited", savingThrow: "Will",
                  summary: "You permanently alter a creature's memory of an event.",
                  desc: "You alter the target's memory of events that occurred within the last day, affecting up to 5 minutes of memory. You can eliminate all memory of the event, allow the target to recall it with perfect clarity, change the details, or create memory of an event that never happened. The target must attempt a Will save to resist the effect.",
                  heightened: "(6th) You can affect memories up to 1 year old and up to 30 minutes long.",
                  source: "Dark Archive", isPremium: true),

            .make("Synaptic Pulse", rank: 5, traditions: "occult",
                  actions: "2 actions",
                  traits: "Enchantment, Incapacitation, Mental",
                  area: "30-foot emanation",
                  duration: "1 round", savingThrow: "Will",
                  summary: "You release a pulse of psychic energy that stuns nearby creatures.",
                  desc: "You send a massive pulse of psychic energy outward from your mind. Each creature in the area must attempt a Will save. Critical Success: The creature is unaffected. Success: The creature is stunned 1. Failure: The creature is stunned 2. Critical Failure: The creature is stunned 3.",
                  source: "Dark Archive", isPremium: true),

            .make("Mind Probe", rank: 5, traditions: "arcane, occult",
                  actions: "1 minute",
                  traits: "Divination, Linguistic, Mental",
                  range: "30 feet", targets: "1 creature",
                  duration: "sustained up to 1 minute", savingThrow: "Will",
                  summary: "You telepathically probe a creature's mind for information.",
                  desc: "You telepathically delve into the target's mind to seek out information. The target can attempt a Will save to resist. On a failure, you can ask the target a question each round you Sustain the Spell and attempt to uncover the answer from the target's mind. The target is aware you are probing its thoughts.",
                  source: "Dark Archive", isPremium: true),

            .make("Feeblemind", rank: 6, traditions: "arcane, occult",
                  actions: "2 actions",
                  traits: "Curse, Enchantment, Incapacitation, Mental",
                  range: "30 feet", targets: "1 creature",
                  duration: "varies", savingThrow: "Will",
                  summary: "You drastically reduce a creature's mental faculties.",
                  desc: "You drastically reduce the target's mental faculties. The target must attempt a Will save. Critical Success: The target is unaffected. Success: The target is stupefied 2 for 1 round. Failure: The target is stupefied 4 with an unlimited duration. Critical Failure: The target's Intelligence, Wisdom, and Charisma modifiers each decrease to -5 with an unlimited duration.",
                  source: "Dark Archive", isPremium: true),

            .make("Warp Mind", rank: 7, traditions: "arcane, occult",
                  actions: "2 actions",
                  traits: "Emotion, Enchantment, Incapacitation, Mental",
                  range: "120 feet", targets: "1 creature",
                  savingThrow: "Will",
                  summary: "You shatter a creature's psyche, leaving it dazed and confused.",
                  desc: "You scramble a creature's mental faculties and possibly extinguish its higher consciousness. The target must attempt a Will save. Critical Success: The target is unaffected. Success: The target is confused for 1 round. Failure: The target is confused for 1 minute. Critical Failure: The target is confused permanently.",
                  source: "Dark Archive", isPremium: true),

            .make("Possession", rank: 7, traditions: "occult",
                  actions: "2 actions",
                  traits: "Incapacitation, Mental, Necromancy, Possession",
                  range: "30 feet", targets: "1 living creature",
                  duration: "1 minute", savingThrow: "Will",
                  summary: "You project your soul into a creature's body, controlling it.",
                  desc: "You attempt to possess the target, projecting your soul into its body. The target must attempt a Will save. Failure: You possess the target. You control the body while your own body falls unconscious. You use the target's physical ability scores and attacks, but your own mental ability scores, spell slots, and mental abilities. Critical Failure: As failure, but the duration is 10 minutes.",
                  source: "Dark Archive", isPremium: true),

            .make("Maze", rank: 8, traditions: "arcane, occult",
                  actions: "2 actions",
                  traits: "Conjuration, Extradimensional, Teleportation",
                  range: "30 feet", targets: "1 creature",
                  duration: "sustained",
                  summary: "You trap a creature in an extradimensional maze.",
                  desc: "You transport the target into an extradimensional maze of hedges, walls, and corridors. The target must find its way out. Each round, the target can spend its entire turn attempting to escape by succeeding at a Survival check or Perception check against your spell DC. If the target fails, it remains in the maze. When you stop sustaining the spell, the target returns to its previous space.",
                  source: "Dark Archive", isPremium: true),
        ]

        let feats: [FeatEntry] = [
            .make("Amp Cantrip", level: 1, featType: "Psychic",
                  traits: "Psychic",
                  summary: "You pour psychic power into your cantrips, amplifying their effects.",
                  benefit: "When you cast one of your unique psi cantrips, you can choose to amp it. An amped cantrip gains additional effects beyond its normal ones. You can amp a cantrip only if you have the psi points to spend, and amping a cantrip costs 1 Focus Point.",
                  source: "Dark Archive", isPremium: true),

            .make("Distant Mindscape", level: 1, featType: "Psychic",
                  traits: "Psychic",
                  summary: "Your psychic powers reach across greater distances.",
                  benefit: "When you cast a psi cantrip that has a range, you can increase that range by 30 feet. This increase applies before any other abilities that change the range.",
                  source: "Dark Archive", isPremium: true),

            .make("Fortified Mind", level: 1, featType: "Psychic",
                  traits: "Psychic",
                  summary: "Your psychic discipline hardens your mind against intrusion.",
                  benefit: "You gain a +1 circumstance bonus to saving throws against mental effects. If you roll a success on a saving throw against a mental effect, you get a critical success instead.",
                  source: "Dark Archive", isPremium: true),

            .make("Root to Life", level: 4, featType: "Psychic",
                  traits: "Healing, Psychic",
                  prerequisites: "Psychic",
                  summary: "You use psychic energy to pull a dying creature back from the brink.",
                  benefit: "You use your psychic abilities to stabilize a dying creature. You can use 1 action to touch a dying creature and automatically stabilize it. If you spend 2 actions, you can instead give the target 1 Hit Point and bring it to consciousness.",
                  source: "Dark Archive", isPremium: true),

            .make("Esoteric Lore", level: 1, featType: "Thaumaturge",
                  traits: "Thaumaturge",
                  summary: "You draw upon esoteric knowledge to identify creatures and their weaknesses.",
                  benefit: "You gain the Esoteric Lore skill, a special lore skill that can be used to Recall Knowledge about any creature, using your Charisma modifier instead of Intelligence. When you succeed, you also learn one of the creature's resistances or weaknesses.",
                  source: "Dark Archive", isPremium: true),

            .make("Implement's Empowerment", level: 1, featType: "Thaumaturge",
                  traits: "Thaumaturge",
                  summary: "Your implement channels supernatural power into your attacks.",
                  benefit: "When you hold your implement and Strike with another weapon, you gain a +2 damage bonus with that weapon. This bonus increases to +4 at 4th level, +6 at 12th level, and +8 at 19th level.",
                  source: "Dark Archive", isPremium: true),

            .make("Extradimensional Pocket", level: 2, featType: "Thaumaturge",
                  traits: "Thaumaturge",
                  prerequisites: "Thaumaturge Dedication",
                  summary: "Your implement can store objects in a small extradimensional space.",
                  benefit: "You can slip small objects into a fold of space within your implement. Your implement acts as a bag of holding that can contain up to 1 Bulk of items. Only you can retrieve items from this space. If the implement is destroyed, the items within appear at your feet.",
                  source: "Dark Archive", isPremium: true),

            .make("Breached Defenses", level: 2, featType: "Thaumaturge",
                  traits: "Thaumaturge",
                  prerequisites: "Exploit Vulnerability",
                  summary: "You find an even greater weakness in a creature's defenses.",
                  benefit: "When you succeed at Exploit Vulnerability against a creature, you also lower the creature's resistances against your Strikes by an amount equal to 2 + half your level. This applies only to your Strikes, not those of your allies.",
                  source: "Dark Archive", isPremium: true),

            .make("Mortal Weakness", level: 2, featType: "Thaumaturge",
                  traits: "Thaumaturge",
                  prerequisites: "Exploit Vulnerability",
                  summary: "You discover and exploit a creature's deepest vulnerability.",
                  benefit: "When you Exploit Vulnerability and succeed, you can choose to apply mortal weakness instead of the usual effect. The target gains weakness to your Strikes equal to 2 + half your level. This weakness applies to all damage types from your Strikes.",
                  source: "Dark Archive", isPremium: true),

            .make("Scroll Esoterica", level: 4, featType: "Thaumaturge",
                  traits: "Thaumaturge",
                  prerequisites: "Esoteric Lore",
                  summary: "You can create temporary scrolls from esoteric knowledge.",
                  benefit: "During your daily preparations, you can create a temporary scroll containing a spell of a level no higher than half your level rounded up. The scroll is an occult spell from your tradition. It crumbles to dust if not used before your next daily preparations. You can have only one scroll from this feat at a time.",
                  source: "Dark Archive", isPremium: true),
        ]

        for entry in spells { try await db.insertSpell(entry) }
        for entry in feats { try await db.insertFeat(entry) }
    }
}
